// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/projects/create-project/create-project.jsx

import React, { Fragment, useState } from "react";
import { Card, Col, Form, Row } from "react-bootstrap";
import { FilePond } from "react-filepond";
import CreatableSelect from 'react-select/creatable';
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import SpkSunEditor from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-suneditor";
import SpkDatepickr from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-datepicker";
import SpkSelect from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import { AsignSelect, StatusSelect, PrioritySelect } from "../../../../shared/data/dashboards/projects/projectcreatedata";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import MainLayout from "@/Layouts/layout";

const CreateProject = () => {

    const [dates, setDates] = useState({});
    const handleDateChange = (key, date) => {
        if (date) {
            setDates((prevDates) => ({
                ...prevDates,
                [key]: date,
            }));
        } else {
            setDates((prevDates) => {
                const { [key]: removedKey, ...rest } = prevDates;
                return rest;
            });
        }
    };

    const [files, setFiles] = useState({});
    const handleFileUpdate = (fileItems, pondName) => {
        setFiles((prevFiles) => ({
            ...prevFiles,
            [pondName]: fileItems.map((fileItem) => fileItem.file),
        }));
    };

    const components = {
        DropdownIndicator: null,
    };

    const createOption = (label) => ({
        label,
        value: label,
    });

    const [inputValue, setInputValue] = useState('');
    const [value1, setValue1] = useState([
        createOption("Marketing"),
        createOption("Sales"),
        createOption("Development"),
        createOption("Design"),
        createOption("Research"),

    ]);
    const handleKeyDown = (event) => {
        if (!inputValue) return;
        switch (event.key) {
            case 'Enter':
            case 'Tab':
                setValue1((prev) => [...prev, createOption(inputValue)]);
                setInputValue('');
                event.preventDefault();
        }
    };

    const defaultContent = `<p>"Project Omni" is a cloud-based platform designed to streamline project management for small to medium-sized businesses. The application enables users to create, manage, and collaborate on projects with team members. It includes tools for task tracking, time management, file sharing, and real-time messaging. The goal is to improve productivity, enhance communication, and ensure that projects are completed on time and within budget.</p>
                                        <p><br /></p>
     <ol>
        <li className="ql-size-normal">User Authentication and Role Management.</li>
        <li className="">Project Creation and Management.</li>
        <li className="">Task Assignment and Tracking.</li>
        <li className="">Time Tracking Integration.</li>
        <li className="">File Sharing and Document Management.</li>
        <li className="">Real-time Collaboration and Messaging.</li>
    </ol>`

    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Projects-Create Project" />

            <Pageheader title="Dashboards" subtitle="Projects" currentpage="Create Project" activepage="Create Project" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Create Project
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <div className="row gy-3">
                                <Col xl={4}>
                                    <Form.Label htmlFor="input-label" className="">Project Name :</Form.Label>
                                    <Form.Control type="text" className="" id="input-label" placeholder="Enter Project Name" />
                                </Col>
                                <Col xl={4}>
                                    <Form.Label htmlFor="input-label11" className="">Project Manager :</Form.Label>
                                    <Form.Control type="text" className="" id="input-label11" placeholder="Project Manager Name" />
                                </Col>
                                <Col xl={4}>
                                    <Form.Label htmlFor="input-label1" className="">Client / Stakeholder :</Form.Label>
                                    <Form.Control type="text" className="" id="input-label1" placeholder="Enter Client Name" />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label className="">Project Description :</Form.Label>
                                    <div id="project-descriptioin-editor">
                                        <SpkSunEditor height={'300px'} defaulContent={defaultContent} />
                                    </div>
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Start Date :</Form.Label>
                                    <div className="form-group">
                                        <div className="input-group">
                                            <div className="input-group-text text-muted"> <i className="ri-calendar-line"></i> </div>
                                            <SpkDatepickr className="form-control flatpickr-input" Timeinput="Time:" dateFormat="yy/MM/dd h:mm aa" placeholderText='Choose date with time' showTimeInput selected={dates["startDate"] ? new Date(dates["startDate"]) : null} onChange={(date) => handleDateChange("startDate", date)} />
                                        </div>
                                    </div>
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">End Date :</Form.Label>
                                    <div className="form-group">
                                        <div className="input-group">
                                            <div className="input-group-text text-muted"> <i className="ri-calendar-line"></i> </div>
                                            <SpkDatepickr className="form-control flatpickr-input" Timeinput="Time:" dateFormat="yy/MM/dd h:mm aa" placeholderText='Choose date with time' showTimeInput selected={dates["endDate"] ? new Date(dates["endDate"]) : null} onChange={(date) => handleDateChange("endDate", date)} />
                                        </div>
                                    </div>
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Status :</Form.Label>
                                    <SpkSelect name="colors" option={StatusSelect} mainClass="default basic-multi-select" id="choices-multiple-default" menuplacement='auto' classNameprefix="Select2" defaultvalue={[StatusSelect[1]]} />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Priority :</Form.Label>
                                    <SpkSelect name="colors" option={PrioritySelect} mainClass="default basic-multi-select" id="choices-multiple-default" menuplacement='auto' classNameprefix="Select2" defaultvalue={[PrioritySelect[1]]} />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Assigned To</Form.Label>
                                    <SpkSelect multi name="colors" option={AsignSelect} mainClass="default basic-multi-select" id="choices-multiple-default" menuplacement='auto' classNameprefix="Select2" defaultvalue={[AsignSelect[4], AsignSelect[10], AsignSelect[0]]} />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Tags</Form.Label>
                                    <CreatableSelect className="tags-data" components={components} classNamePrefix='react-select' inputValue={inputValue} isClearable isMulti menuIsOpen={false} onChange={(newValue) => {
                                        if (Array.isArray(newValue)) {
                                            setValue1(newValue);
                                        } else {
                                            setValue1([]);
                                        }
                                    }} onInputChange={(newValue) => setInputValue(newValue)} onKeyDown={handleKeyDown} placeholder="Type something and press enter..." value={value1} />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label className="">Attachments</Form.Label>
                                    <FilePond className="multiple-filepond" files={files['dropzone'] || []} onupdatefiles={(fileItems) => handleFileUpdate(fileItems, 'dropzone')} allowMultiple={true} maxFiles={3} server="/api" name="files" labelIdle='Drag & Drop your file here or click ' />
                                </Col>
                            </div>
                        </Card.Body>
                        <Card.Footer>
                            <SpkButton Buttonvariant="" Customclass="btn btn-primary-light btn-wave ms-auto float-end">Create Project</SpkButton>
                        </Card.Footer>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
CreateProject.layout = (page) => <MainLayout>{page}</MainLayout>;
export default CreateProject;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/dashboards/projects/create-project.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import { Editor } from "@tadashi/svelte-editor-quill";
    import FilePond, { registerPlugin } from "svelte-filepond";
    import FilePondPluginImageExifOrientation from "filepond-plugin-image-exif-orientation";
    import FilePondPluginImagePreview from "filepond-plugin-image-preview";
    import "quill/dist/quill.snow.css";
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Col,
        Input,
        Label,
        Row,
    } from "@sveltestrap/sveltestrap";
    import { DateInput } from "date-picker-svelte";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import Select from "svelte-select";
    import {
        AsignSelect,
        StatusSelect,
        PrioritySelect,
    } from "@/shared/data/dashboards/projects/projectcreatedata";
    // Register the plugins
    registerPlugin(
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
    );

    //  date

    let date = new Date();
    let date1 = new Date();
    const options = {
        theme: "snow",
    };

    let data = `<h4><b class="ql-size-large">Quill Snow</b> is a free, open source <a href="https://github.com/quilljs/quill/" target="_blank">Quill Editor</a> built for the modern web. With its <a href="https://quilljs.com/docs/modules/" target="_blank">modular architecture</a> and expressive API, it is completely customizable to fit any need.</h4>
                                    <p><br></p>
                                    <ol>
                                        <li class="ql-size-normal">Write text select and edit with multiple options.</li>
                                        <li class="">This is quill snow editor.</li>
                                        <li class="">Easy to customize and flexible.</li>
                                    </ol>
                                    <p><br></p>
                                    <h4>Quill officially supports a standard toolbar theme <a href="https://github.com/quilljs/quill/" target="_blank">"Snow"</a> and a floating tooltip theme <a href="https://github.com/quilljs/quill/" target="_blank">"Bubble"</a></h4>
                                `;
    let text = "";
    let html = "";

    const onTextChange = (event) => {
        ({ text, html } = event?.detail ?? {});
        data = html;
    };

    let options1 = [
        { value: "apple", label: "Apple" },
        { value: "banana", label: "Banana" },
    ];

    let filterText = "";

    let value = ["Marketing", "Sales", "Development", "Design", "Research"];

    let items = [
       
    ];

    function handleFilter(e) {
        if (value?.find((i) => i.label === filterText)) return;
        if (e.detail.length === 0 && filterText.length > 0) {
            const prev = items.filter((i) => !i.created);
            items = [
                ...prev,
                { value: filterText, label: filterText, created: true },
            ];
        }
    }

    function handleChange(e) {
        items = items.map((i) => {
            delete i.created;
            return i;
        });
    }
</script>

<!-- Page Title -->
<svelte:head>
    <title>CreateProject | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Create Project"
    subTitle="Projects"
    activepage="Dashboards"
    page="Create Project"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={12}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Create Project</div>
            </CardHeader>
            <CardBody>
                <div class="row gy-3">
                    <Col xl={4}>
                        <Label for="input-label" class="">Project Name :</Label>
                        <Input
                            type="text"
                            class=""
                            id="input-label"
                            placeholder="Enter Project Name"
                        />
                    </Col>
                    <Col xl={4}>
                        <Label for="input-label11" class=""
                            >Project Manager :</Label
                        >
                        <Input
                            type="text"
                            class=""
                            id="input-label11"
                            placeholder="Project Manager Name"
                        />
                    </Col>
                    <Col xl={4}>
                        <Label for="input-label1" class=""
                            >Client / Stakeholder :</Label
                        >
                        <Input
                            type="text"
                            class=""
                            id="input-label1"
                            placeholder="Enter Client Name"
                        />
                    </Col>
                    <Col xl={12}>
                        <Label class="">Project Description :</Label>
                        <div id="project-descriptioin-editor">
                            <Editor
                                {options}
                                {data}
                                on:text-change={onTextChange}
                            />
                        </div>
                    </Col>
                    <Col xl={6}>
                        <Label class="">Start Date :</Label>
                        <div class="form-group custom-date-picker">
                            <div class="input-group custom-input-group">
                                <div class="input-group-text text-muted">
                                    <i class="ri-calendar-line"></i>
                                </div>
                                <DateInput
                                    bind:value={date}
                                    class="form-control"
                                    format="yy-MM-dd HH:MM"
                                    closeOnSelection={true}
                                    timePrecision="minute"
                                    dynamicPositioning={true}
                                />
                            </div>
                        </div>
                    </Col>
                    <Col xl={6}>
                        <Label class="">End Date :</Label>
                        <div class="form-group custom-date-picker">
                            <div class="input-group custom-input-group">
                                <div class="input-group-text text-muted">
                                    <i class="ri-calendar-line"></i>
                                </div>
                                <DateInput
                                    bind:value={date1}
                                    class="form-control"
                                    format="yy-MM-dd HH:MM"
                                    closeOnSelection={true}
                                    timePrecision="minute"
                                    dynamicPositioning={true}
                                />
                            </div>
                        </div>
                    </Col>
                    <Col xl={6}>
                        <Label class="">Status :</Label>
                        <Select
                            items={StatusSelect}
                            class="default basic-multi-select"
                            value={StatusSelect[1]}
                            clearable={false}
                            showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Priority :</Label>
                        <Select
                            items={PrioritySelect}
                            class="default basic-multi-select"
                            value={PrioritySelect[1]}
                            clearable={false}
                            showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Assigned To</Label>
                        <Select
                            items={AsignSelect}
                            multiFullItemClearable
                            multiple
                            value={[AsignSelect[4], AsignSelect[1]]}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Tags</Label>
                        <Select
                            on:change={handleChange}
                            multiple
                            on:filter={handleFilter}
                            bind:filterText
                            bind:value
                            {items}
                            showChevron={false}
                            clearable={false}
                            placeholder="Add New Tags"
                        >
                            <div slot="item" let:item>
                                {item.created ? "Add new: " : ""}
                                {item.label}
                            </div>
                        </Select>
                    </Col>
                    <Col xl={12}>
                        <Label class="">Attachments</Label>
                        <FilePond
                            class="multiple-filepond"
                            name="filepond"
                            labelIdle={`Drag & Drop your file here or click`}
                            stylePanelLayout=" "
                            styleLoadIndicatorPosition="center bottom"
                            styleButtonRemoveItemPosition="center bottom"
                            allowMultiple={true}
                        />
                    </Col>
                </div>
            </CardBody>
            <CardFooter>
                <SpkButton
                    color=""
                    customClass="btn btn-primary-light btn-wave ms-auto float-end"
                    >Create Project</SpkButton
                >
            </CardFooter>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->
