// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/ui-elements/list-group/list-group.jsx

import SpkBadge from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import SpkListgroup from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-listgroup";
import { Listgroup1, Listgroup10, Listgroup11, Listgroup12, Listgroup13, Listgroup14, Listgroup15, Listgroup16, Listgroup2, Listgroup3, Listgroup4, Listgroup5, Listgroup6, Listgroup7, Listgroup8, Listgroup9, datalistgroup1, datalistgroup11, datalistgroup12, datalistgroup13, datalistgroup14, datalistgroup15, datalistgroup16, datalistgroup4, datalistgroup6, datalistgroup7, reuseListgroup1, reuseListgroup10, reuseListgroup11, reuseListgroup12, reuseListgroup13, reuseListgroup14, reuseListgroup15, reuseListgroup16, reuseListgroup2, reuseListgroup3, reuseListgroup4, reuseListgroup5, reuseListgroup6, reuseListgroup7, reuseListgroup8, reuseListgroup9 } from "../../../../shared/data/prism-code/uielements-prism";
import { ActiveButtons, BasicButtons, ContextualButtons, CustomButtons, HorizontalButtons, LinksButtons, ListbadgesButtons, SubheadingsButtons } from "../../../../shared/data/general/ui-elements/listgroupdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col, Image, ListGroup, Row } from "react-bootstrap";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const ListGroups = () => {

    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Listgroup" />

            <Pageheader title="Ui Elements" currentpage="List Group" activepage="List Group" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={6}>
                    <ShowCode title="Basic List" customCardClass="custom-card" customCardBodyClass="" dataCode={datalistgroup1} reactCode={Listgroup1} reusableCode={reuseListgroup1}>
                        <SpkListgroup as="ul">
                            {BasicButtons.map((idx, index) => (
                                <ListGroup.Item as="li" key={index}>
                                    <div className="d-flex align-items-center">
                                        <span className="avatar avatar-sm">
                                            <BaseImage src={idx.src} alt="img" />
                                        </span>
                                        <div className="ms-2 fw-semibold">
                                            {idx.text}
                                        </div>
                                    </div>
                                </ListGroup.Item>
                            ))}
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Active items" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup4} dataCode={datalistgroup4} reusableCode={reuseListgroup4}>
                        <SpkListgroup as="ul">
                            {ActiveButtons.map((idx, index) => (
                                <ListGroup.Item as="li" className={`list-group-item ${idx.class1}`} aria-current="true" key={index}>
                                    <div className="d-flex align-items-center">
                                        <div>
                                            <span className="fs-15">
                                                <i className={`bi bi-${idx.class}`}></i>
                                            </span>
                                        </div>
                                        <div className="ms-2">
                                            {idx.text}
                                        </div>
                                    </div>
                                </ListGroup.Item>
                            ))}
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Disabled items" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup2} reusableCode={reuseListgroup2}>

                        <SpkListgroup as="ul">
                            <ListGroup.Item as="li" disabled className="" aria-disabled="true">A disabled item meant to be disabled
                            </ListGroup.Item>
                            <ListGroup.Item as="li">Simply dummy text of the printing</ListGroup.Item>
                            <ListGroup.Item as="li">There are many variations of passages</ListGroup.Item>
                            <ListGroup.Item as="li">All the Lorem Ipsum generators</ListGroup.Item>
                            <ListGroup.Item as="li">Written in 45 BC. This book is a treatise on the theory</ListGroup.Item>
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Flush" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup3} reusableCode={reuseListgroup3}>
                        <SpkListgroup Variant='flush'>
                            <ListGroup.Item className="fw-semibold"><i className="bi bi-envelope align-middle me-2 text-muted"></i>Asish Trivedhi<span className="ms-1 text-muted fw-normal d-inline-block">(+1023-84534)</span></ListGroup.Item>
                            <ListGroup.Item className="fw-semibold"><i className="bi bi-tiktok align-middle me-2 text-muted"></i>Alezander Russo<span className="ms-1 text-muted fw-normal d-inline-block">(+7546-12342)</span></ListGroup.Item>
                            <ListGroup.Item className="fw-semibold"><i className="bi bi-whatsapp align-middle me-2 text-muted"></i>Karem Smith<span className="ms-1 text-muted fw-normal d-inline-block">(+9944-56632)</span></ListGroup.Item>
                            <ListGroup.Item className="fw-semibold"><i className="bi bi-facebook align-middle me-2 text-muted"></i>Melissa Brien<span className="ms-1 text-muted fw-normal d-inline-block">(+1023-34323)</span></ListGroup.Item>
                            <ListGroup.Item className="fw-semibold"><i className="bi bi-instagram align-middle me-2 text-muted"></i>Kamala Harris<span className="ms-1 text-muted fw-normal d-inline-block">(+91-63421)</span></ListGroup.Item>
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Links" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup6} dataCode={datalistgroup6} reusableCode={reuseListgroup6}>
                        <SpkListgroup>
                            {LinksButtons.map((idx, index) => (
                                <ListGroup.Item action className={`list-group-item-action ${idx.class1}`} key={index}
                                    aria-current="true">
                                    <div className="d-flex align-items-center">
                                        <div>
                                            <span className={`avatar avatar-xs bg-${idx.class} text-${idx.color} avatar-rounded`}>
                                                {idx.text1}
                                            </span>
                                        </div>
                                        <div className="ms-2">{idx.text}</div>
                                    </div>
                                </ListGroup.Item>
                            ))}
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="buttons" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup5} reusableCode={reuseListgroup5}>
                        <SpkListgroup>
                            <ListGroup.Item type="button" className="list-group-item-action active" aria-current="true">Simply dummy text of the printing<SpkBadge variant="primary" Customclass="float-end bg-">243</SpkBadge></ListGroup.Item>
                            <ListGroup.Item type="button" className="list-group-item-action">There are many variations of passages<SpkBadge variant="secondary-transparent" Customclass="float-end bg-">35</SpkBadge></ListGroup.Item>
                            <ListGroup.Item type="button" className="list-group-item-action">All the Lorem Ipsum generators<SpkBadge variant="info-transparent" Customclass="float-end bg-">132</SpkBadge></ListGroup.Item>
                            <ListGroup.Item type="button" className="list-group-item-action">All the Lorem Ipsum generators<SpkBadge variant="success-transparent" Customclass="float-end bg-">2525</SpkBadge></ListGroup.Item>
                            <ListGroup.Item type="button" className="list-group-item-action" disabled>A disabled item meant to be disabled<SpkBadge variant="danger-transparent" Customclass="float-end bg-">21</SpkBadge></ListGroup.Item>
                        </SpkListgroup>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-2 --> */}

            <Row>
                <Col xl={6}>
                    <ShowCode title="Contextual classes with hover styles" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup15} dataCode={datalistgroup15} reusableCode={reuseListgroup15}>
                        <ListGroup>
                            {ContextualButtons.map((idx, index) => (
                                <ListGroup.Item variant={idx.class} action className=" list-group-item-action" key={index}>{idx.text}</ListGroup.Item>
                            ))}
                        </ListGroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Contextual classes" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup16} dataCode={datalistgroup16} reusableCode={reuseListgroup16}>
                        <SpkListgroup as="ul">
                            {ContextualButtons.map((idx, index) => (
                                <ListGroup.Item as="li" variant={idx.class} key={index}>{idx.text}</ListGroup.Item>
                            ))}
                        </SpkListgroup>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-2 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xl={6}>
                    <ShowCode title="Solid Colored Lists" customCardClass="custom-card" customCardBodyClass="" dataCode={datalistgroup14} reactCode={Listgroup14} reusableCode={reuseListgroup14}>
                        <SpkListgroup as="ul">
                            {ContextualButtons.map((idx, index) => (
                                <ListGroup.Item className={`list-item-solid-${idx.class} ${idx.class1}`} as="li" key={index}>{idx.text}</ListGroup.Item>
                            ))}
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Custom content" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup13} dataCode={datalistgroup13} reusableCode={reuseListgroup13}>
                        <SpkListgroup>
                            {CustomButtons.map((idx, index) => (
                                <ListGroup.Item action className={`list-group-item-action ${idx.class1}`} key={index}
                                    aria-current="true">
                                    <div className="d-flex w-100 justify-content-between gap-1">
                                        <h6 className={`mb-1 fw-semibold ${idx.color}`}>{idx.heading}</h6>
                                        <small className={idx.class2}>{idx.text1}</small>
                                    </div>
                                    <p className="mb-1">{idx.text2}</p>
                                    <small>{idx.text3}</small>
                                </ListGroup.Item>
                            ))}
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Sub headings" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup7} dataCode={datalistgroup7} reusableCode={reuseListgroup7}>
                        <SpkListgroup as="ol" Numbered={true}>
                            {SubheadingsButtons.map((idx, index) => (
                                <ListGroup.Item as="li" className="list-group-item d-flex justify-content-between align-items-start" key={index}>
                                    <div className="ms-2 me-auto text-muted">
                                        <div className="fw-semibold fs-14 text-default">{idx.text1}</div>
                                        {idx.text2}
                                    </div>
                                    <SpkBadge variant={idx.class}>{idx.text3}</SpkBadge>
                                </ListGroup.Item>
                            ))}
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Numbered Lists" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup8} reusableCode={reuseListgroup8}>
                        <SpkListgroup as="ol" Numbered={true}>
                            <ListGroup.Item as="li">Simply dummy text of the printing.</ListGroup.Item>
                            <ListGroup.Item as="li">There are many variations of passages.</ListGroup.Item>
                            <ListGroup.Item as="li">All the Lorem Ipsum generators.</ListGroup.Item>
                            <ListGroup.Item as="li">Written in 45 BC. This book is a treatise on the theory.</ListGroup.Item>
                            <ListGroup.Item as="li">Randomised words which don't look.</ListGroup.Item>
                            <ListGroup.Item as="li">Always free from repetition, injected humour.</ListGroup.Item>
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="List With Checkboxes" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup9} reusableCode={reuseListgroup9}>
                        <SpkListgroup as="ul">
                            <ListGroup.Item as="li">
                                <input className="form-check-input me-2 fw-semibold" type="checkbox" value=""
                                    aria-label="..." defaultChecked />
                                Accurate information at any given point.
                            </ListGroup.Item>
                            <ListGroup.Item as="li">
                                <input className="form-check-input me-2 fw-semibold" type="checkbox" value=""
                                    aria-label="..." />
                                Hearing the information and responding.
                            </ListGroup.Item>
                            <ListGroup.Item as="li">
                                <input className="form-check-input me-2 fw-semibold" type="checkbox" value=""
                                    aria-label="..." defaultChecked />
                                Setting up and customizing your own sales.
                            </ListGroup.Item>
                            <ListGroup.Item as="li">
                                <input className="form-check-input me-2 fw-semibold" type="checkbox" value=""
                                    aria-label="..." defaultChecked />
                                New Admin Launched.
                            </ListGroup.Item>
                            <ListGroup.Item as="li">
                                <input className="form-check-input me-2 fw-semibold" type="checkbox" value=""
                                    aria-label="..." />
                                To maximize profits and improve productivity.
                            </ListGroup.Item>
                            <ListGroup.Item as="li">
                                <input className="form-check-input me-2 fw-semibold" type="checkbox" value=""
                                    aria-label="..." />
                                To have a complete 360° overview of sales information, having.
                            </ListGroup.Item>
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="List With Radios" customCardClass="custom-card" customCardBodyClass="" reactCode={Listgroup10} reusableCode={reuseListgroup10}>
                        <SpkListgroup>
                            <ListGroup.Item className="list-group-item">
                                <input className="form-check-input me-2" type="radio" value=""
                                    name="list-radio" defaultChecked />
                                Accurate information at any given point.
                            </ListGroup.Item>
                            <ListGroup.Item className="list-group-item">
                                <input className="form-check-input me-2" type="radio" value=""
                                    name="list-radio" defaultChecked />
                                Hearing the information and responding.
                            </ListGroup.Item>
                            <ListGroup.Item className="list-group-item">
                                <input className="form-check-input me-2" type="radio" value=""
                                    name="list-radio" defaultChecked />
                                Setting up and customizing your own sales.
                            </ListGroup.Item>
                            <ListGroup.Item className="list-group-item">
                                <input className="form-check-input me-2" type="radio" value=""
                                    name="list-radio" />
                                New Admin Launched.
                            </ListGroup.Item>
                            <ListGroup.Item className="list-group-item">
                                <input className="form-check-input me-2" type="radio" value=""
                                    name="list-radio" />
                                To maximize profits and improve productivity.
                            </ListGroup.Item>
                            <ListGroup.Item className="list-group-item">
                                <input className="form-check-input me-2" type="radio" value=""
                                    name="list-radio" />
                                To have a complete 360° overview of sales information, having.
                            </ListGroup.Item>
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="List With badges" customCardClass="custom-card" customCardBodyClass="" dataCode={datalistgroup11} reactCode={Listgroup11} reusableCode={reuseListgroup11}>
                        <SpkListgroup as="ul">
                            {ListbadgesButtons.map((idx, index) => (
                                <ListGroup.Item as="li" key={index}
                                    className="list-group-item d-flex justify-content-between align-items-center fw-medium">
                                    {idx.text1}
                                    <SpkBadge variant={idx.class} Customclass={idx.color}>{idx.text2}</SpkBadge>
                                </ListGroup.Item>
                            ))}
                        </SpkListgroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Horizontal" customCardClass="custom-card" customCardBodyClass="horizontal-listgroup" dataCode={datalistgroup12} reactCode={Listgroup12} reusableCode={reuseListgroup12}>
                        {HorizontalButtons.map((idx, index) => (
                            <SpkListgroup as="ul" CustomClass={`list-group-horizontal${idx.class}`} key={index}>
                                <ListGroup.Item as="li">An item</ListGroup.Item>
                                <ListGroup.Item as="li">A second item</ListGroup.Item>
                                <ListGroup.Item as="li">A third item</ListGroup.Item>
                            </SpkListgroup>
                        ))}
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-3 --> */}

        </Fragment>
    )
};
// Assign layout
ListGroups.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ListGroups;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/general/ui-elements/list-group.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import ShowCode from "@/components/showcode/ShowCode.svelte";
    import {
        dataListgroup1,
        dataListgroup2,
        Listgroup1,
        Listgroup2,
        Listgroup3,
        dataListgroup5,
        Listgroup4,
        Listgroup5,
        dataListgroup7,
        dataListgroup11,
        dataListgroup15,
        dataListgroup16,
        Listgroup11,
        Listgroup12,
        Listgroup13,
        Listgroup14,
        Listgroup15,
        Listgroup16,
        Listgroup6,
        Listgroup7,
        Listgroup8,
        dataListgroup10,
        Listgroup10,
        Listgroup9,
    } from "@/shared/data/prism-code/uielementsprim";
    import {
        Badge,
        Col,
        ListGroupItem,
        Image,
        Row,
    } from "@sveltestrap/sveltestrap";
    import SpkBadge from "@/shared/@spk/uielements/badge/SpkBadge.svelte";
    import {
        ActiveButtons,
        BasicButtons,
        ContextualButtons,
        CustomButtons,
        HorizontalButtons,
        LinksButtons,
        ListbadgesButtons,
        SubheadingsButtons,
    } from "@/shared/data/uielements/listgroupdata";
    import SpkListGroup from "@/shared/@spk/uielements/ListGroup/SpkListGroup.svelte";
</script>

<!-- Page Title -->
<svelte:head>
    <title>ListGroup | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<Pageheader homepage="List Group" activepage="UI Elements" page="List Group" />

<!-- Start:: row-1 -->
<Row>
    <Col xl={6}>
        <ShowCode
            title="Basic List"
            svelteCode={Listgroup1}
            dataCode={dataListgroup1}
        >
            <SpkListGroup>
                {#each BasicButtons as listgroup}
                    <ListGroupItem>
                        <div class="d-flex align-items-center">
                            <span class="avatar avatar-sm">
                                <Image src={listgroup.src} alt="img" />
                            </span>
                            <div class="ms-2 fw-semibold">
                                {listgroup.text}
                            </div>
                        </div>
                    </ListGroupItem>
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title="Active items"
            svelteCode={Listgroup2}
            dataCode={dataListgroup2}
        >
            <SpkListGroup>
                {#each ActiveButtons as listgroup}
                    <ListGroupItem
                        class={`list-group-item ${listgroup.class1}`}
                        aria-current="true"
                    >
                        <div class="d-flex align-items-center">
                            <div>
                                <span class="fs-15">
                                    <i class={`bi bi-${listgroup.class}`}></i>
                                </span>
                            </div>
                            <div class="ms-2">
                                {listgroup.text}
                            </div>
                        </div>
                    </ListGroupItem>
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Disabled items" svelteCode={Listgroup3}>
            <SpkListGroup>
                <ListGroupItem disabled aria-disabled="true"
                    >A disabled item meant to be disabled
                </ListGroupItem>
                <ListGroupItem>Simply dummy text of the printing</ListGroupItem>
                <ListGroupItem
                    >There are many variations of passages</ListGroupItem
                >
                <ListGroupItem>All the Lorem Ipsum generators</ListGroupItem>
                <ListGroupItem
                    >Written in 45 BC. This book is a treatise on the theory</ListGroupItem
                >
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Flush" svelteCode={Listgroup4}>
            <SpkListGroup Flush={true}>
                <ListGroupItem class="fw-semibold"
                    ><i class="bi bi-envelope align-middle me-2 text-muted"
                    ></i>Asish Trivedhi<span
                        class="ms-1 text-muted fw-normal d-inline-block"
                        >(+1023-84534)</span
                    ></ListGroupItem
                >
                <ListGroupItem class="fw-semibold"
                    ><i class="bi bi-tiktok align-middle me-2 text-muted"
                    ></i>Alezander Russo<span
                        class="ms-1 text-muted fw-normal d-inline-block"
                        >(+7546-12342)</span
                    ></ListGroupItem
                >
                <ListGroupItem class="fw-semibold"
                    ><i class="bi bi-whatsapp align-middle me-2 text-muted"
                    ></i>Karem Smith<span
                        class="ms-1 text-muted fw-normal d-inline-block"
                        >(+9944-56632)</span
                    ></ListGroupItem
                >
                <ListGroupItem class="fw-semibold"
                    ><i class="bi bi-facebook align-middle me-2 text-muted"
                    ></i>Melissa Brien<span
                        class="ms-1 text-muted fw-normal d-inline-block"
                        >(+1023-34323)</span
                    ></ListGroupItem
                >
                <ListGroupItem class="fw-semibold"
                    ><i class="bi bi-instagram align-middle me-2 text-muted"
                    ></i>Kamala Harris<span
                        class="ms-1 text-muted fw-normal d-inline-block"
                        >(+91-63421)</span
                    ></ListGroupItem
                >
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title="Links"
            svelteCode={Listgroup5}
            dataCode={dataListgroup5}
        >
            <SpkListGroup>
                {#each LinksButtons as listgroup}
                    <ListGroupItem
                        action
                        tag="a"
                        href="#!"
                        class={`${listgroup.class1}`}
                        aria-current="true"
                    >
                        <div class="d-flex align-items-center">
                            <div>
                                <span
                                    class={`avatar avatar-xs bg-${listgroup.class} text-${listgroup.color} avatar-rounded`}
                                >
                                    {listgroup.text1}
                                </span>
                            </div>
                            <div class="ms-2">{listgroup.text}</div>
                        </div>
                    </ListGroupItem>
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="buttons" svelteCode={Listgroup6}>
            <SpkListGroup>
                <ListGroupItem
                    action
                    tag="button"
                    active
                    class=" "
                    aria-current="true"
                    >Simply dummy text of the printing<span
                        class="badge float-end bg-primary">243</span
                    ></ListGroupItem
                >
                <ListGroupItem action tag="button"
                    >There are many variations of passages<span
                        class="badge float-end bg-secondary-transparent"
                        >35</span
                    ></ListGroupItem
                >
                <ListGroupItem action tag="button"
                    >All the Lorem Ipsum generators<span
                        class="badge float-end bg-info-transparent">132</span
                    ></ListGroupItem
                >
                <ListGroupItem action tag="button"
                    >All the Lorem Ipsum generators<span
                        class="badge float-end bg-success-transparent"
                        >2525</span
                    ></ListGroupItem
                >
                <ListGroupItem action tag="button" disabled
                    >A disabled item meant to be disabled<span
                        class="badge float-end bg-danger-transparent">21</span
                    ></ListGroupItem
                >
            </SpkListGroup>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-1 -->

<!-- Start:: row-2 -->
<Row>
    <Col xl={6}>
        <ShowCode
            title="Contextual classes"
            svelteCode={Listgroup7}
            dataCode={dataListgroup7}
        >
            <SpkListGroup>
                {#each ContextualButtons as listgroup}
                    <ListGroupItem color={listgroup.class}
                        >{listgroup.text}</ListGroupItem
                    >
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title="Contextual classes with hover styles"
            svelteCode={Listgroup8}
            dataCode={dataListgroup7}
        >
            <SpkListGroup>
                {#each ContextualButtons as listgroup}
                    <ListGroupItem action color={listgroup.class}
                        >{listgroup.text}</ListGroupItem
                    >
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-2 -->

<!-- Start:: row-3 -->
<Row>
    <Col xl={6}>
        <ShowCode
            title="Solid Colored Lists"
            svelteCode={Listgroup9}
            dataCode={dataListgroup7}
        >
            <SpkListGroup>
                {#each ContextualButtons as listgroup}
                    <ListGroupItem
                        class={`list-item-solid-${listgroup.class} ${listgroup.class1}`}
                        >{listgroup.text}</ListGroupItem
                    >
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title="Custom content"
            svelteCode={Listgroup10}
            dataCode={dataListgroup10}
        >
            <SpkListGroup>
                {#each CustomButtons as listgroup}
                    <ListGroupItem
                        action
                        class={` ${listgroup.class1}`}
                        aria-current="true"
                    >
                        <div class="d-flex w-100 justify-content-between gap-1">
                            <h6
                                class={`mb-1 fw-semibold text-${listgroup.color}`}
                            >
                                {listgroup.heading}
                            </h6>
                            <small class={listgroup.class2}
                                >{listgroup.text1}</small
                            >
                        </div>
                        <p class="mb-1">{listgroup.text2}</p>
                        <small>{listgroup.text3}.</small>
                    </ListGroupItem>
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-3 -->

<!-- Start:: row-4 -->
<Row>
    <Col xl={6}>
        <ShowCode
            title="Sub headings"
            svelteCode={Listgroup11}
            dataCode={dataListgroup11}
        >
            <SpkListGroup Numbered={true}>
                {#each SubheadingsButtons as listgroup}
                    <ListGroupItem
                        class="list-group-item d-flex justify-content-between align-items-start"
                    >
                        <div class="ms-2 me-auto text-muted">
                            <div class="fw-semibold fs-14 text-default">
                                {listgroup.text1}
                            </div>
                            {listgroup.text2}
                        </div>
                        <SpkBadge CustomClass={listgroup.class}
                            >{listgroup.text3}</SpkBadge
                        >
                    </ListGroupItem>
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Numbered Lists" svelteCode={Listgroup12}>
            <SpkListGroup Numbered={true}>
                <ListGroupItem>Simply dummy text of the printing.</ListGroupItem
                >
                <ListGroupItem
                    >There are many variations of passages.</ListGroupItem
                >
                <ListGroupItem>All the Lorem Ipsum generators.</ListGroupItem>
                <ListGroupItem
                    >Written in 45 BC. This book is a treatise on the theory.</ListGroupItem
                >
                <ListGroupItem>Randomised words which don't look.</ListGroupItem
                >
                <ListGroupItem
                    >Always free from repetition, injected humour.</ListGroupItem
                >
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="List With Checkboxes" svelteCode={Listgroup13}>
            <SpkListGroup>
                <ListGroupItem>
                    <input
                        class="form-check-input me-2 fw-semibold"
                        type="checkbox"
                        value=""
                        aria-label="..."
                        checked
                    />
                    Accurate information at any given point.
                </ListGroupItem>
                <ListGroupItem>
                    <input
                        class="form-check-input me-2 fw-semibold"
                        type="checkbox"
                        value=""
                        aria-label="..."
                    />
                    Hearing the information and responding.
                </ListGroupItem>
                <ListGroupItem>
                    <input
                        class="form-check-input me-2 fw-semibold"
                        type="checkbox"
                        value=""
                        aria-label="..."
                        checked
                    />
                    Setting up and customizing your own sales.
                </ListGroupItem>
                <ListGroupItem>
                    <input
                        class="form-check-input me-2 fw-semibold"
                        type="checkbox"
                        value=""
                        aria-label="..."
                        checked
                    />
                    New Admin Launched.
                </ListGroupItem>
                <ListGroupItem>
                    <input
                        class="form-check-input me-2 fw-semibold"
                        type="checkbox"
                        value=""
                        aria-label="..."
                    />
                    To maximize profits and improve productivity.
                </ListGroupItem>
                <ListGroupItem>
                    <input
                        class="form-check-input me-2 fw-semibold"
                        type="checkbox"
                        value=""
                        aria-label="..."
                    />
                    To have a complete 360° overview of sales information, having.
                </ListGroupItem>
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="List With Radios" svelteCode={Listgroup14}>
            <SpkListGroup>
                <ListGroupItem class="list-group-item">
                    <input
                        class="form-check-input me-2"
                        type="radio"
                        value=""
                        name="list-radio"
                    />
                    Accurate information at any given point.
                </ListGroupItem>
                <ListGroupItem class="list-group-item">
                    <input
                        class="form-check-input me-2"
                        type="radio"
                        value=""
                        name="list-radio"
                    />
                    Hearing the information and responding.
                </ListGroupItem>
                <ListGroupItem class="list-group-item">
                    <input
                        class="form-check-input me-2"
                        type="radio"
                        value=""
                        name="list-radio"
                        checked
                    />
                    Setting up and customizing your own sales.
                </ListGroupItem>
                <ListGroupItem class="list-group-item">
                    <input
                        class="form-check-input me-2"
                        type="radio"
                        value=""
                        name="list-radio"
                    />
                    New Admin Launched.
                </ListGroupItem>
                <ListGroupItem class="list-group-item">
                    <input
                        class="form-check-input me-2"
                        type="radio"
                        value=""
                        name="list-radio"
                    />
                    To maximize profits and improve productivity.
                </ListGroupItem>
                <ListGroupItem class="list-group-item">
                    <input
                        class="form-check-input me-2"
                        type="radio"
                        value=""
                        name="list-radio"
                    />
                    To have a complete 360° overview of sales information, having.
                </ListGroupItem>
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title="List With badges"
            svelteCode={Listgroup15}
            dataCode={dataListgroup15}
        >
            <SpkListGroup>
                {#each ListbadgesButtons as listgroup}
                    <ListGroupItem
                        class="list-group-item d-flex justify-content-between align-items-center fw-semibold"
                    >
                        {listgroup.text1}
                        <Badge color={listgroup.class} class={listgroup.color}
                            >{listgroup.text2}</Badge
                        >
                    </ListGroupItem>
                {/each}
            </SpkListGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title="Horizontal"
            svelteCode={Listgroup16}
            dataCode={dataListgroup16}
        >
            {#each HorizontalButtons as listgroup}
                <SpkListGroup
                    CustomClass={`mb-2 list-group-horizontal${listgroup.class} `}
                >
                    <ListGroupItem>An item</ListGroupItem>
                    <ListGroupItem>A second item</ListGroupItem>
                    <ListGroupItem>A third item</ListGroupItem>
                </SpkListGroup>
            {/each}
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-4 -->
