// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/ui-elements/pagination/pagination.jsx
import MainLayout from "@/Layouts/layout";
import { pagination1, pagination2, pagination3, pagination4, pagination5, pagination6, pagination7, pagination8, pagination9 } from "../../../../shared/data/prism-code/uielements-prism";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col, Pagination, Row } from "react-bootstrap";

const Paginations = () => {

	return (

		<Fragment>

			{/* <!-- Page Header --> */}

			<Head title="Pagination" />

			<Pageheader title="Ui Elements" currentpage="Pagination" activepage="Pagination" />

			{/* <!-- Page Header Close --> */}

			{/* <!-- Start:: row-1 --> */}

			<Row>
				<Col xxl={6} xl={6}>
					<ShowCode title="Basic Pagination" customCardClass="custom-card customclass-pagination" customCardBodyClass="" reactCode={pagination1}>
						<nav aria-label="Page navigation">
							<Pagination className="pagination mb-0">
								<Pagination.Item disabled className="disabled" >Previous</Pagination.Item>
								<Pagination.Item >1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item >Next</Pagination.Item>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
				<Col xxl={6} xl={6}>
					<ShowCode title="Pagination With Icons" customCardClass="custom-card customclass-pagination" customCardBodyClass="" reactCode={pagination2}>
						<nav aria-label="Page navigation">
							<Pagination className="mb-0">
								<Pagination.Item className=""><i className="bx bx-chevron-left align-middle"></i></Pagination.Item>
								<Pagination.Item className="">1</Pagination.Item>
								<Pagination.Item className="">2</Pagination.Item>
								<Pagination.Item className="">3</Pagination.Item>
								<Pagination.Item className=""><span aria-hidden="true"><i className="bx bx-chevron-right align-middle"></i></span></Pagination.Item>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
				<Col xxl={12} xl={12}>
					<ShowCode title="Pagination Sizing" customCardClass="custom-card" customCardBodyClass="d-sm-flex flex-wrap justify-content-between" reactCode={pagination5}>
						<nav aria-label="...">
							<Pagination className="pagination pagination-sm mb-2 mb-sm-0">
								<Pagination.Item active aria-current="page">1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item >3</Pagination.Item>
							</Pagination>
						</nav>
						<nav aria-label="...">
							<Pagination className="pagination  mb-2 mb-sm-0">
								<Pagination.Item active aria-current="page">1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item >3</Pagination.Item>
							</Pagination>
						</nav>
						<nav aria-label="...">
							<Pagination className="pagination pagination-lg mb-2 mb-sm-0">
								<Pagination.Item className=" active" aria-current="page">1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item >3</Pagination.Item>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
			</Row>

			{/* <!-- End:: row-1 --> */}

			{/* <!-- Start:: row-2  --> */}

			<Row>
				<Col xl={12}>
					<ShowCode title="Center & Right Aligned Pagination" customCardClass="custom-card customclass-pagination" customCardBodyClass="" reactCode={pagination4}>
						<nav aria-label="Page navigation">
							<Pagination className="justify-content-center">
								<Pagination.Item disabled>Previous
								</Pagination.Item>
								<Pagination.Item >1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item >Next
								</Pagination.Item>
							</Pagination>
						</nav>
						<nav aria-label="Page navigation">
							<Pagination className="justify-content-end mb-0">
								<Pagination.Item disabled >Previous
								</Pagination.Item>
								<Pagination.Item >1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item >Next
								</Pagination.Item>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>

					<ShowCode title="Active and disabled states" customCardClass="custom-card customclass-pagination" customCardBodyClass="d-flex flex-wrap" reactCode={pagination3}>
						<nav aria-label="..." className="me-3">
							<Pagination className="pagination">
								<Pagination.Item disabled>Previous
								</Pagination.Item>
								<Pagination.Item >1</Pagination.Item>
								<Pagination.Item active aria-current="page" >2
								</Pagination.Item>
								<Pagination.Item >Next
								</Pagination.Item>
							</Pagination>
						</nav>
						<nav aria-label="...">
							<Pagination className="pagination">
								<Pagination.Item disabled>Previous
								</Pagination.Item>
								<Pagination.Item >1</Pagination.Item>
								<Pagination.Item active aria-current="page">2
								</Pagination.Item>
								<Pagination.Item >Next
								</Pagination.Item>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
			</Row>

			{/* <!-- End:: row-2  --> */}

			{/* <!-- Start:: row-3 --> */}

			<Row>
				<Col xl={12}>
					<ShowCode title="Pagination Style-1" customCardClass="custom-card customclass-pagination" customCardBodyClass="" reactCode={pagination6}>
						<nav aria-label="Page navigation" className="pagination-style-1">
							<Pagination className="pagination mb-0">
								<Pagination.Item disabled >
									<i className="ri-arrow-left-s-line align-middle"></i>
								</Pagination.Item>
								<Pagination.Item >1</Pagination.Item>
								<Pagination.Item active >2</Pagination.Item>
								<Pagination.Item ><i className="bi bi-three-dots"></i>
								</Pagination.Item>
								<Pagination.Item >21</Pagination.Item>
								<Pagination.Item >
									<i className="ri-arrow-right-s-line align-middle"></i>
								</Pagination.Item>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Pagination Style-2" customCardClass="custom-card" customCardBodyClass="" reactCode={pagination7}>
						<nav aria-label="Page navigation" className="pagination-style-2">
							<Pagination className="mb-0 flex-wrap">
								<Pagination.Item disabled >Prev</Pagination.Item>
								<Pagination.Item active >1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item ><i className="bi bi-three-dots"></i></Pagination.Item>
								<Pagination.Item >17</Pagination.Item>
								<Pagination.Next linkClassName="text-primary">Next</Pagination.Next>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Pagination Style-3" customCardClass="custom-card" customCardBodyClass="" reactCode={pagination8}>
						<nav aria-label="Page navigation" className="pagination-style-3">
							<Pagination className=" mb-0 flex-wrap">
								<Pagination.Item disabled>Prev</Pagination.Item>
								<Pagination.Item active >1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item ><i className="bi bi-three-dots"></i></Pagination.Item>
								<Pagination.Item >16</Pagination.Item>
								<Pagination.Next linkClassName="text-primary">Next</Pagination.Next>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Pagination Style-4" customCardClass="custom-card" customCardBodyClass="" reactCode={pagination9}>
						<nav aria-label="Page navigation" className="pagination-style-4">
							<Pagination className="mb-0 flex-wrap">
								<Pagination.Item disabled >Prev</Pagination.Item>
								<Pagination.Item active >1</Pagination.Item>
								<Pagination.Item >2</Pagination.Item>
								<Pagination.Item ><i className="bi bi-three-dots"></i></Pagination.Item>
								<Pagination.Item >16</Pagination.Item>
								<Pagination.Item >17</Pagination.Item>
								<Pagination.Next linkClassName="text-primary">Next</Pagination.Next>
							</Pagination>
						</nav>
					</ShowCode>
				</Col>
			</Row>

			{/* <!-- End:: row-3 --> */}

		</Fragment>
	)
};
// Assign layout
Paginations.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Paginations;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/general/ui-elements/pagination.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import ShowCode from "@/components/showcode/ShowCode.svelte";
    import {
        pagination2,
        pagination3,
        pagination1,
        pagination4,
        pagination5,
        pagination6,
        pagination7,
        pagination8,
        pagination9,
    } from "@/shared/data/prism-code/uielementsprim";
    import {
        Col,
        Pagination,
        PaginationItem,
        PaginationLink,
        Row,
    } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Pagination | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<Pageheader homepage="Pagination" activepage="UI Elements" page="Pagination" />
<!-- Start:: row-1 -->
<Row>
    <Col xxl={6} xl={6}>
        <ShowCode
            title="Basic Pagination"
            customCardBodyClass="px-sm-3 px-2"
            svelteCode={pagination1}
        >
            <Pagination class="customPaginationPageBottom">
                <PaginationItem disabled>
                    <PaginationLink
                        on:click={(e) => e.preventDefault()}
                        first
                        href="#!">Previous</PaginationLink
                    >
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink
                        on:click={(e) => e.preventDefault()}
                        href="#!">1</PaginationLink
                    >
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink
                        on:click={(e) => e.preventDefault()}
                        href="#!">2</PaginationLink
                    >
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink
                        on:click={(e) => e.preventDefault()}
                        last
                        href="#!">Next</PaginationLink
                    >
                </PaginationItem>
            </Pagination>
        </ShowCode>
    </Col>
    <Col xxl={6} xl={6}>
        <ShowCode title="Pagination With Icons" svelteCode={pagination2}>
            <Pagination class="customPaginationPageBottom">
                <PaginationItem>
                    <PaginationLink first href="#!"
                        ><span><i class="bx bx-chevron-left align-middle"></i></span
                        ></PaginationLink
                    >
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">1</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">3</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink last href="#!"
                        ><span><i class="bx bx-chevron-right align-middle"></i></span
                        ></PaginationLink
                    >
                </PaginationItem>
            </Pagination>
        </ShowCode>
    </Col>
    <Col xxl={12} xl={12}>
        <ShowCode
            title="Pagination Sizing"
            customCardBodyClass="d-flex flex-wrap justify-content-between gap-2"
            svelteCode={pagination3}
        >
            <Pagination size="sm" class="customPaginationPageBottom">
                <PaginationItem active>
                    <PaginationLink href="#!">1</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink last href="#!">3</PaginationLink>
                </PaginationItem>
            </Pagination>
            <Pagination size="" class="customPaginationPageBottom">
                <PaginationItem active>
                    <PaginationLink href="#!">1</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink last href="#!">3</PaginationLink>
                </PaginationItem>
            </Pagination>
            <Pagination size="lg" class="customPaginationPageBottom">
                <PaginationItem active>
                    <PaginationLink href="#!">1</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink last href="#!">3</PaginationLink>
                </PaginationItem>
            </Pagination>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-1 -->

<!-- Start:: row-2  -->
<Row>
    <Col xl={12}>
        <ShowCode
            title="Center & Right Aligned Pagination"
            customCardBodyClass="overflow-x-scroll"
            svelteCode={pagination4}
        >
            <Pagination
                class="justify-content-center d-flex customPaginationPageBottom"
            >
                <PaginationItem disabled>
                    <PaginationLink first href="#!">Previous</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">1</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink last href="#!">Next</PaginationLink>
                </PaginationItem>
            </Pagination>
            <Pagination
                class="justify-content-sm-end d-flex customPaginationPageBottom"
            >
                <PaginationItem disabled>
                    <PaginationLink first href="#!">Previous</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">1</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink last href="#!">Next</PaginationLink>
                </PaginationItem>
            </Pagination>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode
            title="Active and disabled states"
            customCardBodyClass="d-flex flex-wrap"
            svelteCode={pagination5}
        >
            <Pagination class="customPaginationPageBottom">
                <PaginationItem disabled>
                    <PaginationLink first href="#!">Previous</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">1</PaginationLink>
                </PaginationItem>
                <PaginationItem active>
                    <PaginationLink href="#!">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink last href="#!">Next</PaginationLink>
                </PaginationItem>
            </Pagination>
            <Pagination class="ms-3 customPaginationPageBottom">
                <PaginationItem disabled>
                    <PaginationLink first href="#!">Previous</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">1</PaginationLink>
                </PaginationItem>
                <PaginationItem active>
                    <PaginationLink href="#!">2</PaginationLink>
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink last href="#!">Next</PaginationLink>
                </PaginationItem>
            </Pagination>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-2  -->

<!-- Start:: row-3 -->
<Row>
    <Col xl={12}>
        <ShowCode title="Pagination Style-1" svelteCode={pagination6}>
            <Pagination
                class="pagination-style-1 customPaginationPageBottom"
                listClassName="flex-wrap"
            >
                <PaginationItem disabled>
                    <PaginationLink href="#!">
                        <i class="ri-arrow-left-s-line align-middle"
                        ></i></PaginationLink
                    >
                </PaginationItem>
                <PaginationItem>
                    <PaginationLink href="#!">1</PaginationLink></PaginationItem
                >
                <PaginationItem active>
                    <PaginationLink href="#!">2</PaginationLink></PaginationItem
                >
                <PaginationItem
                    ><PaginationLink href="#!"
                        ><i class="bi bi-three-dots"></i></PaginationLink
                    ></PaginationItem
                >
                <PaginationItem>
                    <PaginationLink href="#!">21</PaginationLink
                    ></PaginationItem
                >
                <PaginationItem
                    ><PaginationLink href="#!">
                        <i class="ri-arrow-right-s-line align-middle"
                        ></i></PaginationLink
                    ></PaginationItem
                >
            </Pagination>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Pagination Style-2" svelteCode={pagination7}>
            <Pagination
                class="pagination-style-2 customPaginationPageBottom"
                listClassName="flex-wrap"
            >
                <PaginationItem disabled>
                    <PaginationLink href="#!">Prev</PaginationLink>
                </PaginationItem>
                <PaginationItem active>
                    <PaginationLink href="#!">1</PaginationLink></PaginationItem
                >
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink></PaginationItem
                >
                <PaginationItem
                    ><PaginationLink href="#!"
                        ><i class="bi bi-three-dots"></i></PaginationLink
                    ></PaginationItem
                >
                <PaginationItem>
                    <PaginationLink href="#!">17</PaginationLink
                    ></PaginationItem
                >
                <PaginationItem
                    ><PaginationLink href="#!" class="text-primary"
                        >Next</PaginationLink
                    ></PaginationItem
                >
            </Pagination>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Pagination Style-3" svelteCode={pagination8}>
            <Pagination
                class="pagination-style-3 customPaginationPageBottom"
                listClassName="flex-wrap"
            >
                <PaginationItem disabled>
                    <PaginationLink href="#!">Prev</PaginationLink>
                </PaginationItem>
                <PaginationItem active>
                    <PaginationLink href="#!">1</PaginationLink></PaginationItem
                >
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink></PaginationItem
                >
                <PaginationItem
                    ><PaginationLink href="#!"
                        ><i class="bi bi-three-dots"></i></PaginationLink
                    ></PaginationItem
                >
                <PaginationItem>
                    <PaginationLink href="#!">16</PaginationLink
                    ></PaginationItem
                >
                <PaginationItem
                    ><PaginationLink href="#!" class="text-primary"
                        >Next</PaginationLink
                    ></PaginationItem
                >
            </Pagination>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Pagination Style-4" svelteCode={pagination9}>
            <Pagination
                class="pagination-style-4 customPaginationPageBottom"
                listClassName="flex-wrap"
            >
                <PaginationItem disabled>
                    <PaginationLink href="#!">Prev</PaginationLink>
                </PaginationItem>
                <PaginationItem active>
                    <PaginationLink href="#!">1</PaginationLink></PaginationItem
                >
                <PaginationItem>
                    <PaginationLink href="#!">2</PaginationLink></PaginationItem
                >
                <PaginationItem
                    ><PaginationLink href="#!"
                        ><i class="bi bi-three-dots"></i></PaginationLink
                    ></PaginationItem
                >
                <PaginationItem>
                    <PaginationLink href="#!">16</PaginationLink
                    ></PaginationItem
                >
                <PaginationItem>
                    <PaginationLink href="#!">17</PaginationLink
                    ></PaginationItem
                >
                <PaginationItem
                    ><PaginationLink href="#!" class="text-primary"
                        >Next</PaginationLink
                    ></PaginationItem
                >
            </Pagination>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-3 -->
