// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/ui-elements/tooltips/tooltips.jsx

import SpkTooltips from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-tooltips";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import { datatooltip1, datatooltip3, reusabletooltip1, reusabletooltip2, reusabletooltip3, reusabletooltip4, reusabletooltip5, reusabletooltip6, tooltip1, tooltip2, tooltip3, tooltip4, tooltip5, tooltip6 } from "../../../../shared/data/prism-code/uielements-prism";
import { SVGtooltip, Tooltipdirtooltip } from "../../../../shared/data/general/ui-elements/tooltipsdata";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col,  Row } from "react-bootstrap";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import { Link ,Head } from "@inertiajs/react";

const Tooltips = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Tooltips" />

            <Pageheader title="Ui Elements" currentpage="Tooltips" activepage="Tooltips" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={12}>
                    <ShowCode title="Tooltip Directions" customCardClass="custom-card" customCardBodyClass="" dataCode={datatooltip1} reactCode={tooltip1} reusableCode={reusabletooltip1}>
                        <div className="btn-list">
                            {Tooltipdirtooltip.map((idx, index) => (
                                <SpkTooltips placement={idx.text} title={`Tooltip on ${idx.text}`} key={index} >
                                    <SpkButton Customclass="btn-wave waves-effect waves-light" Buttontype="button" Buttonvariant="primary">
                                        Tooltip on {idx.text}
                                    </SpkButton>
                                </SpkTooltips>
                            ))}
                        </div>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xl={12}>
                    <ShowCode title="Colored Tooltips" customCardClass="custom-card" customCardBodyClass="" reactCode={tooltip4} reusableCode={reusabletooltip4}>
                        <div className="btn-list">
                            <SpkTooltips placement="top" tooltipClass="tooltip-primary" title="primary Tooltip " trigger={['hover', 'focus']} >
                                <SpkButton Buttontype="button" Buttonvariant='primary'>
                                    Primary Tooltip
                                </SpkButton>
                            </SpkTooltips>
                            <SpkTooltips placement="right" tooltipClass="tooltip-secondary" title="Secondary Tooltip " trigger={['hover', 'focus']} >
                                <SpkButton Buttontype="button" Buttonvariant='secondary'>
                                    Secondary Tooltip
                                </SpkButton>
                            </SpkTooltips>
                            <SpkTooltips placement="top" tooltipClass="tooltip-warning" title="Warning Tooltip " trigger={['hover', 'focus']} >
                                <SpkButton Buttontype="button" Buttonvariant='warning'>
                                    Warning Tooltip
                                </SpkButton>
                            </SpkTooltips>
                            <SpkTooltips placement="top" tooltipClass="tooltip-info" title="Info Tooltip " trigger={['hover', 'focus']} >
                                <SpkButton Buttontype="button" Buttonvariant='info'>
                                    Info Tooltip
                                </SpkButton>
                            </SpkTooltips>
                            <SpkTooltips placement="top" tooltipClass="tooltip-success" title="Success Tooltip " trigger={['hover', 'focus']} >
                                <SpkButton Buttontype="button" Buttonvariant='success'>
                                    Success Tooltip
                                </SpkButton>
                            </SpkTooltips>
                            <SpkTooltips placement="top" tooltipClass="tooltip-danger" title="Danger Tooltip " trigger={['hover', 'focus']} >
                                <SpkButton Buttontype="button" Buttonvariant='danger'>
                                    Danger Tooltip
                                </SpkButton>
                            </SpkTooltips>
                            <SpkTooltips placement="top" tooltipClass="tooltip-light" title="Light Tooltip " trigger={['hover', 'focus']} >
                                <SpkButton Buttontype="button" Buttonvariant='light'>
                                    Light Tooltip
                                </SpkButton>
                            </SpkTooltips>
                            <SpkTooltips placement="top" tooltipClass="tooltip-dark" title="Dark Tooltip " trigger={['hover', 'focus']} >
                                <SpkButton Buttontype="button" Buttonvariant='dark'>
                                    Dark Tooltip
                                </SpkButton>
                            </SpkTooltips>
                        </div>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-3 --> */}

            {/* <!-- Start:: row-2 --> */}

            <Row>
                <Col xl={6}>
                    <ShowCode title="Tooltips on links" customCardClass="custom-card" customCardBodyClass="" reactCode={tooltip2} reusableCode={reusabletooltip2}>
                        <p className="text-muted mb-0">
                            Hover on the link to view the
                            <SpkTooltips placement="top" tooltipClass="tooltip-primary" title="Link Tooltip ">
                                <Link href="#!"  onClick={(e) => e.preventDefault()} className="text-primary ms-1 d-inline-flex">Tooltip</Link>
                            </SpkTooltips>
                        </p>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="With an SVG's" customCardClass="custom-card" customCardBodyClass="" dataCode={datatooltip3} reactCode={tooltip3} reusableCode={reusabletooltip3}>
                        {SVGtooltip.map((idx, index) => (
                            <SpkTooltips key={index} placement="top" tooltipClass={`tooltip-${idx.color}`} title={idx.text}>
                                <Link href="#!" className={`me-3 svg-${idx.color}`}  onClick={(e) => e.preventDefault()}>
                                    <svg xmlns="http://www.w3.org/2000/svg" className={`svg-${idx.color}`} height="24px" viewBox="0 0 24 24" width="24px" fill="#000000">
                                        <path d="M0 0h24v24H0V0z" fill="none" /><path
                                            d={idx.class} /></svg>
                                </Link>
                            </SpkTooltips>
                        ))}
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-2 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xl={6}>
                    <ShowCode title="Disabled elements" customCardClass="custom-card" customCardBodyClass="" reactCode={tooltip5} reusableCode={reusabletooltip5}>
                        <SpkTooltips id="tooltip-disabled" title="Disabled tooltip" trigger={['hover', 'focus']} >
                            <span className="d-inline-block">
                                <SpkButton Disabled={true} Customclass="btn-primary" Style={{ pointerEvents: "none" }}>
                                    Disabled button
                                </SpkButton>
                            </span>
                        </SpkTooltips>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Tooltip For Images" customCardClass="custom-card" customCardBodyClass="" reactCode={tooltip6} reusableCode={reusabletooltip6}>
                        <SpkTooltips placement="top" tooltipClass="tooltip-primary" title="Alex Carey">
                            <Link href="#!"  onClick={(e) => e.preventDefault()}
                                className="avatar avatar-md me-2 online avatar-rounded">
                                <BaseImage src="/build/assets/images/faces/12.jpg" alt="img" />
                            </Link>
                        </SpkTooltips>

                        <SpkTooltips placement="top" tooltipClass="tooltip-primary" title="Marina Kai">
                            <Link href="#!"  onClick={(e) => e.preventDefault()}
                                className="avatar avatar-lg me-2 online avatar-rounded">
                                <BaseImage src="/build/assets/images/faces/3.jpg" alt="img" />
                            </Link>
                        </SpkTooltips>
                        <SpkTooltips placement="top" tooltipClass="tooltip-primary" title="Tim Cook">
                            <Link href="#!"  onClick={(e) => e.preventDefault()}
                                className="avatar avatar-xl me-2 offline avatar-rounded">
                                <BaseImage src="/build/assets/images/faces/15.jpg" alt="img" />
                            </Link>
                        </SpkTooltips>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-3 --> */}

        </Fragment>
    )
};
// Assign layout
Tooltips.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Tooltips;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/general/ui-elements/tooltips.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import SpkTooltips from "@/shared/@spk/uielements/Tooltips/SpkTooltips.svelte";
    import { Col, Row } from "@sveltestrap/sveltestrap";
    import ShowCode from "@/components/showcode/ShowCode.svelte";
    import {
        datatooltip1,
        tooltip1,
        tooltip2,
        datatooltip2,
        datatooltip4,
        tooltip3,
        tooltip4,
        tooltip5,
        tooltip6,
    } from "@/shared/data/prism-code/uielementsprim";
    import {
        Coloredtooltip,
        SVGtooltip,
        Tooltipdirtooltip,
    } from "@/shared/data/uielements/tooltipsdata";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Tooltips | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<Pageheader homepage="Tooltips" activepage="UI Elements" page="Tooltips" />
<!-- Start:: row-1 -->
<Row>
    <Col xl={12}>
        <ShowCode
            title="Tooltip Directions"
            customCardClass=""
            svelteCode={tooltip1}
            dataCode={datatooltip1}
        >
            <div class="btn-list">
                {#each Tooltipdirtooltip as tooltip (tooltip.id)}
                    <SpkButton
                        id={`tooltipButton-${tooltip.id}`}
                        color="primary"
                        text={tooltip.text}
                    />
                    <SpkTooltips
                        customClass=""
                        targetId={`tooltipButton-${tooltip.id}`}
                        content={tooltip.text}
                        placement={tooltip.text.split(" ")[2]}
                    />
                {/each}
            </div>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-1 -->

<!-- Start:: row-2 -->
<Row>
    <Col xl={12}>
        <ShowCode
            title="Colored Tooltips"
            customCardClass=""
            svelteCode={tooltip2}
            dataCode={datatooltip2}
        >
            <div class="btn-list">
                {#each Coloredtooltip as tooltip (tooltip.id)}
                    <SpkButton
                        id={`tooltip-${tooltip.id}`}
                        color={tooltip.color}
                        text={tooltip.text}
                    />
                    <SpkTooltips
                        placement={tooltip.placement}
                        customClass={`tooltip-${tooltip.color}`}
                        targetId={`tooltip-${tooltip.id}`}
                        content={tooltip.text}
                    />
                {/each}
            </div>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-2 -->

<!-- Start:: row-3 -->
<Row>
    <Col xl={6}>
        <ShowCode title="Tooltips on links" svelteCode={tooltip3}>
            <p class="text-muted mb-0">
                Hover on the link to view the
                <a href="#!" id="link" class="text-primary ms-1 d-inline-flex"
                    >Tooltip
                </a>
                <SpkTooltips
                    placement="top"
                    customClass={`tooltip-primary`}
                    targetId="link"
                    content=" Link Tooltip"
                />
            </p>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title="With an SVG's"
            svelteCode={tooltip4}
            dataCode={datatooltip4}
        >
            <!-- svelte-ignore a11y_consider_explicit_label -->
            {#each SVGtooltip as tooltip (tooltip.id)}
                <a
                    href="#!"
                    id={`svgtooltip-${tooltip.id}`}
                    class={`me-3 svg-${tooltip.color}`}
                >
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class={`svg-${tooltip.color}`}
                        height="24px"
                        viewBox="0 0 24 24"
                        width="24px"
                        fill="#000000"
                    >
                        <path d="M0 0h24v24H0V0z" fill="none" /><path
                            d={tooltip.class}
                        /></svg
                    >
                </a>
                <SpkTooltips
                    placement="top"
                    customClass={`tooltip-${tooltip.color}`}
                    targetId={`svgtooltip-${tooltip.id}`}
                    content={tooltip.text}
                />
            {/each}
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Disabled elements" svelteCode={tooltip5}>
            <span id="tooltip-disabled" class="d-inline-block">
                <SpkButton
                    color="primary"
                    disabled={true}
                    text="Disabled button"
                />
            </span>
            <SpkTooltips
                placement="top"
                targetId="tooltip-disabled"
                content="Disabled tooltip"
            />
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Tooltip For Images" svelteCode={tooltip6}>
            <a
                href="#!"
                id="Alex"
                class="avatar avatar-md me-2 online avatar-rounded"
            >
                <img
                    loading="lazy"
                    src="../../images/faces/12.jpg"
                    alt="img"
                /></a
            >
            <SpkTooltips
                placement="top"
                customClass={`tooltip-primary`}
                targetId="Alex"
                content="Alex Carey"
            />
            <a
                href="#!"
                id="Marina"
                class="avatar avatar-lg me-2 online avatar-rounded"
            >
                <img
                    loading="lazy"
                    src="../../images/faces/3.jpg"
                    alt="img"
                /></a
            >
            <SpkTooltips
                placement="top"
                customClass={`tooltip-primary`}
                targetId="Marina"
                content="Marina Kai"
            />
            <a
                href="#!"
                id="Tim"
                class="avatar avatar-xl me-2 online avatar-rounded"
            >
                <img
                    loading="lazy"
                    src="../../images/faces/15.jpg"
                    alt="img"
                /></a
            >
            <SpkTooltips
                placement="top"
                customClass={`tooltip-primary`}
                targetId="Tim"
                content="Tim Cook"
            />
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-3 -->
