// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/general/advanced-ui/carousel.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Carousel from "svelte-carousel";
    import { Col, Row } from "@sveltestrap/sveltestrap";
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import ShowCode from "@/components/showcode/ShowCode.svelte";
    import {
        carousel1,
        carousel2,
        carousel3,
        datacarousel2,
        carousel9,
        datacarousel9,
        datacarousel3,
        datacarousel1,
        carousel7,
        carousel8,
    } from "@/shared/data/prism-code/advanceuiprism.js";
    import {
        SlidesOnly,
        Controls,
        Indicators,
        AutoPlay,
    } from "@/shared/data/adavanec-ui/carouseldata.js";
    import Slidewithcaption from "@/view/carousel/Slidewithcaption.svelte";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Carousel | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader homepage="Carousel" activepage="Advanced Ui" page="Carousel" />
<!-- Page Header Close -->

<!-- Start:: row-1 -->
<Row>
    <Col xl={4} lg={6} md={6} sm={12}>
        <ShowCode
            title="Slides Only"
            svelteCode={carousel1}
            dataCode={datacarousel1}
        >
            <!-- {#if browser} -->
                <!-- Ensure carousel only renders in the browser (client-side) -->
                <Carousel
                    particlesToShow={1}
                    particlesToScroll={1}
                    arrows={false}
                    dots={false}
                    autoplay
                    autoplayDuration={3000}
                >
                    <!-- Loop through images array and render each image -->
                    {#each SlidesOnly as src}
                        <div class="item">
                            <img
                                loading="lazy"
                                {src}
                                alt=""
                                class="d-block w-100"
                            />
                        </div>
                    {/each}
                </Carousel>
            <!-- {/if} -->
        </ShowCode>
    </Col>
    <Col xl={4} lg={6} md={6} sm={12}>
        <ShowCode
            title="With controls"
            svelteCode={carousel2}
            dataCode={datacarousel2}
        >
            <!-- {#if browser} -->
                <!-- Ensure carousel only renders in the browser (client-side) -->
                <Carousel
                    particlesToShow={1}
                    particlesToScroll={1}
                    arrows={true}
                    dots={false}
                    autoplay
                    autoplayDuration={3000}
                >
                    <!-- Loop through images array and render each image -->
                    {#each Controls as src}
                        <div class="item">
                            <img
                                loading="lazy"
                                {src}
                                alt=""
                                class="d-block w-100"
                            />
                        </div>
                    {/each}
                </Carousel>
            <!-- {/if} -->
        </ShowCode>
    </Col>
    <Col xl={4} lg={6} md={6} sm={12}>
        <ShowCode
            title="With indicators"
            svelteCode={carousel3}
            dataCode={datacarousel3}
        >
            <!-- {#if browser} -->
                <!-- Ensure carousel only renders in the browser (client-side) -->
                <Carousel
                    particlesToShow={1}
                    particlesToScroll={1}
                    arrows={true}
                    dots={true}
                    autoplay
                    autoplayDuration={3000}
                >
                    <!-- Loop through images array and render each image -->
                    {#each Indicators as src}
                        <div class="item">
                            <img
                                loading="lazy"
                                {src}
                                alt=""
                                class="d-block w-100"
                            />
                        </div>
                    {/each}
                </Carousel>
            <!-- {/if} -->
        </ShowCode>
    </Col>
   
    <Col xl={4} lg={6} md={6} sm={12}>
        <ShowCode
            title="Autoplay with duration progress"
            svelteCode={carousel7}
        >
            <!-- {#if browser} -->
                <Carousel
                    particlesToShow={1}
                    particlesToScroll={1}
                    autoplay
                    arrows={true}
                    autoplayDuration={3000}
                    autoplayProgressVisible
                >
                    {#each AutoPlay as src}
                        <div class="item">
                            <img
                                loading="lazy"
                                {src}
                                alt=""
                                class="d-block w-100"
                            />
                        </div>
                    {/each}
                </Carousel>
            <!-- {/if} -->
        </ShowCode>
    </Col>
    <Col xl={4} lg={6} md={6} sm={12}>
        <ShowCode title="Autoplay with pause on focus" svelteCode={carousel8}>
            <!-- {#if browser} -->
                <Carousel
                    autoplay
                    autoplayDuration={5000}
                    autoplayProgressVisible
                    pauseOnFocus
                >
                    {#each AutoPlay as src}
                        <div class="item">
                            <img
                                loading="lazy"
                                {src}
                                alt=""
                                class="d-block w-100"
                            />
                        </div>
                    {/each}
                </Carousel>
            <!-- {/if} -->
        </ShowCode>
    </Col>
    <Col xl={4} lg={6} md={6} sm={12}>
        <ShowCode
            title="With captions"
            svelteCode={carousel9}
            dataCode={datacarousel9}
        >
            <Slidewithcaption />
        </ShowCode>
    </Col>

</Row>
<!-- End:: row-4 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/advanced-ui/carousel/carousel.jsx

import MainLayout from "@/Layouts/layout";
import SpkCarouselComponent from "../../../../shared/@spk-reusable-components/general-reusable/reusable-advancedui/spk-carousel";
import { Captioncarousel, Carouseldata, Crosscarousel, Darkcarousel, Disablecarousel, Indicatorcarousel, Individualcarousel, Slidecarousel } from "../../../../shared/data/general/adavanec-ui/carouseldata";
import { carousel1, carousel2, carousel3, carousel4, carousel5, carousel6, carousel7, carousel8, reusablecarousel1, reusablecarousel2, reusablecarousel3, reusablecarousel4, reusablecarousel5, reusablecarousel6, reusablecarousel7, reusablecarousel8 } from "../../../../shared/data/prism-code/advanced-ui-prism";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col, Row } from "react-bootstrap"

const Carousel = () => {
    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Carousel"} />

            <Pageheader title="Advanced Ui" currentpage="Carousel" activepage="Carousel" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={4} lg={6} md={6} sm={12}>
                    <ShowCode title="Slides Only" customCardHeaderClass="" reactCode={carousel3} reusableCode={reusablecarousel3}>
                        <SpkCarouselComponent mainClass="custom-slide-carousel" items={Slidecarousel} />
                    </ShowCode>
                </Col>
                <Col xl={4} lg={6} md={6} sm={12}>
                    <ShowCode title="With controls" customCardHeaderClass="" reactCode={carousel1} reusableCode={reusablecarousel1}>
                        <SpkCarouselComponent items={Carouseldata} controls={true} />
                    </ShowCode>
                </Col>
                <Col xl={4} lg={6} md={6} sm={12}>
                    <ShowCode title="With indicators" customCardHeaderClass="" reactCode={carousel2} reusableCode={reusablecarousel2}>
                        <SpkCarouselComponent items={Indicatorcarousel} mainClass="carousel slide" controls={true} indicators={true} />
                    </ShowCode>
                </Col>
                <Col xl={4} lg={6} md={6} sm={12}>
                    <ShowCode title="With captions" customCardHeaderClass="" reactCode={carousel4} reusableCode={reusablecarousel4}>
                        <SpkCarouselComponent items={Captioncarousel} mainClass="carousel slide" controls={true} indicators={true} />
                    </ShowCode>
                </Col>
                <Col xl={4} lg={6} md={6} sm={12}>
                    <ShowCode title="Crossfade" customCardHeaderClass="" reactCode={carousel6} reusableCode={reusablecarousel6}>
                        <SpkCarouselComponent items={Crosscarousel} fade={true} mainClass="carousel slide carousel-fade" controls={true} indicators={false} />
                    </ShowCode>
                </Col>
                <Col xl={4} lg={6} md={6} sm={12}>
                    <ShowCode title="Individual .carousel-item interval" customCardHeaderClass="" reactCode={carousel5} reusableCode={reusablecarousel5}>
                        <SpkCarouselComponent interval1={1000} items={Individualcarousel} mainClass="carousel slide" controls={true} indicators={false} />
                    </ShowCode>
                </Col>
                <Col xxl={4} md={6}>
                    <ShowCode title="Disable touch swiping" customCardHeaderClass="" reactCode={carousel7} reusableCode={reusablecarousel7}>
                        <SpkCarouselComponent items={Disablecarousel} mainClass="carousel slide" controls={true} indicators={false}
                            data-bs-interval="false" />
                    </ShowCode>
                </Col>
                <Col xxl={4} md={6}>
                    <ShowCode title="Dark variant" customCardHeaderClass="" reactCode={carousel8} reusableCode={reusablecarousel8}>
                        <SpkCarouselComponent items={Darkcarousel} mainClass="carousel slide " controls={true} indicators={true} />
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

        </Fragment>
    )
};
// Assign layout
Carousel.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Carousel;
