// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/authentication/sign-in/basic/basic.jsx

import SpkButton from "../../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import React, { Fragment, useState } from "react";
import { Card, Col, Form, Image, Row } from "react-bootstrap";
import { Head, Link, router } from "@inertiajs/react";
import { toast, ToastContainer } from "react-toastify";
import AuthenticationLayout from "@/Layouts/authenticationlayout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const Basic = () => {

    const [values, setValues] = useState({
        email: 'tomphillip21@gmail.com',
        password: '12345678',
        showPassword: false
    });

    const [errors, setErrors] = useState({});

    const validate = () => {
        const newErrors = {};

        // Email validation
        if (!values.email) {
            newErrors.email = "Email is required.";
        } else if (!/\S+@\S+\.\S+/.test(values.email)) {
            newErrors.email = "Invalid email format.";
        }

        // Password validation
        if (!values.password) {
            newErrors.password = "Password is required.";
        } else if (values.password.length < 6) {
            newErrors.password = "Password must be at least 6 characters.";
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        if (validate()) {
            router.get(`${__APP_BASE_PATH__}/dashboards/sales`);
            toast.success('Login successful', {
                position: 'top-right',
                autoClose: 1500,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                draggable: true,
            });
            // Handle form submission logic here
        }
    };


    return (

        <Fragment>

            <Head title="Signin-Basic" />

            <div className="authentication-basic-background">
                <BaseImage src="/build/assets/images/media/backgrounds/9.png" alt="" />
            </div>
            <div className="container">
                <Row className="justify-content-center align-items-center authentication authentication-basic h-100">
                    <Col xxl={4} xl={5} lg={6} md={6} sm={8} className="col-12">
                        <Card className="custom-card border-0 my-4">
                            <Card.Body className="p-5 custom-sign">
                                <div className="mb-4">
                                    <Link href={`${__APP_BASE_PATH__}/dashboards/sales`}>
                                        <BaseImage src="/build/assets/images/brand-logos/toggle-logo.png" alt="logo" className="desktop-dark" />
                                    </Link>
                                </div>
                                <div>
                                    <h4 className="mb-1 fw-semibold">Hi,Welcome back!</h4>
                                    <p className="mb-4 text-muted fw-normal text-nowrap">Please enter your credentials</p>
                                </div>
                                <Form onSubmit={handleSubmit}>
                                    <div className="row gy-3">
                                        <Col xl={12}>
                                            <Form.Label htmlFor="signin-email" className="text-default">Email</Form.Label>
                                            <Form.Control
                                                type="email"
                                                className="form-control "
                                                id="signup-firstname"
                                                placeholder="Enter Email ID"
                                                value={values.email}
                                                onChange={(e) => setValues({ ...values, email: e.target.value })}
                                                isInvalid={!!errors.email}
                                            />
                                            <Form.Control.Feedback type="invalid">{errors.email}</Form.Control.Feedback>
                                        </Col>
                                        <Col xl={12} className="mb-2">
                                            <Form.Label htmlFor="signin-password" className="text-default d-block">Password</Form.Label>
                                            <div className="position-relative">
                                                <Form.Control
                                                    type={values.showPassword ? "text" : "password"}
                                                    className="form-control "
                                                    id="signup-password"
                                                    placeholder="Password"
                                                    value={values.password}
                                                    onChange={(e) => setValues({ ...values, password: e.target.value })}
                                                    isInvalid={!!errors.password}
                                                />
                                                <BaseLink href="#!" className="show-password-button text-muted"
                                                    onClick={() => setValues((prev) => ({ ...prev, showPassword: !prev.showPassword }))}>
                                                    {values.showPassword ? (
                                                        <i className="ri-eye-line align-middle"></i>
                                                    ) : (
                                                        <i className="ri-eye-off-line align-middle"></i>
                                                    )}
                                                </BaseLink>
                                                <Form.Control.Feedback type="invalid">{errors.password}</Form.Control.Feedback>
                                            </div>
                                            <div className="mt-2">
                                                <div className="form-check">
                                                    <input className="form-check-input" type="checkbox" defaultValue="" id="defaultCheck1" defaultChecked />
                                                    <label className="form-check-label" htmlFor="defaultCheck1">
                                                        Remember me
                                                    </label>
                                                    <Link href={`${__APP_BASE_PATH__}/pages/authentication/reset-password/basic/`} className="float-end link-danger fw-medium fs-12">Forget password ?</Link>
                                                </div>
                                            </div>
                                        </Col>
                                    </div>
                                    <div className="d-grid mt-3">
                                        <SpkButton Buttontype="submit" Customclass="btn btn-primary">Sign In</SpkButton>
                                    </div>
                                </Form>
                                <div className="text-center my-3 authentication-barrier">
                                    <span className="op-4 fs-13">OR</span>
                                </div>
                                <div className="d-grid mb-3">
                                    <SpkButton Customclass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill mb-3">
                                        <span className="avatar avatar-xs">
                                            <BaseImage src="/build/assets/images/media/apps/google.png" alt="" />
                                        </span>
                                        <span className="lh-1 ms-2 fs-13 text-default fw-medium">Signup with Google</span>
                                    </SpkButton>
                                    <SpkButton Customclass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill">
                                        <span className="avatar avatar-xs">
                                            <BaseImage src="/build/assets/images/media/apps/facebook.png" alt="" />
                                        </span>
                                        <span className="lh-1 ms-2 fs-13 text-default fw-medium">Signup with Facebook</span>
                                    </SpkButton>
                                </div>
                                <div className="text-center mt-3 fw-medium">
                                    Dont have an account? <Link href={`${__APP_BASE_PATH__}/pages/authentication/sign-up/basic/`} className="text-primary">Sign Up</Link>
                                </div>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
                <ToastContainer />
            </div>
        </Fragment>
    )
};
// Assign layout
Basic.layout = (page) => <AuthenticationLayout>{page}</AuthenticationLayout>;
export default Basic;

// Dashboard Template/vyzor-svelte/final/src/routes/(auth)/authentication/sign-in/basic/+page.svelte
<script lang="ts">
    import {
        Card,
        CardBody,
        Col,
        Form,
        Image,
        Input,
        Label,
        Row,
    } from "@sveltestrap/sveltestrap";
    import { goto } from "$app/navigation";
    import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";
    import { onMount } from "svelte";
    import { base } from "$app/paths";
    const basePath =base
    let values = {
        email: "",
        password: "",
        showPassword: false,
    };
    let errors: Record<string, string> = {};

    const validate = () => {
        const newErrors: Record<string, string> = {};

        // Email validation
        if (!values.email) {
            newErrors.email = "Email is required.";
        } else if (!/\S+@\S+\.\S+/.test(values.email)) {
            newErrors.email = "Invalid email format.";
        }

        // Password validation
        if (!values.password) {
            newErrors.password = "Password is required.";
        } else if (values.password.length < 6) {
            newErrors.password = "Password must be at least 6 characters.";
        }

        errors = newErrors;
        return Object.keys(newErrors).length === 0;
    };
    let matched: string;
    const handleSubmit = (event: Event) => {
        event.preventDefault();
        if (validate()) {
            (matched = "Save Password successful"), goto(`${basePath}/dashboards/sales/`);
        }
    };

    const togglePassword = () => {
        values.showPassword = !values.showPassword;
    };

     const setBodyClass = (action: string) => {
        if (action === "add") {
            document.body.classList.add(
                "authentication-background",
                "authenticationcover-background",
                "position-relative",
            );
            document.body.style.display = "block";
        } else {
            document.body.classList.remove(
                "authentication-background",
                "authenticationcover-background",
                "position-relative",
            );
            document.body.style.display = "none";
        }
    };

    onMount(() => {
        if (localStorage.getItem("visited") === "true") {
            setBodyClass("add");
        } else {
            setBodyClass("add");
            localStorage.setItem("visited", "true");
        }

        const handleBeforeUnload = () => {
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };

        window.addEventListener("beforeunload", handleBeforeUnload);

        return () => {
            window.removeEventListener("beforeunload", handleBeforeUnload);
            setBodyClass("remove");
            localStorage.removeItem("visited");
            document.body.removeAttribute("style");
        };
    });
</script>

<!-- Page Title -->
<svelte:head>
    <title>Signin-Basic | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<div class="authentication-basic-background">
    <Image src="../../images/media/backgrounds/9.png" alt="" />
</div>
<div class="container">
    <Row
        class="justify-content-center align-items-center authentication authentication-basic h-100"
    >
        <Col xxl={4} xl={5} lg={6} md={6} sm={8} class="col-12">
            <Card class="custom-card border-0 my-4">
                <CardBody class="p-5">
                    <div class="mb-4">
                        <a href={`${basePath}/dashboards/sales/`}>
                            <Image
                                src="../../images/brand-logos/toggle-logo.png"
                                alt="logo"
                                class="desktop-dark"
                            />
                        </a>
                    </div>
                    <div>
                        <h4 class="mb-1 fw-semibold">Hi,Welcome back!</h4>
                        <p class="mb-4 text-muted fw-normal">
                            Please enter your credentials
                        </p>
                    </div>
                    <Form on:submit={handleSubmit}>
                        <div class="row gy-3">
                            <Col xl={12}>
                                <Label for="signin-email" class="text-default"
                                    >Email</Label
                                >
                                <Input
                                    type="email"
                                    class="form-control "
                                    id="signup-firstname"
                                    placeholder="Enter Email ID"
                                    bind:value={values.email}
                                />
                                {#if errors.email}
                                    <p class="text-danger text-sm">
                                        {errors.email}
                                    </p>
                                {/if}
                            </Col>
                            <Col xl={12} class="mb-2">
                                <Label
                                    for="signin-password"
                                    class="text-default d-block">Password</Label
                                >
                                <div class="position-relative">
                                    <Input
                                        type={values.showPassword
                                            ? "text"
                                            : "password"}
                                        class="form-control "
                                        id="signup-password"
                                        placeholder="Password"
                                        bind:value={values.password}
                                    />
                                    <a
                                        href="#!"
                                        class="show-password-button text-muted"
                                        on:click={togglePassword}
                                    >
                                        {#if values.showPassword}
                                            <i class="ri-eye-line align-middle"
                                            ></i>
                                        {:else}
                                            <i
                                                class="ri-eye-off-line align-middle"
                                            ></i>
                                        {/if}
                                    </a>
                                    {#if errors.password}
                                        <p class="text-danger text-sm">
                                            {errors.password}
                                        </p>
                                    {/if}
                                    {#if matched}
                                        <p class="text-success text-sm">
                                            {errors.password}
                                        </p>
                                    {/if}
                                </div>
                                <div class="mt-2">
                                    <div class="form-check">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            defaultValue=""
                                            id="defaultCheck1"
                                            defaultChecked
                                        />
                                        <label
                                            class="form-check-label"
                                            for="defaultCheck1"
                                        >
                                            Remember me
                                        </label>
                                        <a
                                            href={`${basePath}/authentication/reset-password/basic/`}
                                            class="float-end link-danger fw-medium fs-12"
                                            >Forget password ?</a
                                        >
                                    </div>
                                </div>
                            </Col>
                        </div>
                        <div class="d-grid mt-3">
                            <SpkButton
                                buttontype="submit"
                                customClass="btn btn-primary">Sign In</SpkButton
                            >
                        </div>
                    </Form>
                    <div class="text-center my-3 authentication-barrier">
                        <span class="op-4 fs-13">OR</span>
                    </div>
                    <div class="d-grid mb-3">
                        <SpkButton
                            customClass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill mb-3"
                        >
                            <span class="avatar avatar-xs">
                                <Image
                                    src="../../images/media/apps/google.png"
                                    alt=""
                                />
                            </span>
                            <span class="lh-1 ms-2 fs-13 text-default fw-medium"
                                >Signup with Google</span
                            >
                        </SpkButton>
                        <SpkButton
                            customClass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill"
                        >
                            <span class="avatar avatar-xs">
                                <Image
                                    src="../../images/media/apps/facebook.png"
                                    alt=""
                                />
                            </span>
                            <span class="lh-1 ms-2 fs-13 text-default fw-medium"
                                >Signup with Facebook</span
                            >
                        </SpkButton>
                    </div>
                    <div class="text-center mt-3 fw-medium">
                        Dont have an account? <a
                            href={`${basePath}/authentication/sign-up/basic/`}
                            class="text-primary">Sign Up</a
                        >
                    </div>
                </CardBody>
            </Card>
        </Col>
    </Row>
</div>
