// Dashboard Template/vyzor-svelte/final/src/routes/(auth)/authentication/coming-soon/+page.svelte
<script lang="ts">
    import Timer from "$lib/view/Timer.svelte";
    import { Col, Image, Input, Row } from "@sveltestrap/sveltestrap";
    import { onMount, onDestroy } from "svelte";
    import { base } from "$app/paths";
    const basePath = base;

    const setBodyClass = (action: string) => {
        if (action === "add") {
            document.body.classList.add(
                "coming-soon-main",
                "position-relative",
            );
        } else {
            document.body.classList.remove(
                "coming-soon-main",
                "position-relative",
            );
        }
    };

    onMount(() => {
        if (localStorage.getItem("visited") === "true") {
            setBodyClass("add");
        } else {
            setBodyClass("add");
            localStorage.setItem("visited", "true");
        }

        const handleBeforeUnload = () => {
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };

        window.addEventListener("beforeunload", handleBeforeUnload);

        return () => {
            window.removeEventListener("beforeunload", handleBeforeUnload);
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };
    });
</script>

<!-- Page Title -->
<svelte:head>
    <title>ComingSoon | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<div class="coming-soon-background">
    <Image src="../images/media/backgrounds/9.png" alt="" />
</div>
<Row class="authentication coming-soon g-0 my-4 justify-content-center">
    <Col xxl={7} xl={7} lg={7} md={7} sm={7} class=" col-11 my-auto">
        <div class="authentication-cover text-center">
            <div class="authentication-cover-content">
                <div
                    class="row justify-content-center align-items-center mx-0 g-0"
                >
                    <div
                        class="col-xxl-7 col-xl-7 col-lg-7 col-md-12 col-sm-12 col-12"
                    >
                        <div>
                            <div class="mb-3">
                                <a href={`${basePath}/dashboards/sales`}>
                                    <img
                                        src="../images/brand-logos/desktop-logo.png"
                                        alt=""
                                        class="authentication-brand"
                                    />
                                    <img
                                        src="../images/brand-logos/desktop-dark.png"
                                        alt=""
                                        class="authentication-brand dark"
                                    />
                                </a>
                            </div>
                            <h1 class="mb-0">Coming Soon</h1>
                            <Timer />
                            <p class="mb-4 fs-18">
                                Big things are coming your way! We're putting
                                the final touches <br /> on something amazing. Stay
                                tuned!
                            </p>
                            <div class="input-group">
                                <Input
                                    type="email"
                                    class="form-control form-control-lg"
                                    placeholder="info@gmail.com"
                                    aria-label="info@gmail.com"
                                    aria-describedby="button-addon2"
                                />
                                <button
                                    class="btn btn-primary btn-lg"
                                    type="button"
                                    id="button-addon2">Subscribe</button
                                >
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </Col>
</Row>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/authentication/coming-soon/coming-soon.jsx

import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import { DayCounter } from "../../../../shared/data/authentication/comingsoondata";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Col, Form } from "react-bootstrap";
import ParticleCard from "../../../../shared/data/authentication/particles";
import { Link } from "@inertiajs/react";
import AuthenticationLayout from "@/Layouts/authenticationlayout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const ComingSoon = () => {

    return (

        <Fragment>
            <Head title="Coming Soon" />
            <div className="coming-soon-background">
                <BaseImage src="/build/assets/images/media/backgrounds/9.png" alt="" />
            </div>
            <ParticleCard />
            <div className="row authentication coming-soon g-0 my-4 justify-content-center">
                <Col xxl={7} xl={7} lg={7} md={7} sm={7} className="col-11 my-auto">
                    <div className="authentication-cover text-center">
                        <div className="authentication-cover-content">
                            <div className="row justify-content-center align-items-center mx-0 g-0">
                                <Col xxl={7} xl={7} lg={7} md={12} sm={12} className="col-12">
                                    <div>
                                        <div className="mb-3">
                                            <Link href={`${__APP_BASE_PATH__}/dashboards/sales`}>
                                                <BaseImage src="/build/assets/images/brand-logos/desktop-logo.png" alt="" className="authentication-brand" />
                                                <BaseImage src="/build/assets/images/brand-logos/desktop-dark.png" alt="" className="authentication-brand dark" />
                                            </Link>
                                        </div>
                                        <h1 className="mb-0">Coming Soon</h1>
                                        <DayCounter />
                                        <p className="mb-4 fs-18">Big things are coming your way! We're putting the final touches <br /> on something amazing. Stay tuned!</p>
                                        <div className="input-group">
                                            <Form.Control type="email" className="form-control-lg" placeholder="info@gmail.com" aria-label="info@gmail.com" aria-describedby="button-addon2" />
                                            <SpkButton Buttonvariant="primary" Customclass="btn btn-lg" Buttontype="button">Subscribe</SpkButton>
                                        </div>
                                    </div>
                                </Col>
                            </div>
                        </div>
                    </div>
                </Col>
            </div>
        </Fragment>
    )
};
// Assign layout
ComingSoon.layout = (page) => <AuthenticationLayout>{page}</AuthenticationLayout>;
export default ComingSoon;
