// Dashboard Template/vyzor-svelte/final/src/lib/@spk/reusable-widgets/spk-productscard.svelte
<script lang="ts">
    import { Col } from "@sveltestrap/sveltestrap";

    interface ProductCardProps {
        color?: string;
        svgIcon?: string;
        title?: string;
        value?: string | number;
        percentage?: string;
        percentageColor?: string;
    }

    export let products: ProductCardProps = {};
</script>
 <Col xxl={2} xl={3} lg={4} md={6}>
        <div class="text-center">
          <div class="lh-1 mb-3">
            <span class={`avatar avatar-lg bg-${products.color}-transparent avatar-rounded`}>
              <span class={`avatar avatar-sm bg-${products.color} avatar-rounded svg-white`}>
                {@html products.svgIcon}
              </span>
            </span>
          </div>
          <span class="d-block mb-1">{products.title}</span>
          <h5 class="fw-semibold">{products.value}</h5>
          <div class="fs-13">
            <span class={`text-${products.percentageColor} me-1`}>{products.percentage} </span>  This Week
          </div>
        </div>
      </Col>

// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/reusable-widgets/spk-productscard.tsx

import { Fragment } from "react";

interface ProductCardProps  {
    products: {
      color: string;
      svgIcon: React.ReactNode;
      title: string;
      value: string | number;
      percentage: string;
      percentageColor: string;
    };
  };
  

const SpkProductscard: React.FC<ProductCardProps> = ({ products }) => {
  return (
    <Fragment>
      <div className="col-xxl-2 col-xl-3 col-lg-4 col-md-6">
        <div className="text-center">
          <div className="lh-1 mb-3">
            <span className={`avatar avatar-lg bg-${products.color}-transparent avatar-rounded`}>
              <span className={`avatar avatar-sm bg-${products.color} avatar-rounded svg-white`}>
                {products.svgIcon}
              </span>
            </span>
          </div>
          <span className="d-block mb-1">{products.title}</span>
          <h5 className="fw-semibold">{products.value}</h5>
          <div className="fs-13">
            <span className={`text-${products.percentageColor} me-1`}>{products.percentage} </span>  This Week
          </div>
        </div>
      </div>
    </Fragment>
  );
};

export default SpkProductscard;
