// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/general/utilities/avatars/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import ShowCode from "$lib/components/layout-components/showcode/ShowCode.svelte";
    import {
        avatar1,
        avatar2,
        avatar3,
        avatar4,
        avatar5,
        avatar6,
        avatar7,
        avatar8,
        avatar9,
        avatardata1,
        avatardata2,
        avatardata3,
        avatardata4,
        avatardata5,
        avatardata6,
        avatardata7,
        avatardata8,
    } from "$lib/components/common/prism-code/utilitiesprism";
    import {
        Avatardata,
        Avataricon,
        Avatarinitial,
        Avatarnumber,
        Avataroffline,
        Avataronline,
        Avatarsize,
        Avatarstack,
    } from "$lib/data/utilities/avatars";
    import { Badge, Image } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Avatars | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<!-- Page Header -->
<Pageheader homepage="Avatars" activepage="Utilities" page="Avatars" />
<!-- Page Header Close -->

<!-- Start::row-1 -->
<!-- svelte-ignore a11y_consider_explicit_label -->
<div class="row">
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title=" Avatars"
            svelteCode={avatar1}
            dataCode={avatardata1}
            customCardBodyClass="py-4"
        >
            {#each Avatardata as idx}
                <span class={`avatar me-2 ${idx.class}`}>
                    <img src={idx.src} alt="img" />
                </span>
            {/each}
        </ShowCode>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title={`  Avatar Sizes <p class="subtitle text-muted fs-12 fw-normal"> Avatars of different sizes </p>`}
            svelteCode={avatar2}
            dataCode={avatardata2}
            customCardBodyClass=""
        >
            {#each Avatarsize as idx}
                <span class={`avatar avatar-${idx.class} me-2`}>
                    <Image src={idx.src} alt="Avatar" />
                </span>
            {/each}
        </ShowCode>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title="Avatar With Icons<p class='subtitle text-muted fs-12 fw-normal'>  Avatar contains icons to perform respective action.</p>"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={avatar3}
            dataCode={avatardata3}
        >
            {#each Avataricon as idx}
                <span class={`avatar avatar-${idx.class} me-2 avatar-rounded`}>
                    <Image src={idx.src} alt="img" />
                    <a
                        href="#!"
                        class={`badge bg-${idx.class1} rounded-pill avatar-badge`}
                        ><i class={`fe fe-${idx.icon}`}></i></a
                    >
                </span>
            {/each}
        </ShowCode>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title=" Avatar With Online Status Indicators<p class='subtitle text-muted fs-12 fw-normal'>  avatars having online status indicator.</p>"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={avatar4}
            dataCode={avatardata4}
        >
            {#each Avataronline as idx}
                <span class={`avatar avatar-${idx.class} me-2 avatar-rounded`}>
                    <Image src={idx.src} alt="img" />
                </span>
            {/each}
        </ShowCode>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title="  Avatar With Offline Status Indicators<p class='subtitle text-muted fs-12 fw-normal'> avatars having a offline status indicator.</p>"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={avatar5}
            dataCode={avatardata5}
        >
            {#each Avataroffline as idx}
                <span class={`avatar avatar-${idx.class} me-2 avatar-rounded`}>
                    <Image src={idx.src} alt="img" />
                </span>
            {/each}
        </ShowCode>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title=" Avatars With Number Badges<p class='subtitle text-muted fs-12 fw-normal'>   Avatar numbers indicates the no. of unread notififactions/messages. </p>"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={avatar6}
            dataCode={avatardata6}
        >
            {#each Avatarnumber as idx}
                <span class={`avatar avatar-${idx.class} me-2 avatar-rounded`}>
                    <img src={idx.src} alt="img" />
                    <Badge
                        color=""
                        class={`badge rounded-pill bg-${idx.class1} avatar-badge`}
                        >{idx.data}</Badge
                    >
                </span>
            {/each}
        </ShowCode>
    </div>
</div>
<!-- End::row-1 -->

<!-- Start::row-3 -->
<div class="row">
    <div class="col-xl-12 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title=" Avatar With Initials <p class='subtitle text-muted fs-12 fw-normal'> Avatar contains intials when user profile doesn't exist.</p>"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={avatar7}
            dataCode={avatardata7}
        >
            {#each Avatarinitial as idx}
                <span class={`avatar avatar-${idx.data} m-2 bg-${idx.color}`}>
                    {idx.data1}
                </span>
            {/each}
        </ShowCode>
    </div>
    <div class="col-xl-12 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title="Stacked Avatars<p class='subtitle text-muted fs-12 fw-normal'> Group of avatars stacked together.</p>"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={avatar8}
            dataCode={avatardata8}
        >
            <div class="avatar-list-stacked">
                {#each Avatarstack as idx}
                    <span class="avatar">
                        <img src={idx.src} alt="img" />
                    </span>
                {/each}
                <a class="avatar bg-primary" href="#!"> +8 </a>
            </div>
        </ShowCode>
    </div>
    <div class="col-xl-12 col-lg-6 col-md-12 col-sm-12">
        <ShowCode
            title="Rounded Stacked Avatars<p class='subtitle text-muted fs-12 fw-normal'> Group of avatars stacked together.</p>"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={avatar9}
            dataCode={avatardata8}
        >
            <div class="avatar-list-stacked">
                {#each Avatarstack as idx}
                    <span class="avatar avatar-rounded">
                        <img src={idx.src} alt="img" />
                    </span>
                {/each}
                <a
                        class="avatar bg-primary avatar-rounded"
                        href="#!"
                    >
                        +8
                    </a>
            </div>
        </ShowCode>
    </div>
</div>
<!-- End::row-3 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/utilities/avatars/avatars.jsx

import SpkBadge from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import { avatar1, avatar2, avatar3, avatar4, avatar5, avatar6, avatar7, avatar8, avatar9, avatardata1, avatardata2, avatardata3, avatardata4, avatardata5, avatardata6, avatardata7, avatardata8 } from "../../../../shared/data/prism-code/utilities-prism";
import { Avatardata, Avataricon, Avatarinitial, Avatarnumber, Avataroffline, Avataronline, Avatarsize, Avatarstack } from "../../../../shared/data/general/utilities/avatarsdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col, Image, Row } from "react-bootstrap";
import BaseLink from "@/shared/layouts-components/baselink/baselink";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const Avatars = () => {

    return (

        <Fragment>

            <Head title={"Avatars"} />

            <Pageheader title="Utilities" currentpage="Avatars" activepage="Avatars" />

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6} lg={6} md={12} sm={12} className="">
                    <ShowCode title="Avatars" customCardClass="custom-card" customCardBodyClass="py-4" reactCode={avatar1} dataCode={avatardata1}>
                        {Avatardata.map((idx, index) => (
                            <span className={`avatar me-2 ${idx.class}`} key={index}>
                                <BaseImage src={idx.src} alt="img" />
                            </span>
                        ))}
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={12} sm={12} className="">
                    <ShowCode title=" Avatar Sizes <p class='subtitle text-muted fs-12 fw-normal'>  Avatars of different sizes </p>" customCardClass="custom-card" customCardBodyClass="" reactCode={avatar2} dataCode={avatardata2} >
                        {Avatarsize.map((idx, index) => (
                            <span key={index} className={`avatar avatar-${idx.class} me-2`}>
                                <BaseImage src={idx.src} alt="img" />
                            </span>
                        ))}
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={12} sm={12} className="">
                    <ShowCode title="Avatar With Icons<p class='subtitle text-muted fs-12 fw-normal'>  Avatar contains icons to perform respective action.</p>" customCardClass="custom-card" customCardBodyClass="" reactCode={avatar3} dataCode={avatardata3}>
                        {Avataricon.map((idx, index) => (
                            <span key={index} className={`avatar avatar-${idx.class} me-2 avatar-rounded`}>
                                <BaseImage src={idx.src} alt="img" />
                                <BaseLink href="#!" className={`badge bg-${idx.class1} rounded-pill avatar-badge`}><i className={`fe fe-${idx.icon}`}></i></BaseLink>
                            </span>
                        ))}
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={12} sm={12} className="">
                    <ShowCode title=" Avatar With Online Status Indicators<p class='subtitle text-muted fs-12 fw-normal'>  avatars having online status indicator.</p>" customCardClass="custom-card" customCardBodyClass="" reactCode={avatar4} dataCode={avatardata4}>
                        {Avataronline.map((idx, index) => (
                            <span key={index} className={`avatar avatar-${idx.class} me-2 avatar-rounded`}>
                                <BaseImage src={idx.src} alt="img" />
                            </span>
                        ))}
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={12} sm={12} className="">
                    <ShowCode title="  Avatar With Offline Status Indicators<p class='subtitle text-muted fs-12 fw-normal'> avatars having a offline status indicator.</p>" customCardClass="custom-card" customCardBodyClass="" reactCode={avatar5} dataCode={avatardata5}>
                        {Avataroffline.map((idx, index) => (
                            <span key={index} className={`avatar avatar-${idx.class} me-2 avatar-rounded`}>
                                <BaseImage src={idx.src} alt="img" />
                            </span>
                        ))}
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={12} sm={12} className="">
                    <ShowCode title=" Avatars With Number Badges<p class='subtitle text-muted fs-12 fw-normal'>   Avatar numbers indicates the no. of unread notififactions/messages. </p>" customCardClass="custom-card" customCardBodyClass="" reactCode={avatar6} dataCode={avatardata6}>
                        {Avatarnumber.map((idx, index) => (
                            <span key={index} className={`avatar avatar-${idx.class} me-2 avatar-rounded`}>
                                <BaseImage src={idx.src} alt="img" />
                                <SpkBadge Customclass={`rounded-pill bg-${idx.class1} avatar-badge`}>{idx.data}</SpkBadge>
                            </span>
                        ))}
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End::row-1 --> */}

            {/* <!-- Start::row-3 --> */}

            <Row>
                <Col xl={12} lg={6} md={12} sm={12} className="">
                    <ShowCode title=" Avatar With Initials <p class='subtitle text-muted fs-12 fw-normal'> Avatar contains intials when user profile doesn't exist.</p>" customCardClass="custom-card" customCardBodyClass="" reactCode={avatar7} dataCode={avatardata7}>
                        {Avatarinitial.map((idx, index) => (
                            <span key={index} className={`avatar avatar-${idx.data} m-2 bg-${idx.color}`}>
                                {idx.data1}
                            </span>
                        ))}

                    </ShowCode>
                </Col>
                <Col xl={12} lg={6} md={12} sm={12} className="">
                    <ShowCode title="Stacked Avatars<p class='subtitle text-muted fs-12 fw-normal'> Group of avatars stacked together.</p>" customCardClass="custom-card" customCardBodyClass="" reactCode={avatar8} dataCode={avatardata8}>
                        <div className="avatar-list-stacked">
                            {Avatarstack.map((idx, index) => (
                                <span key={index} className="avatar">
                                    <BaseImage src={idx.src} alt="img" />
                                </span>
                            ))}
                            <BaseLink className="avatar bg-primary text-fixed-white" href="#!">
                                +8
                            </BaseLink>
                        </div>
                    </ShowCode>
                </Col>
                <Col xl={12} lg={6} md={12} sm={12} className="">
                    <ShowCode title="Rounded Stacked Avatars<p class='subtitle text-muted fs-12 fw-normal'> Group of avatars stacked together.</p>" customCardClass="custom-card" customCardBodyClass="" reactCode={avatar9} dataCode={avatardata8}>
                        <div className="avatar-list-stacked">
                            {Avatarstack.map((idx, index) => (
                                <span key={index} className="avatar avatar-rounded">
                                    <BaseImage src={idx.src} alt="img" />
                                </span>
                            ))}
                            <BaseLink className="avatar bg-primary avatar-rounded text-fixed-white" href="#!">
                                +8
                            </BaseLink>
                        </div>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End::row-3 --> */}

        </Fragment>
    )
};

// Assign layout
Avatars.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Avatars;
