// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/application-reusable/spk-kanbancard.tsx
import React, { Fragment } from "react";
import { Card, Dropdown, Image } from "react-bootstrap";
import SpkDropdown from "../general-reusable/reusable-uielements/spk-dropdown";
import { Link } from "react-router-dom";

interface Types {
    createdDate: string;
    daysLeft: string;
    tags: string[];
    description?: string;
    title?: string;
    comments: string;
    likes: string;
    avatars: string[];
    Content?: boolean;
    imgSrc?: boolean;
    src?: any;
}

interface SpkKanbanCardProps {
    kanban: Types;
    cardClass?: string;
}

const SpkKanbanCard: React.FC<SpkKanbanCardProps> = ({ kanban, cardClass }) => {
    return (
        <Fragment>
            <Card className={`custom-card ${cardClass || ""}`}>
                <Card.Body className="p-0">
                    <div className="p-3 kanban-board-head">
                        <div className="d-flex text-muted justify-content-between mb-1 fs-12 fw-medium">
                            <div>
                                <i className="ri-time-line me-1 align-middle d-inline-block"></i>
                                Created - {kanban.createdDate}
                            </div>
                            <div>{kanban.daysLeft}</div>
                        </div>

                        <div className="d-flex align-items-center justify-content-between">
                            <div className="task-badges">
                                {kanban.tags.map((tag, index) => (
                                    <span key={index} className={`badge ${index !== 0 ? "ms-1" : ""}`}>
                                        {tag}
                                    </span>
                                ))}
                            </div>
                            <SpkDropdown toggleas="a" Navigate="#!" Customtoggleclass="btn btn-sm btn-light btn-white no-caret" IconClass="ri-more-2-fill" Icon={true}>
                                <li className=""><Dropdown.Item href="#!"><i className="ri-eye-line me-1 align-middle d-inline-block"></i>View</Dropdown.Item></li>
                                <li className=""><Dropdown.Item href="#!"><i className="ri-delete-bin-line me-1 align-middle d-inline-block"></i>Edit</Dropdown.Item></li>
                                <li><Dropdown.Item href="#!"><i className="ri-edit-line me-1 align-middle d-inline-block"></i>Delete</Dropdown.Item></li>
                            </SpkDropdown>
                        </div>
                        {kanban.Content &&
                            <div className="kanban-content mt-2">
                                <h6 className="fw-medium mb-1 fs-15">{kanban.title}</h6>
                                <div className="kanban-task-description">{kanban.description}</div>
                            </div>
                        }
                        {kanban.imgSrc &&
                            <div className="kanban-content mt-2">
                                <div className="task-image mt-2">
                                    <Image  src={kanban.src} className="img-fluid rounded kanban-image" alt="" />
                                </div>
                                <h6 className="fw-medium mt-2 mb-0">{kanban.title}</h6>
                            </div>
                        }
                    </div>

                    <div className="p-3 border-top border-block-start-dashed">
                        <div className="d-flex align-items-center justify-content-between">
                            <div>
                                <Link to="#!" className="me-2 text-primary">
                                    <span className="me-1"><i className="ri-thumb-up-fill align-middle fw-normal"></i></span><span className="fw-medium fs-12">{kanban.likes}</span>
                                </Link>
                                <Link to="#!" className="text-muted">
                                    <span className="me-1"><i className="ri-message-2-line align-middle fw-normal"></i></span><span className="fw-medium fs-12">{kanban.comments}</span>
                                </Link>
                            </div>
                            <div className="avatar-list-stacked">
                                {kanban.avatars.map((src, index) => (
                                    <span key={index} className="avatar avatar-sm avatar-rounded">
                                        <Image src={src} alt={`avatar-${index}`} />
                                    </span>
                                ))}
                            </div>
                        </div>
                    </div>
                </Card.Body>
            </Card>
        </Fragment>
    );
};

export default SpkKanbanCard;

// Dashboard Template/vyzor-svelte/final/src/lib/@spk/application-reusable/spk-kanbancard.svelte
<script lang="ts">
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";
    import SpkDropdown from "../uielements/Dropdown/SpkDropdown.svelte";
    import { kanbanKardDropdown } from "$lib/data/uielements/dropdowndata";

    interface Types {
        createdDate?: string;
        daysLeft?: string;
        tags?: string[];
        description?: string;
        title?: string;
        comments?: string;
        likes?: string;
        avatars?: string[];
        Content?: boolean;
        imgSrc?: boolean;
        src?: any;
    }

    export let kanban: Types = {};
    export let cardClass: string = "";
</script>

<Card class={`custom-card ${cardClass || ""}`}>
    <CardBody class="p-0">
        <div class="p-3 kanban-board-head">
            <div
                class="d-flex text-muted justify-content-between mb-1 fs-12 fw-medium"
            >
                <div>
                    <i class="ri-time-line me-1 align-middle d-inline-block"
                    ></i>
                    Created - {kanban.createdDate}
                </div>
                <div>{kanban.daysLeft}</div>
            </div>

            <div class="d-flex align-items-center justify-content-between">
                <div class="task-badges">
                    {#each kanban.tags ?? [] as tag, index}
                        <span class={`badge ${index !== 0 ? "ms-1" : ""}`}>
                            {tag}
                        </span>
                    {/each}
                </div>
                <SpkDropdown
                    option={kanbanKardDropdown}
                    ToggleClass="btn btn-sm btn-light btn-white no-caret"
                    Caret={false}
                    parent={`<i class="ri-more-2-fill"></i>`}
                />
            </div>
            {#if kanban.Content}
                <div class="kanban-content mt-2">
                    <h6 class="fw-medium mb-0 mt-2 fs-15">{kanban.title}</h6>
                    <div class="kanban-task-description">
                        {kanban.description}
                    </div>
                </div>
            {/if}
            {#if kanban.imgSrc}
                <div class="kanban-content mt-2">
                    <div class="task-image mt-2">
                        <Image
                            src={kanban.src}
                            class="img-fluid rounded kanban-image"
                            alt=""
                        />
                    </div>
                    <h6 class="fw-medium mb-0 mt-2 fs-15">{kanban.title}</h6>
                </div>
            {/if}
        </div>

        <div class="p-3 border-top border-block-start-dashed">
            <div class="d-flex align-items-center justify-content-between">
                <div>
                    <a href="#!" class="me-2 text-primary">
                        <span class="me-1"
                            ><i class="ri-thumb-up-fill align-middle fw-normal"
                            ></i></span
                        ><span class="fw-medium fs-12">{kanban.likes}</span>
                    </a>
                    <a href="#!" class="text-muted">
                        <span class="me-1"
                            ><i class="ri-message-2-line align-middle fw-normal"
                            ></i></span
                        ><span class="fw-medium fs-12">{kanban.comments}</span>
                    </a>
                </div>
                <div class="avatar-list-stacked">
                    {#each kanban.avatars ?? [] as src}
                        <span class="avatar avatar-sm avatar-rounded">
                            <Image {src} alt={`avatar`} />
                        </span>
                    {/each}
                </div>
            </div>
        </div>
    </CardBody>
</Card>
