// Dashboard Template/vyzor-laravel-react-inertia/starterkit/resources/js/shared/@spk-reusable-components/application-reusable/spk-listcard.jsx

import { Fragment } from "react";
import { Card } from "react-bootstrap";
import SpkBadge from "../general-reusable/reusable-uielements/spk-badge";
import CountUp from 'react-countup';


const SpkListCard = ({ cardClass="", bodyClass="", list, listCard, titleClass="", jobsCard }) => {
  return (
    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className={bodyClass}>
          <div className={`d-flex align-items-start gap-3 flex-wrap ${list.flexClass}`}>
            <div className="flex-fill">
              <span className={titleClass}>{list.title}</span>
              <div className="pb-0 mt-0">
                {listCard &&
                  <div>
                      <span className="fs-13 fw-medium">{list.titles}</span>
                    <div className={`d-flex align-items-center gap-2 mb-2 ${list.ValueClass1}`}>
                      <h4 className={`fw-medium mb-0 ${list.ValueClass}`}>
                      {list.count === "46658" ? "$" : ""}
                      {list.count === "1250450" ? "$" : ""}
                      <CountUp className="count-up" decimals={list.decimals} end={list.count} />
                      {list.count === 33 ? "k" : ""}
                      </h4>
                      {listCard &&
                        <SpkBadge variant="" Customclass={`bg-${list.priceColor}`}>
                          {list.price}
                        </SpkBadge>
                      }
                    </div>
                    <p className={`text-muted fs-12 mb-0 lh-1 ${list.smallText}`}>
                      <span className={`text-${list.iconColor} me-1 d-inline-block ${list.percentColor}`}>
                        <i className={list.icon}></i>
                        {list.percent}
                      </span>
                      <span className="monthly-percent fs-14">this month</span>
                    </p>
                  </div>
                }
                {jobsCard &&
                  <div className="d-flex align-items-center gap-2">
                    <h3 className="fw-semibold mb-0">{list.count}</h3>
                    <span className={`text-${list.iconColor}`}><i className={list.icon}></i>{list.percent}</span>
                  </div>
                }
              </div>
            </div>
            <div className={`avatar avatar-md ${list.avatarClass} bg-${list.priceColor}-transparent mb-2 svg-${list.priceColor}`}>
              {list.svgIcon}
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkListCard;

// Dashboard Template/vyzor-svelte/final/src/lib/@spk/application-reusable/spk-listcard.svelte
<script lang="ts">
    import { Card, CardBody } from "@sveltestrap/sveltestrap";
    import SpkBadge from "../uielements/badge/SpkBadge.svelte";

    interface ListData {
        title?: string;
        count?: number | string;
        price?: string;
        priceColor?: string;
        iconColor?: string;
        icon?: string;
        smallText?: string;
        avatarClass?: string;
        ValueClass?: string;
        ValueClass1?: string;
        flexClass?: string;
        percent?: string;
        svgIcon?: string;
        percentColor?: string;
        titles?: string;
    }

    export let cardClass: string = "";
    export let bodyClass: string = "";
    export let list: ListData = {};
    export let listCard: boolean = false;
    export let titleClass: string = "";
    export let jobsCard: boolean = false;
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class={bodyClass}>
        <div class={`d-flex align-items-start gap-3 ${list.flexClass}`}>
            <div class="flex-fill">
                <h6 class={titleClass}>{list.title}</h6>
                <div class="pb-0 mt-0">
                    {#if listCard}
                        <div>
                            <span class="fs-13 fw-medium">{list.titles}</span>
                            <div
                                class={`d-flex align-items-center gap-2 mb-2 ${list.ValueClass1}`}
                            >
                                <h4 class={`fw-medium mb-0 ${list.ValueClass}`}>
                                    <span
                                        class="count-up"
                                        data-count={list.count}
                                    >
                                        {list.count}
                                    </span>
                                </h4>
                                {#if listCard}
                                <span class={`badge bg-${list.priceColor}`}>{list.price}</span>
                                {/if}
                            </div>
                            <p
                                class={`text-muted fs-12 mb-0 lh-1 ${list.smallText}`}
                            >
                                <span
                                    class={`text-${list.iconColor} me-1 d-inline-block ${list.percentColor}`}
                                >
                                    <i class={list.icon}></i>
                                    {list.percent}
                                </span>
                                <span class="monthly-percent">this month</span>
                            </p>
                        </div>
                    {/if}
                    {#if jobsCard}
                        <div class="d-flex align-items-center gap-2">
                            <h3 class="fw-semibold mb-0">{list.count}</h3>
                            <span class={`text-${list.iconColor}`}
                                ><i class={list.icon}></i>{list.percent}</span
                            >
                        </div>
                    {/if}
                </div>
            </div>
            <div
                class={`avatar ${list.avatarClass} bg-${list.priceColor}-transparent mb-3 svg-${list.priceColor} mx-auto`}
            >
                {@html list.svgIcon}
            </div>
        </div>
    </CardBody>
</Card>
