// Dashboard Template/vyzor-angular/final/src/app/components/general/uielements/buttons/buttons.ts
import { Component } from '@angular/core';
import * as PrismCode from '../../../../shared/prismData/buttons';
import { SharedModule } from '../../../../shared/shared.module';
import { ShowcodeCard } from '../../../../shared/components/showcode-card/showcode-card';
@Component({
  selector: 'app-buttons',
  standalone: true,
  imports: [SharedModule,ShowcodeCard],
  templateUrl: './buttons.html',
  styleUrls: ['./buttons.scss']
})
export class Buttons {
  buttons=[
    {class:'btn btn-primary btn-wave',text:'Primary'},
    {class:'btn btn-secondary btn-wave',text:'Secondary'},
    {class:'btn btn-success btn-wave',text:'Success'},
    {class:'btn btn-danger btn-wave',text:'Danger'},
    {class:'btn btn-warning btn-wave',text:'Warning'},
    {class:'btn btn-info btn-wave',text:'Info'},
    {class:'btn btn-light btn-wave',text:'Light'},
    {class:'btn btn-dark btn-wave text-white',text:'Dark'},
    {class:'btn btn-link btn-wave',text:'Link'},
  ]
  lightButtons=[
    {class:'btn btn-primary-light btn-wave',text:'Primary'},
    {class:'btn btn-secondary-light btn-wave',text:'Secondary'},
    {class:'btn btn-success-light btn-wave',text:'Success'},
    {class:'btn btn-danger-light btn-wave',text:'Danger'},
    {class:'btn btn-warning-light btn-wave',text:'Warning'},
    {class:'btn btn-info-light btn-wave',text:'Info'},
    {class:'btn btn-purple-light btn-wave',text:'Purple'},
    {class:'btn btn-teal-light btn-wave',text:'Teal'},
    {class:'btn btn-orange-light btn-wave',text:'Orange'},
  ]
  lightRoundedButtons=[
    {class:'btn btn-primary-light rounded-pill btn-wave',text:'Primary'},
    {class:'btn btn-secondary-light  rounded-pill btn-wave',text:'Secondary'},
    {class:'btn btn-success-light rounded-pill btn-wave',text:'Success'},
    {class:'btn btn-danger-light rounded-pill btn-wave',text:'Danger'},
    {class:'btn btn-warning-light rounded-pill btn-wave',text:'Warning'},
    {class:'btn btn-info-light rounded-pill btn-wave',text:'Info'},
    {class:'btn btn-purple-light rounded-pill btn-wave',text:'Purple'},
    {class:'btn btn-teal-light rounded-pill btn-wave',text:'Teal'},
    {class:'btn btn-orange-light rounded-pill btn-wave',text:'Orange'},
  ]
  roundedButtons=[
    {class:'btn btn-primary rounded-pill btn-wave',text:'Primary'},
    {class:'btn btn-secondary rounded-pill btn-wave',text:'Secondary'},
    {class:'btn btn-success rounded-pill btn-wave',text:'Success'},
    {class:'btn btn-danger rounded-pill btn-wave',text:'Danger'},
    {class:'btn btn-warning rounded-pill btn-wave',text:'Warning'},
    {class:'btn btn-info rounded-pill btn-wave',text:'Info'},
    {class:'btn btn-light rounded-pill btn-wave',text:'Light'},
    {class:'btn btn-dark rounded-pill btn-wave text-white',text:'Dark'},
    {class:'btn btn-link rounded-pill btn-wave',text:'Link'},
  ]
 outlineButtons=[
    {class:'btn btn-outline-primary btn-wave',text:'Primary'},
    {class:'btn btn-outline-secondary btn-wave',text:'Secondary'},
    {class:'btn btn-outline-success btn-wave',text:'Success'},
    {class:'btn btn-outline-danger btn-wave',text:'Danger'},
    {class:'btn btn-outline-warning btn-wave',text:'Warning'},
    {class:'btn btn-outline-info btn-wave',text:'Info'},
    {class:'btn btn-outline-light btn-wave',text:'Light'},
    {class:'btn btn-outline-dark btn-wave',text:'Dark'},
  ]
  roundedOutlineButtons=[
     {class:'btn btn-outline-primary rounded-pill btn-wave',text:'Primary'},
     {class:'btn btn-outline-secondary rounded-pill btn-wave',text:'Secondary'},
     {class:'btn btn-outline-success rounded-pill btn-wave',text:'Success'},
     {class:'btn btn-outline-danger rounded-pill btn-wave',text:'Danger'},
     {class:'btn btn-outline-warning rounded-pill btn-wave',text:'Warning'},
     {class:'btn btn-outline-info rounded-pill btn-wave',text:'Info'},
     {class:'btn btn-outline-light rounded-pill btn-wave',text:'Light'},
     {class:'btn btn-outline-dark rounded-pill btn-wave',text:'Dark'},
   ]
   gradientButtons=[
    {class:'btn btn-primary-gradient btn-wave',text:'Primary'},
    {class:'btn btn-secondary-gradient btn-wave',text:'Secondary'},
    {class:'btn btn-success-gradient btn-wave',text:'Success'},
    {class:'btn btn-danger-gradient btn-wave',text:'Danger'},
    {class:'btn btn-warning-gradient btn-wave',text:'Warning'},
    {class:'btn btn-info-gradient btn-wave',text:'Info'},
    {class:'btn btn-orange-gradient btn-wave',text:'Orange'},
    {class:'btn btn-purple-gradient btn-wave',text:'Purple'},
    {class:'btn btn-teal-gradient btn-wave',text:'Teal'},
  ]
  roundedGradientButtons=[
    {class:'btn btn-primary-gradient rounded-pill btn-wave',text:'Primary'},
    {class:'btn btn-secondary-gradient rounded-pill btn-wave',text:'Secondary'},
    {class:'btn btn-success-gradient rounded-pill btn-wave',text:'Success'},
    {class:'btn btn-danger-gradient rounded-pill btn-wave',text:'Danger'},
    {class:'btn btn-warning-gradient rounded-pill btn-wave',text:'Warning'},
    {class:'btn btn-info-gradient rounded-pill btn-wave',text:'Info'},
    {class:'btn btn-orange-gradient rounded-pill btn-wave',text:'Orange'},
    {class:'btn btn-purple-gradient rounded-pill btn-wave',text:'Purple'},
    {class:'btn btn-teal-gradient rounded-pill btn-wave',text:'Teal'},
  ]
  ghostButtons=[
    {class:'btn btn-primary-ghost btn-wave',text:'Primary'},
    {class:'btn btn-secondary-ghost btn-wave',text:'Secondary'},
    {class:'btn btn-success-ghost btn-wave',text:'Success'},
    {class:'btn btn-danger-ghost btn-wave',text:'Danger'},
    {class:'btn btn-warning-ghost btn-wave',text:'Warning'},
    {class:'btn btn-info-ghost btn-wave',text:'Info'},
    {class:'btn btn-orange-ghost btn-wave',text:'Orange'},
    {class:'btn btn-purple-ghost btn-wave',text:'Purple'},
    {class:'btn btn-teal-ghost btn-wave',text:'Teal'},
  ]
  disabledButtons=[
    {class: 'btn btn-primary',text:'Primary button'},
    {class: 'btn btn-secondary',text:'Button'},
    {class: 'btn btn-outline-primary',text:'Primary button'},
    {class: 'btn btn-outline-secondary',text:'Button'},
  ]
  toggleButtons=[
    {class: 'btn btn-primary btn-wave',text:'Toggle button',disabled:false},
    {class: 'btn btn-secondary active btn-wave',text:'Active toggle button',disabled:false},
    {class: 'btn btn-teal btn-wave',text:'Disabled toggle button',disabled:true},
  ]
  toggleButtons2=[
    {class: 'btn btn-primary btn-wave',text:'Toggle link',disabled:false},
    {class: 'btn btn-secondary active btn-wave',text:'Active toggle link',disabled:false},
    {class: 'btn btn-teal btn-wave',text:'Disabled toggle link',disabled:true},
  ]
  loadingButtons=[
    {class:'btn btn-primary btn-loader',icon:'ri-loader-2-fill fs-16',text:'Loading',disabled:false},
    {class:'btn btn-outline-secondary btn-loader',icon:'ri-loader-2-fill fs-16',text:'Loading',disabled:false},
    {class:'btn btn-info-light btn-loader',icon:'ri-loader-4-line fs-16',text:'Loading',disabled:false},
    {class:'btn btn-warning-light btn-loader',icon:'ri-loader-5-line fs-16',text:'Loading',disabled:false},
    {class:'btn btn-success btn-loader',icon:'ri-refresh-line fs-16',text:'Disabled',disabled:true},
  ]
  iconButtons=[
    {class:'btn btn-icon btn-primary btn-wave',icon:'ri-bank-fill'},
    {class:'btn btn-icon btn-info btn-wave',icon:'ri-medal-fill'},
    {class:'btn btn-icon btn-danger btn-wave',icon:'ri-archive-line'},
    {class:'btn btn-icon btn-warning btn-wave me-5',icon:'ri-calendar-2-line'},
  ]
  iconButtons2=[
    {class:'btn btn-icon btn-primary-light rounded-pill btn-wave',icon:'ri-home-smile-line'},
    {class:'btn btn-icon btn-secondary-transparent rounded-pill btn-wave',icon:'ri-delete-bin-line'},
    {class:'btn btn-icon btn-success-light rounded-pill btn-wave',icon:'ri-notification-3-line'},
    {class:'btn btn-icon btn-danger-light rounded-pill btn-wave me-5',icon:'ri-chat-settings-line'},
  ]
  iconButtons3=[
    {class:'btn btn-icon btn-outline-primary rounded-pill btn-wave',icon:'ri-phone-line'},
    {class:'btn btn-icon btn-outline-teal rounded-pill btn-wave',icon:'ri-customer-service-2-line'},
    {class:'btn btn-icon btn-outline-success rounded-pill btn-wave',icon:'ri-live-line'},
    {class:'btn btn-icon btn-outline-secondary rounded-pill btn-wave',icon:'ri-save-line'},
  ]
  iconButtonsSizes=[
    {class:'btn btn-sm btn-icon btn-primary btn-wave',icon:'ri-bank-fill'},
    {class:'btn btn-icon btn-info btn-wave',icon:'ri-medal-fill'},
    {class:'btn btn-lg btn-icon btn-danger btn-wave',icon:'ri-archive-line'},
  ]
  iconButtonsSizes1=[
    {class:'btn btn-sm btn-icon btn-primary-light rounded-pill btn-wave',icon:'ri-home-smile-line'},
    {class:'btn btn-icon btn-secondary-transparent rounded-pill btn-wave',icon:'ri-delete-bin-line'},
    {class:'btn btn-lg btn-icon btn-success-light rounded-pill btn-wave',icon:'ri-notification-3-line'},
  ]
  iconButtonsSizes2=[
    {class:'btn btn-sm btn-icon btn-outline-primary rounded-pill btn-wave',icon:'ri-phone-line'},
    {class:'btn btn-icon btn-outline-teal rounded-pill btn-wave',icon:'ri-customer-service-2-line'},
    {class:'btn btn-lg btn-icon btn-outline-success rounded-pill btn-wave',icon:'ri-live-line'},
  ]
  socialButtons=[
    {class:'btn btn-icon btn-facebook btn-wave',icon:'ri-facebook-line'},
    {class:'btn btn-icon btn-twitter btn-wave',icon:'ri-twitter-x-line'},
    {class:'btn btn-icon btn-instagram btn-wave',icon:'ri-instagram-line'},
    {class:'btn btn-icon btn-github btn-wave',icon:'ri-github-line'},
    {class:'btn btn-icon btn-youtube btn-wave',icon:'ri-youtube-line'},
    {class:'btn btn-icon btn-google btn-wave',icon:'ri-google-line'},
  ]
  sizesButtons=[
    {class:'btn btn-primary btn-sm btn-wave',buttonText:'Small button'},
    {class:'btn btn-secondary  btn-wave',buttonText:'Default button'},
    {class:'btn btn-success btn-lg btn-wave',buttonText:'Large button'},
  ]
  buttonWidths=[
    {class:'btn btn-primary btn-w-xs btn-wave',size:'XS'},
    {class:'btn btn-secondary btn-w-sm btn-wave',size:'SM'},
    {class:'btn btn-warning btn-w-md btn-wave',size:'MD'},
    {class:'btn btn-info btn-w-lg btn-wave',size:'LG'},
  ]
  shadowButtons=[
    {class:'btn btn-primary shadow-sm btn-wave'},
    {class:'btn btn-primary shadow btn-wave'},
    {class:'btn btn-primary shadow-lg btn-wave'},
  ]
  shadowButtons1=[
    {class:'btn btn-secondary btn-sm shadow-sm btn-wave'},
    {class:'btn btn-info shadow btn-wave'},
    {class:'btn btn-lg btn-success shadow-lg btn-wave'},
  ]
  coloredButtons=[
    {class:'btn btn-primary shadow-primary btn-wave'},
    {class:'btn btn-secondary shadow-secondary btn-wave'},
    {class:'btn btn-success shadow-success btn-wave'},
    {class:'btn btn-info shadow-info btn-wavee'},
    {class:'btn btn-warning shadow-warning btn-wave'},
    {class:'btn btn-danger shadow-danger btn-wave'},
    {class:'btn btn-purple shadow-purple btn-wave'},
    {class:'btn btn-orange shadow-orange btn-wave'},
  ]
  raisedButtons=[
    {class:'btn btn-primary btn-raised-shadow btn-wave'},
    {class:'btn btn-secondary btn-raised-shadow btn-wave'},
    {class:'btn btn-success btn-raised-shadow btn-wave'},
    {class:'btn btn-info btn-raised-shadow btn-wavee'},
    {class:'btn btn-warning btn-raised-shadow btn-wave'},
    {class:'btn btn-danger btn-raised-shadow btn-wave'},
    {class:'btn btn-purple btn-raised-shadow btn-wave'},
    {class:'btn btn-orange btn-raised-shadow btn-wave'},
  ]
  labelButtons=[
    {class:'btn btn-primary label-btn',icon:'ri-chat-smile-line label-btn-icon me-2',text:'Primary'},
    {class:'btn btn-secondary label-btn',icon:'ri-settings-4-line label-btn-icon me-2',text:'Secondary'},
    {class:'btn btn-warning label-btn rounded-pill',icon:'ri-spam-2-line label-btn-icon me-2 rounded-pill',text:'Warning'},
    {class:'btn btn-info label-btn rounded-pill',icon:'ri-phone-line label-btn-icon me-2 rounded-pill',text:'Info'},
    {class:'btn btn-success label-btn label-end',icon:'ri-thumb-up-line label-btn-icon ms-2',text:'Success'},
    {class:'btn btn-danger label-btn label-end rounded-pill',icon:'ri-close-line label-btn-icon ms-2 rounded-pill',text:'Cancel'},
  ]
  customButtons=[
    {class:'btn btn-info custom-button rounded-pill',icon:'ri-twitter-x-line text-info',text:'Twitter'},
    {class:'btn btn-teal-light btn-border-down',text:'Border'},
    {class:'btn btn-secondary-light btn-border-start',text:'Border'},
    {class:'btn btn-purple-light btn-border-end',text:'Border'},
    {class:'btn btn-warning-light btn-border-top',text:'Border'},
    {class:'btn btn-secondary btn-glare',text:'Glare Button'},
    {class:'btn btn-danger btn-hover btn-hover-animate',text:'Like'},
    {class:'btn btn-success btn-darken-hover',text:'Hover'},
    {class:'btn btn-orange btn-custom-border',text:'Hover'},
  ]
  prsimCodeData: any = PrismCode;
  Blockbutton = [
    {id:1, class:"Button", color:"btn btn-primary w-100" },
    {id:2, class:"Button", color:"btn btn-secondary w-100"},
  ]

  Blockbutton1 = [
    {id:1, class:"Button", color:"btn btn-info"},
    {id:2, class:"Button", color:"btn btn-success"},
  ]

  Blockbutton2 = [
    {id:2, class:"Button", color:"btn btn-danger"},
    {id:1, class:"Button", color:"btn btn-warning"},
  ]
  Blockbutton3 = [
    {id:1, class:"Button", color:"btn btn-teal"},
    {id:2, class:"Button", color:"btn btn-purple"},
  ]
}

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/ui-elements/buttons/buttons.jsx

import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import { ColoredButtons, DefaultButtons, GhostButtons, GradientButtons, LightButtons, OutlineButtons, SocialIconButtons } from "../../../../shared/data/general/ui-elements/buttonsdata";
import React, { Fragment } from "react";
import { Col, Row } from "react-bootstrap";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import { dataButton1, dataButton17, dataButton21, dataButton22, dataButton3, dataButton5, dataButton7, dataButton8, dataButton9, reactButton1, reactButton10, reactButton11, reactButton12, reactButton13, reactButton14, reactButton15, reactButton16, reactButton17, reactButton18, reactButton19, reactButton2, reactButton20, reactButton21, reactButton22, reactButton23, reactButton24, reactButton25, reactButton3, reactButton5, reactButton6, reactButton7, reactButton8, reactButton9, reactbutton1, reuseButton1, reuseButton10, reuseButton11, reuseButton12, reuseButton13, reuseButton14, reuseButton15, reuseButton16, reuseButton17, reuseButton18, reuseButton19, reuseButton2, reuseButton20, reuseButton21, reuseButton22, reuseButton23, reuseButton24, reuseButton25, reuseButton3, reuseButton5, reuseButton6, reuseButton7, reuseButton8, reuseButton9, reusebutton1, } from "../../../../shared/data/prism-code/uielements-prism";
import MainLayout from "@/Layouts/layout";


const Buttons = () => {

	return (

		<Fragment>

			{/* <!-- Page Header --> */}

			<Head title="Uielements" />

			<Pageheader title="Ui Elements" currentpage="Buttons" activepage="Buttons" />

			{/* <!-- Page Header Close --> */}

			<Row>
				<Col xl={12}>
					<ShowCode title="Default Buttons" customCardBodyClass="" dataCode={dataButton1} reactCode={reactButton1} reusableCode={reuseButton1}>
						<div className="btn-list">
							{DefaultButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass="waves-effect waves-light me-2" key={index}>{idx.text}</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Rounded Buttons" customCardBodyClass="" dataCode={dataButton1} reactCode={reactButton2} reusableCode={reuseButton2}>
						<div className="btn-list">
							{DefaultButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass="rounded-pill me-2" key={index}>{idx.text}</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Light Buttons" customCardBodyClass="" reactCode={reactbutton1} reusableCode={reusebutton1}>
						<div className="btn-list">
							<SpkButton Buttontype="button" Buttonvariant="primary-light" Customclass="me-2">Primary</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="secondary-light" Customclass="me-2">Secondary</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="success-light" Customclass="me-2">Success</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="danger-light" Customclass="me-2">Danger</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="warning-light" Customclass="me-2">Warning</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="info-light" Customclass="me-2">Info</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="purple-light" Customclass="me-2">Purple</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="teal-light" Customclass="me-2">Teal</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="orange-light" Customclass="me-2">Orange</SpkButton>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Light Rounded Buttons" customCardBodyClass="" dataCode={dataButton3} reactCode={reactButton3} reusableCode={reuseButton3}>
						<div className="btn-list">
							{LightButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass="rounded-pill me-2" key={index}>{idx.text}</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Outline Buttons" customCardBodyClass="" dataCode={dataButton5} reactCode={reactButton5} reusableCode={reuseButton5}>
						<div className="btn-list">
							{OutlineButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass="me-2" key={index}>{idx.text}</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Rounded Outline Buttons" customCardBodyClass="" dataCode={dataButton5} reactCode={reactButton6} reusableCode={reuseButton6}>
						<div className="btn-list">
							{OutlineButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass=" rounded-pill me-2" key={index}>{idx.text}</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Gradient Buttons" customCardBodyClass="" dataCode={dataButton7} reactCode={reactButton7} reusableCode={reuseButton7}>
						<div className="btn-list">
							{GradientButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass="me-2" key={index}>{idx.text}</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Rounded Gradient Buttons" customCardBodyClass="" dataCode={dataButton8} reactCode={reactButton8} reusableCode={reuseButton8}>
						<div className="btn-list">
							{GradientButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass="rounded-pill me-2" key={index}>{idx.text}</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Ghost Buttons" customCardBodyClass="" dataCode={dataButton9} reactCode={reactButton9} reusableCode={reuseButton9}>
						<div className="btn-list">
							{GhostButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass="rounded-pill me-2" key={index}>{idx.text}</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Button tags" customCardBodyClass="" reactCode={reactButton10} reusableCode={reuseButton10}>
						<div className="btn-list">
							<SpkButton Buttontype="button" Buttonvariant="primary" Navigate={"#!"} >Link</SpkButton>
							<SpkButton Buttontype="submit" Buttonvariant="secondary" >Button</SpkButton>
							<SpkButton as="input" Buttontype="button" Buttonvariant="info" Value="Input" />
							<SpkButton as="input" Buttontype="submit" Buttonvariant="warning" />
							<SpkButton as="input" Buttontype="reset" Buttonvariant="success" />
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="disabled state with anchor tags" customCardBodyClass="" reactCode={reactButton11} reusableCode={reuseButton11}>
						<div className="btn-list">
							<div className="mb-4">
								<SpkButton Buttontype="button" Buttonvariant="primary" Disabled={true}> Primary Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="secondary" Disabled={true}> Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="outline-primary" Disabled={true}>Primary Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="outline-secondary" Disabled={true}>Button</SpkButton>
							</div>

							<div>
								<SpkButton Buttontype="button" Buttonvariant="primary" Disabled={true}>Primary Link</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="secondary" Disabled={true}>Link</SpkButton>
							</div>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="button plugin toggle states" customCardBodyClass="" reactCode={reactButton12} reusableCode={reuseButton12}>
						<div className="btn-list">
							<div className="mb-4">
								<SpkButton Buttontype="button" Buttonvariant="primary">Toggle button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="secondary">Active toggle button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="teal" Disabled={true}>Disabled toggle button</SpkButton>
							</div>
							<div>
								<SpkButton Buttontype="button" Buttonvariant="primary" Navigate={"#!"}>Toggle link</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="secondary" Navigate={"#!"}>Active toggle link</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="teal" Disabled={true} Navigate={"#!"}>Disabled toggle link</SpkButton>
							</div>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title=" Link functionally caveat" customCardBodyClass="" reactCode={reactButton13} reusableCode={reuseButton13}>
						<div className="btn-list">
							<SpkButton Buttontype="button" Buttonvariant="primary" Disabled={true}>Primary link</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="secondary" Disabled={true}>Link</SpkButton>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Loading Buttons" customCardBodyClass="" reactCode={reactButton14} reusableCode={reuseButton14}>
						<div className="btn-list d-md-flex flex-wrap">

							<SpkButton Buttontype="button" Buttonvariant="primary" Customclass="btn-loader">
								<span className="me-2">Loading</span>
								<span className="loading"><i className="ri-loader-2-fill fs-16"></i></span>
							</SpkButton>

							<SpkButton Buttontype="button" Buttonvariant="outline-secondary" Customclass="btn-loader">
								<span className="me-2">Loading</span>
								<span className="loading"><i className="ri-loader-2-fill fs-16"></i></span>
							</SpkButton>

							<SpkButton Buttontype="button" Buttonvariant="info-transparent" Customclass="btn-loader">
								<span className="me-2">Loading</span>
								<span className="loading"><i className="ri-loader-4-line fs-16"></i></span>
							</SpkButton>

							<SpkButton Buttontype="button" Buttonvariant="warning-transparent" Customclass="btn-loader">
								<span className="me-2">Loading</span>
								<span className="loading"><i className="ri-loader-5-line fs-16"></i></span>
							</SpkButton>

							<SpkButton Buttontype="button" Buttonvariant="success" Customclass="btn-loader" Disabled={true}>
								<span className="me-2">Disabled</span>
								<span className="loading"><i className="ri-refresh-line fs-16"></i></span>
							</SpkButton>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Icon Buttons" customCardBodyClass="" reactCode={reactButton15} reusableCode={reuseButton15}>
						<div className="btn-list d-md-flex d-block">
							<div className="mb-md-0 mb-2">
								<SpkButton Buttontype="button" Buttonvariant="primary" Customclass="btn-icon">
									<i className="ri-bank-fill"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="info" Customclass="btn-icon">
									<i className="ri-medal-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="danger" Customclass="btn-icon">
									<i className="ri-archive-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="warning" Customclass="btn-icon me-5">
									<i className="ri-calendar-2-line"></i>
								</SpkButton>
							</div>
							<div className="mb-md-0 mb-2">
								<SpkButton Buttontype="button" Buttonvariant="primary-transparent" Customclass="rounded-pill btn-icon">
									<i className="ri-home-smile-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="secondary-transparent" Customclass="rounded-pill btn-icon">
									<i className="ri-delete-bin-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="success-transparent" Customclass="rounded-pill btn-icon">
									<i className="ri-notification-3-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="danger-transparent" Customclass="rounded-pill btn-icon me-5">
									<i className="ri-chat-settings-line"></i>
								</SpkButton>
							</div>
							<div className="">
								<SpkButton Buttontype="button" Buttonvariant="outline-primary" Customclass="rounded-pill btn-icon">
									<i className="ri-phone-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="outline-teal" Customclass="rounded-pill btn-icon">
									<i className="ri-customer-service-2-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="outline-success" Customclass="rounded-pill btn-icon">
									<i className="ri-live-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="outline-secondary" Customclass="rounded-pill btn-icon">
									<i className="ri-save-line"></i>
								</SpkButton>
							</div>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Icon Button Sizes" reactCode={reactButton16} reusableCode={reuseButton16}>
						<div className="btn-list d-md-flex d-block gap-5">
							<div className="mb-md-0 mb-2">
								<SpkButton Size="sm" Buttontype="button" Buttonvariant="primary" Customclass="btn-icon">
									<i className="ri-bank-fill"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="info" Customclass="btn-icon">
									<i className="ri-medal-line"></i>
								</SpkButton>
								<SpkButton Size="lg" Buttontype="button" Buttonvariant="danger" Customclass="btn-icon">
									<i className="ri-archive-line"></i>
								</SpkButton>
							</div>
							<div className="mb-md-0 mb-2">
								<SpkButton Size="sm" Buttontype="button" Buttonvariant="primary-light" Customclass="rounded-pill btn-icon">
									<i className="ri-home-smile-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="secondary-light" Customclass="rounded-pill btn-icon">
									<i className="ri-delete-bin-line"></i>
								</SpkButton>
								<SpkButton Size="lg" Buttontype="button" Buttonvariant="success-light" Customclass="rounded-pill btn-icon">
									<i className="ri-notification-3-line"></i>
								</SpkButton>
							</div>
							<div className="">
								<SpkButton Size="sm" Buttontype="button" Buttonvariant="outline-primary" Customclass="rounded-pill btn-icon">
									<i className="ri-phone-line"></i>
								</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="outline-teal" Customclass="rounded-pill btn-icon">
									<i className="ri-customer-service-2-line"></i>
								</SpkButton>
								<SpkButton Size="lg" Buttontype="button" Buttonvariant="outline-success" Customclass="rounded-pill btn-icon">
									<i className="ri-live-line"></i>
								</SpkButton>
							</div>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title=" Social Buttons" customCardBodyClass="" dataCode={dataButton17} reactCode={reactButton17} reusableCode={reuseButton17}>
						{SocialIconButtons.map((idx, index) => (
							<SpkButton Buttontype="button" Buttonvariant={idx.class1} Customclass="waves-effect waves-light m-1 btn-icon" key={index}>
								<i className={`ri-${idx.class}-line`}></i>
							</SpkButton>
						))}
					</ShowCode>
				</Col>
				<Col xl={12}>
					<div className="row">
						<Col xl={12}>
							<ShowCode title="Sizes" customCardBodyClass="" reactCode={reactButton18} reusableCode={reuseButton18}>
								<div className="btn-list">
									<SpkButton Size="sm" Buttontype="button" Buttonvariant="primary" Customclass="">
										Small button
									</SpkButton>
									<SpkButton Buttontype="button" Buttonvariant="secondary" Customclass="">
										Default button
									</SpkButton>
									<SpkButton Size="lg" Buttontype="button" Buttonvariant="success" Customclass="">
										Large button
									</SpkButton>
								</div>
							</ShowCode>
						</Col>
					</div>
				</Col>
				<Col xl={12}>
					<div className="row">
						<Col xl={12}>
							<ShowCode title="Button Widths" customCardBodyClass="" reactCode={reactButton19} reusableCode={reuseButton19}>
								<div className="btn-list">
									<SpkButton Buttontype="button" Buttonvariant="primary" Customclass="btn-w-xs">XS</SpkButton>
									<SpkButton Buttontype="button" Buttonvariant="secondary" Customclass="btn-w-sm">SM</SpkButton>
									<SpkButton Buttontype="button" Buttonvariant="warning" Customclass="btn-w-md">MD</SpkButton>
									<SpkButton Buttontype="button" Buttonvariant="info" Customclass="btn-w-lg">LG</SpkButton>
								</div>
							</ShowCode>
						</Col>
					</div>
				</Col>
				<Col xl={12}>
					<ShowCode title="Buttons With Different Shadows" customCardBodyClass="" reactCode={reactButton20} reusableCode={reuseButton20}>
						<div className="btn-list d-flex flex-wrap">
							<div className="me-5">
								<SpkButton Buttontype="button" Buttonvariant="primary" Customclass="shadow-sm">Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="primary" Customclass="shadow">Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="primary" Customclass="shadow-lg">Button</SpkButton>
							</div>
							<div>

								<SpkButton Size="sm" Buttontype="button" Buttonvariant="secondary" Customclass="shadow-sm">Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="info" Customclass="shadow">Button</SpkButton>
								<SpkButton Size="lg" Buttontype="button" Buttonvariant="success" Customclass="shadow-lg">Button</SpkButton>
							</div>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Different Colored Buttons With Shadows" customCardBodyClass="" reactCode={reactButton21} dataCode={dataButton21} reusableCode={reuseButton21}>
						<div className="btn-list">
							{ColoredButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass={`shadow-${idx.class}`} key={index}>Button</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Raised Buttons" customCardBodyClass="" reactCode={reactButton22} dataCode={dataButton22} reusableCode={reuseButton22}>
						<div className="btn-list">
							{ColoredButtons.map((idx, index) => (
								<SpkButton Buttontype="button" Buttonvariant={idx.class} Customclass="btn-raised-shadow" key={index}>Button</SpkButton>
							))}
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Label Buttons" customCardBodyClass="" reactCode={reactButton23} reusableCode={reuseButton23}>
						<div className="btn-list">
							<SpkButton Buttontype="button" Buttonvariant="primary" Customclass="label-btn">
								<i className="ri-chat-smile-line label-btn-icon me-2"></i>
								Primary
							</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="secondary" Customclass="label-btn">
								<i className="ri-settings-4-line label-btn-icon me-2"></i>
								Secondary
							</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="warning" Customclass="label-btn rounded-pill">
								<i className="ri-spam-2-line label-btn-icon me-2 rounded-pill"></i>
								Warning
							</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="info" Customclass="label-btn rounded-pill">
								<i className="ri-phone-line label-btn-icon me-2 rounded-pill"></i>
								Info
							</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="success" Customclass="label-btn label-end">
								<i className="ri-thumb-up-line label-btn-icon ms-2"></i>
								Success
							</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="danger" Customclass="label-btn label-end rounded-pill">
								<i className="ri-close-line label-btn-icon ms-2 rounded-pill"></i>
								Cancel
							</SpkButton>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Custom Buttons" customCardBodyClass="" reactCode={reactButton24} reusableCode={reuseButton24}>
						<div className="btn-list">
							<SpkButton Buttontype="button" Buttonvariant="info" Customclass="custom-button rounded-pill">
								<span className="custom-btn-icons"><i className="ri-twitter-x-line text-info"></i></span>
								Twitter
							</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="teal-light" Customclass="btn-border-down">Border</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="secondary-light" Customclass="btn-border-start">Border</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="purple-light" Customclass="btn-border-end">Border</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="warning-light" Customclass="btn-border-top">Border</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="secondary" Customclass="btn-glare"> Glare Border</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="danger" Customclass="btn-hover btn-hover-animate">Like</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="success" Customclass="btn-darken-down">Hover</SpkButton>
							<SpkButton Buttontype="button" Buttonvariant="orange" Customclass="btn-custom-down">Hover</SpkButton>
						</div>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Block buttons" customCardBodyClass="" reactCode={reactButton25} reusableCode={reuseButton25}>
						<div className="btn-list">
							<div className="d-grid gap-2 mb-4">
								<SpkButton Buttontype="button" Buttonvariant="primary">Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="secondary">Button</SpkButton>
							</div>
							<div className="d-grid gap-2 d-md-block">

								<SpkButton Buttontype="button" Buttonvariant="info">Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="success">Button</SpkButton>
							</div>
							<div className="d-grid gap-2 col-6 mx-auto">

								<SpkButton Buttontype="button" Buttonvariant="danger">Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="warning">Button</SpkButton>
							</div>
							<div className="d-grid gap-2 d-md-flex justify-content-md-end">

								<SpkButton Buttontype="button" Buttonvariant="teal">Button</SpkButton>
								<SpkButton Buttontype="button" Buttonvariant="purple">Button</SpkButton>
							</div>
						</div>
					</ShowCode>
				</Col>
			</Row>

		</Fragment>
	)
};
// Assign layout
Buttons.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Buttons;
