// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/dashboards/ecommerce/checkout.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import SpkBadge from "@/shared/@spk/uielements/badge/SpkBadge.svelte";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import {
        CheckoutSummary,
        SummaryData,
    } from "@/shared/data/dashboards/ecommerce/checkoutdata";
    import {
        Card,
        CardBody,
        Col,
        Container,
        Image,
        Input,
        ListGroup,
        ListGroupItem,
        Modal,
        ModalBody,
        Nav,
        NavItem,
        NavLink,
        Row,
        TabContent,
        TabPane,
    } from "@sveltestrap/sveltestrap";

    const basePath = __BASE_PATH__

    let show = false;

    const handleShow = (e) => {
        e.preventDefault();
        show = true;
    };

    const handleClose = () => {
        show = false;
    };

    let activeTab = 1;
</script>

<!-- Page Title -->
<svelte:head>
    <title>Checkout | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Checkout"
    subTitle="Ecommerce"
    activepage="Dashboards"
    page="Checkout"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Container>
    <Row>
        <Col xl={8}>
            <Card class="custom-card !border-0">
                <CardBody>
                    <h5 class="mb-3">Personal Info</h5>
                    <Row class="gy-4">
                        <Col md={6}>
                            <Input
                                type="text"
                                class=""
                                id="firstName"
                                placeholder="First Name"
                            />
                        </Col>
                        <Col md={6}>
                            <Input
                                type="text"
                                class=""
                                id="lastName"
                                placeholder="Last Name"
                            />
                        </Col>
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="emailAddress"
                                placeholder="Email Address"
                            />
                        </Col>
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="mobileNumber"
                                placeholder="Mobile Number"
                            />
                        </Col>
                    </Row>
                    <div
                        class="mt-5 mb-3 d-flex align-items-center justify-content-between flex-wrap"
                    >
                        <h5 class="fw-semibold mb-0">Shipping Address</h5>
                        <a
                            href="#select-address"
                            onclick={handleShow}
                            class="link-primary"
                            data-bs-toggle="modal">Select From Address Book</a
                        >
                    </div>
                    <Row class="mb-4">
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="fullName"
                                placeholder="Full Name"
                            />
                        </Col>
                    </Row>
                    <Row class="gy-4">
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="address1"
                                placeholder="Address 1"
                            />
                        </Col>
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="address2"
                                placeholder="Address 2"
                            />
                        </Col>
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="landMark"
                                placeholder="Landmark"
                            />
                        </Col>
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="pinZipCode"
                                placeholder="Pincode / Zipcode"
                            />
                        </Col>
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="city"
                                placeholder="City"
                            />
                        </Col>
                        <Col md={6}>
                            <Input
                                type="email"
                                class=""
                                id="stateDistrict"
                                placeholder="State, District"
                            />
                        </Col>
                        <div class="col-md-12">
                            <Input
                                type="textarea"
                                rows={3}
                                class="form-control"
                                id="deliveryInstructions"
                                placeholder="Delivery Instructions"
                            />
                        </div>
                        <Col md={12}>
                            <div
                                class="form-group d-flex align-items-center flex-wrap"
                            >
                                <div class="min-w-fit-content me-4">
                                    <p class="mb-0 fw-medium">Address Type:</p>
                                </div>
                                <div class="flex-grow-1">
                                    <div class="d-flex gap-4 flex-wrap">
                                        <div class="form-check mb-0">
                                            <input
                                                class="form-check-input"
                                                type="radio"
                                                name="addressType"
                                                id="radio-1"
                                                defaultChecked
                                            />
                                            <label
                                                class="form-check-labe fs-13l"
                                                for="radio-1">Home</label
                                            >
                                        </div>
                                        <div class="form-check mb-0">
                                            <input
                                                class="form-check-input"
                                                type="radio"
                                                name="addressType"
                                                id="radio-2"
                                            />
                                            <label
                                                class="form-check-label fs-13"
                                                for="radio-2">Work</label
                                            >
                                        </div>
                                        <div class="form-check mb-0">
                                            <input
                                                class="form-check-input"
                                                type="radio"
                                                name="addressType"
                                                id="radio-3"
                                            />
                                            <label
                                                class="form-check-label fs-13"
                                                for="radio-3">Other</label
                                            >
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </Col>
                    </Row>
                    <div class="mt-5">
                        <h5 class="fw-semibold mb-3">Payment Method</h5>
                        <Nav
                            class="nav-tabs custom-nav-tabs-2 gap-3"
                            id="myTab"
                            role="tablist"
                        >
                            <NavItem role="presentation" class="me-0">
                                <NavLink
                                    on:click={(e) => {
                                        (activeTab = 1), e.preventDefault();
                                    }}
                                    active={activeTab == 1}
                                    role="tab"
                                >
                                    <div class="d-flex align-items-center">
                                        <span class="min-w-fit-content me-3">
                                            <i class={`bi bi-paypal fs-20`}></i>
                                        </span>
                                        <div class="flex-grow-1">PayPal</div>
                                    </div>
                                </NavLink>
                            </NavItem>
                            <NavItem role="presentation" class="me-0">
                                <NavLink
                                    on:click={(e) => {
                                        (activeTab = 2), e.preventDefault();
                                    }}
                                    active={activeTab == 2}
                                    role="tab"
                                >
                                    <div class="d-flex align-items-center">
                                        <span class="min-w-fit-content me-3">
                                            <i class={`bi bi-credit-card fs-20`}
                                            ></i>
                                        </span>
                                        <div class="flex-grow-1">
                                            Credit Or Debit Card
                                        </div>
                                    </div>
                                </NavLink>
                            </NavItem>
                            <NavItem role="presentation" class="me-0">
                                <NavLink
                                    on:click={(e) => {
                                        (activeTab = 3), e.preventDefault();
                                    }}
                                    active={activeTab == 3}
                                    role="tab"
                                >
                                    <div class="d-flex align-items-center">
                                        <span class="min-w-fit-content me-3">
                                            <i class={`bi bi-globe fs-20`}></i>
                                        </span>
                                        <div class="flex-grow-1">
                                            UPI / Net Banking
                                        </div>
                                    </div>
                                </NavLink>
                            </NavItem>
                            <NavItem role="presentation" >
                                <NavLink
                                    on:click={(e) => {
                                        (activeTab = 4), e.preventDefault();
                                    }}
                                    active={activeTab == 4}
                                    role="tab"
                                >
                                    <div class="d-flex align-items-center">
                                        <span class="min-w-fit-content me-3">
                                            <i class={`bi bi-cash-stack fs-20`}
                                            ></i>
                                        </span>
                                        <div class="flex-grow-1">
                                            Cash On Delivery
                                        </div>
                                    </div>
                                </NavLink>
                            </NavItem>
                        </Nav>
                        <TabContent id="checkoutTab">
                            <TabPane
                                class={`p-0 border-0 ${activeTab == 1 ? "active" : ""}`}
                                id="paypal-tab"
                                role="tabpanel"
                            >
                                <p class="mb-3 mt-4 text-muted">
                                    Order will be placed once the payment is
                                    done. Please read all the terms &amp;
                                    conditions about <a
                                        href="#!"
                                        class="text-primary text-decoration-underline"
                                        >refund policy</a
                                    >.
                                </p>
                                <a href="#!" class="btn btn-primary"
                                    >Proceed to pay <i
                                        class="ti ti-arrow-right fs-18 ms-2 align-middle d-inline-block rtl-transform-icon"
                                    ></i></a
                                >
                            </TabPane>
                            <TabPane
                                class={`p-0 border-0 ${activeTab == 2 ? "active" : ""}`}
                                id="card-tab"
                                role="tabpanel"
                            >
                                <p class="mb-2 mt-4 fw-medium">Card Details:</p>
                                <Row class="gy-4">
                                    <Col md={6}>
                                        <Input
                                            type="text"
                                            class=""
                                            id="cardHolderName"
                                            placeholder="Card Holder Name"
                                        />
                                    </Col>
                                    <Col md={6}>
                                        <Input
                                            type="text"
                                            class=""
                                            id="cardNumber"
                                            placeholder="Card Number"
                                        />
                                    </Col>
                                    <div class="col-md-3">
                                        <Input
                                            type="text"
                                            class=""
                                            id="expDate"
                                            placeholder="Expiry Date"
                                        />
                                    </div>
                                    <div class="col-md-2">
                                        <Input
                                            type="text"
                                            class=""
                                            id="cvv"
                                            placeholder="CVV"
                                        />
                                    </div>
                                </Row>
                                <p class="mb-3 mt-2 fs-13 text-muted">
                                    <span><i class="ti ti-lock fs-16"></i></span
                                    >
                                    <span
                                        >Your transaction is secured with
                                        encryption.</span
                                    >
                                </p>
                                <a href="#!" class="btn btn-primary"
                                    >Proceed to pay <i
                                        class="ti ti-arrow-right fs-18 ms-2 align-middle d-inline-block rtl-transform-icon"
                                    ></i></a
                                >
                            </TabPane>
                            <TabPane
                                class={`p-0 border-0 ${activeTab == 3 ? "active" : ""}`}
                                id="netbanking-tab"
                                role="tabpanel"
                            >
                                <p class="mb-3 mt-4 text-muted">
                                    Order will be placed once the payment is
                                    done. Please read all the terms & conditions
                                    about <a
                                        href="#!"
                                        class="text-primary text-decoration-underline"
                                        >refund policy</a
                                    >.
                                </p>
                                <a href="#!" class="btn btn-primary"
                                    >Proceed to pay <i
                                        class="ti ti-arrow-right fs-18 ms-2 align-middle d-inline-block rtl-transform-icon"
                                    ></i></a
                                >
                            </TabPane>
                            <TabPane
                                class={`p-0 border-0 ${activeTab == 4 ? "active" : ""}`}
                                id="cod-tab"
                                role="tabpanel"
                            >
                                <p class="mb-3 mt-4 text-muted">
                                    Proceed to place order. If you have any
                                    doubts regarding returning/exchanging
                                    products, checkout <a
                                        href="#!"
                                        class="text-primary text-decoration-underline"
                                        >Return & Exchange policy</a
                                    >
                                </p>
                                <a href="#!" class="btn btn-primary"
                                    >Proceed to checkout <i
                                        class="ti ti-arrow-right align-middle fs-18 ms-2 d-inline-block rtl-transform-icon"
                                    ></i></a
                                >
                            </TabPane>
                        </TabContent>
                    </div>
                </CardBody>
            </Card>
        </Col>
        <Col xl={4}>
            <Card class="custom-card overflow-hidden">
                <CardBody class="p-0">
                    <ListGroup class="list-group-flush">
                        {#each CheckoutSummary as product}
                            <ListGroupItem class="">
                                <div class="d-flex align-items-center gap-3">
                                    <div class="lh-1">
                                        <span class="avatar avatar-xxl">
                                            <Image
                                                src={`${basePath}${product.imageUrl}`}
                                                alt={product.name}
                                            />
                                        </span>
                                    </div>
                                    <div class="flex-fill">
                                        <span class="fw-semibold d-block mb-2"
                                            >{product.name}</span
                                        >
                                        <span
                                            class="text-muted d-block fs-13 mb-1"
                                            >Color : {product.color}</span
                                        >
                                        <div
                                            class="d-flex align-items-center justify-content-between flex-wrap"
                                        >
                                            <span
                                                class="text-muted d-block fs-13"
                                            >
                                                Qty : {product.quantity} x ${product.price.toFixed(
                                                    2,
                                                )}
                                            </span>
                                            <div class="fw-semibold">
                                                ${(
                                                    product.quantity *
                                                    product.price
                                                ).toFixed(2)}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </ListGroupItem>
                        {/each}
                    </ListGroup>
                </CardBody>
                <div class="card-footer">
                    <span class="d-block fs-14 text-muted mb-1"
                        >Have a coupon ? Enter below</span
                    >
                    <div class="input-group mb-1">
                        <Input
                            type="text"
                            class="form-control-sm"
                            placeholder="Coupon Code"
                            aria-label="coupon-code"
                            aria-describedby="coupons"
                        />
                        <SpkButton
                            color="primary"
                            customClass="btn input-group-text">Apply</SpkButton
                        >
                    </div>
                    <ul class="list-unstyled cart-order-summary-list mt-3">
                        {#each SummaryData as item}
                            <li>
                                <div
                                    class={`d-flex align-items-center justify-content-between ${item.isTotal ? "text-primary" : ""}`}
                                >
                                    <div>{item.label}</div>
                                    <div
                                        class={`fw-medium ${item.isTotal ? "fw-semibold h5 mb-0 text-primary" : ""} ${item.isFree ? "text-success" : ""}`}
                                    >
                                        {item.value}
                                    </div>
                                </div>
                            </li>
                        {/each}
                    </ul>
                </div>
            </Card>
        </Col>
    </Row>
</Container>

<!--End::row-1 -->

<!-- Start:: select address modal -->

<Modal
    isOpen={show}
    size="lg"
    toggle={handleClose}
    class="modal-style-1 modal-3"
    fade
    centered
    id="select-address"
>
    <ModalBody>
        <div class="d-flex align-items-start justify-content-between mb-4">
            <h6 class="fs-18 mb-0">Select Address</h6>
            <SpkButton
                color=""
                onclickfunc={handleClose}
                buttontype="button"
                customClass="btn-close select_address"
            ></SpkButton>
        </div>
        <div class="row">
            <Col md={12}>
                <Card class="custom-card checkout-address-card">
                    <CardBody>
                        <!-- form-check -->

                        <input
                            class="form-check-input d-none"
                            type="radio"
                            id="address1_select"
                            name="select-address"
                            defaultChecked
                        />
                        <label
                            class="position-absolute all-0 cursor-pointer"
                            for="address1_select"
                        ></label>

                        <!-- form-check -->

                        <SpkBadge
                            Color=""
                            CustomClass="bg-secondary rounded-pill custom-badge-3"
                            >Default</SpkBadge
                        >

                        <div class="d-flex align-items-center gap-2 mb-3">
                            <div class="lh-1">
                                <span
                                    class="avatar avatar-md avatar-rounded border"
                                    ><i class="ti ti-home fs-5"></i></span
                                >
                            </div>
                            <h6 class="fs-16 mb-0">Home</h6>
                        </div>
                        <p class="mb-1 fw-medium text-default">Ruby Disousa</p>
                        <p class="mb-1 fw-medium text-muted fs-13">
                            rubyakuner@ginna.mail
                        </p>
                        <p class="mb-2 fw-medium text-muted fs-13">
                            +11-23-1116773
                        </p>
                        <p class="mb-0 fs-13 text-muted">
                            H.No: 3-116/458, Golden Park, Marias St., Near
                            12Amet Residency, 14756, United States Of America
                        </p>
                    </CardBody>
                </Card>
            </Col>
            <Col md={12}>
                <Card class="checkout-address-card">
                    <CardBody>
                        <!-- form-check -->

                        <input
                            class="form-check-input d-none"
                            type="radio"
                            id="address2_select"
                            name="select-address"
                        />
                        <label
                            class="position-absolute all-0 cursor-pointer"
                            for="address2_select"
                        ></label>

                        <!-- form-check -->

                        <div class="d-flex align-items-center gap-2 mb-3">
                            <div class="lh-1">
                                <span
                                    class="avatar avatar-md avatar-rounded border"
                                    ><i class="ti ti-briefcase fs-16"></i></span
                                >
                            </div>
                            <h6 class="fs-16 mb-0">Work</h6>
                        </div>
                        <p class="mb-1 fw-medium text-default">Ruby Disousa</p>
                        <p class="mb-1 fw-medium text-muted fs-13">
                            rubyakuner@ginna.mail
                        </p>
                        <p class="mb-2 fw-medium text-muted fs-13">
                            +11-23-1116773
                        </p>
                        <p class="mb-0 fs-13 text-muted">
                            Taj Building, 3rd Floor, Room No: 3, Silver St.,
                            Adugiahsuk, LICE, 14756, United States Of America
                        </p>
                    </CardBody>
                </Card>
            </Col>
        </div>
        <div class="d-flex align-items-center gap-2 justify-content-end">
            <a
                href="#!"
                onclick={handleClose}
                class="btn btn-light"
                data-bs-dismiss="modal">Cancel</a
            >
            <a href="#!" class="btn btn-primary">Select address</a>
        </div>
    </ModalBody>
</Modal>

<!-- End:: select address modal -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/ecommerce/checkout/Checkout.jsx

import React, { Fragment, useState } from "react";
import { Card, Col, Container, Form, Image, ListGroup, Modal, Nav, Row, Tab } from "react-bootstrap";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { CheckoutSummary, SummaryData } from "../../../../shared/data/dashboards/ecommerce/checkoutdata";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import SpkBadge from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";
const Checkout = () => {

    const [show, setShow] = useState(false)
    const handleShow = () => setShow(true);
    const handleClose = () => setShow(false);

    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Dashboards-Checkout" />

            <Pageheader title="Dashboards" subtitle="Ecommerce" currentpage="Checkout" activepage="Checkout" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Container>
                <Row>
                    <Col xl={8}>
                        <Card className="custom-card !border-0">
                            <Card.Body>
                                <h5 className="mb-3">
                                    Personal Info
                                </h5>
                                <Row className="gy-4">
                                    <Col md={6}>
                                        <Form.Control type="text" className="" id="firstName" placeholder="First Name" />
                                    </Col>
                                    <Col md={6}>
                                        <Form.Control type="text" className="" id="lastName" placeholder="Last Name" />
                                    </Col>
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="emailAddress" placeholder="Email Address" />
                                    </Col>
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="mobileNumber" placeholder="Mobile Number" />
                                    </Col>
                                </Row>
                                <div className="mt-5 mb-3 d-flex align-items-center justify-content-between flex-wrap">
                                    <h5 className="fw-semibold mb-0">Shipping Address</h5>
                                    <BaseLink href="#select-address" onClick={handleShow} className="link-primary" data-bs-toggle="modal">Select From Address Book</BaseLink>
                                </div>
                                <Row className="mb-4">
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="fullName" placeholder="Full Name" />
                                    </Col>
                                </Row>
                                <Row className="gy-4">
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="address1" placeholder="Address 1" />
                                    </Col>
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="address2" placeholder="Address 2" />
                                    </Col>
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="landMark" placeholder="Landmark" />
                                    </Col>
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="pinZipCode" placeholder="Pincode / Zipcode" />
                                    </Col>
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="city" placeholder="City" />
                                    </Col>
                                    <Col md={6}>
                                        <Form.Control type="email" className="" id="stateDistrict" placeholder="State, District" />
                                    </Col>
                                    <div className="col-md-12">
                                        <Form.Control as="textarea" rows={3} className="form-control" id="deliveryInstructions" placeholder="Delivery Instructions" />
                                    </div>
                                    <Col md={12}>
                                        <div className="form-group d-flex align-items-center flex-wrap">
                                            <div className="min-w-fit-content me-4">
                                                <p className="mb-0 fw-medium">Address Type:</p>
                                            </div>
                                            <div className="flex-grow-1">
                                                <div className="d-flex gap-4 flex-wrap">
                                                    <div className="form-check mb-0">
                                                        <input className="form-check-input" type="radio" name="addressType" id="radio-1" defaultChecked />
                                                        <label className="form-check-labe fs-13l" htmlFor="radio-1">Home</label>
                                                    </div>
                                                    <div className="form-check mb-0">
                                                        <input className="form-check-input" type="radio" name="addressType" id="radio-2" />
                                                        <label className="form-check-label fs-13" htmlFor="radio-2">Work</label>
                                                    </div>
                                                    <div className="form-check mb-0">
                                                        <input className="form-check-input" type="radio" name="addressType" id="radio-3" />
                                                        <label className="form-check-label fs-13" htmlFor="radio-3">Other</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </Col>
                                </Row>
                                <div className="mt-5">
                                    <h5 className="fw-semibold mb-3">Payment Method</h5>
                                    <Tab.Container defaultActiveKey={"paypal"}>
                                        <Nav className="nav-tabs custom-nav-tabs-2 gap-3" id="myTab" role="tablist">
                                            <Nav.Item role="presentation" className="me-0" >
                                                <Nav.Link eventKey={"paypal"} role="tab">
                                                    <div className="d-flex align-items-center">
                                                        <span className="min-w-fit-content me-3">
                                                            <i className={`bi bi-paypal fs-20`}></i>
                                                        </span>
                                                        <div className="flex-grow-1">PayPal</div>
                                                    </div>
                                                </Nav.Link>
                                            </Nav.Item>
                                            <Nav.Item role="presentation" className="me-0" >
                                                <Nav.Link eventKey={"credit"} role="tab" className="me-0">
                                                    <div className="d-flex align-items-center">
                                                        <span className="min-w-fit-content me-3">
                                                            <i className={`bi bi-credit-card fs-20`}></i>
                                                        </span>
                                                        <div className="flex-grow-1">Credit Or Debit Card</div>
                                                    </div>
                                                </Nav.Link>
                                            </Nav.Item>
                                            <Nav.Item role="presentation" className="me-0" >
                                                <Nav.Link eventKey={"upi"} role="tab" className="me-0">
                                                    <div className="d-flex align-items-center">
                                                        <span className="min-w-fit-content me-3">
                                                            <i className={`bi bi-globe fs-20`}></i>
                                                        </span>
                                                        <div className="flex-grow-1">UPI / Net Banking</div>
                                                    </div>
                                                </Nav.Link>
                                            </Nav.Item>
                                            <Nav.Item role="presentation" className="me-0" >
                                                <Nav.Link eventKey={"cash"} role="tab">
                                                    <div className="d-flex align-items-center">
                                                        <span className="min-w-fit-content me-3">
                                                            <i className={`bi bi-cash-stack fs-20`}></i>
                                                        </span>
                                                        <div className="flex-grow-1">Cash On Delivery</div>
                                                    </div>
                                                </Nav.Link>
                                            </Nav.Item>
                                        </Nav>
                                        <Tab.Content>
                                            <Tab.Pane eventKey={"paypal"} className="tab-pane p-0 border-0" id="paypal-tab" role="tabpanel">
                                                <p className="mb-3 mt-4 text-muted">Order will be placed once the payment is done. Please read all the terms &amp; conditions about <BaseLink href="#!" className="text-primary text-decoration-underline">refund policy</BaseLink>.</p>
                                                <BaseLink href="#!" className="btn btn-primary">Proceed to pay <i className="ti ti-arrow-right fs-18 ms-2 align-middle d-inline-block rtl-transform-icon"></i></BaseLink>
                                            </Tab.Pane>
                                            <Tab.Pane eventKey={"credit"} className="tab-pane p-0 border-0" id="card-tab" role="tabpanel">
                                                <p className="mb-2 mt-4 fw-medium">Card Details:</p>
                                                <Row className="gy-4">
                                                    <Col md={6}>
                                                        <Form.Control type="text" className="" id="cardHolderName" placeholder="Card Holder Name" />
                                                    </Col>
                                                    <Col md={6}>
                                                        <Form.Control type="text" className="" id="cardNumber" placeholder="Card Number" />
                                                    </Col>
                                                    <div className="col-md-3">
                                                        <Form.Control type="text" className="" id="expDate" placeholder="Expiry Date" />
                                                    </div>
                                                    <div className="col-md-2">
                                                        <Form.Control type="text" className="" id="cvv" placeholder="CVV" />
                                                    </div>
                                                </Row>
                                                <p className="mb-3 mt-2 fs-13 text-muted">
                                                    <span><i className="ti ti-lock fs-16"></i></span>
                                                    <span>Your transaction is secured with encryption.</span>
                                                </p>
                                                <BaseLink href="#!" className="btn btn-primary">Proceed to pay <i className="ti ti-arrow-right fs-18 ms-2 align-middle d-inline-block rtl-transform-icon"></i></BaseLink>
                                            </Tab.Pane>
                                            <Tab.Pane eventKey={"upi"} className="tab-pane p-0 border-0" id="netbanking-tab" role="tabpanel">
                                                <p className="mb-3 mt-4 text-muted">Order will be placed once the payment is done. Please read all the terms & conditions about <BaseLink href="#!" className="text-primary text-decoration-underline">refund policy</BaseLink>.</p>
                                                <BaseLink href="#!" className="btn btn-primary">Proceed to pay <i className="ti ti-arrow-right fs-18 ms-2 align-middle d-inline-block rtl-transform-icon"></i></BaseLink>
                                            </Tab.Pane>
                                            <Tab.Pane eventKey={"cash"} className="tab-pane p-0 border-0" id="cod-tab" role="tabpanel">
                                                <p className="mb-3 mt-4 text-muted">Proceed to place order. If you have any doubts regarding returning/exchanging products, checkout <BaseLink href="#!" className="text-primary text-decoration-underline">Return & Exchange policy</BaseLink></p>
                                                <BaseLink href="#!" className="btn btn-primary">Proceed to checkout <i className="ti ti-arrow-right align-middle fs-18 ms-2 d-inline-block rtl-transform-icon"></i></BaseLink>
                                            </Tab.Pane>
                                        </Tab.Content>
                                    </Tab.Container>
                                </div>
                            </Card.Body>
                        </Card>
                    </Col>
                    <Col xl={4}>
                        <Card className="custom-card overflow-hidden">
                            <Card.Body className="p-0">
                                <ListGroup className="list-group-flush">
                                    {CheckoutSummary.map((product) => (
                                        <ListGroup.Item className="" key={product.id}>
                                            <div className="d-flex align-items-center gap-3">
                                                <div className="lh-1">
                                                    <span className="avatar avatar-xxl">
                                                        <BaseImage src={product.imageUrl} alt={product.name} />
                                                    </span>
                                                </div>
                                                <div className="flex-fill">
                                                    <span className="fw-semibold d-block mb-2">{product.name}</span>
                                                    <span className="text-muted d-block fs-13 mb-1">Color : {product.color}</span>
                                                    <div className="d-flex align-items-center justify-content-between flex-wrap">
                                                        <span className="text-muted d-block fs-13">
                                                            Qty : {product.quantity} x ${product.price.toFixed(2)}
                                                        </span>
                                                        <div className="fw-semibold">
                                                            ${(product.quantity * product.price).toFixed(2)}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </ListGroup.Item>
                                    ))}
                                </ListGroup>
                            </Card.Body>
                            <div className="card-footer">
                                <span className="d-block fs-14 text-muted mb-1">Have a coupon ? Enter below</span>
                                <div className="input-group mb-1">
                                    <Form.Control type="text" className="form-control-sm" placeholder="Coupon Code" aria-label="coupon-code" aria-describedby="coupons" />
                                    <SpkButton Buttonvariant="primary" Customclass="btn input-group-text">Apply</SpkButton>
                                </div>
                                <ul className="list-unstyled cart-order-summary-list mt-3">
                                    {SummaryData.map((item, index) => (
                                        <li key={index}>
                                            <div className={`d-flex align-items-center justify-content-between ${item.isTotal ? 'text-primary' : ''}`}>
                                                <div>{item.label}</div>
                                                <div className={`fw-medium ${item.isTotal ? 'fw-semibold h5 mb-0 text-primary' : ''} ${item.isFree ? 'text-success' : ''}`}>
                                                    {item.value}
                                                </div>
                                            </div>
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </Card>
                    </Col>
                </Row>
            </Container>

            {/* <!--End::row-1 --> */}

            {/* <!-- Start:: select address modal --> */}

            <Modal show={show} size="lg" onHide={handleClose} className="fade modal-style-1 modal-3" centered id="select-address" aria-hidden="true">
                <Modal.Body>
                    <div className="d-flex align-items-start justify-content-between mb-4">
                        <h6 className="fs-18 mb-0">Select Address</h6>
                        <SpkButton Buttonvariant="" onClickfunc={handleClose} Buttontype="button" Customclass="btn-close p-1" data-bs-dismiss="modal" aria-label="Close"></SpkButton>
                    </div>
                    <div className="row">
                        <Col md={12}>
                            <Card className="custom-card checkout-address-card">
                                <Card.Body>

                                    {/* <!-- form-check --> */}

                                    <input className="form-check-input d-none" type="radio" id="address1_select" name="select-address" defaultChecked />
                                    <label className="position-absolute all-0 cursor-pointer" htmlFor="address1_select"></label>

                                    {/* <!-- form-check --> */}

                                    <SpkBadge variant="" Customclass="bg-secondary rounded-pill custom-badge-3">Default</SpkBadge>

                                    <div className="d-flex align-items-center gap-2 mb-3">
                                        <div className="lh-1">
                                            <span className="avatar avatar-md avatar-rounded border"><i className="ti ti-home fs-5"></i></span>
                                        </div>
                                        <h6 className="fs-16 mb-0">Home</h6>
                                    </div>
                                    <p className="mb-1 fw-medium text-default">Ruby Disousa</p>
                                    <p className="mb-1 fw-medium text-muted fs-13">rubyakuner@ginna.mail</p>
                                    <p className="mb-2 fw-medium text-muted fs-13">+11-23-1116773</p>
                                    <p className="mb-0 fs-13 text-muted">
                                        H.No: 3-116/458, Golden Park, Marias St.,
                                        Near 12Amet Residency, 14756, United States Of America
                                    </p>
                                </Card.Body>
                            </Card>
                        </Col>
                        <Col md={12}>
                            <Card className="custom-card checkout-address-card">
                                <Card.Body>

                                    {/* <!-- form-check --> */}

                                    <input className="form-check-input d-none" type="radio" id="address2_select" name="select-address" />
                                    <label className="position-absolute all-0 cursor-pointer" htmlFor="address2_select"></label>

                                    {/* <!-- form-check --> */}

                                    <div className="d-flex align-items-center gap-2 mb-3">
                                        <div className="lh-1">
                                            <span className="avatar avatar-md avatar-rounded border"><i className="ti ti-briefcase fs-16"></i></span>
                                        </div>
                                        <h6 className="fs-16 mb-0">Work</h6>
                                    </div>
                                    <p className="mb-1 fw-medium">Ruby Disousa</p>
                                    <p className="mb-1 fw-medium text-muted fs-13">rubyakuner@ginna.mail</p>
                                    <p className="mb-2 fw-medium text-muted fs-13">+11-23-1116773</p>
                                    <p className="mb-0 fs-13 text-muted">
                                        Taj Building, 3rd Floor, Room No: 3, Silver St.,
                                        Adugiahsuk, LICE, 14756, United States Of America
                                    </p>
                                </Card.Body>
                            </Card>
                        </Col>
                    </div>
                    <div className="d-flex align-items-center gap-2 justify-content-end">
                        <BaseLink href="#!" onClick={handleClose} className="btn btn-light" data-bs-dismiss="modal">Cancel</BaseLink>
                        <BaseLink href="#!" className="btn btn-primary">Select address</BaseLink>
                    </div>
                </Modal.Body>
            </Modal>

            {/* <!-- End:: select address modal --> */}

        </Fragment>
    )
};

Checkout.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Checkout;
