// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/general-reusable/reusable-uielements/reusable-cards/spkcollapsecard.jsx

import React, { Fragment, useState } from 'react'
import { Card, Collapse } from 'react-bootstrap'
import SpkButton from '../spk-buttons';
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const SpkCollapsecard = ({ Customheaderclass, OnClickFunc, expandButton = false, collapseToggle = false, normalToggle = false, hideToggle = false, children, Title, footertext, Navigate, }) => {

    const [BasicExpanded, setBasicExpanded] = useState(true);

    const BasicHandleExpandClick = () => {
        setBasicExpanded(!BasicExpanded);
    };

    //Card With Close Button
    const [Basicshow, setBasicshow] = useState(true);

    return (
        <Fragment>
            {Basicshow ?
                <Card className="custom-card">
                    <Card.Header className={`card-header justify-content-between border-bottom-0 ${Customheaderclass}`}>
                        {collapseToggle && <Card.Title>
                            {Title}
                        </Card.Title>
                        }
                        {hideToggle &&
                            Basicshow ?
                            <Card.Title>
                                {Title}
                            </Card.Title> : null
                        }

                        {
                            normalToggle &&
                            <Card.Title>
                                {Title}
                            </Card.Title>
                        }
                        {expandButton &&
                            <BaseLink href={Navigate} onClick={BasicHandleExpandClick} >
                                <i className={`ri-${BasicExpanded ? 'arrow-down-s-line' : 'arrow-up-s-line'} fs-18`}></i>
                            </BaseLink>
                        }
                        {
                            hideToggle &&
                                Basicshow ?
                                <BaseLink href={Navigate} onClick={() => setBasicshow(false)} >
                                    <i className='ri-close-line fs-18'></i>
                                </BaseLink> : null
                        }
                        {
                            normalToggle &&
                            <BaseLink href={Navigate} onClick={OnClickFunc} >
                                <i className="ri-fullscreen-line"></i>
                            </BaseLink>

                        }
                    </Card.Header>
                    {
                        collapseToggle &&
                        <>
                            <Collapse className="border-top" in={BasicExpanded} timeout={3000}>
                                <div>
                                    <Card.Body>
                                        {children}
                                    </Card.Body>
                                    <Card.Footer>
                                        <SpkButton Buttonvariant="primary">{footertext}</SpkButton>
                                    </Card.Footer>
                                </div>
                            </Collapse>
                        </>
                    }

                    {
                        hideToggle &&
                            Basicshow ? <>
                            <Card.Body className="border-top">
                                {children}
                            </Card.Body>
                            <Card.Footer>
                                <SpkButton Buttonvariant="primary">{footertext}</SpkButton>
                            </Card.Footer>
                        </> : null
                    }


                    {
                        normalToggle &&
                        <>
                            <Card.Body className="border-top">
                                {children}
                            </Card.Body>
                            <Card.Footer>
                                <SpkButton Buttonvariant="primary">{footertext}</SpkButton>
                            </Card.Footer>
                        </>
                    }

                </Card> : null
            }

        </Fragment >
    )
}

export default SpkCollapsecard

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/uielements/reusable-cards/spkcollapsecard.svelte
<script>
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        CardTitle,
        Collapse,
    } from "@sveltestrap/sveltestrap";
    import SpkButton from "../Button/SpkButton.svelte";

    export let CustomCardClass = "";
    export let Customheaderclass = "";
    export let footertext = "";
    export let Title = "";
    export let Navigate = "";
    export let expandButton = false;
    export let collapseToggle = false;
    export let normalToggle = false;
    export let hideToggle = false;

    // State variables
    let BasicExpanded = true;
    let Basicshow = true;

    // Toggle expand state
    function BasicHandleExpandClick() {
        BasicExpanded = !BasicExpanded;
    }

    // Hide the close button
    function closeButtonFunc() {
        Basicshow = false;
    }

    //  full screen

    //Fullscreen
    let isFullscreen = false; // Track fullscreen state

    function toggleFullscreen() {
        isFullscreen = !isFullscreen; // Toggle fullscreen state
    }
</script>

{#if Basicshow}
    <Card
        class={`custom-card ${CustomCardClass} ${isFullscreen ? "card-fullscreen" : ""} `}
    >
        <CardHeader
            class={`card-header justify-content-between border-bottom-0 ${Customheaderclass}`}
        >
            {#if collapseToggle}
                <CardTitle>
                    {Title}
                </CardTitle>
            {/if}

            {#if hideToggle}
                {#if Basicshow}
                    <CardTitle>
                        {Title}
                    </CardTitle>
                {:else}
                    {null}
                {/if}
            {/if}

            {#if normalToggle}
                <CardTitle>
                    {Title}
                </CardTitle>
            {/if}

            <!-- svelte-ignore a11y_consider_explicit_label -->
            {#if expandButton}
                <a href={Navigate} on:click={BasicHandleExpandClick}>
                    <i
                        class={`${BasicExpanded ? "ri-arrow-down-s-line" : "ri-arrow-up-s-line"} fs-18`}
                    ></i>
                </a>
            {/if}
            {#if hideToggle}
                {#if Basicshow}
                    <a href={Navigate} on:click={closeButtonFunc}>
                        <i class="ri-close-line fs-18"></i>
                    </a>
                {/if}
            {/if}

            {#if normalToggle}
                <a href={Navigate} on:click={toggleFullscreen}>
                    <i class="ri-fullscreen-line"></i>
                </a>
            {/if}
        </CardHeader>

        {#if collapseToggle}
            <Collapse class="border-top" isOpen={BasicExpanded}>
                <div>
                    <CardBody>
                        <slot />
                    </CardBody>
                    <CardFooter>
                        <SpkButton color="primary">{footertext}</SpkButton>
                    </CardFooter>
                </div>
            </Collapse>
        {/if}

        {#if hideToggle}
            {#if Basicshow}
                <CardBody class="border-top">
                    <slot />
                </CardBody>
                <CardFooter>
                    <SpkButton color="primary">{footertext}</SpkButton>
                </CardFooter>
            {:else}
                {null}
            {/if}
        {/if}

        {#if normalToggle}
            <CardBody class="border-top">
                <slot />
            </CardBody>
            <CardFooter>
                <SpkButton color="primary">{footertext}</SpkButton>
            </CardFooter>
        {/if}
    </Card>
{/if}
