// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/general/ui-elements/object-fit.svelte

<script context="module">
    import MainLayout from '@/layouts/MainLayout.svelte';
    export const layout = MainLayout; 
</script>
<script>
  import Pageheader from "@/components/page-header/Pageheader.svelte";
  import ShowCode from "@/components/showcode/ShowCode.svelte";
  import { Col, Row, Image } from "@sveltestrap/sveltestrap";
  import {
    objectfit1,
    objectfit10,
    objectfit11,
    objectfit12,
    objectfit13,
    objectfit14,
    objectfit15,
    objectfit2,
    objectfit3,
    objectfit4,
    objectfit5,
    objectfit6,
    objectfit7,
    objectfit8,
    objectfit9,
  } from "@/shared/data/prism-code/uielementsprim";
</script>

<!-- Page Title -->
<svelte:head>
  <title>ObjectFit | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<Pageheader homepage="Object Fit" activepage="UI Elements" page="Object Fit" />
<!-- Start::row-1 -->
<Row>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Contain"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit1}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-contain border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Cover"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit2}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-cover border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Fill"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit3}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-fill border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Scale Down"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit4}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-scale border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit None"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit5}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-none border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Contain (SM - responsive)"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit6}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-sm-contain border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Contain (MD - responsive)"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit7}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-md-contain border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Contain (LG - responsive)"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit8}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-lg-contain border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Contain (XL - responsive)"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit9}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-xl-contain border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Contain (XXL - responsive)"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit10}
    >
      <Image
        src="../../images/media/media-28.jpg"
        class="object-fit-xxl-contain border rounded"
        alt="..."
      />
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Contain Video"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit11}
    >
      <video
        src="../../video/1.mp4"
        class="object-fit-contain rounded border"
        autoPlay
        loop
        muted
      ></video>
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Cover Video"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit12}
    >
      <video
        src="../../video/1.mp4"
        class="object-fit-cover rounded border"
        autoPlay
        loop
        muted
      ></video>
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Fill Video"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit13}
    >
      <video
        src="../../video/1.mp4"
        class="object-fit-fill rounded border"
        autoPlay
        loop
        muted
      ></video>
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit Scale Video"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit14}
    >
      <video
        src="../../video/1.mp4"
        class="object-fit-scale rounded border"
        autoPlay
        loop
        muted
      ></video>
    </ShowCode>
  </Col>
  <Col xxl={6} xl={6} lg={6} md={6} sm={12}>
    <ShowCode
      title="Object Fit None Video"
      customCardBodyClass="object-fit-container"
      svelteCode={objectfit15}
    >
      <video
        src="../../video/1.mp4"
        class="object-fit-none rounded border"
        autoPlay
        loop
        muted
      ></video>
    </ShowCode>
  </Col>
</Row>
<!-- End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/ui-elements/object-fit/object-fit.jsx

import { objectfit1, objectfit10, objectfit11, objectfit12, objectfit13, objectfit14, objectfit15, objectfit2, objectfit3, objectfit4, objectfit5, objectfit6, objectfit7, objectfit8, objectfit9 } from "../../../../shared/data/prism-code/uielements-prism";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col, Row } from "react-bootstrap";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";

const ObjectFit = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Objectfit" />

            <Pageheader title="Ui Elements" currentpage="Object Fit" activepage="Object Fit" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Contain" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit3}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-contain border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Cover" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit4}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-cover border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Fill" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit1}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-fill border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Scale Down" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit2}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-scale border rounded" alt="..." />
                    </ShowCode>

                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit None" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit5}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-none border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Contain (SM - responsive)" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit6}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-sm-contain border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Contain (MD - responsive)" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit7}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-md-contain border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Contain (LG - responsive)" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit8}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-lg-contain border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Contain (XL - responsive)" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit9}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-xl-contain border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Contain (XXL - responsive)" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit10}>
                        <BaseImage src="/build/assets/images/media/media-28.jpg" className="object-fit-xxl-contain border rounded" alt="..." />
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Contain Video" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit11}>
                        <video src={`${__APP_BASE_PATH__}/build/assets/video/1.mp4`} className="object-fit-contain rounded border" autoPlay loop muted></video>
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Cover Video" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit12}>
                        <video src={`${__APP_BASE_PATH__}/build/assets/video/1.mp4`} className="object-fit-cover rounded border" autoPlay loop muted></video>
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Fill Video" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit13}>
                        <video src={`${__APP_BASE_PATH__}/build/assets/video/1.mp4`} className="object-fit-fill rounded border" autoPlay loop muted></video>
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit Scale Video" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit14}>
                        <video src={`${__APP_BASE_PATH__}/build/assets/video/1.mp4`} className="object-fit-contain rounded border" autoPlay loop muted></video>
                    </ShowCode>
                </Col>
                <Col xxl={6} xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Object Fit None Video" customCardClass="custom-card" customCardBodyClass="object-fit-container" reactCode={objectfit15}>
                        <video src={`${__APP_BASE_PATH__}/build/assets/video/1.mp4`} className="object-fit-none rounded border" autoPlay loop muted></video>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End::row-1 --> */}
        </Fragment>
    )
};
// Assign layout
ObjectFit.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ObjectFit;
