// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/applications/task/kanban-board/+page.svelte
<script lang="ts">
    import SpkKanbancard from "$lib/@spk/application-reusable/spk-kanbancard.svelte";
    import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import FilePond, { registerPlugin } from "svelte-filepond";
    import FilePondPluginImageExifOrientation from "filepond-plugin-image-exif-orientation";
    import FilePondPluginImagePreview from "filepond-plugin-image-preview";
    import {
        cars,
        KanbanCards,
        kanbanCardsdanger,
        kanbanCardsinfo,
        kanbanCardsuccess,
        kanbanCardswarning,
        Option1,
        simpleItems1,
    } from "$lib/data/applications/task/kanbandata";
    import {
        Card,
        CardBody,
        Col,
        Image,
        Input,
        Label,
        Modal,
        ModalBody,
        ModalFooter,
        ModalHeader,
        Row,
    } from "@sveltestrap/sveltestrap";
    import { onMount } from "svelte";
    import Select from "svelte-select";
    import { DateInput } from "date-picker-svelte";

    // Register the plugins
    registerPlugin(
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
    );

    //  date

    let date = new Date();
    let date1 = new Date();

    let leftContainerRef1: HTMLElement;
    let rightContainerRef1: HTMLElement;
    let topContainerRef1: HTMLElement;
    let bottomContainerRef1: HTMLElement;
    let lastContainerRef1: HTMLElement;
    let childCount: number = 0;
    let childCount1: number = 0;
    let childCount2: number = 0;
    let childCount3: number = 0;
    let childCount4: number = 0;

    function updateCounts() {
        childCount = leftContainerRef1?.children.length || 0;
        childCount1 = rightContainerRef1?.children.length || 0;
        childCount2 = topContainerRef1?.children.length || 0;
        childCount3 = bottomContainerRef1?.children.length || 0;
        childCount4 = lastContainerRef1?.children.length || 0;
    }

    onMount(() => {
        const observer1 = new MutationObserver(updateCounts);
        const observer2 = new MutationObserver(updateCounts);
        const observer3 = new MutationObserver(updateCounts);
        const observer4 = new MutationObserver(updateCounts);
        const observer5 = new MutationObserver(updateCounts);

        observer1.observe(leftContainerRef1, { childList: true });
        observer2.observe(rightContainerRef1, { childList: true });
        observer3.observe(topContainerRef1, { childList: true });
        observer4.observe(bottomContainerRef1, { childList: true });
        observer5.observe(lastContainerRef1, { childList: true });

        // Initial count
        updateCounts();

        return () => {
            observer1.disconnect();
            observer2.disconnect();
            observer3.disconnect();
            observer4.disconnect();
            observer5.disconnect();
        };
    });


    onMount(async () => {
        if (typeof global === "undefined") {
            window.global = window;
        }

        // Dynamically import dragula only on the client-side
        const dragula = await import("dragula");
        // Initialize Dragula with two containers
        const drake = dragula.default([
            leftContainerRef1,
            rightContainerRef1,
            topContainerRef1,
            bottomContainerRef1,
            lastContainerRef1,
        ]);
        return () => drake.destroy();
    });

    let modals: any = {};

    // Function to open the modal
    const handleModalOpen = (modalName: any) => {
        modals[modalName] = true;
    };

    // Function to close the modal
    const handleModalClose = (modalName: any) => {
        modals[modalName] = false;
    };
</script>

<!-- Page Title -->
<svelte:head>
    <title>KanbanBoard | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Kanban Board"
    activepage="Applications"
    subTitle="Task"
    page="Kanban Board"
/>
<!-- Page Header Close -->
<!-- Start:: row-1 -->

<Row>
    <Col xl={12}>
        <Card class="custom-card">
            <CardBody class="p-3">
                <div
                    class="d-sm-flex align-items-center flex-wrap gap-3 kanban-header justify-content-between"
                >
                    <div
                        class="d-sm-flex align-items-center flex-wrap gap-3 w-sm-50 mb-sm-0 mb-3"
                    >
                        <div class="mb-sm-0 mb-3">
                            <SpkButton
                                color="primary"
                                customClass="btn me-2"
                                onclickfunc={() => handleModalOpen("addmodal")}
                                ><i
                                    class="ri-add-line me-1 fw-medium align-middle"
                                ></i>New Board</SpkButton
                            >
                        </div>
                        <div>
                            <div class="avatar-list-stacked">
                                <span class="avatar avatar-sm avatar-rounded">
                                    <Image
                                        src="../../images/faces/2.jpg"
                                        alt="img"
                                    />
                                </span>
                                <span class="avatar avatar-sm avatar-rounded">
                                    <Image
                                        src="../../images/faces/8.jpg"
                                        alt="img"
                                    />
                                </span>
                                <span class="avatar avatar-sm avatar-rounded">
                                    <Image
                                        src="../../images/faces/2.jpg"
                                        alt="img"
                                    />
                                </span>
                                <span class="avatar avatar-sm avatar-rounded">
                                    <Image
                                        src="../../images/faces/10.jpg"
                                        alt="img"
                                    />
                                </span>
                                <span class="avatar avatar-sm avatar-rounded">
                                    <Image
                                        src="../../images/faces/4.jpg"
                                        alt="img"
                                    />
                                </span>
                                <span class="avatar avatar-sm avatar-rounded">
                                    <Image
                                        src="../../images/faces/13.jpg"
                                        alt="img"
                                    />
                                </span>
                                <a
                                    class="avatar avatar-sm bg-primary avatar-rounded text-fixed-white"
                                    href="#!"
                                >
                                    +8
                                </a>
                            </div>
                        </div>
                    </div>
                    <div
                        class="d-sm-flex align-items-center justify-content-end gap-3 custom-kanaban"
                    >
                        <Select
                            items={Option1}
                            placeholder="Sort By"
                            clearable={false}
                                    showChevron={true}
                        />
                        <!-- <SpkSelect name="colors" option={Option1} mainClass="w-full !rounded-md"
                                        menuplacement='auto' classprefix="Select2" defaultvalue={[Option1[0]]} /> -->
                        <div class="d-flex mt-sm-0 mt-3" role="search">
                            <Input
                                class="me-2"
                                type="search"
                                placeholder="Search"
                                aria-label="Search"
                            />
                            <SpkButton
                                color=""
                                customClass="btn btn-light"
                                buttontype="submit">Search</SpkButton
                            >
                        </div>
                    </div>
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!-- End:: row-1 -->

<!-- Start::row-2 -->
<div class="VYZOR-kanban-board">
    <div class="kanban-tasks-type new">
        <div class="pe-3 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <span class="d-block fw-medium fs-15">New - 04</span>
                <div>
                    <a
                        aria-label="anchor"
                        href="#!"
                        onclick={() => handleModalOpen("taskmodal")}
                        class="btn btn-sm bg-white text-default border btn-wave"
                    >
                        <i class="ri-add-line align-middle me-1 fw-medium"
                        ></i>Add Task
                    </a>
                </div>
            </div>
        </div>
        <div class="kanban-tasks overflow-y-scroll" id="new-tasks">
           
            <div
                id="new-tasks-draggable"
                data-view-btn="new-tasks"
                bind:this={leftContainerRef1}
                class={`${childCount === 0 ? "task-Null" : ""}`}
            >
                {#each KanbanCards as idx}
                    <SpkKanbancard kanban={idx} />
                {/each}
            </div>
        </div>
        <div
            class={`d-grid view-more-button mt-3 ${childCount === 0 ? "d-none" : ""}`}
        >
            <SpkButton color="" customClass="btn btn-primary-light btn-wave"
                >View More</SpkButton
            >
        </div>
    </div>
    <div class="kanban-tasks-type todo">
        <div class="pe-3 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <span class="d-block fw-medium fs-15">Todo - 36</span>
                <div>
                    <a
                        aria-label="anchor"
                        href="#!"
                        onclick={() => handleModalOpen("taskmodal")}
                        class="btn btn-sm bg-white text-default border btn-wave"
                    >
                        <i class="ri-add-line align-middle me-1 fw-medium"
                        ></i>Add Task
                    </a>
                </div>
            </div>
        </div>
        <div class="kanban-tasks overflow-y-scroll" id="todo-tasks">
            <div
                id="todo-tasks-draggable"
                data-view-btn="todo-tasks"
                bind:this={rightContainerRef1}
                class={`${childCount1 === 0 ? "task-Null" : ""}`}
            >
                {#each kanbanCardswarning as idx}
                    <SpkKanbancard kanban={idx} />
                {/each}
            </div>
        </div>
        <div
            class={`d-grid view-more-button mt-3 ${childCount1 === 0 ? "d-none" : ""}`}
        >
            <SpkButton color="" customClass="btn btn-warning-light btn-wave"
                >View More</SpkButton
            >
        </div>
    </div>
    <div class="kanban-tasks-type in-progress">
        <div class="pe-3 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <span class="d-block fw-medium fs-15">On Going - 25</span>
                <div>
                    <a
                        aria-label="anchor"
                        href="#!"
                        onclick={() => handleModalOpen("taskmodal")}
                        class="btn btn-sm bg-white text-default border btn-wave"
                    >
                        <i class="ri-add-line align-middle me-1 fw-medium"
                        ></i>Add Task
                    </a>
                </div>
            </div>
        </div>
        <div class="kanban-tasks overflow-y-scroll" id="inprogress-tasks">
            <div
                id="inprogress-tasks-draggable"
                data-view-btn="inprogress-tasks"
                bind:this={topContainerRef1}
                class={`${childCount2 === 0 ? "task-Null" : ""}`}
            >
                {#each kanbanCardsinfo as idx}
                    <SpkKanbancard kanban={idx} />
                {/each}
            </div>
        </div>
        <div
            class={`d-grid view-more-button mt-3 ${childCount2 === 0 ? "d-none" : ""}`}
        >
            <SpkButton color="" customClass="btn btn-info-light btn-wave"
                >View More</SpkButton
            >
        </div>
    </div>
    <div class="kanban-tasks-type inreview">
        <div class="pe-3 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <span class="d-block fw-medium fs-15">In Review - 02</span>
                <div>
                    <a
                        aria-label="anchor"
                        href="#!"
                        onclick={() => handleModalOpen("taskmodal")}
                        class="btn btn-sm bg-white text-default border btn-wave"
                    >
                        <i class="ri-add-line align-middle me-1 fw-medium"
                        ></i>Add Task
                    </a>
                </div>
            </div>
        </div>
        <div class="kanban-tasks overflow-y-scroll" id="inreview-tasks">
            <div
                id="inreview-tasks-draggable"
                data-view-btn="inreview-tasks"
                bind:this={bottomContainerRef1}
                class={`${childCount3 === 0 ? "task-Null" : ""}`}
            >
                {#each kanbanCardsdanger as idx}
                    <SpkKanbancard kanban={idx} />
                {/each}
            </div>
        </div>
        <div
            class={`d-grid view-more-button mt-3 ${childCount3 === 0 ? "d-none" : ""}`}
        >
            <SpkButton color="" customClass="btn btn-danger-light btn-wave"
                >View More</SpkButton
            >
        </div>
    </div>
    <div class="kanban-tasks-type completed">
        <div class="pe-3 mb-3">
            <div class="d-flex justify-content-between align-items-center">
                <span class="d-block fw-medium fs-15">Completed - 36</span>
                <div>
                    <a
                        aria-label="anchor"
                        href="#!"
                        onclick={() => handleModalOpen("taskmodal")}
                        class="btn btn-sm bg-white text-default border btn-wave"
                    >
                        <i class="ri-add-line align-middle me-1 fw-medium"
                        ></i>Add Task
                    </a>
                </div>
            </div>
        </div>
        <div class="kanban-tasks overflow-y-scroll" id="completed-tasks">
            <div
                id="completed-tasks-draggable"
                data-view-btn="completed-tasks"
                bind:this={lastContainerRef1}
                class={`${childCount4 === 0 ? "task-Null" : ""}`}
            >
                {#each kanbanCardsuccess as idx}
                    <SpkKanbancard kanban={idx} />
                {/each}
            </div>
        </div>
        <div
            class={`d-grid view-more-button mt-3 ${childCount4 === 0 ? "d-none" : ""}`}
        >
            <SpkButton color="" customClass="btn btn-success-light btn-wave"
                >View More</SpkButton
            >
        </div>
    </div>
</div>

<!--End::row-2 -->

<!-- Modal Code  -->

<Modal
    isOpen={modals["addmodal"]}
    toggle={() => handleModalClose("addmodal")}
    centered
    fade
    id="add-board"
    tabindex={-1}
>
    <ModalHeader toggle={() => handleModalClose("addmodal")}>
        <h6 class="modal-title">Add Board</h6>
        <!-- <SpkButton color="" Buttontype="button" onClickfunc={() => handleClose("addmodal")} Customclass="btn-close" Buttondismiss="modal" Buttonlabel="Close"></SpkButton> -->
    </ModalHeader>
    <ModalBody>
        <Row>
            <Col xl={12}>
                <label for="board-title" class="form-label"
                    >Task Board Title</label
                >
                <Input
                    type="text"
                    class=""
                    id="board-title"
                    placeholder="Board Title"
                />
            </Col>
        </Row>
    </ModalBody>
    <ModalFooter>
        <SpkButton
            color="light"
            buttontype="button"
            onclickfunc={() => handleModalClose("addmodal")}
        >
            Cancel
        </SpkButton>
        <SpkButton color="primary" buttontype="button">Add Board</SpkButton>
    </ModalFooter>
</Modal>

<!-- Start::add task modal -->

<Modal
    isOpen={modals["taskmodal"] || false}
    toggle={() => handleModalClose("taskmodal")}
    centered
    fade
    id="add-task"
    tabindex={-1}
>
    <div class="">
        <div class="">
            <ModalHeader toggle={() => handleModalClose("taskmodal")}>
                <h6>Add Task</h6>
                <!-- <SpkButton Buttontype="button" color="" Customclass="btn-close" data-bs-dismiss="modal"
                                aria-label="Close" onClickfunc={() => handleClose("taskmodal")} ></SpkButton> -->
            </ModalHeader>
            <ModalBody class="px-4">
                <Row class="gy-2">
                    <Col xl={6}>
                        <Label for="task-name" class="form-label"
                            >Task Name</Label
                        >
                        <input
                            type="text"
                            class="form-control"
                            id="task-name"
                            placeholder="Task Name"
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="task-id" class="form-label">Task ID</Label>
                        <input
                            type="text"
                            class="form-control"
                            id="task-id"
                            placeholder="Task ID"
                        />
                    </Col>
                    <Col xl={12}>
                        <Label for="text-area" class="form-label"
                            >Task Description</Label
                        >
                        <textarea
                            class="form-control"
                            id="text-area"
                            rows={2}
                            placeholder="Write Description"
                        ></textarea>
                    </Col>
                    <Col xl={12}>
                        <Label for="text-area" class="form-label"
                            >Task Images</Label
                        >
                        <FilePond
                            class="multiple-filepond"
                            name="filepond"
                            labelIdle={`Drag & Drop your files or <span class="filepond--label-action">Browse</span>`}
                            stylePanelLayout=" "
                            styleLoadIndicatorPosition="center bottom"
                            styleButtonRemoveItemPosition="center bottom"
                            allowMultiple={true}
                        />
                    </Col>
                    <Col xl={12}>
                        <Label class="form-label">Assigned To</Label>
                        <Select
                            items={simpleItems1}
                            placeholder="Sort By"
                            showChevron={false}
                            multiFullItemClearable
                            multiple
                            
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="form-label">Target Date</Label>
                        <div class="form-group custom-date-picker">
                            <div class="input-group">
                                <div class="input-group-text text-muted">
                                    <i class="ri-calendar-line"></i>
                                </div>
                                <DateInput
                                    bind:value={date}
                                    class="form-control"
                                    format="yy-MM-dd"
                                    closeOnSelection={true}
                                />
                            </div>
                        </div>
                    </Col>
                    <Col xl={6}>
                        <Label class="form-label">Tags</Label>
                        <Select
                            items={cars}
                            placeholder="Sort By"
                            clearable={false}
                                    showChevron={true}
                        />
                        <!-- <SpkSelect multi name="colors" option={cars} mainClass="w-full !rounded-md" menuplacement='top' classNameprefix="Select2" /> -->
                    </Col>
                </Row>
            </ModalBody>
            <ModalFooter>
                <SpkButton
                    color="light"
                    buttontype="button"
                    customClass="btn btn-light"
                    onclickfunc={() => handleModalClose("taskmodal")}
                    >Cancel</SpkButton
                >
                <SpkButton
                    color="primary"
                    buttontype="button"
                    customClass="btn btn-primary">Add Task</SpkButton
                >
            </ModalFooter>
        </div>
    </div>
</Modal>

<!-- End::add task modal -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/applications/task/kanban-board/kanban-board.jsx

import React, { Fragment, useEffect, useRef, useState } from "react";
import { Card, Col, Form, Modal, Row } from "react-bootstrap";
import SimpleBar from "simplebar-react";
import { FilePond } from "react-filepond";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import SpkSelect from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import { KanbanCards, kanbanCardsdanger, kanbanCardsinfo, kanbanCardswarning, Option1, kanbanCardsuccess, simpleItems1, cars } from "../../../../shared/data/applications/task/kanbandata";
import SpkKanbanCard from "../../../../shared/@spk-reusable-components/application-reusable/spk-kanbancard";
import SpkDatepickr from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-datepicker";
import dragula from "dragula";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";
import { Head } from "@inertiajs/react";

const KanbanBoard = () => {

    const [files, setFiles] = useState([]);
    const [dates, setDates] = useState({});
    const handleDateChange = (key, date) => {
        if (date) {
            setDates((prevDates) => ({
                ...prevDates,
                [key]: date,
            }));
        } else {
            setDates((prevDates) => {
                const { [key]: removedKey, ...rest } = prevDates;
                return rest;
            });
        }
    };

    const [show, setShow] = useState({});

    const handleShow = (offcanvasName) => {
        setShow((prevShow) => {
            if (prevShow[offcanvasName] !== true) {
                return { ...prevShow, [offcanvasName]: true };
            }
            return prevShow;
        });
    };

    const handleClose = (offcanvasName) => {
        setShow((prevShow) => {
            if (prevShow[offcanvasName] !== false) {
                return { ...prevShow, [offcanvasName]: false };
            }
            return prevShow;
        });
    };

    const leftContainerRef = useRef(null);
    const rightContainerRef = useRef(null);
    const topContainerRef = useRef(null);
    const bottomContainerRef = useRef(null);
    const lastContainerRef = useRef(null);

    useEffect(() => {
        if (leftContainerRef.current && rightContainerRef.current) {
            dragula([leftContainerRef.current, rightContainerRef.current, topContainerRef.current, bottomContainerRef.current, lastContainerRef.current]);

            if (document.querySelector('.firstdrag')?.classList.contains('task-Null')) {

                document.querySelector('.view-more-button')?.classList.add('d-none');
            }
        }
    }, []);

    const leftButtonRef = useRef(null);
    const rightButtonRef = useRef(null);
    const topButtonRef = useRef(null);
    const bottomButtonRef = useRef(null);
    const lastButtonRef = useRef(null);

    // Store all the refs in an array
    const elementsToModify = [
        { containerRef: leftContainerRef, buttonRef: leftButtonRef },
        { containerRef: rightContainerRef, buttonRef: rightButtonRef },
        { containerRef: topContainerRef, buttonRef: topButtonRef },
        { containerRef: bottomContainerRef, buttonRef: bottomButtonRef },
        { containerRef: lastContainerRef, buttonRef: lastButtonRef }
    ];

    const OnDivChange = () => {
        elementsToModify.forEach(({ containerRef, buttonRef }) => {
            const element = containerRef.current;
            const button = buttonRef.current;

            if (element?.children.length <= 0) {
                element?.classList.add("task-Null");
                if (button) {
                    button.classList.add("d-none");
                }
            } else {
                element?.classList.remove("task-Null");
                if (button) {
                    button.classList.remove("d-none");
                }
            }
        });
    };


    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Apps-Kanban Board" />

            <Pageheader title="Applications" subtitle="Task" currentpage="Kanban Board" activepage="Kanban Board" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Body className="p-3">
                            <div className="d-sm-flex align-items-center flex-wrap gap-3 kanban-header justify-content-between">
                                <div className="d-sm-flex align-items-center flex-wrap gap-3 w-sm-50 mb-sm-0 mb-3">
                                    <div className="mb-sm-0 mb-3">
                                        <SpkButton Buttonvariant="primary" Customclass="btn me-2" onClickfunc={() => handleShow("addmodal")}><i className="ri-add-line me-1 fw-medium align-middle"></i>New Board</SpkButton>
                                    </div>
                                    <div>
                                        <div className="avatar-list-stacked">
                                            <span className="avatar avatar-sm avatar-rounded">
                                                <BaseImage src={"/build/assets/images/faces/2.jpg"} alt="img" />
                                            </span>
                                            <span className="avatar avatar-sm avatar-rounded">
                                                <BaseImage src="/build/assets/images/faces/8.jpg" alt="img" />
                                            </span>
                                            <span className="avatar avatar-sm avatar-rounded">
                                                <BaseImage src={"/build/assets/images/faces/2.jpg"} alt="img" />
                                            </span>
                                            <span className="avatar avatar-sm avatar-rounded">
                                                <BaseImage src="/build/assets/images/faces/10.jpg" alt="img" />
                                            </span>
                                            <span className="avatar avatar-sm avatar-rounded">
                                                <BaseImage src="/build/assets/images/faces/4.jpg" alt="img" />
                                            </span>
                                            <span className="avatar avatar-sm avatar-rounded">
                                                <BaseImage src="/build/assets/images/faces/13.jpg" alt="img" />
                                            </span>
                                            <BaseLink className="avatar avatar-sm bg-primary avatar-rounded text-fixed-white" href="#!">
                                                +8
                                            </BaseLink>
                                        </div>
                                    </div>
                                </div>
                                <div className="d-sm-flex align-items-center flex-wrap justify-content-end gap-3 custom-kanaban">
                                    <SpkSelect name="colors" option={Option1} mainClass="w-full !rounded-md"
                                        menuplacement='auto' classNameprefix="Select2" defaultvalue={[Option1[0]]} />
                                    <div className="d-flex mt-sm-0 mt-3" role="search">
                                        <Form.Control className="me-2" type="search" placeholder="Search" aria-label="Search" />
                                        <SpkButton Buttonvariant="" Customclass="btn btn-light" Buttontype="submit">Search</SpkButton>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start::row-2 --> */}

            <div className="VYZOR-kanban-board">
                <div className="kanban-tasks-type new">
                    <div className="pe-3 mb-3">
                        <div className="d-flex justify-content-between align-items-center">
                            <span className="d-block fw-medium fs-15">New - 04</span>
                            <div>
                                <BaseLink  href="#!" onClick={() => handleShow("taskmodal")} className="btn btn-sm bg-white text-default border btn-wave">
                                    <i className="ri-add-line align-middle me-1 fw-medium"></i>Add Task
                                </BaseLink>
                            </div>
                        </div>
                    </div>
                    <SimpleBar className="kanban-tasks" id="new-tasks">
                        <div id="new-tasks-draggable" data-view-btn="new-tasks" ref={leftContainerRef} onMouseEnter={OnDivChange}>

                            {KanbanCards.map((idx, index) => (
                                <SpkKanbanCard key={index} kanban={idx} />
                            ))}
                        </div>
                    </SimpleBar>
                    <div className="d-grid view-more-button mt-3" ref={leftButtonRef}>
                        <SpkButton Buttonvariant="" Customclass="btn btn-primary-light btn-wave">View More</SpkButton>
                    </div>
                </div>
                <div className="kanban-tasks-type todo">
                    <div className="pe-3 mb-3">
                        <div className="d-flex justify-content-between align-items-center">
                            <span className="d-block fw-medium fs-15">Todo - 36</span>
                            <div>
                                <BaseLink  href="#!" onClick={() => handleShow("taskmodal")} className="btn btn-sm bg-white text-default border btn-wave">
                                    <i className="ri-add-line align-middle me-1 fw-medium"></i>Add Task
                                </BaseLink>
                            </div>
                        </div>
                    </div>
                    <SimpleBar className="kanban-tasks" id="todo-tasks">
                        <div id="todo-tasks-draggable" data-view-btn="todo-tasks" ref={rightContainerRef} onMouseEnter={OnDivChange}>

                            {kanbanCardswarning.map((idx, index) => (
                                <SpkKanbanCard key={index} kanban={idx} />
                            ))}
                        </div>
                    </SimpleBar>
                    <div className="d-grid view-more-button mt-3" ref={rightButtonRef}>
                        <SpkButton Buttonvariant="" Customclass="btn btn-warning-light btn-wave">View More</SpkButton>
                    </div>
                </div>
                <div className="kanban-tasks-type in-progress">
                    <div className="pe-3 mb-3">
                        <div className="d-flex justify-content-between align-items-center">
                            <span className="d-block fw-medium fs-15">On Going - 25</span>
                            <div>
                                <BaseLink  href="#!" onClick={() => handleShow("taskmodal")} className="btn btn-sm bg-white text-default border btn-wave">
                                    <i className="ri-add-line align-middle me-1 fw-medium"></i>Add Task
                                </BaseLink>
                            </div>
                        </div>
                    </div>
                    <SimpleBar className="kanban-tasks" id="inprogress-tasks">
                        <div id="inprogress-tasks-draggable" data-view-btn="inprogress-tasks" ref={topContainerRef} onMouseEnter={OnDivChange}>

                            {kanbanCardsinfo.map((idx, index) => (
                                <SpkKanbanCard key={index} kanban={idx} />
                            ))}
                        </div>
                    </SimpleBar>
                    <div className="d-grid view-more-button mt-3" ref={topButtonRef}>
                        <SpkButton Buttonvariant="" Customclass="btn btn-info-light btn-wave">View More</SpkButton>
                    </div>
                </div>
                <div className="kanban-tasks-type inreview">
                    <div className="pe-3 mb-3">
                        <div className="d-flex justify-content-between align-items-center">
                            <span className="d-block fw-medium fs-15">In Review - 02</span>
                            <div>
                                <BaseLink href="#!" onClick={() => handleShow("taskmodal")} className="btn btn-sm bg-white text-default border btn-wave">
                                    <i className="ri-add-line align-middle me-1 fw-medium"></i>Add Task
                                </BaseLink>
                            </div>
                        </div>
                    </div>
                    <SimpleBar className="kanban-tasks" id="inreview-tasks">
                        <div id="inreview-tasks-draggable" data-view-btn="inreview-tasks" ref={bottomContainerRef} onMouseEnter={OnDivChange}>

                            {kanbanCardsdanger.map((idx, index) => (
                                <SpkKanbanCard key={index} kanban={idx} />
                            ))}
                        </div>
                    </SimpleBar>
                    <div className="d-grid view-more-button mt-3" ref={bottomButtonRef}>
                        <SpkButton Buttonvariant="" Customclass="btn btn-danger-light btn-wave">View More</SpkButton>
                    </div>
                </div>
                <div className="kanban-tasks-type completed">
                    <div className="pe-3 mb-3">
                        <div className="d-flex justify-content-between align-items-center">
                            <span className="d-block fw-medium fs-15">Completed - 36</span>
                            <div>
                                <BaseLink href="#!" onClick={() => handleShow("taskmodal")} className="btn btn-sm bg-white text-default border btn-wave">
                                    <i className="ri-add-line align-middle me-1 fw-medium"></i>Add Task
                                </BaseLink>
                            </div>
                        </div>
                    </div>
                    <SimpleBar className="kanban-tasks" id="completed-tasks">
                        <div id="completed-tasks-draggable" data-view-btn="completed-tasks" ref={lastContainerRef} onMouseEnter={OnDivChange}>

                            {kanbanCardsuccess.map((idx, index) => (
                                <SpkKanbanCard key={index} kanban={idx} />
                            ))}
                        </div>
                    </SimpleBar>
                    <div className="d-grid view-more-button mt-3" ref={lastButtonRef}>
                        <SpkButton Buttonvariant="" Customclass="btn btn-success-light btn-wave">View More</SpkButton>
                    </div>
                </div>
            </div>

            {/* <!--End::row-2 --> */}

            {/* Modal Code */}

            <Modal show={show["addmodal"] || false} onHide={() => handleClose("addmodal")} centered className="fade" id="add-board" tabIndex={-1} aria-hidden="true">
                <Modal.Header>
                    <h6 className="modal-title">Add Board</h6>
                    <SpkButton Buttonvariant="" Buttontype="button" onClickfunc={() => handleClose("addmodal")} Customclass="btn-close" Buttondismiss="modal" Buttonlabel="Close"></SpkButton>
                </Modal.Header>
                <Modal.Body>
                    <Row>
                        <Col xl={12}>
                            <label htmlFor="board-title" className="form-label">Task Board Title</label>
                            <Form.Control type="text" className="" id="board-title" placeholder="Board Title" />
                        </Col>
                    </Row>
                </Modal.Body>
                <Modal.Footer>
                    <SpkButton Buttonvariant="light" Buttontype="button" onClickfunc={() => handleClose("addmodal")} data-bs-dismiss="modal">
                        Cancel
                    </SpkButton>
                    <SpkButton Buttonvariant="primary" Buttontype="button">
                        Add Board
                    </SpkButton>
                </Modal.Footer>
            </Modal>

            {/* <!-- Start::add task modal --> */}

            <Modal show={show["taskmodal"] || false} onHide={() => handleClose("taskmodal")} centered className="fade" id="add-task" tabIndex={-1}>
                <div className="">
                    <div className="">
                        <Modal.Header>
                            <Modal.Title as="h6" >Add Task</Modal.Title>
                            <SpkButton Buttontype="button" Buttonvariant="" Customclass="btn-close" data-bs-dismiss="modal"
                                aria-label="Close" onClickfunc={() => handleClose("taskmodal")} ></SpkButton>
                        </Modal.Header>
                        <Modal.Body className="px-4">
                            <Row className="gy-2">
                                <Col xl={6}>
                                    <Form.Label htmlFor="task-name" className="form-label">Task Name</Form.Label>
                                    <input type="text" className="form-control" id="task-name" placeholder="Task Name" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="task-id" className="form-label">Task ID</Form.Label>
                                    <input type="text" className="form-control" id="task-id" placeholder="Task ID" />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="text-area" className="form-label">Task Description</Form.Label>
                                    <textarea className="form-control" id="text-area" rows={2}
                                        placeholder="Write Description"></textarea>
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="text-area" className="form-label">Task Images</Form.Label>
                                    <FilePond className="multiple-filepond" files={files} onupdatefiles={setFiles} allowMultiple={true} maxFiles={6} server="/api" name="files" labelIdle='Drag & Drop your file here or click' />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label className="form-label">Assigned To</Form.Label>
                                    <SpkSelect name="colors" multi={true} option={simpleItems1} mainClass="basic-multi-select" placeholder="Sort By" menuplacement='auto' classNameprefix="Select2" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="form-label">Target Date</Form.Label>
                                    <div className="form-group">
                                        <div className="input-group">
                                            <div className="input-group-text text-muted"> <i
                                                className="ri-calendar-line"></i> </div>
                                            <SpkDatepickr className="form-control" Timeinput="Time:" dateFormat="yy/MM/dd h:mm aa" selected={dates["TargetDate"] ? new Date(dates["TargetDate"]) : null} onChange={(date) => handleDateChange("TargetDate", date)} placeholderText='Choose date and time' showTimeInput />
                                        </div>
                                    </div>
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="form-label">Tags</Form.Label>
                                    <SpkSelect multi name="colors" option={cars} mainClass="w-full !rounded-md" menuplacement='top' classNameprefix="Select2" />
                                </Col>
                            </Row>
                        </Modal.Body>
                        <Modal.Footer>
                            <SpkButton Buttonvariant="light" Buttontype="button" Customclass="btn btn-light" data-bs-dismiss="modal" onClickfunc={() => handleClose("taskmodal")} >Cancel</SpkButton>
                            <SpkButton Buttonvariant='primary' Buttontype="button" Customclass="btn btn-primary">Add Task</SpkButton>
                        </Modal.Footer>
                    </div>
                </div>
            </Modal>

            {/* <!-- End::add task modal --> */}

        </Fragment>
    )
};
// Assign layout
KanbanBoard.layout = (page) => <MainLayout>{page}</MainLayout>;
export default KanbanBoard;
