// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/dashboards-reusable/spk-analyticscard.tsx


import { Fragment } from "react";
import { Card } from "react-bootstrap";

interface AnalyticProps {
  svgIcon: React.ReactNode;
  svgColor: string;
  title: string;
  value: string | number;
  icon: string;
  iconColor: string;
  percent: string;
  year: string;
}

interface SpkAnalyticsCardProps {
  analytic: AnalyticProps;
  cardClass?: string;
  bodyClass?: string;
}

const SpkAnalyticsCard: React.FC<SpkAnalyticsCardProps> = ({analytic, cardClass, bodyClass}) => {
  return (
    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className={bodyClass}>
          <div className="d-flex align-items-start gap-3">
            <div>
              <span className={`avatar avatar-md bg-${analytic.svgColor} svg-white`}>
                {analytic.svgIcon}
              </span>
            </div>
            <div>
              <span className="d-block text-muted">{analytic.title}</span>
              <h5 className="fw-semibold mb-1">{analytic.value}</h5>
              <div className="text-muted fs-12">
                <span className={`text-${analytic.iconColor}`}>
                  <i className={analytic.icon}></i> {analytic.percent}
                </span>{" "}
                {analytic.year}
              </div>
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkAnalyticsCard;

// Dashboard Template/vyzor-svelte/final/src/lib/@spk/dashboards-reusable/spk-analyticscard.svelte
<script lang="ts">
    import { Card, CardBody } from "@sveltestrap/sveltestrap";

    interface AnalyticProps {
        svgIcon?: string;
        svgColor?: string;
        title?: string;
        value?: string | number;
        icon?: string;
        iconColor?: string;
        percent?: string;
        year?: string;
    }
    export let analytic: AnalyticProps = {};
    export let cardClass: string = "";
    export let bodyClass: string = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class={bodyClass}>
        <div class="d-flex align-items-start gap-3">
            <div>
                <span
                    class={`avatar avatar-md bg-${analytic.svgColor} svg-white`}
                >
                    {@html analytic.svgIcon}
                </span>
            </div>
            <div>
                <span class="d-block text-muted">{analytic.title}</span>
                <h5 class="fw-semibold mb-1">{analytic.value}</h5>
                <div class="text-muted fs-12">
                    <span class={`text-${analytic.iconColor}`}>
                        <i class={analytic.icon}></i>
                        {analytic.percent}
                    </span>{" "}
                    {analytic.year}
                </div>
            </div>
        </div>
    </CardBody>
</Card>
