// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/dashboards-reusable/spk-schoolcard.tsx

import React, { Fragment } from "react";
import { Card } from "react-bootstrap";
import SpkBadge from "../general-reusable/reusable-uielements/spk-badge";

interface SchoolCardProps {
  cardClass?: string;
  bodyClass?: string;
  school: {
    title: string;
    value: string | number;
    percent: string;
    badgeColor: string;
    svgColor: string;
    svgIcon: React.ReactNode;
    icon?:string;
  };
}

const SpkSchoolCard: React.FC<SchoolCardProps> = ({ cardClass, bodyClass, school }) => {
  return (
    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className={bodyClass}>
          <div className="d-flex align-items-center gap-2 justify-content-between">
            <div>
              <span className="d-block mb-1">{school.title}</span>
              <div className="d-flex align-items-center gap-2 flex-wrap">
                <h5 className="fw-semibold mb-0">{school.value}</h5>
                <div className="fs-12 text-muted">
                  <SpkBadge variant="" Customclass={`bg-${school.badgeColor}-transparent rounded-pill d-inline-flex align-items-center`}>
                    <i className={`ti ti-trending-${school.icon} me-1 align-middle`}></i>{school.percent}
                  </SpkBadge>   This Year
                </div>
              </div>
            </div>
            <div className="lh-1">
              <span className={`avatar avatar-lg bg-${school.svgColor}-transparent svg-${school.svgColor}`}>
                {school.svgIcon}
              </span>
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkSchoolCard;

// Dashboard Template/vyzor-svelte/final/src/lib/@spk/dashboards-reusable/spk-schoolcard.svelte
<script lang="ts">
    import { Card, CardBody } from "@sveltestrap/sveltestrap";
    import SpkBadge from "../uielements/badge/SpkBadge.svelte";

    interface SchoolCardProps {
        title?: string;
        value?: string | number;
        percent?: string;
        badgeColor?: string;
        svgColor?: string;
        svgIcon?: string;
        icon?: string;
    }

    export let school: SchoolCardProps = {};
    export let cardClass: string = "";
    export let bodyClass: string = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class={bodyClass}>
        <div
            class="d-flex align-items-center gap-2 justify-content-between"
        >
            <div>
                <span class="d-block mb-1">{school.title}</span>
                <div class="d-flex align-items-center gap-2 flex-wrap">
                    <h5 class="fw-semibold mb-0">{school.value}</h5>
                    <div class="fs-12 text-muted">
                        <SpkBadge
                            Color=""
                            CustomClass={`bg-${school.badgeColor}-transparent rounded-pill d-inline-flex align-items-center`}
                        >
                            <i
                                class={`ti ti-trending-${school.icon} me-1 align-middle`}
                            ></i>{school.percent}
                        </SpkBadge> This Year
                    </div>
                </div>
            </div>
            <div class="lh-1">
                <span
                    class={`avatar avatar-lg bg-${school.svgColor}-transparent svg-${school.svgColor}`}
                >
                    {@html school.svgIcon}
                </span>
            </div>
        </div>
    </CardBody>
</Card>
