// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/dashboards/crm/deals.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import SpkDealscard from "@/shared/@spk/dashboards-reusable/crm/spk-dealscard.svelte";
    import SpkBadge from "@/shared/@spk/uielements/badge/SpkBadge.svelte";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import SpkDropdown from "@/shared/@spk/uielements/Dropdown/SpkDropdown.svelte";

    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import {
        DangerDeals,
        dealCards,
        InfoDeal,
        PinkDeals,
        PrimaryDeal,
        SuccessDeal,
        WarningDeal,
    } from "@/shared/data/dashboards/crm/dealsdata";
    import { crmDashDropdown } from "@/shared/data/uielements/dropdowndata";
    import {
        Card,
        CardBody,
        Col,
        Input,
        InputGroup,
        Label,
        Modal,
        ModalBody,
        ModalFooter,
        ModalHeader,
        Row,
    } from "@sveltestrap/sveltestrap";
    import { DateInput } from "date-picker-svelte";
    import { onMount } from "svelte";

    let show = false;

    function handleShow() {
        show = true;
    }

    function handleClose() {
        show = false;
    }

    let avatar; // To store the avatar image data
    let fileinput; // To reference the file input element

    const onFileSelected = (e) => {
        let image = e.target.files[0]; // Get the selected file
        if (image) {
            let reader = new FileReader();
            reader.readAsDataURL(image); // Read the file as a data URL

            reader.onload = (e) => {
                avatar = e.target.result; // Update avatar with the result
            };
        }
    };

    let firstContainerRef;
    let secondContainerRef;
    let thirdContainerRef;
    let fourthContainerRef;
    let fifthContainerRef;
    let sixthContainerRef;

    onMount(async () => {
        if (typeof global === "undefined") {
            window.global = window;
        }

        // Dynamically import dragula only on the client-side
        const dragula = await import("dragula");
        // Initialize Dragula with two containers
        const drake = dragula.default([
            firstContainerRef,
            secondContainerRef,
            thirdContainerRef,
            fourthContainerRef,
            fifthContainerRef,
            sixthContainerRef,
        ]);
        return () => drake.destroy();
    });
    // Date
    let date = new Date();
</script>

<!-- Page Title -->
<svelte:head>
    <title>Deals | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Deals"
    subTitle="CRM"
    activepage="Dashboards"
    page="Deals"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={12}>
        <Card class="custom-card">
            <CardBody>
                <div
                    class="d-flex align-items-center flex-wrap gap-2 justify-content-between"
                >
                    <div class="d-flex align-items-center">
                        <span class="fw-medium fs-16 me-1">Deals</span>
                    </div>
                    <div class="d-flex flex-wrap gap-2">
                        <SpkButton
                            color="primary"
                            customClass="btn"
                            onclickfunc={handleShow}
                            ><i class="ri-add-line me-1 fw-medium align-middle"
                            ></i>New Deal</SpkButton
                        >
                        <SpkButton color="success" customClass="btn"
                            >Export As CSV</SpkButton
                        >
                        <SpkDropdown
                            option={crmDashDropdown}
                            ToggleClass="btn btn-light btn-wave waves-effect waves-light no-caret"
                            Caret={false}
                            parent={`Sort By <i class="ri-arrow-down-s-line align-middle ms-1 d-inline-block"></i>`}
                        />
                    </div>
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->

<!-- Start::row-2 -->

<Row>
    {#each dealCards as deal}
        <Col xxl={2} xl={4} lg={6} md={6}>
            <Card class="custom-card">
                <CardBody class="p-3">
                    <div
                        class="d-flex align-items-top flex-wrap justify-content-between"
                    >
                        <div>
                            <div class={`fw-medium fs-15 ${deal.labelClass}`}>
                                {deal.label}
                            </div>
                            <SpkBadge
                                Color=""
                                CustomClass="bg-light text-default"
                                >{deal.badgeText}</SpkBadge
                            >
                        </div>
                        <div>
                            <span class={`fw-medium ${deal.amountStyle}`}
                                >{deal.amount}</span
                            >
                        </div>
                    </div>
                </CardBody>
            </Card>
        </Col>
    {/each}
</Row>

<!-- End::row-2 -->

<!-- Start::row-3 -->

<Row>
    <div class="col-xxl-2" id="leads-discovered" bind:this={firstContainerRef}>
        {#each PrimaryDeal as idx}
            <SpkDealscard deal={idx} />
        {/each}
    </div>
    <div class="col-xxl-2" id="leads-qualified" bind:this={secondContainerRef}>
        {#each WarningDeal as idx}
            <SpkDealscard deal={idx} />
        {/each}
    </div>
    <div class="col-xxl-2" id="contact-initiated" bind:this={thirdContainerRef}>
        {#each SuccessDeal as idx}
            <SpkDealscard deal={idx} />
        {/each}
    </div>
    <div class="col-xxl-2" id="needs-identified" bind:this={fourthContainerRef}>
        {#each InfoDeal as idx}
            <SpkDealscard deal={idx} />
        {/each}
    </div>
    <div class="col-xxl-2" id="negotiation" bind:this={fifthContainerRef}>
        {#each DangerDeals as idx}
            <SpkDealscard deal={idx} />
        {/each}
    </div>
    <div class="col-xxl-2" id="deal-finalized" bind:this={sixthContainerRef}>
        {#each PinkDeals as idx}
            <SpkDealscard deal={idx} />
        {/each}
    </div>
</Row>

<!-- End::row-3 -->

<!-- Start:: New Deal -->

<Modal
    isOpen={show}
    toggle={handleClose}
    fade
    id="create-deal"
    tabindex={-1}
    centered
>
    <ModalHeader toggle={handleClose}>
        <h6 class="modal-title">New Deal</h6>
    </ModalHeader>
    <ModalBody>
        <Row class="gy-3">
            <Col xl={12}>
                <div class="mb-0 text-center">
                    <span class="avatar avatar-xxl avatar-rounded">
                        {#if avatar}
                            <img
                                loading="lazy"
                                class="avatar"
                                src={avatar}
                                alt="Avatar"
                            />
                        {:else}
                            <img
                                src="../../images/faces/9.jpg"
                                alt="Profile"
                                id="profile-img"
                            />
                        {/if}
                        <a
                            href="#!"
                            class="badge rounded-pill bg-primary avatar-badge"
                            on:click={() => fileinput.click()}
                            aria-label="Change profile picture"
                        >
                            <i class="fe fe-camera"></i>
                        </a>
                        <input
                            style="display:none"
                            type="file"
                            class="position-absolute w-100 h-100 op-0"
                            id="profile-change"
                            accept=".jpg, .jpeg, .png"
                            on:change={onFileSelected}
                            bind:this={fileinput}
                        />
                    </span>
                </div>
            </Col>
            <Col xl={6}>
                <Label for="deal-name" class="">Contact Name</Label>
                <Input
                    type="text"
                    class=""
                    id="deal-name"
                    placeholder="Contact Name"
                />
            </Col>
            <Col xl={6}>
                <Label for="deal-lead-score" class="">Deal Value</Label>
                <Input
                    type="number"
                    class=""
                    id="deal-lead-score"
                    placeholder="Deal Value"
                />
            </Col>
            <Col xl={12}>
                <Label for="company-name" class="">Company Name</Label>
                <Input
                    type="text"
                    class=""
                    id="company-name"
                    placeholder="Company Name"
                />
            </Col>
            <Col xl={12}>
                <Label class="">Last Contacted</Label>
                <InputGroup class="custom-input-group custom-date-picker">
                    <div class="input-group-text custom-input-group text-muted">
                        <i class="ri-calendar-line"></i>
                    </div>
                    <DateInput
                        bind:value={date}
                        class="form-control"
                        format="yy-MM-dd HH:MM"
                        closeOnSelection={true}
                        dynamicPositioning={true}
                    />
                </InputGroup>
            </Col>
        </Row>
    </ModalBody>
    <ModalFooter>
        <SpkButton color="light" buttontype="button" onclickfunc={handleClose}
            >Cancel</SpkButton
        >
        <SpkButton color="primary" buttontype="button">Create Deal</SpkButton>
    </ModalFooter>
</Modal>

<!-- End:: New Deal -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/crm/deals/deals.jsx

import React, { Fragment, useEffect, useRef, useState } from "react";
import { Card, Col, Dropdown, Form, Image, InputGroup, Modal, Row } from "react-bootstrap";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import SpkDropdown from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-dropdown";
import { DangerDeals, dealCards, InfoDeal, PinkDeals, PrimaryDeal, SuccessDeal, WarningDeal } from "../../../../shared/data/dashboards/crm/dealsdata";
import SpkBadge from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import SpkDealsCard from "../../../../shared/@spk-reusable-components/dashboards-reusable/crm/spk-dealscard";
import SpkDatepickr from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-datepicker";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import dragula from "dragula";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const Deals = () => {

    const [show, setShow] = useState(false);
    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);
    const slideArrow = (selector) => document.querySelector(selector)

    const [startDate, setStartDate] = useState();
    const handleDateChange = (date) => {
        if (date) {
            setStartDate(date);
        }
    };

    const firstContainerRef = useRef(null);
    const secondContainerRef = useRef(null);
    const thirdContainerRef = useRef(null);
    const fourthContainerRef = useRef(null);
    const fifthContainerRef = useRef(null);
    const sixthContainerRef = useRef(null);

    useEffect(() => {
        if (firstContainerRef.current && secondContainerRef.current) {
            dragula([firstContainerRef.current, secondContainerRef.current, thirdContainerRef.current, fourthContainerRef.current, fifthContainerRef.current, sixthContainerRef.current]);
            if (slideArrow(".firstdrag")?.classList.contains("task-Null")) {
                slideArrow(".view-more-button")?.classList.add("d-none");
            }
        }
    }, []);

    //upload image
    const [avatar, setAvatar] = useState('');
    const fileInputRef = useRef(null);

    const triggerFileInput = () => {
        fileInputRef.current?.click();
    };

    const onFileSelected = (event) => {
        const file = event.target.files[0];
        if (file && file.type.startsWith('image/')) {
            const reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = (e) => {
                setAvatar(e.target.result);
            };
        }
    };

    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Dashboards-Deals" />

            <Pageheader title="Dashboards" subtitle="CRM" currentpage="Deals" activepage="Deals" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Body>
                            <div className="d-flex align-items-center flex-wrap gap-2 justify-content-between">
                                <div className="d-flex align-items-center">
                                    <span className="fw-medium fs-16 me-1">Deals</span>
                                </div>
                                <div className="d-flex flex-wrap gap-2">
                                    <SpkButton Buttonvariant="primary" Customclass="btn" onClickfunc={handleShow} data-bs-toggle="modal" data-bs-target="#create-contact"><i className="ri-add-line me-1 fw-medium align-middle"></i>New Deal</SpkButton>
                                    <SpkButton Buttonvariant="success" Customclass="btn">Export As CSV</SpkButton>
                                    <SpkDropdown toggleas="a"  Customtoggleclass="btn btn-light btn-wave waves-effect waves-light no-caret" Toggletext="Sort By" Arrowicon={true}>
                                        <Dropdown.Item href="#!">Newest</Dropdown.Item>
                                        <Dropdown.Item href="#!">Date Added</Dropdown.Item>
                                        <Dropdown.Item href="#!">A - Z</Dropdown.Item>
                                    </SpkDropdown>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

            {/* <!-- Start::row-2 --> */}

            <Row>
                {dealCards.map((deal) => (
                    <Col xxl={2} xl={4} lg={6} md={6} className="" key={deal.id}>
                        <Card className="custom-card">
                            <Card.Body className="p-3">
                                <div className="d-flex align-items-top flex-wrap justify-content-between">
                                    <div>
                                        <div className={`fw-medium fs-15 ${deal.labelClass}`}>{deal.label}</div>
                                        <SpkBadge variant="" Customclass="bg-light text-default">{deal.badgeText}</SpkBadge>
                                    </div>
                                    <div>
                                        <span className={`fw-medium ${deal.amountStyle}`}>{deal.amount}</span>
                                    </div>
                                </div>
                            </Card.Body>
                        </Card>
                    </Col>
                ))}
            </Row>

            {/* <!-- End::row-2 --> */}

            {/* <!-- Start::row-3 --> */}

            <Row>
                <Col xxl={2} id="leads-discovered" ref={firstContainerRef}>
                    {PrimaryDeal.map((idx, index) => (
                        <SpkDealsCard key={index} deal={idx} />
                    ))}
                </Col>
                <Col xxl={2} id="leads-qualified" ref={secondContainerRef}>
                    {WarningDeal.map((idx, index) => (
                        <SpkDealsCard key={index} deal={idx} />
                    ))}
                </Col>
                <Col xxl={2} id="contact-initiated" ref={thirdContainerRef}>
                    {SuccessDeal.map((idx, index) => (
                        <SpkDealsCard key={index} deal={idx} />
                    ))}
                </Col>
                <Col xxl={2} id="needs-identified" ref={fourthContainerRef}>
                    {InfoDeal.map((idx, index) => (
                        <SpkDealsCard key={index} deal={idx} />
                    ))}
                </Col>
                <Col xxl={2} id="negotiation" ref={fifthContainerRef}>
                    {DangerDeals.map((idx, index) => (
                        <SpkDealsCard key={index} deal={idx} />
                    ))}
                </Col>
                <Col xxl={2} id="deal-finalized" ref={sixthContainerRef}>
                    {PinkDeals.map((idx, index) => (
                        <SpkDealsCard key={index} deal={idx} />
                    ))}
                </Col>
            </Row>

            {/* <!-- End::row-3 --> */}

            {/* <!-- Start:: New Deal --> */}

            <Modal show={show} onHide={handleClose} className="fade" id="create-deal" tabIndex={-1} centered>
                <div className="modal-content border-0">
                    <Modal.Header>
                        <h6 className="modal-title">New Deal</h6>
                        <SpkButton Buttonvariant="" Customclass="btn-close" onClickfunc={handleClose} Buttondismiss="modal" Buttonlabel="Close" />
                    </Modal.Header>
                    <Modal.Body>
                        <Row className="gy-3">
                            <Col xl={12}>
                                <div className="mb-0 text-center">
                                    <span className="avatar avatar-xxl avatar-rounded">
                                    {avatar ? (
                                        <Image src={avatar} alt="Avatar" className="avatar" loading="lazy" />
                                    ) : (
                                        <BaseImage src="/build/assets/images/faces/9.jpg" alt="" id="profile-img" />
                                    )}
                                    <SpkBadge variant="primary" Customclass="rounded-pill avatar-badge" Onclickfun={triggerFileInput}>
                                        <input type="file" name="photo" className="position-absolute w-100 h-100 op-0" id="profile-change" ref={fileInputRef} onChange={onFileSelected} style={{ display: 'none' }} />
                                        <i className="fe fe-camera"></i>
                                    </SpkBadge>
                                    </span>
                                </div>
                            </Col>
                            <Col xl={6}>
                                <Form.Label htmlFor="deal-name" className="">Contact Name</Form.Label>
                                <Form.Control type="text" className="" id="deal-name" placeholder="Contact Name" />
                            </Col>
                            <Col xl={6}>
                                <Form.Label htmlFor="deal-lead-score" className="">Deal Value</Form.Label>
                                <Form.Control type="number" className="" id="deal-lead-score" placeholder="Deal Value" />
                            </Col>
                            <Col xl={12}>
                                <Form.Label htmlFor="company-name" className="">Company Name</Form.Label>
                                <Form.Control type="text" className="" id="company-name" placeholder="Company Name" />
                            </Col>
                            <Col xl={12}>
                                <Form.Label className="">Last Contacted</Form.Label>
                                <InputGroup className="custom-input-group">
                                    <div className="input-group-text text-muted"> <i className="ri-calendar-line"></i> </div>
                                    <SpkDatepickr className="form-control breadcrumb-input border-1  " Timeinput="Time:" dateFormat="yy/MM/dd h:mm aa" selected={startDate} onChange={handleDateChange} placeholderText='Choose date and time' showTimeInput />
                                </InputGroup>
                            </Col>
                        </Row>
                    </Modal.Body>
                    <Modal.Footer>
                        <SpkButton Buttonvariant="light" Buttontype="button" onClickfunc={handleClose}
                            Buttondismiss="modal">Cancel</SpkButton>
                        <SpkButton Buttonvariant="primary" Buttontype="button">Create Deal</SpkButton>
                    </Modal.Footer>
                </div>
            </Modal>

            {/* <!-- End:: New Deal --> */}

        </Fragment>
    )
};

Deals.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Deals;
