// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/reusable-pages/blog/spk-blogcard.svelte
<script>
    import { Link } from "@inertiajs/svelte";
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";

    const basePath = __BASE_PATH__;
    export let blog = {};
</script>

<Card class="custom-card border-0 blog-card shadow-none">
    <CardBody class="p-0">
        <!-- svelte-ignore a11y_consider_explicit_label -->
        <Link href={`${basePath}/pages/blog/blog-details`} class="stretched-link"
        ></Link>
        <div class="blog-image mb-3">
            <Image src={blog.image} class="card-img" alt="..." />
        </div>
        <span class="d-block mb-1 text-primary blog-category">{blog.title}</span
        >
        <h6 class="mb-0 blog-title lh-base">{blog.desc}</h6>
    </CardBody>
</Card>

// Dashboard Template/vyzor-nuxt/final/app/components/@spk/pages/blog/spk-blogcard.vue
<script setup>
defineProps({
    card: Object
})
</script>

<template>
    <div class="card custom-card border-0 blog-card shadow-none">
        <div class="card-body p-0">
            <NuxtLink to="/pages/blog/blog-details" class="stretched-link"></NuxtLink>
            <div class="blog-image mb-3">
                <img :src="card.image" class="card-img" alt="...">
            </div>
            <span class="d-block mb-1 text-primary blog-category">{{ card.title }}</span>
            <h6 class="mb-0 blog-title lh-base">{{ card.desc }}</h6>
        </div>
    </div>
</template>

<style scoped></style>
