// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/bar-chart/bar-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import * as barchartdata from "../../../../shared/data/charts/apexcharts/barchartdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const BarChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Bar Charts"} />

            <Pageheader title="Charts" currentpage="Apex Bar Charts" subtitle="Apex Charts" activepage="Apex Bar Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Basic Bar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-basic">
                                <Spkapexcharts chartOptions={barchartdata.Barbasicoptions} chartSeries={barchartdata.Barbasicseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Grouped Bar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-group">
                                <Spkapexcharts chartOptions={barchartdata.Bargroupoptions} chartSeries={barchartdata.Bargroupseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Stacked Bar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-stacked">
                                <Spkapexcharts chartOptions={barchartdata.Barstackoptions} chartSeries={barchartdata.Barstackseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">100% Stacked Bar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-full">
                                <Spkapexcharts chartOptions={barchartdata.Barstack1options} chartSeries={barchartdata.Barstck1series} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Bar Chart With Negative Values</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-negative">
                                <Spkapexcharts chartOptions={barchartdata.Barchartoptions} chartSeries={barchartdata.Barchartseries} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Bar Chart With Markers</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-markers">
                                <Spkapexcharts chartOptions={barchartdata.Barmakeroptions} chartSeries={barchartdata.Barmakerseries} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Reversed Bar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-reversed">
                                <Spkapexcharts chartOptions={barchartdata.Barreverseoptions} chartSeries={barchartdata.Barreverseseries} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Bar With Category DataLabels</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-categories">
                                <Spkapexcharts chartOptions={barchartdata.Barlableoptions} chartSeries={barchartdata.Barlabelseries} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Patterned Bar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-pattern">
                                <Spkapexcharts chartOptions={barchartdata.Barpatternoptions} chartSeries={barchartdata.Barpatternseries} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Bar With Image Fill</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="bar-image">
                                <Spkapexcharts chartOptions={barchartdata.Barimgoptions} chartSeries={barchartdata.Barimgseries} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
BarChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default BarChart;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/bar-chart/+page.svelte

<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import { Card, CardBody, CardHeader, Col, Row } from "@sveltestrap/sveltestrap";
    import * as barchartdata from "$lib/data/charts/apexcharts/barchartsdata"
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
</script>

<!-- Page Title -->
<svelte:head>
    <title>BarChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
   <!-- Page Header -->
  <Pageheader homepage='Apex Bar Charts'  activepage='Charts' subTitle="Apex Charts" page='Apex Bar Charts' />
  <!-- Page Header Close -->

    <!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Basic Bar Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-basic">
                                <Spkapexcharts id="bar-basic" options={barchartdata.Barbasicoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Grouped Bar Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-group">
                                <Spkapexcharts id="bar-group" options={barchartdata.Bargroupoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Stacked Bar Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-stacked">
                                <Spkapexcharts id="bar-stacked" options={barchartdata.Barstackoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">100% Stacked Bar Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-full">
                                <Spkapexcharts id="bar-full" options={barchartdata.Barstack1options}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Bar Chart With Negative Values</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-negative">
                                <Spkapexcharts id="bar-negative" options={barchartdata.Barchartoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Bar Chart With Markers</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-markers">
                                <Spkapexcharts id="bar-markers" options={barchartdata.Barmakeroptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Reversed Bar Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-reversed">
                                <Spkapexcharts  id="bar-reversed" options={barchartdata.Barreverseoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Bar With Category DataLabels</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-categories">
                                <Spkapexcharts id="bar-categories" options={barchartdata.Barlableoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Patterned Bar Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-pattern">
                                <Spkapexcharts id="bar-pattern" options={barchartdata.Barpatternoptions}/>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Bar With Image Fill</div>
                        </CardHeader>
                        <CardBody>
                            <div id="bar-image">
                                <Spkapexcharts id="bar-image"  options={barchartdata.Barimgoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!--End::row-1 -->
