// Dashboard Template/vyzor-nuxt/final/app/components/@spk/dashboards/crm/spk-deals-card.vue
<script lang="ts" setup>
defineProps({
    card: {
        type: Object as () => {
            imgSrc: string,
            title: string,
            price: string | number,
            company: string,
            date: string
        },
        required: true
    }
})
</script>

<template>
    <div class="card custom-card">
        <div class="card-body">
            <div class="d-flex align-items-center fw-medium justify-content-between gap-1 flex-wrap">
                <div class="d-flex align-items-center gap-2 flex-wrap">
                    <div class="lh-1">
                        <span class="avatar avatar-sm avatar-rounded">
                            <img v-if="card.imgSrc" :src="card.imgSrc" alt="">
                            <span v-else>{{ card.avater }}</span>
                        </span>
                    </div>
                    <div class="fs-14">{{ card.title }}</div>
                </div>
                <div>{{ card.price }}</div>
            </div>
            <div class="deal-description">
                <div class="my-1">
                    <a href="javascript:void(0);" class="company-name">{{ card.company }}</a>
                </div>
                <div class="text-muted fs-12">{{ card.date }}</div>
            </div>
        </div>
    </div>
</template>

<style scoped></style>

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/dashboards-reusable/crm/spk-dealscard.svelte
<script>
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";

    export let deal = {};
    export let cardClass = "";
    export let bodyClass = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class={bodyClass}>
        <div
            class="d-flex align-items-center fw-medium justify-content-between gap-1 flex-wrap"
        >
            <div class="d-flex align-items-center gap-2 flex-wrap">
                <div class="lh-1">
                    <span class="avatar avatar-sm avatar-rounded">
                        <Image src={deal.imgSrc} alt={deal.title} />
                    </span>
                </div>
                <div class="fs-14">{deal.title}</div>
            </div>
            <div>{deal.price}</div>
        </div>
        <div class="deal-description">
            <div class="my-1">
                <a href="#!" class="company-name">
                    {deal.company}
                </a>
            </div>
            <div class="text-muted fs-12">{deal.date}</div>
        </div>
    </CardBody>
</Card>
