// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/area-chart/+page.svelte

<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import * as areachartdata from "$lib/data/charts/apexcharts/areachartdata"
    import { Card, CardBody, CardHeader, Col, Image, Row } from "@sveltestrap/sveltestrap";
    import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";
</script>

<!-- Page Title -->
<svelte:head>
    <title>AreaChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
  homepage="Apex Area Charts"
  page="Apex Area Charts"
   activepage='Charts' subTitle="Apex Charts"
/>
<!-- Page Header Close -->

 <!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Basic Area Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="area-basic">
                                <Spkapexcharts id="area-basic" options={areachartdata.Areabasicoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Spline Area Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="area-spline">
                                <Spkapexcharts id="area-spline" options={areachartdata.Areasplineoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Area Chart With Negative Values</div>
                        </CardHeader>
                        <CardBody>
                            <div id="area-negative">
                                <Spkapexcharts id="area-negative" options={areachartdata.Areavalueoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Selection-Github Style Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="wrapper">
                                <div id="chart-months">
                                    <Spkapexcharts id="chart-months" options={areachartdata.Areagithuboptions}  />
                                </div>

                                <div class="github-style d-flex align-items-center">
                                    <div class="me-2">
                                        <Image class="userimg rounded" src="../../images/faces/1.jpg"
                                            data-hovercard-user-id="634573" alt="" width={38} height={38} />
                                    </div>
                                    <div class="userdetails lh-1">
                                        <a href="#!" class="username fw-semibold fs-14">coder</a>
                                        <span class="cmeta d-block mt-1">
                                            <span class="commits"></span> commits
                                        </span>
                                    </div>
                                </div>

                                <div id="chart-years">
                                    <Spkapexcharts id="chart-years" options={areachartdata.optionsYears} />
                                </div>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Stacked Area Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="area-stacked">
                                <Spkapexcharts id="area-stacked" options={areachartdata.Areastackoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Irregular Time Series Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="area-irregular">
                                <Spkapexcharts id="area-irregular" options={areachartdata.Areatimeoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Area Chart With Null Values</div>
                        </CardHeader>
                        <CardBody>
                            <div id="area-null">
                                <Spkapexcharts id="area-null" options={areachartdata.Areanulloptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Area Chart-Datetime X-Axis Chart</div>
                            <div class="btn-group ms-auto">
                                <SpkButton color="primary" customClass="btn  btn-sm">1M</SpkButton>
                                <SpkButton color="primary" customClass="btn  btn-sm">6M</SpkButton>
                                <SpkButton color="primary" customClass="btn  btn-sm">1Y</SpkButton>
                                <SpkButton color="primary" customClass="btn  btn-sm">ALL</SpkButton>
                            </div>
                        </CardHeader>
                        <CardBody>
                            <div id="area-datetime">
                                <Spkapexcharts id="area-datetime" options={areachartdata.Dateoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/area-chart/area-chart.jsx

import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import * as areachartdata from "../../../../shared/data/charts/apexcharts/areachartdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const AreaChart = () => {

    return (

        <Fragment>

            <Head title={"Apex Area Charts"} />

            <Pageheader title="Charts" currentpage="Apex Area Charts" subtitle="Apex Charts" activepage="Apex Area Charts" />

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Basic Area Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="area-basic">
                                <Spkapexcharts chartOptions={areachartdata.Areabasicoptions} chartSeries={areachartdata.Areabasicseries} type="area" width={"100%"} height={300} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Spline Area Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="area-spline">
                                <Spkapexcharts chartOptions={areachartdata.Areasplineoptions} chartSeries={areachartdata.Areasplineseries} type="area" width={"100%"} height={300} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Area Chart With Negative Values</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="area-negative">
                                <Spkapexcharts chartOptions={areachartdata.Areavalueoptions} chartSeries={areachartdata.Areavalueseries} type="area" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Selection-Github Style Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="wrapper">
                                <div id="chart-months">
                                    <Spkapexcharts chartOptions={areachartdata.Areagithuboptions} chartSeries={areachartdata.Areagithubseries} type="area" width={"100%"} height={130} />
                                </div>

                                <div className="github-style d-flex align-items-center">
                                    <div className="me-2">
                                        <BaseImage className="userimg rounded" src="/build/assets/images/faces/1.jpg"
                                            data-hovercard-user-id="634573" alt="" width="38" height="38" />
                                    </div>
                                    <div className="userdetails lh-1">
                                        <BaseLink href="#!" className="username fw-semibold fs-14">coder</BaseLink>
                                        <span className="cmeta d-block mt-1">
                                            <span className="commits"></span> commits
                                        </span>
                                    </div>
                                </div>

                                <div id="chart-years">
                                    <Spkapexcharts chartOptions={areachartdata.optionsYears} chartSeries={areachartdata.seriesYears} type="area" width={"100%"} height={140} />
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Stacked Area Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="area-stacked">
                                <Spkapexcharts chartOptions={areachartdata.Areastackoptions} chartSeries={areachartdata.Areastackseries} type="area" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Irregular Time Series Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="area-irregular">
                                <Spkapexcharts chartOptions={areachartdata.Areatimeoptions} chartSeries={areachartdata.Areatimeseries} type="area" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Area Chart With Null Values</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="area-null">
                                <Spkapexcharts chartOptions={areachartdata.Areanulloptions} chartSeries={areachartdata.Areanullseries} type="area" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Area Chart-Datetime X-Axis Chart</div>

                        </Card.Header>
                        <Card.Body>
                            <div id="area-datetime">
                                <Spkapexcharts chartOptions={areachartdata.Dateoptions} chartSeries={areachartdata.Dateseries} type='area' height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
AreaChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default AreaChart;
