// Dashboard Template/vyzor-laravel-svelte/final/resources/js/components/switcher/LandingSwitcher.svelte
<script>
    export let isOpen;
    export let toggle;
    import { onMount, onDestroy } from "svelte";
    import { Offcanvas, OffcanvasBody, Button } from "@sveltestrap/sveltestrap";
    import { themeStore } from "./switcher.js";

    let endOpen = false;
    const toggleEnd = () => {
        endOpen = !endOpen;
    };

    let userData = themeStore.userData;

    function toggleTheme(newTheme) {
        themeStore.updateColorThemeFn(newTheme);
        localStorage.setItem("vyzorcolortheme", newTheme);
        localStorage.removeItem("vyzorMenu");
        localStorage.removeItem("vyzorHeader");
    }

    function directionFn(value) {
        themeStore.UpdateDirectionFn(value);
        localStorage.setItem("vyzordirection", value);
    }

    function themePrimaryFn(value) {
        themeStore.updateThemePrimaryFn(value);
        localStorage.setItem("vyzorprimaryRGB", value);
    }

    function primaryColorFn(color) {
        if (!color || color === "#") {
            color = "#000000";
        }

        let primaryRgb = convertRgbToIndividual(color);
        themePrimaryFn(primaryRgb);
    }

    let initialColor = "";

    function convertRgbToIndividual(hex) {
        hex = hex.replace("#", "");

        // If the hex is empty or invalid, return a default RGB value
        if (hex.length !== 6 || !/^([0-9A-Fa-f]{6})$/.test(hex)) {
            return "0, 0, 0"; // Default to black
        }

        // Extract the red, green, and blue values
        let r = parseInt(hex.substring(0, 2), 16);
        let g = parseInt(hex.substring(2, 4), 16);
        let b = parseInt(hex.substring(4, 6), 16);

        return `${r}, ${g}, ${b}`;
    }

    function reset() {
        themeStore.custompageReset();
    }

    function custompageLocalStorageFn() {
        themeStore.custompageLocalStorage();
    }

    // Cleanup subscriptions on component destroy
    onMount(() => {
        custompageLocalStorageFn();
        return () => {};
    });

    let windowWidth;
    if (typeof window !== "undefined") {
        windowWidth = window.innerWidth;
        const updateWidth = () => {
            windowWidth = window.innerWidth;
            let html = document.documentElement;
        };

        // Add event listener for window resize
        window.addEventListener("resize", updateWidth);

        // Cleanup the event listener on component destroy

        onDestroy(() => {
            window.removeEventListener("resize", updateWidth);
        });
    }
</script>

<!-- Start Switcher -->
<Offcanvas
    class=" offcanvas-end"
    {isOpen}
    {toggle}
    placement="end"
    header="Switcher"
    id="switcher-canvas"
    aria-labelledby="offcanvasRightLabel"
>
    <OffcanvasBody>
        <div class="">
            <p class="switcher-style-head">Theme Color Mode:</p>
            <div class="row switcher-style g-0">
                <div class="col-4">
                    <div class="form-check switch-select">
                        <label
                            class="form-check-label"
                            for="switcher-light-theme"
                        >
                            Light
                        </label>
                        <input
                            class="form-check-input"
                            type="radio"
                            name="theme-style"
                            id="switcher-light-theme"
                            on:click={() => toggleTheme("light")}
                            checked={$userData.colortheme === "light"}
                        />
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-check switch-select">
                        <label
                            class="form-check-label"
                            for="switcher-dark-theme"
                        >
                            Dark
                        </label>
                        <input
                            class="form-check-input"
                            type="radio"
                            name="theme-style"
                            id="switcher-dark-theme"
                            on:click={() => toggleTheme("dark")}
                            checked={$userData.colortheme === "dark"}
                        />
                    </div>
                </div>
            </div>
        </div>
        <div class="">
            <p class="switcher-style-head">Directions:</p>
            <div class="row switcher-style g-0">
                <div class="col-4">
                    <div class="form-check switch-select">
                        <label class="form-check-label" for="switcher-ltr">
                            LTR
                        </label>
                        <input
                            class="form-check-input"
                            type="radio"
                            name="direction"
                            id="switcher-ltr"
                            on:change={() => directionFn("ltr")}
                            checked={$userData.direction === "ltr"}
                        />
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-check switch-select">
                        <label class="form-check-label" for="switcher-rtl">
                            RTL
                        </label>
                        <input
                            class="form-check-input"
                            type="radio"
                            name="direction"
                            id="switcher-rtl"
                            on:change={() => directionFn("rtl")}
                            checked={$userData.direction === "rtl"}
                        />
                    </div>
                </div>
            </div>
        </div>
        <div class="theme-colors">
            <p class="switcher-style-head">Theme Primary:</p>
            <div class="d-flex align-items-center switcher-style">
                <div class="form-check switch-select me-3">
                    <input
                        class="form-check-input color-input color-primary-1"
                        type="radio"
                        name="theme-primary"
                        id="switcher-primary"
                        on:change={() => themePrimaryFn("42 ,16, 164")}
                        checked={$userData.themePrimary === "42 ,16, 164"}
                    />
                </div>
                <div class="form-check switch-select me-3">
                    <input
                        class="form-check-input color-input color-primary-2"
                        type="radio"
                        name="theme-primary"
                        id="switcher-primary1"
                        on:change={() => themePrimaryFn("125 ,0, 189")}
                        checked={$userData.themePrimary === "125 ,0, 189"}
                    />
                </div>
                <div class="form-check switch-select me-3">
                    <input
                        class="form-check-input color-input color-primary-3"
                        type="radio"
                        name="theme-primary"
                        id="switcher-primary2"
                        on:change={() => themePrimaryFn("4, 118, 141")}
                        checked={$userData.themePrimary === "4, 118, 141"}
                    />
                </div>
                <div class="form-check switch-select me-3">
                    <input
                        class="form-check-input color-input color-primary-4"
                        type="radio"
                        name="theme-primary"
                        id="switcher-primary3"
                        on:change={() => themePrimaryFn("138, 0, 32")}
                        checked={$userData.themePrimary === "138, 0, 32"}
                    />
                </div>
                <div class="form-check switch-select me-3">
                    <input
                        class="form-check-input color-input color-primary-5"
                        type="radio"
                        name="theme-primary"
                        id="switcher-primary4"
                        on:change={() => themePrimaryFn("9 ,124, 103")}
                        checked={$userData.themePrimary === "9 ,124, 103"}
                    />
                </div>
                <div
                    class="form-check switch-select ps-0 mt-1 color-primary-light"
                >
                    <div class="theme-container-primary"></div>
                    <div class="pickr-container-primary">
                        <div class="pickr">
                            <input
                                type="color"
                                class="pcr-button"
                                role="button"
                                aria-label="toggle color picker dialog"
                                style="--pcr-color: rgba(132, 90, 223, 1);"
                                bind:value={initialColor}
                                on:input={(event) =>
                                    primaryColorFn(event.target.value)}
                            />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <p class="switcher-style-head">reset:</p>
            <div class="text-center">
                <button id="reset-all" class="btn btn-danger mt-3" on:click={reset}>Reset</button
                >
            </div>
        </div>
    </OffcanvasBody>
</Offcanvas>
<!-- End Switcher -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/layouts-components/switcher/landing-switcher.jsx

import  { Fragment, useContext, useEffect, useState } from "react";
import { Col, Form, Offcanvas, Row } from "react-bootstrap";
import { data$, getState } from "../services/switcherServices";
import SpkButton from "../../@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import { updateTheme, Reset1, setDirection, setPrimaryColor, ThemePrimaryColor, LocalStorageBackup } from "../../data/switcherdata/switcherdata";
import { Initialload } from "../../../contextapi";

const Landingswitcher = ({ show, handleClose }) => {

  let [variable, setVariable] = useState(getState());
  useEffect(() => {
    const subscription = data$.subscribe((e) => {
      setVariable(e);
    });

    return () => subscription.unsubscribe();
  }, []);
  const theme = useContext(Initialload);

  useEffect(() => {
      if (!theme.pageloading) {
        LocalStorageBackup(theme.setpageloading);
      }
    }, []);
  return (
    <Fragment>
      {/* <!-- Start Switcher --> */}
      <Offcanvas className="offcanvas offcanvas-end" placement="end" show={show} onHide={handleClose} tabIndex={-1} id="switcher-canvas" aria-labelledby="offcanvasRightLabel">
        <Offcanvas.Header className="offcanvas-header border-bottom">
          <h5 className="offcanvas-title" id="offcanvasRightLabel">
            Switcher
          </h5>
          <SpkButton Buttontype="button" Buttonvariant="" Customclass="btn-close" data-bs-dismiss="offcanvas" aria-label="Close" onClickfunc={handleClose}></SpkButton>
        </Offcanvas.Header>
        <Offcanvas.Body className="offcanvas-body">
          <div className="">
            <p className="switcher-style-head">Theme Color Mode:</p>
            <Row className="row switcher-style gx-0">
              <Col className="col-4">
                <Form.Check className="form-check switch-select">
                  <Form.Check.Label className="form-check-label" htmlFor="switcher-light-theme">
                    Light
                  </Form.Check.Label>
                  <Form.Check.Input className="form-check-input" type="radio" name="theme-style" id="switcher-light-theme" checked={variable.dataThemeMode === "light"} onChange={(_e) => { }} onClick={() => updateTheme('light', "clicked")}/>
                </Form.Check>
              </Col>
              <Col className="col-4">
                <Form.Check className="form-check switch-select">
                  <Form.Check.Label className="form-check-label" htmlFor="switcher-dark-theme">
                    Dark
                  </Form.Check.Label>
                  <Form.Check.Input className="form-check-input" type="radio" name="theme-style" id="switcher-dark-theme" checked={variable.dataThemeMode === "dark"} onChange={(_e) => { }} onClick={() => updateTheme('dark', "clicked")}/>
                </Form.Check>
              </Col>
            </Row>
          </div>
          <div className="">
            <p className="switcher-style-head">Directions:</p>
            <div className="row switcher-style gx-0">
              <div className="col-4">
                <Form.Check className="form-check switch-select">
                  <Form.Check.Label className="form-check-label" htmlFor="switcher-ltr">
                    LTR
                  </Form.Check.Label>
                  <Form.Check.Input className="form-check-input" type="radio" name="direction" id="switcher-ltr" checked={variable.dir === "ltr"} onChange={(_e) => { }} onClick={() => setDirection("ltr")}/>
                </Form.Check>
              </div>
              <div className="col-4">
                <Form.Check className="form-check switch-select">
                  <Form.Check.Label className="form-check-label" htmlFor="switcher-rtl">
                    RTL
                  </Form.Check.Label>
                  <Form.Check.Input className="form-check-input" type="radio" name="direction" id="switcher-rtl" checked={variable.dir === "rtl"} onChange={(_e) => { }} onClick={() => setDirection("rtl")}/>
                </Form.Check>
              </div>
            </div>
          </div>
          <div className="theme-colors">
            <p className="switcher-style-head">Theme Primary:</p>
            <div className="d-flex flex-wrap align-items-center switcher-style">
                                            <Form.Check className="form-check switch-select me-3">
                                                <Form.Check.Input className="form-check-input color-input color-primary-1" type="radio" name="theme-primary" id="switcher-primary"
                                                 checked={variable.colorPrimaryRgb === ' 42 ,16, 164'} onChange={(_e) => { }} onClick={() => setPrimaryColor(' 42 ,16, 164')}/>
                                            </Form.Check>
                                            <Form.Check className="form-check switch-select me-3">
                                                <Form.Check.Input className="form-check-input color-input color-primary-2" type="radio" name="theme-primary" id="switcher-primary1"
                                                 checked={variable.colorPrimaryRgb === '125 ,0, 189'} onChange={(_e) => { }} onClick={() => setPrimaryColor('125 ,0, 189')}/>
                                            </Form.Check>
                                            <Form.Check className="form-check switch-select me-3">
                                                <Form.Check.Input className="form-check-input color-input color-primary-3" type="radio" name="theme-primary" id="switcher-primary2"
                                                 checked={variable.colorPrimaryRgb === '4, 118, 141'} onChange={(_e) => { }} onClick={() => setPrimaryColor('4, 118, 141')}/>
                                            </Form.Check>
                                            <Form.Check className="form-check switch-select me-3">
                                                <Form.Check.Input className="form-check-input color-input color-primary-4" type="radio" name="theme-primary" id="switcher-primary3"
                                                 checked={variable.colorPrimaryRgb === '138, 0, 32'} onChange={(_e) => { }} onClick={() => setPrimaryColor('138, 0, 32')}/>
                                            </Form.Check>
                                            <Form.Check className="form-check switch-select me-3">
                                                <Form.Check.Input className="form-check-input color-input color-primary-5" type="radio" name="theme-primary" id="switcher-primary4"
                                                 checked={variable.colorPrimaryRgb === '9 ,124, 103'} onChange={(_e) => { }} onClick={() => setPrimaryColor('9 ,124, 103')} />
                                            </Form.Check>
                                            <Form.Check className="form-check switch-select ps-0 mt-1 color-primary-light">
                                                <div className="theme-container-primary">
                                                    <SpkButton Customclass="">nano</SpkButton>
                                                </div>
                                                <div className="pickr-container-primary"  >
                                                    <div className='pickr'>
                                                        <SpkButton Customclass='pcr-button btn-primary' onClickfunc={(ele) => {
                                                            if (ele.target.querySelector("input")) {
                                                                ele.target.querySelector("input").click();
                                                            }
                                                        }}>
                                                            <ThemePrimaryColor />
                                                        </SpkButton>
                                                    </div>
                                                </div>
                                            </Form.Check>
                                        </div>
          </div>
          <div>
            <p className="switcher-style-head">reset:</p>
            <div className="text-center">
              <SpkButton Id="reset-all" Customclass="btn btn-danger mt-3" Buttonvariant="danger" onClickfunc={Reset1}>
                Reset
              </SpkButton>
            </div>
          </div>
        </Offcanvas.Body>
      </Offcanvas>
      {/* <!-- End Switcher --> */}
    </Fragment>
  );
};

export default Landingswitcher;
