// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/candlestick-chart/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import { Card, CardBody, CardHeader, CardTitle, Col, Row } from "@sveltestrap/sveltestrap";
    import { Basiccandlestick, Candlebrush, Candleline, Candlexaxis, optionsBar } from "$lib/data/charts/apexcharts/candlestickdata";
    // import { Candbasicoptions, CandeoptionsBar, Candsyncoptions } from "$lib/data/charts/apexcharts/candlestickdata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>CandlestickChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Candlestick Charts"
    page="Apex Candlestick Charts"
    activepage="Charts"
    subTitle="Apex Charts"
/>
<!-- Page Header Close -->

  <!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Basic Candlestick Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <div id="candlestick-basic">
                                <Spkapexcharts id="candlestick-basic" options={Basiccandlestick}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Candlestick Synced With Brush Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                                <Spkapexcharts options={Candlebrush} id="chart-candlestick"/>
                                <Spkapexcharts id="chart-bar" options={optionsBar}  />

                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Candlestick With Category X-axis</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <div id="candlestick-categoryx">
                                <Spkapexcharts options={Candlexaxis} id="candlestick-categoryx"  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Candlestick With Line Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <div id="candlestick-line">
                                <Spkapexcharts options={Candleline} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/candlestick-chart/candlestick-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";

import { Candbasicoptions, Candbasicseries, CandeoptionsBar, Candlineoptions, Candlineseries, CandseriesBar, Candsyncedseries, Candsyncoptions } from "../../../../shared/data/charts/apexcharts/candlestickdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const CandlestickChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Apex Candlestick Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Candlestick Charts" activepage="Apex Candlestick Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Candlestick Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="candlestick-basic">
                                <Spkapexcharts chartOptions={Candbasicoptions} chartSeries={Candbasicseries} type="candlestick" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Candlestick Synced With Brush Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="chart-candlestick">
                                <Spkapexcharts chartOptions={Candsyncoptions} chartSeries={Candsyncedseries} type="candlestick" width={"100%"} height={215} />
                            </div>
                            <div id="chart-bar">
                                <Spkapexcharts chartOptions={CandeoptionsBar} chartSeries={CandseriesBar} type="bar" width={"100%"} height={120} />
                            </div>

                        </Card.Body>
                    </Card>
                </Col>

                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Candlestick With Line Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="candlestick-line">
                                <Spkapexcharts chartOptions={Candlineoptions} chartSeries={Candlineseries} type="candlestick" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )

};
// Assign layout
CandlestickChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default CandlestickChart;
