// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/radialbar-chart/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import { Card, CardBody, CardHeader, Col, Row } from "@sveltestrap/sveltestrap";
    import * as radialdata from "$lib/data/charts/apexcharts/radialbarchartdata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>RadialbarChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Radialbar Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Radialbar Charts"
/>
<!-- Page Header Close -->

  <!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Basic Pie Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="radialbar-basic">
                                <Spkapexcharts options={radialdata.Pieoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Multiple Radialbar Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="radialbar-multiple">
                                <Spkapexcharts options={radialdata.Multiroptions} id="radialbar-multiple" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Circle Chart - Custom Angle</div>
                        </CardHeader>
                        <CardBody>
                            <div id="circle-custom">
                                <Spkapexcharts options={radialdata.Customoptions} id="circle-custom" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Gradient Circle Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="gradient-circle">
                                <Spkapexcharts options={radialdata.Gradientoptions} id="gradient-circle"  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Stroked Circular Gauge</div>
                        </CardHeader>
                        <CardBody>
                            <div id="circular-stroked">
                                <Spkapexcharts options={radialdata.Strokeoptions} id="circular-stroked" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Circle Chart With Image</div>
                        </CardHeader>
                        <CardBody>
                            <div id="circle-image">
                                <Spkapexcharts options={radialdata.Circleoptions} id="circle-image"  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Semi Circular Gauge</div>
                        </CardHeader>
                        <CardBody>
                            <div id="circular-semi">
                                <Spkapexcharts options={radialdata.Gaugeoptions} id="circular-semi" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/radialbar-chart/radialbar-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import * as radialdata from "../../../../shared/data/charts/apexcharts/radialbardata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const RadialbarChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Radialbar Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Radialbar Charts" activepage="Apex Radialbar Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Basic Pie Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="radialbar-basic">
                                <Spkapexcharts chartOptions={radialdata.Pieoptions} chartSeries={radialdata.Pieseries} type="radialBar" width={"100%"} height={300} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Multiple Radialbar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="radialbar-multiple">
                                <Spkapexcharts chartOptions={radialdata.Multiroptions} chartSeries={radialdata.Multirseries} type="radialBar" width={"100%"} height={300} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Circle Chart - Custom Angle</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="circle-custom">
                                <Spkapexcharts chartOptions={radialdata.Customoptions} chartSeries={radialdata.Customseries} type="radialBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Gradient Circle Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="gradient-circle">
                                <Spkapexcharts chartOptions={radialdata.Gradientoptions} chartSeries={radialdata.Gradientseries} type="radialBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Stroked Circular Gauge</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="circular-stroked">
                                <Spkapexcharts chartOptions={radialdata.Strokeoptions} chartSeries={radialdata.Storkeseries} type="radialBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Circle Chart With Image</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="circle-image">
                                <Spkapexcharts chartOptions={radialdata.Circleoptions} chartSeries={radialdata.Circleseries} type="radialBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Semi Circular Gauge</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="circular-semi">
                                <Spkapexcharts chartOptions={radialdata.Gaugeoptions} chartSeries={radialdata.Gaugeseries} type="radialBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
RadialbarChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default RadialbarChart;
