// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/pages/authentication/sign-in/cover.svelte
<script context="module">
    import Authlayout from "@/layouts/Authlayout.svelte";
    export const layout = Authlayout;
</script>

<script>
    import {
        Card,
        CardBody,
        Col,
        Form,
        Image,
        Input,
        Label,
        Row,
    } from "@sveltestrap/sveltestrap";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import { onMount } from "svelte";
    import { Inertia } from "@inertiajs/inertia";
    import { Link } from "@inertiajs/svelte";
    const basePath = __BASE_PATH__;
    let values = {
        email: "",
        password: "",
        showPassword: false,
    };
    let errors = {};

    const validate = () => {
        const newErrors = {};

        // Email validation
        if (!values.email) {
            newErrors.email = "Email is required.";
        } else if (!/\S+@\S+\.\S+/.test(values.email)) {
            newErrors.email = "Invalid email format.";
        }

        // Password validation
        if (!values.password) {
            newErrors.password = "Password is required.";
        } else if (values.password.length < 6) {
            newErrors.password = "Password must be at least 6 characters.";
        }

        errors = newErrors;
        return Object.keys(newErrors).length === 0;
    };
    let matched;
    const handleSubmit = (event) => {
        event.preventDefault();
        if (validate()) {
            (matched = "Save Password successful"),
                Inertia.visit(`${basePath}/dashboards/sales/`);
        }
    };

    const togglePassword = () => {
        values.showPassword = !values.showPassword;
    };

    const setBodyClass = (action) => {
        if (action === "add") {
            document.body.classList.add("bg-white");
        } else {
            document.body.classList.remove("bg-white");
        }
    };

    onMount(() => {
        if (localStorage.getItem("visited") === "true") {
            setBodyClass("add");
        } else {
            setBodyClass("add");
            localStorage.setItem("visited", "true");
        }

        const handleBeforeUnload = () => {
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };

        window.addEventListener("beforeunload", handleBeforeUnload);

        return () => {
            window.removeEventListener("beforeunload", handleBeforeUnload);
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };
    });
</script>

<!-- Page Title -->
<svelte:head>
    <title>Signin-Cover | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<Row class="authentication authentication-cover-main mx-0">
    <Col xxl={9} xl={9}>
        <Row class="justify-content-center align-items-center h-100">
            <Col xxl={4} xl={5} lg={6} md={6} sm={8} class="col-12">
                <Card class="custom-card border-0 shadow-none my-4">
                    <CardBody class="p-5">
                        <div>
                            <h4 class="mb-1 fw-semibold">Hi,Welcome back!</h4>
                            <p class="mb-4 text-muted fw-normal">
                                Please enter your credentials
                            </p>
                        </div>
                        <Form on:submit={handleSubmit}>
                            <Row class=" gy-3">
                                <Col xl={12}>
                                    <Label
                                        for="signin-email"
                                        class="text-default">Email</Label
                                    >
                                    <Input
                                        type="email"
                                        class="form-control "
                                        id="signup-firstname"
                                        placeholder="Enter Email ID"
                                        bind:value={values.email}
                                    />
                                    {#if errors.email}
                                        <p class="text-danger text-sm">
                                            {errors.email}
                                        </p>
                                    {/if}
                                </Col>
                                <Col xl={12} class="mb-2">
                                    <Label
                                        for="signin-password"
                                        class="text-default d-block"
                                        >Password</Label
                                    >
                                    <div class="position-relative">
                                        <Input
                                            type={values.showPassword
                                                ? "text"
                                                : "password"}
                                            class="form-control "
                                            id="signup-password"
                                            placeholder="Password"
                                            bind:value={values.password}
                                        />
                                        <a
                                            href="#!"
                                            class="show-password-button text-muted"
                                            on:click={togglePassword}
                                        >
                                            {#if values.showPassword}
                                                <i
                                                    class="ri-eye-line align-middle"
                                                ></i>
                                            {:else}
                                                <i
                                                    class="ri-eye-off-line align-middle"
                                                ></i>
                                            {/if}
                                        </a>
                                        {#if errors.password}
                                            <p class="text-danger text-sm">
                                                {errors.password}
                                            </p>
                                        {/if}
                                        {#if matched}
                                            <p class="text-success text-sm">
                                                {errors.password}
                                            </p>
                                        {/if}
                                    </div>
                                    <div class="mt-2">
                                        <div class="form-check">
                                            <input
                                                class="form-check-input"
                                                type="checkbox"
                                                defaultValue=""
                                                id="defaultCheck1"
                                                defaultChecked
                                            />
                                            <label
                                                class="form-check-label"
                                                for="defaultCheck1"
                                            >
                                                Remember me
                                            </label>
                                            <Link
                                                href={`${basePath}/pages/authentication/reset-password/basic`}
                                                class="float-end link-danger fw-medium fs-12"
                                                >Forget password ?</Link
                                            >
                                        </div>
                                    </div>
                                </Col>
                            </Row>
                            <div class="d-grid mt-3">
                                <SpkButton
                                    buttontype="submit"
                                    customClass="btn btn-primary"
                                    >Sign In</SpkButton
                                >
                            </div>
                        </Form>
                        <div class="text-center my-3 authentication-barrier">
                            <span class="op-4 fs-13">OR</span>
                        </div>
                        <div class="d-grid mb-3">
                            <SpkButton
                                customClass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill mb-3"
                            >
                                <span class="avatar avatar-xs">
                                    <Image
                                        src={`${basePath}/images/media/apps/google.png`}
                                        alt=""
                                    />
                                </span>
                                <span
                                    class="lh-1 ms-2 fs-13 text-default fw-medium"
                                    >Signup with Google</span
                                >
                            </SpkButton>
                            <SpkButton
                                customClass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill"
                            >
                                <span class="avatar avatar-xs">
                                    <Image
                                        src={`${basePath}/images/media/apps/facebook.png`}
                                        alt=""
                                    />
                                </span>
                                <span
                                    class="lh-1 ms-2 fs-13 text-default fw-medium"
                                    >Signup with Facebook</span
                                >
                            </SpkButton>
                        </div>
                        <div class="text-center mt-3 fw-medium">
                            Dont have an account? <Link
                                href={`${basePath}/pages/authentication/sign-up/basic/`}
                                class="text-primary">Sign Up</Link
                            >
                        </div>
                    </CardBody>
                </Card>
            </Col>
        </Row>
    </Col>
    <Col xxl={3} xl={3} lg={12} class="d-xl-block d-none px-0">
        <div class="authentication-cover overflow-hidden">
            <div class="authentication-cover-logo">
                <Link href={`${basePath}/dashboards/sales`}>
                    <Image
                        src={`${basePath}/images/brand-logos/toggle-logo.png`}
                        alt="logo"
                        class="desktop-dark"
                    />
                </Link>
            </div>
            <div class="authentication-cover-background">
                <Image src={`${basePath}/images/media/backgrounds/9.png`} alt="" />
            </div>
            <div class="authentication-cover-content">
                <div class="p-5">
                    <h3 class="fw-semibold lh-base">Welcome to Dashboard</h3>
                    <p class="mb-0 text-muted fw-medium">
                        Manage your website and content with ease using our
                        powerful admin tools.
                    </p>
                </div>
                <div>
                    <Image
                        src={`${basePath}/images/media/media-72.png`}
                        alt=""
                        class="img-fluid"
                    />
                </div>
            </div>
        </div>
    </Col>
</Row>

// Dashboard Template/vyzor-react-ts/final/src/components/pages/authentication/sign-in/cover/cover.tsx

import SpkButton from "../../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import Seo from "../../../../../shared/layouts-components/seo/seo";
import { Fragment, useState } from "react"
import { Card, Col, Form, Image, Row } from "react-bootstrap";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import togglelogo from '../../../../../assets/images/brand-logos/toggle-logo.png';
import BG9 from '../../../../../assets/images/media/backgrounds/9.png';
import media72 from '../../../../../assets/images/media/media-72.png';
import facebook from '../../../../../assets/images/media/apps/facebook.png';
import google from '../../../../../assets/images/media/apps/google.png';
interface CoverProps { }

const Cover: React.FC<CoverProps> = () => {

    const [values, setValues] = useState<any>({
        email: '',
        password: '',
        showPassword: false
    });

    const [errors, setErrors] = useState<any>({});

    const validate = () => {
        const newErrors: any = {};

        // Email validation
        if (!values.email) {
            newErrors.email = "Email is required.";
        } else if (!/\S+@\S+\.\S+/.test(values.email)) {
            newErrors.email = "Invalid email format.";
        }

        // Password validation
        if (!values.password) {
            newErrors.password = "Password is required.";
        } else if (values.password.length < 6) {
            newErrors.password = "Password must be at least 6 characters.";
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };
    const router = useNavigate()
    const handleSubmit = (e: any) => {
        e.preventDefault();
        if (validate()) {
            router(`${import.meta.env.BASE_URL}dashboards/sales/`);
            toast.success('Login successful', {
                position: 'top-right',
                autoClose: 1500,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                draggable: true,
            });
            // Handle form submission logic here
        }
    };


    return (

        <Fragment>
            <Seo title="Signin-Cover" />

            <Row className="authentication authentication-cover-main mx-0">
                <Col xxl={9} xl={9}>
                    <Row className="justify-content-center align-items-center h-100">
                        <Col xxl={4} xl={5} lg={6} md={6} sm={8} className="col-12">
                            <Card className="custom-card border-0 shadow-none my-4">
                                <Card.Body className="p-5">
                                    <div>
                                        <h4 className="mb-1 fw-semibold">Hi,Welcome back!</h4>
                                        <p className="mb-4 text-muted fw-normal text-nowrap">Please enter your credentials</p>
                                    </div>
                                    <Form onSubmit={handleSubmit}>
                                        <Row className=" gy-3">
                                            <Col xl={12}>
                                                <Form.Label htmlFor="signin-email" className="text-default">Email</Form.Label>
                                                <Form.Control
                                                    type="email"
                                                    className="form-control "
                                                    id="signup-firstname"
                                                    placeholder="Enter Email ID"
                                                    value={values.email}
                                                    onChange={(e) => setValues({ ...values, email: e.target.value })}
                                                    isInvalid={!!errors.email}
                                                />
                                                <Form.Control.Feedback type="invalid">{errors.email}</Form.Control.Feedback>
                                            </Col>
                                            <Col xl={12} className="mb-2">
                                                <Form.Label htmlFor="signin-password" className="text-default d-block">Password</Form.Label>
                                                <div className="position-relative">
                                                    <Form.Control
                                                        type={values.showPassword ? "text" : "password"}
                                                        className="form-control "
                                                        id="signup-password"
                                                        placeholder="Password"
                                                        value={values.password}
                                                        onChange={(e) => setValues({ ...values, password: e.target.value })}
                                                        isInvalid={!!errors.password}
                                                    />
                                                    <Link to="#!" className="show-password-button text-muted"
                                                        onClick={() => setValues((prev: any) => ({ ...prev, showPassword: !prev.showPassword }))}>
                                                        {values.showPassword ? (
                                                            <i className="ri-eye-line align-middle"></i>
                                                        ) : (
                                                            <i className="ri-eye-off-line align-middle"></i>
                                                        )}
                                                    </Link>
                                                    <Form.Control.Feedback type="invalid">{errors.password}</Form.Control.Feedback>
                                                </div>
                                                <div className="mt-2">
                                                    <div className="d-flex align-items-center justify-content-between flex-wrap">
                                                        <div className="form-check">
                                                            <input className="form-check-input" type="checkbox" defaultValue="" id="defaultCheck1" defaultChecked />
                                                            <label className="form-check-label" htmlFor="defaultCheck1">
                                                                Remember me
                                                            </label>
                                                        </div>
                                                        <Link to={`${import.meta.env.BASE_URL}pages/authentication/reset-password/basic`} className="link-danger fw-medium fs-12">Forget password ?</Link>
                                                    </div>
                                                </div>
                                            </Col>
                                        </Row>
                                        <div className="d-grid mt-3">
                                            <SpkButton Buttontype="submit" Customclass="btn btn-primary">Sign In</SpkButton>
                                        </div>
                                    </Form>
                                    <div className="text-center my-3 authentication-barrier">
                                        <span className="op-4 fs-13">OR</span>
                                    </div>
                                    <div className="d-grid mb-3">
                                        <SpkButton Customclass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill mb-3">
                                            <span className="avatar avatar-xs">
                                                <Image  src={google} alt="" />
                                            </span>
                                            <span className="lh-1 ms-2 fs-13 text-default fw-medium">Signup with Google</span>
                                        </SpkButton>
                                        <SpkButton Customclass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill">
                                            <span className="avatar avatar-xs">
                                                <Image  src={facebook} alt="" />
                                            </span>
                                            <span className="lh-1 ms-2 fs-13 text-default fw-medium">Signup with Facebook</span>
                                        </SpkButton>
                                    </div>
                                    <div className="text-center mt-3 fw-medium">
                                        Dont have an account? <Link to={`${import.meta.env.BASE_URL}pages/authentication/sign-up/basic/`} className="text-primary">Sign Up</Link>
                                    </div>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>
                </Col>
                <Col xxl={3} xl={3} lg={12} className="d-xl-block d-none px-0">
                    <div className="authentication-cover overflow-hidden">
                        <div className="authentication-cover-logo">
                            <Link to={`${import.meta.env.BASE_URL}dashboards/sales`}>
                                <Image  src={togglelogo} alt="logo" className="desktop-dark" />
                            </Link>
                        </div>
                        <div className="authentication-cover-background">
                            <Image  src={BG9} alt="" />
                        </div>
                        <div className="authentication-cover-content">
                            <div className="p-5">
                                <h3 className="fw-semibold lh-base">Welcome to Dashboard</h3>
                                <p className="mb-0 text-muted fw-medium">Manage your website and content with ease using our powerful admin tools.</p>
                            </div>
                            <div>
                                <Image  src={media72} alt="" className="img-fluid" />
                            </div>
                        </div>
                    </div>
                </Col>
            </Row>
        </Fragment>
    )
}
export default Cover;
