// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/general-reusable/reusable-uielements/reusable-cards/spkhorizontalcards.jsx

import React, { Fragment } from 'react'
import { Card, Image } from 'react-bootstrap'
import { Link } from "@inertiajs/react";
import BaseImage from '@/shared/layouts-components/baseimage/baseimage';

const Spkhorizontalcards = ({ Imagesrc, CardHeader, Imgclass, Navigate, Imgposition, children, CardFooter, Title, Linktag, Footertext }) => {
    return (
        <Fragment>
            <Card className="custom-card">
                {Linktag ? <Link href={Navigate} className="card-anchor"></Link> : ''}
                <div className="row g-0">
                    {Imgposition === "before" ?
                        <div className="col-md-4">
                            <BaseImage src={Imagesrc} className={Imgclass} alt="..." />
                        </div>
                        : ''}
                    <div className="col-md-8">
                        {CardHeader ?
                            <Card.Header>
                                <div className="card-title">{Title}</div>
                            </Card.Header>
                            : ''}

                        <Card.Body>
                            {children}
                        </Card.Body>

                        {CardFooter ?
                            <Card.Footer>
                                <p className="card-text"><small className="text-muted">{Footertext}</small></p>
                            </Card.Footer> : ''}
                    </div>

                    {Imgposition === "after" ?
                        <div className="col-md-4 ">
                            <BaseImage src={Imagesrc} className="img-fluid rounded-end h-100 w-100" alt="..." />
                        </div>
                        : ''}
                </div>
            </Card>
        </Fragment>
    )
}

export default Spkhorizontalcards

// Dashboard Template/vyzor-svelte/staterkit/src/lib/@spk/uielements/reusable-cards/spkhorizontalcards.svelte
<script lang="ts">
    import {
        Card,
        Image,
        CardHeader,
        CardBody,
        CardFooter,
    } from "@sveltestrap/sveltestrap";

    export let Imagesrc: string = "";
    export let CardFooterTag: boolean = false;
    export let Footertext: string = "";
    export let Title: string = "";
    export let Linktag: boolean = false;
    export let CardHeaderTag: boolean = false;
    export let Imgposition: string = "";
    export let Imgclass: string = "";
    export let Navigate: string = "";
</script>

<Card class="custom-card">
    {#if Linktag}
        <!-- svelte-ignore a11y_consider_explicit_label -->
        <a href={Navigate} class="card-anchor"></a>
    {/if}
    <div class="row g-0">
        {#if Imgposition === "before"}
            <div class="col-md-4">
                <Image src={Imagesrc} class={Imgclass} alt="..." />
            </div>
        {/if}
        <div class="col-md-8">
            {#if CardHeaderTag}
                <CardHeader>
                    <div class="card-title">{Title}</div>
                </CardHeader>
            {/if}
            <CardBody>
                <slot />
            </CardBody>
            {#if CardFooterTag}
                <CardFooter>
                    <p class="card-text">
                        <small class="text-muted">{Footertext}</small>
                    </p>
                </CardFooter>
            {/if}
        </div>
        {#if Imgposition === "after"}
            <div class="col-md-4">
                <Image
                    src={Imagesrc}
                    class="img-fluid rounded-sm-end rounded-bottom h-100 w-100"
                    alt="..."
                />
            </div>
        {/if}
    </div>
</Card>
