// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/general-reusable/reusable-uielements/reusable-cards/spklistgroupcards.jsx
import React, { Fragment } from 'react'
import { Card } from 'react-bootstrap'
import SpkListgroup from '../spk-listgroup'

const SpkListgroupcards = ({ Headertext, children, CardHeader = false, Footertext, Listvariant, CardFooter = false, ListClass, Customfooterclass }) => {
    return (
        <Fragment>
            <Card className="custom-card overflow-hidden">
                {CardHeader ?
                    <Card.Header>
                        {Headertext}
                    </Card.Header>
                    : ""}
                <SpkListgroup Variant={Listvariant} CustomClass={ListClass}>
                    {children}
                </SpkListgroup>
                {CardFooter ?
                    <Card.Footer className={Customfooterclass}>
                        {Footertext}
                    </Card.Footer> : ""}
            </Card>
        </Fragment>
    )
}

export default SpkListgroupcards

// Dashboard Template/vyzor-svelte/staterkit/src/lib/@spk/uielements/reusable-cards/spklistgroupcards.svelte
<script lang="ts">
    import { Card, CardFooter, CardHeader } from "@sveltestrap/sveltestrap";
    import SpkListGroup from "../ListGroup/SpkListGroup.svelte";

    export let Headertext: string = "";
    export let CardHeaderTag: boolean = false;
    export let Footertext: string = "";
    export let Listvariant: boolean;
    export let CardFooterTag: boolean = false;
    export let ListClass: string = "";
    export let Customfooterclass: string = "";
    export let Id: string = "";
</script>

<Card class="custom-card overflow-hidden">
    {#if CardHeaderTag}
        <CardHeader>
            {Headertext}
        </CardHeader>
    {/if}
    <SpkListGroup Flush={Listvariant} CustomClass={ListClass} {Id}>
        <slot />
    </SpkListGroup>
    {#if CardFooterTag}
        <CardFooter class={Customfooterclass}>
            {Footertext}
        </CardFooter>
    {/if}
</Card>
