// Dashboard Template/vyzor-laravel-svelte/final/resources/js/components/backToTop/BackToTop.svelte
<script>
    import { onMount } from "svelte";

    const screenUp = () => {
        window.scrollTo(0, 0);
    };

    onMount(() => {
        const handleScroll = () => {
            const color = document.getElementsByClassName("scrollToTop")[0];
            if (color) {
                window.scrollY > 100
                    ? (color.style.display = "flex")
                    : (color.style.display = "none");
            }
        };

        window.addEventListener("scroll", handleScroll);

        return () => {
            window.removeEventListener("scroll", handleScroll);
        };
    });
</script>

<!-- svelte-ignore a11y_consider_explicit_label -->
<a href="#!" on:click={screenUp}>
    <div class="scrollToTop">
        <span class="arrow lh-1"><i class="ti ti-arrow-big-up fs-18"></i></span>
    </div>
</a>

// Dashboard Template/vyzor-react-ts/final/src/shared/layouts-components/backtotop/backtotop.tsx

import React, { useEffect, useRef } from 'react'

interface BacktotopProps { }

const Backtotop: React.FC<BacktotopProps> = () => {
    const scrollToTopRef = useRef<HTMLDivElement | null>(null);
    const screenUp = () => {
        window.scrollTo(0, 0);
    };

    useEffect(() => {
        const handleScroll = () => {
            if (scrollToTopRef.current) {
                window.scrollY > 100 ? (scrollToTopRef.current.style.display = "flex") : (scrollToTopRef.current.style.display = "none")
            }
        };

        window.addEventListener("scroll", handleScroll);

        return () => {
            window.removeEventListener("scroll", handleScroll);
        };
    }, []);

    return (
        <div ref={scrollToTopRef} className="scrollToTop" onClick={screenUp}>
            <span className="arrow"><i className="ti ti-arrow-big-up fs-16"></i></span>
        </div>
    )
}

export default Backtotop
