// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/chartjs-charts/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import SpkChartjs from "$lib/@spk/charts/SpkChartjs.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
import * as chartjsdata from "$lib/data/charts/chartjsdata"

</script>

<!-- Page Title -->
<svelte:head>
    <title>ChartjsCharts | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="ChartJs Charts"
    activepage="Charts"
    page="ChartJs Charts"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Line Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs id="chartjs-line" type="line" data={chartjsdata.Data} options={chartjsdata.Option} />
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Bar Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs
                id="chartjs-bar"
                type="bar" options={chartjsdata.Option1} data={chartjsdata.Data1}
                />
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Pie Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs
                id="chartjs-pie"
                type="pie" options={chartjsdata.Option2} data={chartjsdata.Data2}
                />
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Doughnut Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs
                id="chartjs-doughnut"
                type="doughnut" options={chartjsdata.Option3} data={chartjsdata.Data3}
                />
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Mixed Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs
                id="chartjs-mixed"
                type="bar" options={chartjsdata.mixOptions} data={chartjsdata.MixedData}

                />
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Polar Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs
                id="chartjs-polar"
                type="polarArea" options={chartjsdata.Option5} data={chartjsdata.Data5}
                />
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Radial Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs
                id="chartjs-radar"
                type="radar" options={chartjsdata.Option6} data={chartjsdata.Data6}
                />
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Scatter Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs
                id="chartjs-scatter" 
                type="scatter" options={chartjsdata.Option7} data={chartjsdata.Data7} 
                />
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Chartjs Bubble Chart</div>
            </CardHeader>
            <CardBody>
                <SpkChartjs
                id="chartjs-bubble"
                type="bubble" options={chartjsdata.Option8} data={chartjsdata.Data8}
                />
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/chartjs-charts/chartjs-charts.jsx

import * as chartjsdata from "../../../shared/data/charts/chartjsdata";
import React, { Fragment } from "react";
import { Head } from "@inertiajs/react";
import { Card, Col, Row } from "react-bootstrap";
import SpkChartJs from "../../../shared/@spk-reusable-components/reusable-plugins/spk-chartjs";
import Pageheader from "../../../shared/layouts-components/pageheader/pageheader";
import MainLayout from "@/Layouts/layout";


const ChartjsCharts = () => {

    return (

        <Fragment>

            <Head title={"Chartjs Charts"} />

            <Pageheader title="Charts" currentpage="ChartJs Charts" activepage="ChartJs Charts" />

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Chartjs Line Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <SpkChartJs id="chartjs-charts" type="line" chartOptions={chartjsdata.Option} chartSeries={chartjsdata.Data} height='300px' />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Chartjs Bar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <SpkChartJs id="chartjs-charts" type="bar" chartOptions={chartjsdata.Option1} chartSeries={chartjsdata.Data1} height='300px' />

                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Chartjs Pie Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <SpkChartJs id="chartjs-charts" type="pie" chartOptions={chartjsdata.Option2} chartSeries={chartjsdata.Data2} height='300px' />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Chartjs Doughnut Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <SpkChartJs id="chartjs-charts" type="doughnut" chartOptions={chartjsdata.Option3} chartSeries={chartjsdata.Data3} height='300px' />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Chartjs Polar Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <SpkChartJs id="chartjs-charts" type="polarArea" chartOptions={chartjsdata.Option5} chartSeries={chartjsdata.Data5} height='300px' />

                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Chartjs Radial Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <SpkChartJs id="chartjs-charts" type="radar" chartOptions={chartjsdata.Option6} chartSeries={chartjsdata.Data6} height='300px' />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Chartjs Scatter Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <SpkChartJs id="chartjs-charts" type="scatter" chartOptions={chartjsdata.Option7} chartSeries={chartjsdata.Data7} height='300px' />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Chartjs Bubble Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <SpkChartJs id="chartjs-charts" type="bubble" chartOptions={chartjsdata.Option8} chartSeries={chartjsdata.Data8} height='300px' />
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
ChartjsCharts.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ChartjsCharts;
