// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/mixed-chart/mixed-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import { Mixedareaoptions, Mixedareaseries, Mixedaxisoptions, Mixedaxisseries, Mixedcolumnoptions, Mixedcolumnseries, Mixedlineoptions, Mixedlineseries } from "../../../../shared/data/charts/apexcharts/mixedchartsdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const MixedChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Apex Mixed Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Mixed Charts" activepage="Apex Mixed Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xxl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Line & Column Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="mixed-linecolumn">
                                <Spkapexcharts chartOptions={Mixedlineoptions} chartSeries={Mixedlineseries} type="line" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xxl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Multiple Y-Axis Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="mixed-multiple-y">
                                <Spkapexcharts chartOptions={Mixedaxisoptions} chartSeries={Mixedaxisseries} type="line" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Line & Area Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="mixed-linearea">
                                <Spkapexcharts chartOptions={Mixedareaoptions} chartSeries={Mixedareaseries} type="line" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Line,Column & Area Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="mixed-all">
                                <Spkapexcharts chartOptions={Mixedcolumnoptions} chartSeries={Mixedcolumnseries} type="line" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
MixedChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default MixedChart;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/mixed-chart/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        CardTitle,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
    import {
        Mixedareaoptions,
        Mixedaxisoptions,
        Mixedcolumnoptions,
        Mixedlineoptions,
    } from "$lib/data/charts/apexcharts/mixedchartsdata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>MixedChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Mixed Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Mixed Charts"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xxl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Line & Column Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="mixed-linecolumn">
                    <Spkapexcharts
                        id="mixed-linecolumn"
                        options={Mixedlineoptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xxl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Multiple Y-Axis Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="mixed-multiple-y">
                    <Spkapexcharts
                        id="mixed-multiple-y"
                        options={Mixedaxisoptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Line & Area Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="mixed-linearea">
                    <Spkapexcharts
                        id="mixed-linearea"
                        options={Mixedareaoptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Line,Column & Area Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="mixed-all">
                    <Spkapexcharts
                        id="mixed-all"
                        options={Mixedcolumnoptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->
