// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/treemap-chart/+page.svelte

<script lang="ts">
          import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        CardTitle,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
    import { Treebasicoptions, Treecoloroptions, Treedisoptions, Treemultioptions } from "$lib/data/charts/apexcharts/treemapdata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>TreemapChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Treemap Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Treemap Charts"
/>
<!-- Page Header Close -->

 <!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Basic Treemap Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <div id="treemap-basic">
                                <Spkapexcharts options={Treebasicoptions} id="treemap-basic" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Multi Dimensional Treemap Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <div id="treemap-multi">
                                <Spkapexcharts options={Treemultioptions} id="treemap-multi" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Distributed Treemap Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <div id="treemap-distributed">
                                <Spkapexcharts options={Treedisoptions}  id="treemap-distributed" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Treemap with color ranges</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <div id="treemap-colorranges">
                                <Spkapexcharts options={Treecoloroptions} id="treemap-colorranges"  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/treemap-chart/treemap-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import { Treebasicoptions, Treebasicseries, Treecoloroptions, Treecolorseries, Treedisoptions, Treedisseries, Treemultioptions, Treemultiseries } from "../../../../shared/data/charts/apexcharts/treemapdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const TreemapChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Treemap Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Treemap Charts" activepage="Apex Treemap Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Treemap Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="treemap-basic">
                                <Spkapexcharts chartOptions={Treebasicoptions} chartSeries={Treebasicseries} type="treemap" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Multi Dimensional Treemap Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="treemap-multi">
                                <Spkapexcharts chartOptions={Treemultioptions} chartSeries={Treemultiseries} type="treemap" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Distributed Treemap Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="treemap-distributed">
                                <Spkapexcharts chartOptions={Treedisoptions} chartSeries={Treedisseries} type="treemap" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Treemap with color ranges</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="treemap-colorranges">
                                <Spkapexcharts chartOptions={Treecoloroptions} chartSeries={Treecolorseries} type="treemap" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
TreemapChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default TreemapChart;
