// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/dashboards/crypto/market-cap/+page.svelte
<script lang="ts">
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import SpkMarketcard from "$lib/@spk/dashboards-reusable/crypto-reusable/spk-marketcard.svelte";
    import SpkTablescomponent from "$lib/@spk/SpkTablescomponent.svelte";
    import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";
    import SpkDropdown from "$lib/@spk/uielements/Dropdown/SpkDropdown.svelte";
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import {
        MarketData,
        MartketTable,
        PortfolioData,
    } from "$lib/data/dashboards/crypto/marketdata";
    import { MarketcapDropdown } from "$lib/data/uielements/dropdowndata";
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Col,
        Image,
        Input,
        ListGroup,
        ListGroupItem,
        Pagination,
        PaginationItem,
        PaginationLink,
        Row,
    } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>MarketCap | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Market Cap"
    subTitle="Crypto"
    activepage="Dashboards"
    page="Market Cap"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    {#each MarketData as market}
        <Col xxl={3} xl={6} lg={12} class="">
            <SpkMarketcard cardClass="overflow-hidden" {market} />
        </Col>
    {/each}
    <Col xxl={3} xl={6} lg={12}>
        <Card class="custom-card overflow-hidden">
            <CardHeader class="justify-content-between">
                <div class="card-title">My Top Currencies</div>
                <div>
                    <a
                        href="#!"
                        class="fw-medium text-success fs-13 text-decoration-underline"
                        >View All</a
                    >
                </div>
            </CardHeader>
            <CardBody class="p-0">
                <ListGroup class="list-group list-group-flush custom-market-cap">
                    {#each PortfolioData as item}
                        <ListGroupItem>
                            <div
                                class="d-flex align-items-center justify-content-between flex-wrap gap-3"
                            >
                                <div class="d-flex align-items-center gap-2">
                                    <div>
                                        <span
                                            class="avatar avatar-sm p-1 bg-light"
                                        >
                                            <Image
                                                src={item.imgSrc}
                                                alt={item.name}
                                            />
                                        </span>
                                    </div>
                                    <div>
                                        <span class="d-block fw-medium"
                                            >{item.name}</span
                                        >
                                    </div>
                                </div>
                                <div>
                                    <span class="fw-medium d-block"
                                        >{item.quantity}</span
                                    >
                                </div>
                                <div class="text-end">
                                    <span class="fw-medium d-block"
                                        >{item.value}</span
                                    >
                                </div>
                            </div>
                        </ListGroupItem>
                    {/each}
                </ListGroup>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->

<!-- Start::row-2  -->

<Row>
    <Col xl={12}>
        <Card class="custom-card">
            <CardHeader class="justify-content-between">
                <div class="card-title">Crypto MarketCap</div>
                <div class="d-flex flex-wrap gap-2">
                    <div>
                        <Input
                            class="form-control-sm"
                            type="text"
                            placeholder="Search Here"
                            aria-label=".form-control-sm example"
                        />
                    </div>
                    <SpkDropdown
                        option={MarketcapDropdown}
                        ToggleClass="btn btn-primary btn-sm btn-wave waves-effect waves-light no-caret"
                        parent={`Sort By <i class="ri-arrow-down-s-line align-middle ms-1 d-inline-block"></i>`}
                        Caret={false}
                    />
                    <div>
                        <SpkButton
                            color=""
                            customClass="btn btn-light btn-sm btn-wave border"
                            >View All</SpkButton
                        >
                    </div>
                </div>
            </CardHeader>
            <CardBody class="p-0">
                <SpkTablescomponent
                    Responsive={true}
                        tableClass="text-nowrap"
                        header={[
                            { title: "" },
                            { title: "#", headerClassname: "fw-medium" },
                            { title: "Crypto Name" },
                            { title: "MarketCap" },
                            { title: "Price (USD)" },
                            { title: "1h Change" },
                            { title: "24h Change" },
                            { title: "Volume (24h)" },
                            { title: "Circulating Supply" },
                            { title: "last 1Week" },
                            { title: "Trade" },
                        ]}
                    >
                        {#each MartketTable as crypto}
                            <tr>
                                <td class="text-center">
                                    <!-- svelte-ignore a11y_consider_explicit_label -->
                                    <a href="#!">
                                        <i class="ri-star-line fs-16 text-muted"
                                        ></i>
                                    </a>
                                </td>
                                <td>{crypto.rank}</td>
                                <td>
                                    <div
                                        class="d-flex align-items-center gap-2"
                                    >
                                        <div class="lh-1">
                                            <span
                                                class="avatar avatar-xs avatar-rounded"
                                            >
                                                <Image
                                                    src={`../../images/crypto-currencies/square-color/${crypto.name}.svg`}
                                                    alt={crypto.name}
                                                />
                                            </span>
                                        </div>
                                        <div class="fw-medium">
                                            <a href="#!"
                                                >{`${crypto.name} (${crypto.symbol})`}</a
                                            >
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <span class="fw-medium"
                                        >{crypto.marketCap}</span
                                    >
                                </td>
                                <td>
                                    <span class="fw-medium">
                                        <a href="#!">{crypto.price}</a>
                                    </span>
                                </td>
                                <td>
                                    <span
                                        class={`fw-medium text-${crypto.priceChangeColor}`}
                                    >
                                        <i
                                            class={`ti ti-arrow-narrow-${crypto.priceIcon} fs-15 fw-medium`}
                                        ></i>
                                        {crypto.priceChange1h}
                                    </span>
                                </td>
                                <td>
                                    <span
                                        class={`fw-medium text-${crypto.priceChange24hColor}`}
                                    >
                                        <i
                                            class={`ti ti-arrow-narrow-${crypto.priceIcons} fs-15 fw-medium`}
                                        ></i>
                                        {crypto.priceChange24h}
                                    </span>
                                </td>
                                <td>
                                    <a href="#!">
                                        <span class="d-block fw-medium"
                                            >{crypto.volume}</span
                                        >
                                    </a>
                                </td>
                                <td>
                                    <a href="#!">
                                        <span class="fw-medium d-block"
                                            >{crypto.circulatingSupply}</span
                                        >
                                    </a>
                                </td>
                                <td>
                                    <div id={crypto.chartId}>
                                        <Spkapexcharts
                                            id={crypto.chartId}
                                            options={crypto.chartOptions}
                                        />
                                    </div>
                                </td>
                                <td>
                                    <SpkButton
                                        color=""
                                        customClass="btn btn-success-light btn-sm"
                                        >Trade</SpkButton
                                    >
                                </td>
                            </tr>
                        {/each}
                    </SpkTablescomponent>
            </CardBody>
            <CardFooter class="border-top-0 ">
                <nav aria-label="Page navigation" class="pagination-style-2">
                    <Pagination
                        class="mb-0 flex-wrap justify-content-end d-flex customPaginationPageBottom"
                    >
                        <PaginationItem>
                            <PaginationLink
                                href="#"
                                on:click={(e) => e.preventDefault()}
                                >Prev</PaginationLink
                            >
                        </PaginationItem>
                        <PaginationItem>
                            <PaginationLink
                                href="#"
                                on:click={(e) => e.preventDefault()}
                                >1</PaginationLink
                            >
                        </PaginationItem>
                        <PaginationItem active>
                            <PaginationLink
                                href="#"
                                on:click={(e) => e.preventDefault()}
                                >2</PaginationLink
                            >
                        </PaginationItem>
                        <PaginationItem>
                            <PaginationLink
                                href="#"
                                on:click={(e) => e.preventDefault()}
                                >...</PaginationLink
                            >
                        </PaginationItem>
                        <PaginationItem>
                            <PaginationLink
                                href="#"
                                on:click={(e) => e.preventDefault()}
                                >17</PaginationLink
                            >
                        </PaginationItem>
                        <PaginationItem>
                            <PaginationLink
                                href="#"
                                on:click={(e) => e.preventDefault()}
                                class="text-primary">Next</PaginationLink
                            >
                        </PaginationItem>
                    </Pagination>
                </nav>
            </CardFooter>
        </Card>
    </Col>
</Row>

<!-- End::row-2  -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/crypto/market-cap/market-cap.jsx

import React, { Fragment } from "react";
import { Card, Col, Dropdown, Form, Image, ListGroup, Pagination, Row } from "react-bootstrap";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { MarketData, MartketTable, PortfolioData } from "../../../../shared/data/dashboards/crypto/marketdata";
import SpkMarketCard from "../../../../shared/@spk-reusable-components/dashboards-reusable/crypto-reusable/spk-marketcard";
import SpkDropdown from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-dropdown";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import SpkTables from "../../../../shared/@spk-reusable-components/reusable-tables/spk-tables";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const Marketcap = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Dashboards-Market Cap" />

            <Pageheader title="Dashboards" subtitle="Crypto" currentpage="Marketcap" activepage="Marketcap" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                {MarketData.map((market, index) => (
                    <Col key={index} xxl={3} xl={6} lg={12} className="">
                        <SpkMarketCard cardClass="overflow-hidden" market={market} />
                    </Col>
                ))}
                <Col xxl={3} xl={6} lg={12}>
                    <Card className="custom-card overflow-hidden">
                        <Card.Header className="justify-content-between">
                            <div className="card-title">
                                My Top Currencies
                            </div>
                            <div>
                                <BaseLink href="#!" className="fw-medium text-success fs-13 text-decoration-underline">View All</BaseLink>
                            </div>
                        </Card.Header>
                        <Card.Body className="p-0">
                            <ListGroup className="list-group list-group-flush">
                                {PortfolioData.map((item, index) => (
                                    <ListGroup.Item key={index}>
                                        <div className="d-flex align-items-center justify-content-between flex-wrap gap-3">
                                            <div className="d-flex align-items-center gap-2">
                                                <div>
                                                    <span className="avatar avatar-sm p-1 bg-light">
                                                        <BaseImage src={item.imgSrc} alt={item.name} width={28} height={28} />
                                                    </span>
                                                </div>
                                                <div>
                                                    <span className="d-block fw-medium">{item.name}</span>
                                                </div>
                                            </div>
                                            <div>
                                                <span className="fw-medium d-block">{item.quantity}</span>
                                            </div>
                                            <div className="text-end">
                                                <span className="fw-medium d-block">{item.value}</span>
                                            </div>
                                        </div>
                                    </ListGroup.Item>
                                ))}
                            </ListGroup>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

            {/* <!-- Start::row-2  --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header className="justify-content-between">
                            <div className="card-title">
                                Crypto MarketCap
                            </div>
                            <div className="d-flex flex-wrap gap-2 align-items-center">
                                <div>
                                    <Form.Control className="form-control-sm" type="text" placeholder="Search Here" aria-label=".form-control-sm example" />
                                </div>
                                <SpkDropdown Customtoggleclass="btn btn-primary btn-sm btn-wave waves-effect waves-light no-caret" Toggletext="Sort By" Arrowicon={true}>
                                    <li><Dropdown.Item >Market Cap</Dropdown.Item></li>
                                    <li><Dropdown.Item >Price</Dropdown.Item></li>
                                    <li><Dropdown.Item >Trading Volume</Dropdown.Item></li>
                                    <li><Dropdown.Item >Price Change (24h)</Dropdown.Item></li>
                                    <li><Dropdown.Item >Rank</Dropdown.Item></li>
                                    <li><Dropdown.Item >A - Z</Dropdown.Item></li>
                                    <li><Dropdown.Item >All-Time High (ATH)</Dropdown.Item></li>
                                </SpkDropdown>
                                <div>
                                    <SpkButton Buttonvariant="" Customclass="btn btn-light btn-sm btn-wave border">View All</SpkButton>
                                </div>
                            </div>
                        </Card.Header>
                        <Card.Body className="p-0">
                            <div className="table-responsive">
                                <SpkTables tableClass="text-nowrap" header={[{ title: "" }, { title: '#', headerClassname: 'fw-medium' }, { title: 'Crypto Name' }, { title: 'MarketCap' }, { title: "Price (USD)" }, { title: '1h Change' }, { title: '24h Change' }, { title: 'Volume (24h)' }, { title: 'Circulating Supply' }, { title: 'last 1Week' }, { title: 'Trade' }]}>
                                    {MartketTable.map((crypto) => (
                                        <tr key={crypto.rank}>
                                            <td className="text-center">
                                                <BaseLink href="#!">
                                                    <i className="ri-star-line fs-16 text-muted"></i>
                                                </BaseLink>
                                            </td>
                                            <td>{crypto.rank}</td>
                                            <td>
                                                <div className="d-flex align-items-center gap-2">
                                                    <div className="lh-1">
                                                        <span className="avatar avatar-xs avatar-rounded">
                                                            <BaseImage src={`${crypto.imgsrc}`} alt={crypto.name} />
                                                        </span>
                                                    </div>
                                                    <div className="fw-medium">
                                                        <BaseLink href="#!">{`${crypto.name} (${crypto.symbol})`}</BaseLink>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <span className="fw-medium">{crypto.marketCap}</span>
                                            </td>
                                            <td>
                                                <span className="fw-medium">
                                                    <BaseLink href="#!">{crypto.price}</BaseLink>
                                                </span>
                                            </td>
                                            <td>
                                                <span className={`fw-medium text-${crypto.priceChangeColor}`}>
                                                    <i className={`ti ti-arrow-narrow-${crypto.priceIcon} fs-15 fw-medium`}></i>
                                                    {crypto.priceChange1h}
                                                </span>
                                            </td>
                                            <td>
                                                <span className={`fw-medium text-${crypto.priceChange24hColor}`}>
                                                    <i className={`ti ti-arrow-narrow-${crypto.priceIcons} fs-15 fw-medium`}></i>
                                                    {crypto.priceChange24h}
                                                </span>
                                            </td>
                                            <td>
                                                <BaseLink href="#!">
                                                    <span className="d-block fw-medium">{crypto.volume}</span>
                                                </BaseLink>
                                            </td>
                                            <td>
                                                <BaseLink href="#!">
                                                    <span className="fw-medium d-block">{crypto.circulatingSupply}</span>
                                                </BaseLink>
                                            </td>
                                            <td>
                                                <div id={crypto.chartId}>
                                                    <Spkapexcharts height={30} width={120} type={"line"} chartOptions={crypto.chartOptions} chartSeries={crypto.chartSeries} />
                                                </div>
                                            </td>
                                            <td>
                                                <SpkButton Buttonvariant="" Customclass="btn btn-success-light btn-sm">Trade</SpkButton>
                                            </td>
                                        </tr>
                                    ))}
                                </SpkTables>
                            </div>
                        </Card.Body>
                        <Card.Footer className="">
                            <nav aria-label="Page navigation" className="pagination-style-2">
                                <Pagination className="mb-0 flex-wrap justify-content-end">
                                    <Pagination.Prev disabled>Prev</Pagination.Prev>
                                    <Pagination.Item active>{1}</Pagination.Item>
                                    <Pagination.Item>{2}</Pagination.Item>
                                    <Pagination.Item><i className="bi bi-three-dots"></i></Pagination.Item>
                                    <Pagination.Item>{17}</Pagination.Item>
                                    <Pagination.Next className="text-primary">Next</Pagination.Next>
                                </Pagination>
                            </nav>
                        </Card.Footer>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End::row-2  --> */}

        </Fragment>
    )
};

Marketcap.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Marketcap;
