// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/funnel-chart/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        CardTitle,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
    import {
        Funneloptions,
        Pyramidoptions,
    } from "$lib/data/charts/apexcharts/funneldata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>FunnelChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Funnel Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Funnel Charts"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Funnel Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="funnel-chart">
                    <Spkapexcharts options={Funneloptions} id="funnel-chart" />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Pyramid Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="pyramid-chart">
                    <Spkapexcharts
                        options={Pyramidoptions}
                        id="pyramid-chart"
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/funnel-chart/funnel-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import { Funneloptions, Funnelseries, Pyramidoptions, Pyramidseries } from "../../../../shared/data/charts/apexcharts/funnelchartdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";

const FunnelChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Apex Funnel Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Funnel Charts" activepage="Apex Funnel Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Funnel Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="funnel-chart">
                                <Spkapexcharts chartOptions={Funneloptions} chartSeries={Funnelseries} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Pyramid Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="pyramid-chart">
                                <Spkapexcharts chartOptions={Pyramidoptions} chartSeries={Pyramidseries} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
FunnelChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default FunnelChart;
