// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/pages/forms/quill-editor.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import { Col, Row } from "@sveltestrap/sveltestrap";
    import { Editor } from "@tadashi/svelte-editor-quill";
    import Editor1 from "@/view/editor/Editor1.svelte";
    import "quill/dist/quill.snow.css";
    import SpkBasicCard from "@/shared/@spk/SpkBasicCard.svelte";

    const options = {
    theme: "snow",
  };

  // initial HTML content
  let data = `<h4><b class="ql-size-large">Quill Snow</b> is a free, open source <a href="https://github.com/quilljs/quill/" target="_blank">Quill Editor</a> built for the modern web. With its <a href="https://quilljs.com/docs/modules/" target="_blank">modular architecture</a> and expressive API, it is completely customizable to fit any need.</h4>
              <p><br></p>
              <ol>
                  <li class="ql-size-normal">Write text select and edit with multiple options.</li>
                  <li class="">This is quill snow editor.</li>
                  <li class="">Easy to customize and flexible.</li>
              </ol>
              <p><br></p>
              <h4>Quill officially supports a standard toolbar theme <a href="https://github.com/quilljs/quill/" target="_blank">"Snow"</a> and a floating tooltip theme <a href="https://github.com/quilljs/quill/" target="_blank">"Bubble"</a></h4>`;

  let text = "";
  let html = data;

  const onTextChange = (event) => {
    const detail = event?.detail ?? {};
    text = detail.text || "";
    html = detail.html || "";
  };
</script>

<!-- Page Title -->
<svelte:head>
    <title>SunEditor | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Quill Editor"
    activepage="Form Editors"
    page="Quill Editor"
/>
<!-- Page Header Close -->

<!-- Start:: row-1 -->
<Row>
    <Col xl={12}>
        <SpkBasicCard
            cardProps="custom-card"
            headerTitle="  Svelte Editor Quill"
        >
            <div slot="customheader"></div>
            <div slot="content">
                <div id="editor">
                    <Editor {options} bind:value={data} on:text-change={onTextChange} >
                        {@html data}
                    </Editor>
                </div>
            </div>
        </SpkBasicCard>
    </Col>
</Row>
<!-- End:: row-1 -->

<!-- Start:: row-2 -->
<Row>
    <Col xl={12}>
        <SpkBasicCard cardProps="custom-card" headerTitle="Cl-editor">
            <div slot="customheader"></div>
            <div slot="content">
                <div id="editor1"><Editor1 /></div>
            </div>
        </SpkBasicCard>
    </Col>
</Row>
<!-- End:: row-2 -->

// Dashboard Template/vyzor-angular/final/src/app/components/pages/form/quill-editor/quill-editor.ts
import { Component } from '@angular/core';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { NgxEditorModule } from 'ngx-editor';

import { AngularEditorModule } from '@wfpena/angular-wysiwyg';
import { QuillModule } from 'ngx-quill';
import { SharedModule } from '../../../../shared/shared.module';
@Component({
  selector: 'app-quill-editor',
  imports: [SharedModule,QuillModule,AngularEditorModule,NgxEditorModule,FormsModule,ReactiveFormsModule],
  templateUrl: './quill-editor.html',
  styleUrl: './quill-editor.scss'
})
export class QuillEditor {
  modules = {
    //formula: true,
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'],
      ['blockquote', 'code-block'],

      [{ 'header': 1 }, { 'header': 2 }],
      [{ 'list': 'ordered' }, { 'list': 'bullet' }],
      [{ 'script': 'sub' }, { 'script': 'super' }],
      [{ 'indent': '-1' }, { 'indent': '+1' }],
      [{ 'direction': 'rtl' }],

      [{ 'size': ['small', false, 'large', 'huge'] }],
      [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

      [{ 'color': [] }, { 'background': [] }],
      [{ 'font': [] }],
      [{ 'align': [] }],

      ['clean'],

      ['link', 'image', 'video']
    ]
  };
  modules1 = {
    //formula: true,
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'],
      ['blockquote', 'code-block'],


    ]
  };


  editorContent = `
    <h4><b class="ql-size-large">Quill Snow</b> is a free, open source <a href="https://github.com/quilljs/quill/" target="_blank">Quill Editor</a> built for the modern web. With its <a href="https://quilljs.com/docs/modules/" target="_blank">modular architecture</a> and expressive API, it is completely customizable to fit any need.</h4>
    <p><br></p>
    <ol>
      <li class="ql-size-normal">Write text select and edit with multiple options.</li>
      <li>This is quill snow editor.</li>
      <li>Easy to customize and flexible.</li>
    </ol>
    <p><br></p>
    <h4>Quill officially supports a standard toolbar theme <a href="https://github.com/quilljs/quill/" target="_blank">"Snow"</a> and a floating tooltip theme <a href="https://github.com/quilljs/quill/" target="_blank">"Bubble"</a></h4>
  `;

  placeholder = `    <h4><b class="ql-size-large">Quill Bubble</b> is a free, open source <a href="https://github.com/quilljs/quill/" target="_blank">Quill Editor</a> built for the modern web. With its <a href="https://quilljs.com/docs/modules/" target="_blank">modular architecture</a> and expressive API, it is completely customizable to fit any need.</h4>
                    <p><br></p>
                    <ol>
                        <li class="ql-size-normal">Write text select and edit with multiple options.</li>
                        <li class="">This is quill bubble editor.</li>
                        <li class="">Easy to customize and flexible.</li>
                    </ol>
                    <p><br></p>
                    <h4>Quill officially supports a standard toolbar theme <a href="https://github.com/quilljs/quill/" target="_blank">"Snow"</a> and a floating tooltip theme <a href="https://github.com/quilljs/quill/" target="_blank">"Bubble"</a></h4>
               `;

}
