// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/pages/blog/blog/+page.svelte
<script lang="ts">
    import { base } from "$app/paths";
    import SpkBlogcard from "$lib/@spk/reusable-pages/blog/spk-blogcard.svelte";
    import SpkPopularcard from "$lib/@spk/reusable-pages/blog/spk-popularcard.svelte";
    import SpkBadge from "$lib/@spk/uielements/badge/SpkBadge.svelte";
    import Spkimageoverlaycard from "$lib/@spk/uielements/reusable-cards/spkimageoverlaycard.svelte";
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import {
        BlogCards,
        BlogCategoryCards,
        BlogPosts,
        PopularBlogs,
        TopStories,
    } from "$lib/data/pages/blog/blogdata";
    import {
        Card,
        CardBody,
        CardHeader,
        Col,
        Image,
        Row,
    } from "@sveltestrap/sveltestrap";
    const basePath = base;
</script>

<!-- Page Title -->
<svelte:head>
    <title>Blog | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader homepage="Blog" subTitle="Blog" activepage="Pages" page="Blog" />
<!-- Page Header Close -->

<!-- Start:: row-1 -->
<!-- svelte-ignore a11y_consider_explicit_label -->
<Row>
    <Col xxl={5}>
        <Card class="custom-card overlay-card blog-card">
            <a href={`${basePath}/pages/blog/blog-details`} class="stretched-link"></a>
            <img
                src="../../images/media/blog/1.jpg"
                class="card-img"
                alt="..."
            />
            <div
                class="card-img-overlay d-flex flex-column p-0 over-content-bottom"
            >
                <CardBody class="text-fixed-white">
                    <div class="text-fixed-white fs-14 mb-2">FEATURED POST</div>
                    <div class="card-text mb-2 fs-2 fw-semibold lh-sm">
                        Exploring the Future of Artificial Intelligence
                    </div>
                </CardBody>
            </div>
        </Card>
    </Col>
    <Col xxl={4}>
        <Row>
            {#each BlogPosts as idx}
                <div class="col-xl-6">
                    <SpkBlogcard blog={idx} />
                </div>
            {/each}
        </Row>
    </Col>
    <Col xxl={3}>
        <Card class="custom-card">
            <div class="card-header justify-content-between">
                <div class="card-title">Top Stories</div>
                <a href="#!" class="fs-13 text-muted text-decoration-underline"
                    >View All <i class="ti ti-arrow-narrow-right"></i></a
                >
            </div>
            <CardBody>
                <ul class="list-unstyled blog-top-stories-list">
                    {#each TopStories as story}
                        <li>
                            <a
                                href={`${basePath}${story.link}`}
                                class="stretched-link"
                            ></a>
                            <div class="d-flex align-items-center gap-3">
                                <div class="lh-1">
                                    <span class="avatar avatar-xl">
                                        <Image
                                            src={story.image}
                                            alt={story.title}
                                        />
                                    </span>
                                </div>
                                <div class="flex-fill">
                                    <SpkBadge
                                        Color=""
                                        CustomClass={`${story.badgeClass}`}
                                        >{story.badgeText}</SpkBadge
                                    >
                                    <h6
                                        class="fw-semibold mb-0 lh-base top-stories-title mt-1"
                                    >
                                        {story.title}
                                    </h6>
                                </div>
                            </div>
                        </li>
                    {/each}
                </ul>
            </CardBody>
        </Card>
    </Col>
</Row>

<!-- End:: row-1 -->

<!-- Start:: row-2 -->

<Col xl={12}>
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h5 class="mb-0 fw-semibold">Popular Topics</h5>
        <p class="mb-0 fw-semibold">
            <a href="#!" class="text-primary"><u>View All</u></a>
        </p>
    </div>
    <Row class="">
        {#each BlogCategoryCards as idx}
            <SpkPopularcard blog={idx} />
        {/each}
    </Row>
</Col>

<!-- End:: row-2 -->

<!-- Start:: row-3 -->

<Row>
    <Col xxl={9}>
        <Row>
            {#each BlogCards as idx}
                <Col xl={3} lg={4} md={6} class="">
                    <SpkBlogcard blog={idx} />
                </Col>
            {/each}
        </Row>
    </Col>
    <Col xxl={3}>
        <Card class="custom-card overflow-hidden">
            <CardHeader class="justify-content-between">
                <div class="card-title">Popular Blogs</div>
                <a href="#!" class="fs-13 text-muted text-decoration-underline"
                    >View All <i class="ti ti-arrow-narrow-right"></i></a
                >
            </CardHeader>
            <CardBody class="p-0">
                <ul class="list-group list-group-flush">
                    {#each PopularBlogs as blog}
                        <li class="list-group-item">
                            <!-- svelte-ignore a11y_consider_explicit_label -->
                            <a
                                href={`${basePath}${blog.link}`}
                                class="stretched-link"
                            ></a>
                            <div class="d-flex align-items-center gap-3">
                                <div class="lh-1">
                                    <span class="avatar avatar-xl">
                                        <Image
                                            width={64}
                                            height={64}
                                            src={blog.image}
                                            alt={blog.title}
                                        />
                                    </span>
                                </div>
                                <div class="flex-fill">
                                    <div
                                        class="popular-blogs-title fw-semibold mb-1"
                                    >
                                        {blog.title}
                                    </div>
                                    <span
                                        class="d-block text-muted fs-13 fw-normal"
                                        >{blog.dateViews}</span
                                    >
                                </div>
                            </div>
                        </li>
                    {/each}
                </ul>
            </CardBody>
        </Card>
    </Col>
</Row>

<!-- End:: row-3 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/blog/blog/blog.jsx

import React, { Fragment } from "react";
import { Card, Col, Image, Row } from "react-bootstrap";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import Spkimageoverlaycard from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/reusable-cards/spkimageoverlaycard";
import { BlogCards, BlogCategoryCards, BlogPosts, PopularBlogs, TopStories } from "../../../../shared/data/pages/blog/blogdata";
import SpkBlogCard from "../../../../shared/@spk-reusable-components/reusable-pages/blog/spk-blogcard";
import { Head, Link } from "@inertiajs/react";
import SpkBadge from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import SpkPopularCard from "../../../../shared/@spk-reusable-components/reusable-pages/blog/spk-popularcard";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const Blog = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Blog-Blog" />

            <Pageheader title="Pages" subtitle="Blog" currentpage="Blog" activepage="Blog" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xxl={5}>
                    <Spkimageoverlaycard CardHeader={false} stretchedLink={true} CustomClass="overlay-card blog-card" Custombodyclass="text-fixed-white" Imgsrc="/build/assets/images/media/blog/1.jpg" Customimgclass="card-img" Customfooterclass="text-fixed-white" CardFooter={false}>
                        <div className="card-text text-fixed-white">
                            <div className="card-img-overlay d-flex flex-column p-0 over-content-bottom">
                                <div className="card-body text-fixed-white">
                                    <div className="text-fixed-white fs-14 mb-2">
                                        FEATURED POST
                                    </div>
                                    <div className="card-text mb-2 fs-2 fw-semibold lh-sm">Exploring the Future of Artificial Intelligence</div>
                                </div>
                            </div>
                        </div>
                    </Spkimageoverlaycard>
                </Col>
                <Col xxl={4}>
                    <Row>
                        {BlogPosts.map((idx, index) => (
                            <div className="col-xl-6" key={index}>
                                <SpkBlogCard blog={idx} />
                            </div>
                        ))}
                    </Row>
                </Col>
                <Col xxl={3}>
                    <Card className="custom-card">
                        <div className="card-header justify-content-between">
                            <div className="card-title">
                                Top Stories
                            </div>
                            <BaseLink href="#!" className="fs-13 text-muted text-decoration-underline">View All <i className="ti ti-arrow-narrow-right"></i></BaseLink>
                        </div>
                        <Card.Body>
                            <ul className="list-unstyled blog-top-stories-list">
                                {TopStories.map((story, index) => (
                                    <li key={index}>
                                        <Link href={`${__APP_BASE_PATH__}/pages/blog/blog-details/`} className="stretched-link"></Link>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="lh-1">
                                                <span className="avatar avatar-xl">
                                                    <BaseImage src={story.image} alt={story.title} />
                                                </span>
                                            </div>
                                            <div className="flex-fill">
                                                <SpkBadge variant="" Customclass={`${story.badgeClass}`}>{story.badgeText}</SpkBadge>
                                                <h6 className="fw-semibold mb-0 lh-base top-stories-title mt-1">{story.title}</h6>
                                            </div>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-2 --> */}

            <Col xl={12}>
                <div className="d-flex justify-content-between align-items-center mb-3">
                    <h5 className="mb-0 fw-semibold">Popular Topics</h5>
                    <p className="mb-0 fw-semibold">
                        <BaseLink href="#!" className="text-primary"><u>View All</u></BaseLink>
                    </p>
                </div>
                <Row className="">
                    {BlogCategoryCards.map((idx, index) => (
                        <SpkPopularCard key={index} blog={idx} />
                    ))}
                </Row>

            </Col>

            {/* <!-- End:: row-2 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xxl={9}>
                    <Row className="row-deck">
                        {BlogCards.map((idx, index) => (
                            <Col xl={3} lg={4} md={6} className="" key={index}>
                                <SpkBlogCard blog={idx} />
                            </Col>
                        ))}
                    </Row>
                </Col>
                <Col xxl={3}>
                    <Card className="custom-card overflow-hidden">
                        <Card.Header className="justify-content-between">
                            <div className="card-title">
                                Popular Blogs
                            </div>
                            <BaseLink href="#!" className="fs-13 text-muted text-decoration-underline">View All <i className="ti ti-arrow-narrow-right"></i></BaseLink>
                        </Card.Header>
                        <Card.Body className="p-0">
                            <ul className="list-group list-group-flush list-popular-blogs ">
                                {PopularBlogs.map((blog, index) => (
                                    <li className="list-group-item" key={index}>
                                        <Link href={`${__APP_BASE_PATH__}/pages/blog/blog-details`} className="stretched-link"></Link>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="lh-1">
                                                <span className="avatar avatar-xl">
                                                    <BaseImage src={blog.image} alt={blog.title} />
                                                </span>
                                            </div>
                                            <div className="flex-fill">
                                                <div className="popular-blogs-title fw-semibold mb-1">{blog.title}</div>
                                                <span className="d-block text-muted fs-13 fw-normal">{blog.dateViews}</span>
                                            </div>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-3 --> */}

        </Fragment>
    )
};

// Assign layout
Blog.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Blog;
