// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/authentication/sign-up/cover/cover.jsx

import SpkButton from "../../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import React, { Fragment, useState } from "react";
import { Card, Col, Form, Row } from "react-bootstrap";
import { Head, Link, router } from "@inertiajs/react";
import { toast, ToastContainer } from "react-toastify";
import AuthenticationLayout from "@/Layouts/authenticationlayout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const Cover = () => {

    const [values, setValues] = useState({
        email: 'tomphillip21@gmail.com',
        password: '12345678',
        showPassword: false
    });

    const [errors, setErrors] = useState({});

    const validate = () => {
        const newErrors = {};

        // Email validation
        if (!values.email) {
            newErrors.email = "Email is required.";
        } else if (!/\S+@\S+\.\S+/.test(values.email)) {
            newErrors.email = "Invalid email format.";
        }

        // Password validation
        if (!values.password) {
            newErrors.password = "Password is required.";
        } else if (values.password.length < 6) {
            newErrors.password = "Password must be at least 6 characters.";
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        if (validate()) {
            router.get(`${__APP_BASE_PATH__}/dashboards/sales`);
            toast.success('Login successful', {
                position: 'top-right',
                autoClose: 1500,
                hideProgressBar: false,
                closeOnClick: true,
                pauseOnHover: true,
                draggable: true,
            });
            // Handle form submission logic here
        }
    };

    return (

        <Fragment>
            <Head title="Signup-Cover" />
            <Row className="authentication authentication-cover-main mx-0">
                <Col xxl={9} xl={9}>
                    <Row className="justify-content-center align-items-center h-100">
                        <Col xxl={4} xl={5} lg={6} md={6} sm={8} className="col-12">
                            <Card className="custom-card border-0  shadow-none my-4">
                                <Card.Body className="p-5">
                                    <div>
                                        <h4 className="mb-1 fw-semibold">Create your account</h4>
                                        <p className="mb-4 text-muted fw-normal text-nowrap">Please enter valid credentials</p>
                                    </div>
                                    <Form onSubmit={handleSubmit}>
                                        <Row className="gy-3">
                                            <Col xl={12}>
                                                <Form.Label htmlFor="signup-username" className="text-default">User Name</Form.Label>
                                                <Form.Control type="text" className="" id="signup-username" placeholder="Enter User Name" defaultValue="Tom Phillip" />
                                            </Col>
                                            <Col xl={12}>
                                                <Form.Label htmlFor="signin-email" className="text-default">Email</Form.Label>
                                                <Form.Control
                                                    type="email"
                                                    className="form-control "
                                                    id="signup-firstname"
                                                    placeholder="Enter Email ID"
                                                    value={values.email}
                                                    onChange={(e) => setValues({ ...values, email: e.target.value })}
                                                    isInvalid={!!errors.email}
                                                />
                                                <Form.Control.Feedback type="invalid">{errors.email}</Form.Control.Feedback>
                                            </Col>
                                            <Col xl={12} className="mb-2">
                                                <Form.Label htmlFor="signin-password" className="text-default d-block">Password</Form.Label>
                                                <div className="position-relative">
                                                    <Form.Control
                                                        type={values.showPassword ? "text" : "password"}
                                                        className="form-control "
                                                        id="signup-password"
                                                        placeholder="Password"
                                                        value={values.password}
                                                        onChange={(e) => setValues({ ...values, password: e.target.value })}
                                                        isInvalid={!!errors.password}
                                                    />
                                                    <BaseLink href="#!" className="show-password-button text-muted"
                                                        onClick={() => setValues((prev) => ({ ...prev, showPassword: !prev.showPassword }))}>
                                                        {values.showPassword ? (
                                                            <i className="ri-eye-line align-middle"></i>
                                                        ) : (
                                                            <i className="ri-eye-off-line align-middle"></i>
                                                        )}
                                                    </BaseLink>
                                                    <Form.Control.Feedback type="invalid">{errors.password}</Form.Control.Feedback>   </div>
                                            </Col>
                                        </Row>
                                        <div className="d-grid mt-3">
                                            <SpkButton Buttontype="submit" Customclass="btn btn-primary">Sign In</SpkButton>
                                        </div>
                                    </Form>
                                    <div className="text-center my-3 authentication-barrier">
                                        <span className="op-4 fs-13">OR</span>
                                    </div>
                                    <div className="d-grid mb-3">
                                        <SpkButton Customclass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill mb-3">
                                            <span className="avatar avatar-xs">
                                                <BaseImage src="/build/assets/images/media/apps/google.png" alt="" />
                                            </span>
                                            <span className="lh-1 ms-2 fs-13 text-default fw-medium">Signup with Google</span>
                                        </SpkButton>
                                        <SpkButton Customclass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill">
                                            <span className="avatar avatar-xs">
                                                <BaseImage src="/build/assets/images/media/apps/facebook.png" alt="" />
                                            </span>
                                            <span className="lh-1 ms-2 fs-13 text-default fw-medium">Signup with Facebook</span>
                                        </SpkButton>
                                    </div>
                                    <div className="text-center mt-3 fw-medium">
                                        Already have a account? <Link href={`${__APP_BASE_PATH__}/pages/authentication/sign-in/basic/`} className="text-primary">Sign In</Link>
                                    </div>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>
                </Col>
                <Col xxl={3} xl={3} lg={12} className="d-xl-block d-none px-0">
                    <div className="authentication-cover overflow-hidden">
                        <div className="authentication-cover-logo">
                            <Link href={`${__APP_BASE_PATH__}/dashboards/sales`}>
                                <BaseImage src="/build/assets/images/brand-logos/toggle-logo.png" alt="logo" className="desktop-dark" />
                            </Link>
                        </div>
                        <div className="authentication-cover-background">
                            <BaseImage src="/build/assets/images/media/backgrounds/9.png" alt="" />
                        </div>
                        <div className="authentication-cover-content">
                            <div className="p-5">
                                <h3 className="fw-semibold lh-base">Welcome to Dashboard</h3>
                                <p className="mb-0 text-muted fw-medium">Manage your website and content with ease using our powerful admin tools.</p>
                            </div>
                            <div>
                                <BaseImage src="/build/assets/images/media/media-72.png" alt="" className="img-fluid" />
                            </div>
                        </div>
                    </div>
                </Col>
            </Row>
            <ToastContainer />
        </Fragment>
    )
};
// Assign layout
Cover.layout = (page) => <AuthenticationLayout>{page}</AuthenticationLayout>;
export default Cover;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/pages/authentication/sign-up/cover.svelte
<script context="module">
    import Authlayout from "@/layouts/Authlayout.svelte";
    export const layout = Authlayout;
</script>

<script>
    import { onMount } from "svelte";
    import {
        Card,
        CardBody,
        Col,
        Form,
        Image,
        Input,
        Label,
        Row,
    } from "@sveltestrap/sveltestrap";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import { Inertia } from "@inertiajs/inertia";
    import { Link } from "@inertiajs/svelte";
    const basePath = __BASE_PATH__;
    let values = {
        email: "tomphillip21@gmail.com",
        password: "12345678",
        showPassword: false,
    };

    let errors = {};

    const validate = () => {
        const newErrors = {};

        // Email validation
        if (!values.email) {
            newErrors.email = "Email is required.";
        } else if (!/\S+@\S+\.\S+/.test(values.email)) {
            newErrors.email = "Invalid email format.";
        }

        // Password validation
        if (!values.password) {
            newErrors.password = "Password is required.";
        } else if (values.password.length < 6) {
            newErrors.password = "Password must be at least 6 characters.";
        }

        errors = newErrors;
        return Object.keys(newErrors).length === 0;
    };

    const togglePassword = () => {
        values.showPassword = !values.showPassword;
    };

    let matched;
    const handleSubmit = (e) => {
        e.preventDefault();
        if (validate()) {
            matched = "Save Password successful";
            Inertia.visit(`${basePath}/`);
        }
    };

    const setBodyClass = (action) => {
        if (action === "add") {
            document.body.classList.add("bg-white");
        } else {
            document.body.classList.remove("bg-white");
        }
    };

    onMount(() => {
        if (localStorage.getItem("visited") === "true") {
            setBodyClass("add");
        } else {
            setBodyClass("add");
            localStorage.setItem("visited", "true");
        }

        const handleBeforeUnload = () => {
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };

        window.addEventListener("beforeunload", handleBeforeUnload);

        return () => {
            window.removeEventListener("beforeunload", handleBeforeUnload);
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };
    });
</script>

<!-- Page Title -->
<svelte:head>
    <title>Signup-Cover | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<Row class="authentication authentication-cover-main mx-0">
    <Col xxl={9} xl={9}>
        <Row class="justify-content-center align-items-center h-100">
            <Col xxl={4} xl={5} lg={6} md={6} sm={8} class="col-12">
                <Card class="custom-card border-0  shadow-none my-4">
                    <CardBody class="p-5">
                        <div>
                            <h4 class="mb-1 fw-semibold">
                                Create your account
                            </h4>
                            <p class="mb-4 text-muted fw-normal">
                                Please enter valid credentials
                            </p>
                        </div>
                        <Form on:submit={handleSubmit}>
                            <Row class="gy-3">
                                <Col xl={12}>
                                    <Label
                                        for="signup-username"
                                        class="text-default">User Name</Label
                                    >
                                    <Input
                                        type="text"
                                        class=""
                                        id="signup-username"
                                        placeholder="Enter User Name"
                                        defaultValue="Tom Phillip"
                                    />
                                </Col>
                                <Col xl={12}>
                                    <Label
                                        for="signin-email"
                                        class="text-default">Email</Label
                                    >
                                    <Input
                                        type="email"
                                        class="form-control "
                                        id="signup-firstname"
                                        placeholder="Enter Email ID"
                                        bind:value={values.email}
                                    />
                                    {#if errors.email}
                                        <p class="text-danger text-sm">
                                            {errors.email}
                                        </p>
                                    {/if}
                                </Col>
                                <Col xl={12} class="mb-2">
                                    <Label
                                        for="signin-password"
                                        class="text-default d-block"
                                        >Password</Label
                                    >
                                    <div class="position-relative">
                                        <Input
                                            type={values.showPassword
                                                ? "text"
                                                : "password"}
                                            class="form-control "
                                            id="signup-password"
                                            placeholder="Password"
                                            bind:value={values.password}
                                        />
                                        <a
                                            href="#!"
                                            class="show-password-button text-muted"
                                            on:click={togglePassword}
                                        >
                                            {#if values.showPassword}
                                                <i
                                                    class="ri-eye-line align-middle"
                                                ></i>
                                            {:else}
                                                <i
                                                    class="ri-eye-off-line align-middle"
                                                ></i>
                                            {/if}
                                        </a>
                                        {#if errors.password}
                                            <p class="text-danger text-sm">
                                                {errors.password}
                                            </p>
                                        {/if}

                                        {#if matched}
                                            <p class="text-success text-sm">
                                                {matched}
                                            </p>
                                        {/if}
                                    </div>
                                </Col>
                            </Row>
                            <div class="d-grid mt-3">
                                <SpkButton
                                    buttontype="submit"
                                    customClass="btn btn-primary"
                                    >Sign Up</SpkButton
                                >
                            </div>
                        </Form>
                        <div class="text-center my-3 authentication-barrier">
                            <span class="op-4 fs-13">OR</span>
                        </div>
                        <div class="d-grid mb-3">
                            <SpkButton
                                customClass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill mb-3"
                            >
                                <span class="avatar avatar-xs">
                                    <Image
                                        src={`${basePath}/images/media/apps/google.png`}
                                        alt=""
                                    />
                                </span>
                                <span
                                    class="lh-1 ms-2 fs-13 text-default fw-medium"
                                    >Signup with Google</span
                                >
                            </SpkButton>
                            <SpkButton
                                customClass="btn btn-white btn-w-lg border d-flex align-items-center justify-content-center flex-fill"
                            >
                                <span class="avatar avatar-xs">
                                    <Image
                                        src={`${basePath}/images/media/apps/facebook.png`}
                                        alt=""
                                    />
                                </span>
                                <span
                                    class="lh-1 ms-2 fs-13 text-default fw-medium"
                                    >Signup with Facebook</span
                                >
                            </SpkButton>
                        </div>
                        <div class="text-center mt-3 fw-medium">
                            Already have a account? <Link
                                href={`${basePath}/pages/authentication/sign-in/basic/`}
                                class="text-primary">Sign In</Link
                            >
                        </div>
                    </CardBody>
                </Card>
            </Col>
        </Row>
    </Col>
    <Col xxl={3} xl={3} lg={12} class="d-xl-block d-none px-0">
        <div class="authentication-cover overflow-hidden">
            <div class="authentication-cover-logo">
                <Link href={`${basePath}/dashboards/sales`}>
                    <Image
                        src={`${basePath}/images/brand-logos/toggle-logo.png`}
                        alt="logo"
                        class="desktop-dark"
                    />
                </Link>
            </div>
            <div class="authentication-cover-background">
                <Image
                    src={`${basePath}/images/media/backgrounds/9.png`}
                    alt=""
                />
            </div>
            <div class="authentication-cover-content">
                <div class="p-5">
                    <h3 class="fw-semibold lh-base">Welcome to Dashboard</h3>
                    <p class="mb-0 text-muted fw-medium">
                        Manage your website and content with ease using our
                        powerful admin tools.
                    </p>
                </div>
                <div>
                    <Image
                        src={`${basePath}/images/media/media-72.png`}
                        alt=""
                        class="img-fluid"
                    />
                </div>
            </div>
        </div>
    </Col>
</Row>
