// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/general/ui-elements/button-group.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import {
        btngroup1,
        btngroup2,
        btngroup3,
        btngroup4,
        btngroup5,
        btngroup6,
        btngroup7,
        btngroup8,
        btngroup9,
        btngroup10,
        btngroup11,
        databutton16,
    } from "@/shared/data/prism-code/uielementsprim";
    import ShowCode from "@/components/showcode/ShowCode.svelte";
    import {
        ButtonGroup,
        Col,
        Row,
        InputGroup,
        InputGroupText,
        Input,
        ButtonToolbar,
        Dropdown,
        DropdownToggle,
        DropdownMenu,
        DropdownItem,
    } from "@sveltestrap/sveltestrap";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import { SocialIconButtons } from "@/shared/data/uielements/buttonsdata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>ButtonGroup | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<Pageheader
    homepage="Button Group"
    activepage="UI Elements"
    page="Buttongroup"
/>
<!--ROW-START-->
<Row>
    <Col xl={6}>
        <ShowCode title="Basic example" svelteCode={btngroup1}>
            <ButtonGroup role="group" aria-label="Basic example">
                <SpkButton
                    color="info"
                    buttontype="button"
                    customClass="btn-wave"
                    ><i class="bi bi-skip-backward"></i></SpkButton
                >
                <SpkButton
                    color="info"
                    buttontype="button"
                    customClass="btn-wave"
                    ><i class="bi bi-pause"></i></SpkButton
                >
                <SpkButton
                    color="info"
                    buttontype="button"
                    customClass="btn-wave"
                    ><i class="bi bi-skip-forward"></i></SpkButton
                >
            </ButtonGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Navigation" svelteCode={btngroup2}>
            <ButtonGroup>
                <SpkButton
                    color="primary"
                    active
                    href="#!"
                    customClass="  active btn-wave"
                    text="Active link"
                />
                <SpkButton color="primary" href="#!" text="Link" />
                <SpkButton color="primary" href="#!" text="Link" />
            </ButtonGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Mixed Style" svelteCode={btngroup3}>
            <ButtonGroup role="group" aria-label="Basic mixed styles example">
                <SpkButton
                    color="danger"
                    buttontype="button"
                    customClass="btn-wave"
                    text="Left"
                />
                <SpkButton
                    color="warning"
                    buttontype="button"
                    customClass="btn-wave"
                    text="Middle"
                />
                <SpkButton
                    color="success"
                    buttontype="button"
                    customClass="btn-wave"
                    text="Right"
                />
            </ButtonGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Outline styled" svelteCode={btngroup4}>
            <ButtonGroup
                class="btn-group1"
                role="group"
                aria-label="Basic outlined example"
            >
                <SpkButton
                    outline={true}
                    color="primary"
                    buttontype="button"
                    customClass="btn-wave"
                    text="Left"
                />
                <SpkButton
                    outline={true}
                    color="primary"
                    buttontype="button"
                    customClass="btn-wave"
                    text="Middle"
                />
                <SpkButton
                    outline={true}
                    color="primary"
                    buttontype="button"
                    customClass="btn-wave"
                    text="Right"
                />
            </ButtonGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title="Checkbox button groups"
            customCardBodyClass=" checkbox-button-group"
            svelteCode={btngroup5}
        >
            <ButtonGroup
                class="btn-group2"
                role="group"
                aria-label="Basic checkbox toggle button group"
            >
                <input type="checkbox" class="btn-check" id="btncheck1" />
                <label class="btn btn-outline-primary" for="btncheck1"
                    >Checkbox 1</label
                >
                <input type="checkbox" class="btn-check" id="btncheck2" />
                <label class="btn btn-outline-primary" for="btncheck2"
                    >Checkbox 2</label
                >
                <input type="checkbox" class="btn-check" id="btncheck3" />
                <label class="btn btn-outline-primary" for="btncheck3"
                    >Checkbox 3</label
                >
            </ButtonGroup>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode
            title=" Radio button groups"
            customCardBodyClass="radio-button-group"
            svelteCode={btngroup6}
        >
            <ButtonGroup
                class="btn-group2"
                role="group"
                aria-label="Basic radio toggle button group"
            >
                <input
                    type="radio"
                    class="btn-check"
                    name="btnradio"
                    id="btnradio1"
                    checked
                />
                <label class="btn btn-outline-primary" for="btnradio1"
                    >Radio 1</label
                >
                <input
                    type="radio"
                    class="btn-check"
                    name="btnradio"
                    id="btnradio2"
                />
                <label class="btn btn-outline-primary" for="btnradio2"
                    >Radio 2</label
                >
                <input
                    type="radio"
                    class="btn-check"
                    name="btnradio"
                    id="btnradio3"
                />
                <label class="btn btn-outline-primary" for="btnradio3"
                    >Radio 3</label
                >
            </ButtonGroup>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Sizing" svelteCode={btngroup7}>
            <ButtonGroup
                class=" btn-group-lg my-1 me-1"
                role="group"
                aria-label="Large button group"
            >
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Left"
                />
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Middle"
                />
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Right"
                />
            </ButtonGroup>
            <ButtonGroup
                class=" my-1 me-1"
                role="group"
                aria-label="Default button group"
            >
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Left"
                />
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Middle"
                />
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Right"
                />
            </ButtonGroup>
            <ButtonGroup
                class=" btn-group-sm my-1 me-1"
                role="group"
                aria-label="Small button group"
            >
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Left"
                />
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Middle"
                />
                <SpkButton
                    outline={true}
                    color="success"
                    buttontype="button"
                    text="Right"
                />
            </ButtonGroup>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Button toolbar" svelteCode={btngroup8}>
            <ButtonToolbar
                class="mb-4 btn-toolbar"
                role="toolbar"
                aria-label="Toolbar with button groups"
            >
                <ButtonGroup
                    class=" me-2 my-1"
                    role="group"
                    aria-label="First group"
                >
                    <SpkButton color="primary" buttontype="button" text="1" />
                    <SpkButton color="primary" buttontype="button" text="2" />
                    <SpkButton color="primary" buttontype="button" text="3" />
                    <SpkButton color="primary" buttontype="button" text="4" />
                </ButtonGroup>
                <ButtonGroup
                    class=" me-2 my-1"
                    role="group"
                    aria-label="Second group"
                >
                    <SpkButton color="secondary" buttontype="button" text="5" />
                    <SpkButton color="secondary" buttontype="button" text="6" />
                    <SpkButton color="secondary" buttontype="button" text="7" />
                </ButtonGroup>
                <ButtonGroup
                    class=" my-1"
                    role="group"
                    aria-label="Third group"
                >
                    <SpkButton
                        color="info"
                        buttontype="button"
                        class="btn btn-info">8</SpkButton
                    >
                </ButtonGroup>
            </ButtonToolbar>
            <ButtonToolbar
                class="mb-3 btn-toolbar"
                role="toolbar"
                aria-label="Toolbar with button groups"
            >
                <ButtonGroup
                    class=" me-2 my-1"
                    role="group"
                    aria-label="First group"
                >
                    <SpkButton
                        outline={true}
                        color="secondary"
                        buttontype="button"
                        text="1"
                    />
                    <SpkButton
                        outline={true}
                        color="secondary"
                        buttontype="button"
                        text="2"
                    />
                    <SpkButton
                        outline={true}
                        color="secondary"
                        buttontype="button"
                        text="3"
                    />
                    <SpkButton
                        outline={true}
                        color="secondary"
                        buttontype="button"
                        text="4"
                    />
                </ButtonGroup>
                <InputGroup>
                    <InputGroupText id="btnGroupAddon">@</InputGroupText>
                    <Input
                        type="text"
                        placeholder="Input group example"
                        aria-label="Input group example"
                        aria-describedby="btnGroupAddon"
                    />
                </InputGroup>
            </ButtonToolbar>
            <ButtonToolbar
                class="justify-content-between btn-toolbar"
                role="toolbar"
                aria-label="Toolbar with button groups"
            >
                <ButtonGroup
                    class="me-2 my-1"
                    role="group"
                    aria-label="First group"
                >
                    <SpkButton
                        outline={true}
                        color="secondary"
                        buttontype="button"
                        text="1"
                    />
                    <SpkButton
                        outline={true}
                        color="secondary"
                        buttontype="button"
                        text="2"
                    />
                    <SpkButton
                        outline={true}
                        color="secondary"
                        buttontype="button"
                        text="3"
                    />
                    <SpkButton
                        outline={true}
                        color="secondary"
                        buttontype="button"
                        text="4"
                    />
                </ButtonGroup>
                <InputGroup>
                    <InputGroupText id="btnGroupAddon2">@</InputGroupText>
                    <Input
                        type="text"
                        placeholder="Input group example"
                        aria-label="Input group example"
                        aria-describedby="btnGroupAddon2"
                    />
                </InputGroup>
            </ButtonToolbar>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Nesting" svelteCode={btngroup9}>
            <ButtonGroup
                role="group"
                aria-label="Button group with nested dropdown"
            >
                <SpkButton color="primary" buttontype="button" text="1" />
                <SpkButton color="primary" buttontype="button" text="2" />
                <Dropdown
                    title="Dropdown"
                    id="bg-nested-dropdown"
                    direction="down"
                    class="btn-group"
                    role="group"
                >
                    <DropdownToggle
                        color="primary"
                        class="dropdown-toggle"
                        type="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        Dropdown
                    </DropdownToggle>
                    <DropdownMenu>
                        <DropdownItem
                            ><a href="#!">Dropdown link</a></DropdownItem
                        >
                        <DropdownItem
                            ><a href="#!">Dropdown link</a></DropdownItem
                        >
                    </DropdownMenu>
                </Dropdown>
            </ButtonGroup>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Vertical variation" svelteCode={btngroup10}>
            <div class="row gap-2">
                <Col sm={3}>
                    <ButtonGroup
                        vertical
                        role="group"
                        aria-label="Vertical button group"
                    >
                        <SpkButton color="primary" buttontype="button"
                            >Button</SpkButton
                        >
                        <SpkButton color="primary" buttontype="button"
                            >Button</SpkButton
                        >
                        <Dropdown
                            title="Dropdown"
                            id="bg-nested-dropdown"
                            direction="down"
                            class="btn-group"
                            role="group"
                        >
                            <DropdownToggle
                                color="primary"
                                class="dropdown-toggle"
                                typetype="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                            >
                                Dropdown
                            </DropdownToggle>
                            <DropdownMenu>
                                <DropdownItem
                                    ><a href="#!">Dropdown link</a
                                    ></DropdownItem
                                >
                                <DropdownItem
                                    ><a href="#!">Dropdown link</a
                                    ></DropdownItem
                                >
                            </DropdownMenu>
                        </Dropdown>
                        <SpkButton color="primary" buttontype="button"
                            >Button</SpkButton
                        >
                        <SpkButton color="primary" buttontype="button"
                            >Button</SpkButton
                        >
                        <Dropdown
                            title="Dropdown"
                            id="bg-nested-dropdown"
                            direction="down"
                            class="btn-group"
                            role="group"
                        >
                            <DropdownToggle
                                color="primary"
                                class="dropdown-toggle"
                                type="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                            >
                                Dropdown
                            </DropdownToggle>
                            <DropdownMenu>
                                <DropdownItem
                                    ><a href="#!">Dropdown link</a
                                    ></DropdownItem
                                >
                                <DropdownItem
                                    ><a href="#!">Dropdown link</a
                                    ></DropdownItem
                                >
                            </DropdownMenu>
                        </Dropdown>
                        <Dropdown
                            title="Dropdown"
                            id="bg-nested-dropdown"
                            direction="down"
                            class="btn-group"
                            role="group"
                        >
                            <DropdownToggle
                                color="primary"
                                class="dropdown-toggle"
                                type="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                            >
                                Dropdown
                            </DropdownToggle>
                            <DropdownMenu>
                                <DropdownItem
                                    ><a href="#!">Dropdown link</a
                                    ></DropdownItem
                                >
                                <DropdownItem
                                    ><a href="#!">Dropdown link</a
                                    ></DropdownItem
                                >
                            </DropdownMenu>
                        </Dropdown>
                        <Dropdown
                            title="Dropdown"
                            id="bg-nested-dropdown"
                            direction="down"
                            class="btn-group"
                            role="group"
                        >
                            <DropdownToggle
                                color="primary"
                                class="dropdown-toggle"
                                type="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                            >
                                Dropdown
                            </DropdownToggle>
                            <DropdownMenu>
                                <DropdownItem
                                    ><a href="#!">Dropdown link</a
                                    ></DropdownItem
                                >
                                <DropdownItem
                                    ><a href="#!">Dropdown link</a
                                    ></DropdownItem
                                >
                            </DropdownMenu>
                        </Dropdown>
                    </ButtonGroup>
                </Col>
                <Col sm={3}>
                    <ButtonGroup
                        vertical
                        role="group"
                        aria-label="Vertical button group"
                    >
                        <SpkButton
                            color="info"
                            buttontype="button"
                            text="Button"
                        />
                        <SpkButton
                            color="info"
                            buttontype="button"
                            text="Button"
                        />
                        <SpkButton
                            color="info"
                            buttontype="button"
                            text="Button"
                        />
                        <SpkButton
                            color="info"
                            buttontype="button"
                            text="Button"
                        />
                        <SpkButton
                            color="info"
                            buttontype="button"
                            text="Button"
                        />
                        <SpkButton
                            color="info"
                            buttontype="button"
                            text="Button"
                        />
                    </ButtonGroup>
                </Col>
                <Col sm={3}>
                    <ButtonGroup
                        vertical
                        role="group"
                        aria-label="Vertical radio toggle button group"
                    >
                        <input
                            type="radio"
                            class="btn-check"
                            name="vbtn-radio"
                            id="vbtn-radio1"
                            checked
                        />
                        <label
                            class="btn btn-outline-danger mb-0"
                            for="vbtn-radio1">Radio 1</label
                        >
                        <input
                            type="radio"
                            class="btn-check"
                            name="vbtn-radio"
                            id="vbtn-radio2"
                        />
                        <label
                            class="btn btn-outline-danger mb-0"
                            for="vbtn-radio2">Radio 2</label
                        >
                        <input
                            type="radio"
                            class="btn-check"
                            name="vbtn-radio"
                            id="vbtn-radio3"
                        />
                        <label
                            class="btn btn-outline-danger mb-0"
                            for="vbtn-radio3">Radio 3</label
                        >
                    </ButtonGroup>
                </Col>
            </div>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode
            title="Social Group Buttons"
            svelteCode={btngroup11}
            dataCode={databutton16}
        >
            <ButtonGroup
                class="btn-group"
                role="group"
                aria-label="Basic example"
            >
                {#each SocialIconButtons as button}
                    <SpkButton
                        color={button.class1}
                        customClass=" btn-icon  btn-wave waves-effect waves-light"
                    >
                        <i class={`fs-16 ri-${button.class}-line`}></i>
                    </SpkButton>
                {/each}
            </ButtonGroup>
        </ShowCode>
    </Col>
</Row>
<!--ROW-END-->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/ui-elements/button-group/button-group.jsx

import SpkButtongroup from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttongroup";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import { btngroup1, btngroup10, btngroup11, btngroup2, btngroup3, btngroup4, btngroup5, btngroup6, btngroup7, btngroup8, btngroup9, datagroup10, reusebtngroup1, reusebtngroup10, reusebtngroup11, reusebtngroup2, reusebtngroup3, reusebtngroup4, reusebtngroup5, reusebtngroup6, reusebtngroup7, reusebtngroup8, reusebtngroup9 } from "../../../../shared/data/prism-code/uielements-prism";
import { SocialIconButtons } from "../../../../shared/data/general/ui-elements/buttonsdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { ButtonGroup, ButtonToolbar, Col, Dropdown, DropdownButton, Form, InputGroup, Row } from "react-bootstrap";
import MainLayout from "@/Layouts/layout";


const ButtonGroups = () => {

    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Uielements-Button Group" />

            <Pageheader title="Ui Elements" currentpage="Button Group" activepage="Button Group" />

            {/* <!-- Page Header Close --> */}

            {/* <!--ROW-START--> */}

            <Row>
                <Col xl={6}>
                    <ShowCode title="Basic example" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup1} reusableCode={reusebtngroup1}>
                        <SpkButtongroup Buttongrplabel="Basic example">
                            <SpkButton Buttonvariant="info" Buttontype="button"><i className="bi bi-skip-backward"></i></SpkButton>
                            <SpkButton Buttonvariant="info" Buttontype="button"><i className="bi bi-pause"></i></SpkButton>
                            <SpkButton Buttonvariant="info" Buttontype="button"><i className="bi bi-skip-forward"></i></SpkButton>
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Navigation" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup3} reusableCode={reusebtngroup3}>
                        <SpkButtongroup>
                            <SpkButton Buttonvariant='primary' Active={true} Navigate="#!" >Active link</SpkButton>
                            <SpkButton Buttonvariant='primary' Navigate="#!">Link</SpkButton>
                            <SpkButton Buttonvariant='primary' Navigate="#!" >Link</SpkButton>
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Mixed Style" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup6} reusableCode={reusebtngroup6}>
                        <SpkButtongroup Buttongrplabel="Basic mixed styles example">
                            <SpkButton Buttonvariant="danger" Buttontype="button">Left</SpkButton>
                            <SpkButton Buttonvariant="warning" Buttontype="button">Middle</SpkButton>
                            <SpkButton Buttonvariant="success" Buttontype="button">Right</SpkButton>
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Outline styled" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup4} reusableCode={reusebtngroup4}>
                        <SpkButtongroup Buttongrplabel="Basic outlined example">
                            <SpkButton Buttonvariant="outline-primary" Buttontype="button">Left</SpkButton>
                            <SpkButton Buttonvariant="outline-primary" Buttontype="button">Middle</SpkButton>
                            <SpkButton Buttonvariant="outline-primary" Buttontype="button">Right</SpkButton>
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title="Checkbox button groups" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup2} reusableCode={reusebtngroup2}>

                        <SpkButtongroup Buttongrplabel="Basic checkbox toggle button group" Customclass="checkbox-toggle">
                            <input type="checkbox" className="btn-check" id="btncheck1" />
                            <label className="btn btn-outline-primary" htmlFor="btncheck1">Checkbox 1</label>

                            <input type="checkbox" className="btn-check" id="btncheck2" />
                            <label className="btn btn-outline-primary" htmlFor="btncheck2">Checkbox 2</label>

                            <input type="checkbox" className="btn-check" id="btncheck3" />
                            <label className="btn btn-outline-primary" htmlFor="btncheck3">Checkbox 3</label>
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title=" Radio button groups" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup5} reusableCode={reusebtngroup5}>
                        <SpkButtongroup Buttongrplabel="Basic radio toggle button group">
                            <input type="radio" className="btn-check" name="btnradio" id="btnradio1"
                                defaultChecked />
                            <label className="btn btn-outline-primary" htmlFor="btnradio1">Radio 1</label>

                            <input type="radio" className="btn-check" name="btnradio" id="btnradio2"
                            />
                            <label className="btn btn-outline-primary" htmlFor="btnradio2">Radio 2</label>

                            <input type="radio" className="btn-check" name="btnradio" id="btnradio3"
                            />
                            <label className="btn btn-outline-primary" htmlFor="btnradio3">Radio 3</label>
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Sizing" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup11} reusableCode={reusebtngroup11}>
                        <SpkButtongroup Size="lg" Customclass="my-1 me-5" Buttongrplabel="Large button group">
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Left</SpkButton>
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Middle</SpkButton>
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Right</SpkButton>
                        </SpkButtongroup>
                        <SpkButtongroup Customclass="my-1 me-5" Buttongrplabel="Default button group">
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Left</SpkButton>
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Middle</SpkButton>
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Right</SpkButton>
                        </SpkButtongroup>
                        <SpkButtongroup Size="sm" Customclass="my-1 me-5" Buttongrplabel="Small button group">
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Left</SpkButton>
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Middle</SpkButton>
                            <SpkButton Buttonvariant="outline-success" Buttontype="button">Right</SpkButton>
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Button toolbar" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup8} reusableCode={reusebtngroup8}>
                        <ButtonToolbar className="mb-4" role="toolbar"
                            aria-label="Toolbar with button groups">
                            <SpkButtongroup Customclass="me-2 my-1" Buttongrplabel="First group">
                                <SpkButton Buttonvariant="primary" Buttontype="button">1</SpkButton>
                                <SpkButton Buttonvariant="primary" Buttontype="button">2</SpkButton>
                                <SpkButton Buttonvariant="primary" Buttontype="button">3</SpkButton>
                                <SpkButton Buttonvariant="primary" Buttontype="button">4</SpkButton>
                            </SpkButtongroup>
                            <SpkButtongroup Customclass="me-2 my-1" Buttongrplabel="Second group">
                                <SpkButton Buttonvariant="secondary" Buttontype="button">5</SpkButton>
                                <SpkButton Buttonvariant="secondary" Buttontype="button">6</SpkButton>
                                <SpkButton Buttonvariant="secondary" Buttontype="button">7</SpkButton>
                            </SpkButtongroup>
                            <SpkButtongroup Customclass="my-1" Buttongrplabel="Third group">
                                <SpkButton Buttonvariant="info" Buttontype="button">8</SpkButton>
                            </SpkButtongroup>
                        </ButtonToolbar>
                        <ButtonToolbar className="mb-3" role="toolbar"
                            aria-label="Toolbar with button groups">
                            <SpkButtongroup Customclass="me-2 my-1" Buttongrplabel="First group">
                                <SpkButton Buttonvariant="outline-secondary" Buttontype="button">1</SpkButton>
                                <SpkButton Buttonvariant="outline-secondary" Buttontype="button">2</SpkButton>
                                <SpkButton Buttonvariant="outline-secondary" Buttontype="button">3</SpkButton>
                                <SpkButton Buttonvariant="outline-secondary" Buttontype="button">4</SpkButton>
                            </SpkButtongroup>
                            <InputGroup>
                                <InputGroup.Text id="btnGroupAddon">@</InputGroup.Text>
                                <Form.Control type="text"
                                    placeholder="Input group example"
                                    aria-label="Input group example"
                                    aria-describedby="btnGroupAddon" />
                            </InputGroup>
                        </ButtonToolbar>
                        <ButtonToolbar className="justify-content-between" role="toolbar"
                            aria-label="Toolbar with button groups">
                            <SpkButtongroup Customclass="my-1" Buttongrplabel="First group">
                                <SpkButton Buttonvariant="outline-secondary" Buttontype="button">1</SpkButton>
                                <SpkButton Buttonvariant="outline-secondary" Buttontype="button">2</SpkButton>
                                <SpkButton Buttonvariant="outline-secondary" Buttontype="button">3</SpkButton>
                                <SpkButton Buttonvariant="outline-secondary" Buttontype="button">4</SpkButton>
                            </SpkButtongroup>
                            <InputGroup>
                                <InputGroup.Text id="btnGroupAddon2">@</InputGroup.Text>
                                <Form.Control type="text"
                                    placeholder="Input group example"
                                    aria-label="Input group example"
                                    aria-describedby="btnGroupAddon2" />
                            </InputGroup>
                        </ButtonToolbar>
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Nesting" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup9} reusableCode={reusebtngroup9}>
                        <SpkButtongroup Customclass="" Buttongrplabel="Button group with nested dropdown">
                            <SpkButton Buttonvariant="primary" Buttontype="button">1</SpkButton>
                            <SpkButton Buttonvariant="primary" Buttontype="button">2</SpkButton>

                            <DropdownButton as={ButtonGroup} title="Dropdown" id="bg-nested-dropdown">
                                <Dropdown.Item eventKey="1">Dropdown link</Dropdown.Item>
                                <Dropdown.Item eventKey="2">Dropdown link</Dropdown.Item>
                            </DropdownButton>
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Vertical variation" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup7} reusableCode={reusebtngroup7}>
                        <div className="row gap-2">
                            <Col sm={3}>
                                <SpkButtongroup Vertical={true} Buttongrplabel="Vertical button group">
                                    <SpkButton Buttonvariant="primary" Buttontype="button">Button</SpkButton>
                                    <SpkButton Buttonvariant="primary" Buttontype="button">Button</SpkButton>
                                    <DropdownButton as={ButtonGroup} title="Dropdown" id="bg-vertical-dropdown-1">
                                        <Dropdown.Item eventKey="1">Dropdown link</Dropdown.Item>
                                        <Dropdown.Item eventKey="2">Dropdown link</Dropdown.Item>
                                    </DropdownButton>
                                    <SpkButton Buttonvariant="primary" Buttontype="button">Button</SpkButton>
                                    <SpkButton Buttonvariant="primary" Buttontype="button">Button</SpkButton>
                                    <DropdownButton as={ButtonGroup} title="Dropdown" id="bg-vertical-dropdown-1">
                                        <Dropdown.Item eventKey="1">Dropdown link</Dropdown.Item>
                                        <Dropdown.Item eventKey="2">Dropdown link</Dropdown.Item>
                                    </DropdownButton>
                                    <DropdownButton as={ButtonGroup} title="Dropdown" id="bg-vertical-dropdown-1">
                                        <Dropdown.Item eventKey="1">Dropdown link</Dropdown.Item>
                                        <Dropdown.Item eventKey="2">Dropdown link</Dropdown.Item>
                                    </DropdownButton>
                                    <DropdownButton as={ButtonGroup} title="Dropdown" id="bg-vertical-dropdown-1">
                                        <Dropdown.Item eventKey="1">Dropdown link</Dropdown.Item>
                                        <Dropdown.Item eventKey="2">Dropdown link</Dropdown.Item>
                                    </DropdownButton>
                                </SpkButtongroup>
                            </Col>
                            <Col sm={3}>
                                <SpkButtongroup Vertical={true} Buttongrplabel="Vertical button group">
                                    <SpkButton Buttonvariant="info" Buttontype="button">Button</SpkButton>
                                    <SpkButton Buttonvariant="info" Buttontype="button">Button</SpkButton>
                                    <SpkButton Buttonvariant="info" Buttontype="button">Button</SpkButton>
                                    <SpkButton Buttonvariant="info" Buttontype="button">Button</SpkButton>
                                    <SpkButton Buttonvariant="info" Buttontype="button">Button</SpkButton>
                                    <SpkButton Buttonvariant="info" Buttontype="button">Button</SpkButton>
                                </SpkButtongroup>
                            </Col>
                            <Col sm={3}>
                                <SpkButtongroup Vertical={true} Buttongrplabel="Vertical radio toggle button group">
                                    <input type="radio" className="btn-check" name="vbtn-radio" id="vbtn-radio1" defaultChecked />
                                    <label className="btn btn-outline-danger" htmlFor="vbtn-radio1">Radio 1</label>
                                    <input type="radio" className="btn-check" name="vbtn-radio" id="vbtn-radio2" />
                                    <label className="btn btn-outline-danger" htmlFor="vbtn-radio2">Radio 2</label>
                                    <input type="radio" className="btn-check" name="vbtn-radio" id="vbtn-radio3" />
                                    <label className="btn btn-outline-danger" htmlFor="vbtn-radio3">Radio 3</label>
                                </SpkButtongroup>
                            </Col>
                        </div>
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Social Group Buttons" customCardClass="custom-card" customCardBodyClass="" reactCode={btngroup10} dataCode={datagroup10} reusableCode={reusebtngroup10}>
                        <SpkButtongroup Buttongrplabel="Basic example">
                            {SocialIconButtons.map((idx, index) => (
                                <SpkButton Buttonvariant={idx.class1} Customclass="btn-icon" key={index}>
                                    <i className={`ri-${idx.class}-line lh-1 fs-17 pt-1`}></i>
                                </SpkButton>
                            ))}
                        </SpkButtongroup>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!--ROW-END--> */}

        </Fragment>
    )
};
// Assign layout
ButtonGroups.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ButtonGroups;
