// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/authentication/two-step-verification/basic/basic.jsx

import SpkButton from "../../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import React, { Fragment, useRef, useState } from "react";
import { Card, Col, Form, Image, Row } from "react-bootstrap";
import { Head, Link, router } from "@inertiajs/react";
import { toast, ToastContainer } from "react-toastify";
import AuthenticationLayout from "@/Layouts/authenticationlayout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const Basic = () => {

    const [inputValues, setInputValues] = useState({
        one: '',
        two: '',
        three: '',
        four: '',
    });

    const [error, setError] = useState('');

    const inputsRef = {
        one: useRef(null),
        two: useRef(null),
        three: useRef(null),
        four: useRef(null),
    };

    const handleChange = (
        current,
        next,
        value
    ) => {
        if (!/^\d?$/.test(value)) return; // Only allow one digit

        const updatedValues = { ...inputValues, [current]: value };
        setInputValues(updatedValues);

        if (value && next && inputsRef[next].current) {
            inputsRef[next].current?.focus();
        }
    };

    const handlePaste = (e) => {
        const paste = e.clipboardData.getData('text').replace(/\D/g, '').slice(0, 4);

        if (paste.length === 4) {
            setInputValues({
                one: paste[0],
                two: paste[1],
                three: paste[2],
                four: paste[3],
            });

            inputsRef.four.current?.focus();
        }

        e.preventDefault();
    };

    const handleSubmit = (e) => {
        e.preventDefault();

        const { one, two, three, four } = inputValues;

        if (!one || !two || !three || !four) {
            setError('All fields are required.');
            return;
        }

        const fullOTP = `${one}${two}${three}${four}`;
        router.get(`${__APP_BASE_PATH__}/dashboards/sales`);
        toast.success('Verify Your Account successful', {
            position: 'top-right',
            autoClose: 1500,
            hideProgressBar: false,
            closeOnClick: true,
            pauseOnHover: true,
            draggable: true,
        });
        console.log('Submitted OTP:', fullOTP);

        setError('');

        // TODO: Call your backend API with OTP
    };
    return (
        <Fragment>
            <Head title="Twostep-Basic" />

            <div className="authentication-basic-background">
                <BaseImage src="/build/assets/images/media/backgrounds/9.png" alt="" />
            </div>
            <div className="container">
                <Row className="justify-content-center align-items-center authentication authentication-basic h-100">
                    <Col xxl={4} xl={5} lg={6} md={8} sm={12} className="col-12">
                        <Card className="custom-card border-0 my-4">
                            <Card.Body className="p-sm-5">
                                <div className="mb-4">
                                    <Link href={`${__APP_BASE_PATH__}/dashboards/sales`}>
                                        <BaseImage src="/build/assets/images/brand-logos/toggle-logo.png" alt="logo" className="desktop-dark" />
                                    </Link>
                                </div>
                                <p className="h4 mb-2 fw-semibold">Verify Your Account</p>
                                <p className="mb-4 text-muted fw-normal text-nowrap two-step-verification">Enter the 4 digit code sent to the registered email Id.</p>
                                <Form onSubmit={handleSubmit} >
                                    <Row className=" gy-3">
                                        <Col xl={12} className="mb-2">
                                            <Row className="">
                                                <Col className="col-3">
                                                    <Form.Control id="one"
                                                        ref={inputsRef.one}
                                                        type="text"
                                                        maxLength={1}
                                                        value={inputValues.one}
                                                        onChange={(e) => handleChange('one', 'two', e.target.value)}
                                                        onPaste={handlePaste}
                                                        className="form-control-lg text-center  "
                                                    />
                                                </Col>
                                                <Col className="col-3">
                                                    <Form.Control id="two"
                                                        ref={inputsRef.two}
                                                        type="text"
                                                        maxLength={1}
                                                        value={inputValues.two}
                                                        onChange={(e) => handleChange('two', 'three', e.target.value)}
                                                        className="form-control-lg text-center "
                                                    />
                                                </Col>
                                                <Col className="col-3">
                                                    <Form.Control id="three"
                                                        ref={inputsRef.three}
                                                        type="text"
                                                        maxLength={1}
                                                        value={inputValues.three}
                                                        onChange={(e) => handleChange('three', 'four', e.target.value)}
                                                        className="form-control-lg text-center  "
                                                    />
                                                </Col>
                                                <Col className="col-3">
                                                    <Form.Control id="four"
                                                        ref={inputsRef.four}
                                                        type="text"
                                                        maxLength={1}
                                                        value={inputValues.four}
                                                        onChange={(e) => handleChange('four', null, e.target.value)}
                                                        className="form-control-lg text-center"
                                                    />
                                                </Col>
                                            </Row>
                                            <div className="form-check mt-3">
                                                <input className="form-check-input" type="checkbox" defaultValue="" id="defaultCheck1" />
                                                <label className="form-check-label" htmlFor="defaultCheck1">
                                                    Did not recieve a code ?<Link href={`${__APP_BASE_PATH__}/applications/email/mail-app`} className="text-primary ms-2 d-inline-block fw-medium">Resend</Link>
                                                </label>
                                            </div>
                                        </Col>
                                        <Col xl={12} className="d-grid mt-3">
                                            {error && <p className="text-danger text-sm text-center mb-2">{error}</p>}
                                            <SpkButton Buttontype="submit" Customclass="btn btn-lg btn-primary">Verify</SpkButton>
                                        </Col>
                                    </Row>
                                </Form>
                                <div className="text-center">
                                    <p className="text-danger mt-3 mb-0 fw-medium"><sup><i className="ri-asterisk"></i></sup>Keep the verification code private!</p>
                                </div>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
                <ToastContainer />
            </div>
        </Fragment>
    )
};
// Assign layout
Basic.layout = (page) => <AuthenticationLayout>{page}</AuthenticationLayout>;
export default Basic;

// Dashboard Template/vyzor-svelte/final/src/routes/(auth)/authentication/two-step-verification/basic/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { goto } from "$app/navigation"; // If using SvelteKit
    import {
        Card,
        CardBody,
        Col,
        Form,
        Image,
        Input,
        Row,
    } from "@sveltestrap/sveltestrap";
    import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";
    import { base } from "$app/paths";
    const basePath = base;

    let inputValues: any = {
        one: "",
        two: "",
        three: "",
        four: "",
    };

    let error = "";

    let refs: any = {
        one: null,
        two: null,
        three: null,
        four: null,
    };

    const handleChange = (currentId: any, nextId: any, value: any) => {
        // const value = e.target.value;
        // if (!/^\d?$/.test(value)) return;

        inputValues = {
            ...inputValues,
            [currentId]: value,
        };

        // Focus the next input element if it exists
        const nextInput = document.getElementById(nextId);
        if (nextInput) {
            nextInput.focus();
        }
    };

    const handlePaste = (e: any) => {
        const paste = e.clipboardData
            .getData("text")
            .replace(/\D/g, "")
            .slice(0, 4);

        if (paste.length === 4) {
            inputValues.one = paste[0];
            inputValues.two = paste[1];
            inputValues.three = paste[2];
            inputValues.four = paste[3];

            refs.four?.focus();
        }

        e.preventDefault();
    };

    let verify: string;

    const handleSubmit = (e: any) => {
        e.preventDefault();

        const { one, two, three, four } = inputValues;

        if (!one || !two || !three || !four) {
            error = "All fields are required.";
            return;
        }

        const fullOTP = `${one}${two}${three}${four}`;
        goto(`${basePath}/dashboards/sales`);

        verify = "Verify Your Account successful";
        error = "";

        // TODO: Call your backend API with OTP
    };

    const setBodyClass = (action: string) => {
        if (action === "add") {
            document.body.classList.add(
                "authentication-background",
                "authenticationcover-background",
                "position-relative",
            );
            document.body.style.display = "block";
        } else {
            document.body.classList.remove(
                "authentication-background",
                "authenticationcover-background",
                "position-relative",
            );
            document.body.style.display = "none";
        }
    };

    onMount(() => {
        if (localStorage.getItem("visited") === "true") {
            setBodyClass("add");
        } else {
            setBodyClass("add");
            localStorage.setItem("visited", "true");
        }

        const handleBeforeUnload = () => {
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };

        window.addEventListener("beforeunload", handleBeforeUnload);

        return () => {
            window.removeEventListener("beforeunload", handleBeforeUnload);
            setBodyClass("remove");
            localStorage.removeItem("visited");
        };
        document.body.removeAttribute("style");
    });
</script>

<!-- Page Title -->
<svelte:head>
    <title>Twostep-Basic | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<div class="authentication-basic-background">
    <Image src="../../images/media/backgrounds/9.png" alt="" />
</div>
<div class="container">
    <Row
        class="justify-content-center align-items-center authentication authentication-basic h-100"
    >
        <Col xxl={4} xl={5} lg={6} md={6} sm={8} class="col-12">
            <Card class="custom-card border-0 my-4">
                <CardBody class="p-5">
                    <div class="mb-4">
                        <a href={`${basePath}/dashboards/sales`}>
                            <Image
                                src="../../images/brand-logos/toggle-logo.png"
                                alt="logo"
                                class="desktop-dark"
                            />
                        </a>
                    </div>
                    <p class="h4 mb-2 fw-semibold">Verify Your Account</p>
                    <p class="mb-4 text-muted fw-normal">
                        Enter the 4 digit code sent to the registered email Id.
                    </p>
                    <Form on:submit={handleSubmit}>
                        <Row class=" gy-3">
                            <Col xl={12} class="mb-2">
                                <Row class="">
                                    <Col class="col-3">
                                        <Input
                                            id="one"
                                            type="text"
                                            maxlength={1}
                                            bind:value={inputValues.one}
                                            on:input={(e) =>
                                                handleChange(
                                                    "one",
                                                    "two",
                                                    e.target.value,
                                                )}
                                            on:paste={handlePaste}
                                            class="form-control-lg text-center "
                                        />
                                    </Col>
                                    <Col class="col-3">
                                        <Input
                                            id="two"
                                            type="text"
                                            maxlength={1}
                                            bind:value={inputValues.two}
                                            on:input={(e) =>
                                                handleChange(
                                                    "two",
                                                    "three",
                                                    e.target.value,
                                                )}
                                            class="form-control-lg text-center "
                                        />
                                    </Col>
                                    <Col class="col-3">
                                        <Input
                                            id="three"
                                            type="text"
                                            maxlength={1}
                                            bind:value={inputValues.three}
                                            on:input={(e) =>
                                                handleChange(
                                                    "three",
                                                    "four",
                                                    e.target.value,
                                                )}
                                            class="form-control-lg text-center  "
                                        />
                                    </Col>
                                    <Col class="col-3">
                                        <Input
                                            id="four"
                                            type="text"
                                            maxlength={1}
                                            bind:value={inputValues.four}
                                            on:input={(e) =>
                                                handleChange(
                                                    "four",
                                                    null,
                                                    e.target.value,
                                                )}
                                            class="form-control-lg text-center"
                                        />
                                    </Col>
                                </Row>
                                <!-- svelte-ignore a11y_label_has_associated_control -->
                                <div class="form-check mt-3">
                                    <input
                                        class="form-check-input"
                                        type="checkbox"
                                        defaultValue=""
                                        id="defaultCheck1"
                                    />
                                    <!-- svelte-ignore attribute_invalid_property_name -->
                                    <!-- svelte-ignore attribute_invalid_property_name -->
                                    <label
                                        class="form-check-label"
                                        for="defaultCheck1"
                                    >
                                        Did not recieve a code ?<a
                                            href={`${basePath}/applications/email/mail-app`}
                                            class="text-primary ms-2 d-inline-block fw-medium"
                                            >Resend</a
                                        >
                                    </label>
                                </div>
                            </Col>
                            <Col xl={12} class="d-grid mt-3">
                                {#if error}
                                    <p
                                        class="text-danger text-sm text-center mb-2"
                                    >
                                        {error}
                                    </p>
                                {/if}

                                {#if verify}
                                    <p
                                        class="text-success text-sm text-center mb-2"
                                    >
                                        {verify}
                                    </p>
                                {/if}
                                <SpkButton
                                    buttontype="submit"
                                    customClass="btn btn-lg btn-primary"
                                    >Verify</SpkButton
                                >
                            </Col>
                        </Row>
                    </Form>
                    <div class="text-center">
                        <p class="text-danger mt-3 mb-0 fw-medium">
                            <sup><i class="ri-asterisk"></i></sup>Keep the
                            verification code private!
                        </p>
                    </div>
                </CardBody>
            </Card>
        </Col>
    </Row>
</div>
