// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/dashboards-reusable/spk-medicalcard.jsx

import React, { Fragment } from "react";
import { Card } from "react-bootstrap";

const SpkMedicalCard = ({ cardClass, bodyClass, medical}) => {

  return (

    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className={bodyClass}>
          <div className="d-flex align-items-start justify-content-between mb-2">
            <div className="flex-fill">
              <div className="mb-2">{medical.title}</div>
              <h4 className={`fw-semibold text-${medical.svgColor} mb-0`}>{medical.value}</h4>
            </div>
            <div>
              <span className={`avatar avatar-md bg-${medical.svgColor}-transparent svg-${medical.svgColor}`}>
                {medical.svgIcon}
              </span>
            </div>
          </div>
          <div className="d-flex fs-13 align-items-center justify-content-between">
            <div className="text-muted">{medical.month}</div>
            <div className={`text-${medical.percentColor} fw-medium d-inline-flex`}>
              <i className={medical.icon}></i>
              {medical.percent}
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkMedicalCard;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/dashboards-reusable/spk-medicalcard.svelte
<script>
    import { Card, CardBody } from "@sveltestrap/sveltestrap";



    export let medical = {};
    export let cardClass = "";
    export let bodyClass = "";
</script>

<Card class={`custom-card ${cardClass}`}>
        <CardBody class={bodyClass}>
          <div class="d-flex align-items-start justify-content-between mb-2">
            <div class="flex-fill">
              <div class="mb-2">{medical.title}</div>
              <h4 class={`fw-semibold text-${medical.svgColor} mb-0`}>{medical.value}</h4>
            </div>
            <div>
              <span class={`avatar avatar-md bg-${medical.svgColor}-transparent svg-${medical.svgColor}`}>
                {@html medical.svgIcon}
              </span>
            </div>
          </div>
          <div class="d-flex fs-13 align-items-center justify-content-between">
            <div class="text-muted">{medical.month}</div>
            <div class={`text-${medical.percentColor} fw-medium d-inline-flex`}>
              <i class={medical.icon}></i>
              {medical.percent}
            </div>
          </div>
        </CardBody>
      </Card>
