// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/general/utilities/gutters.svelte

<script context="module">
    import MainLayout from '@/layouts/MainLayout.svelte';
    export const layout = MainLayout; 
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import { Card, CardBody, CardHeader, Col, Row } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Gutters | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
 <!-- Page Header -->
<Pageheader homepage="Gutters" activepage="Utilities" page="Gutters" />
<!-- Page Header Close -->

  <!-- Start:: row-1 --> 

            <Row>
            <Col xl={12}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                Horizontal gutters
                            </div>
                        </CardHeader>
                        <CardBody>
                            <p><span class="text-danger">.gx-*</span> classes can be used to control the
                                horizontal gutter widths. The <span class="text-danger">.container </span>
                                or <span class="text-danger"> .container-fluid</span> parent may need to be
                                adjusted if larger gutters are used
                                too to avoid unwanted overflow, using a matching padding utility. For
                                example,
                                in the following example we’ve increased the padding with <span
                                    class="text-danger">.px-4</span>:
                            </p>
                            <div class="container px-4 mb-3">
                                <div class="row gx-5 gy-3">
                                    <div class="col">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                </div>
                            </div>
                            <p>An alternative solution is to add a wrapper around the <span
                                class="text-danger">.row</span> with the <span
                                    class="text-danger">.overflow-hidden</span> class:
                            </p>
                            <div class="container overflow-hidden">
                                <div class="row gx-5 gy-3">
                                    <div class="col">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                </div>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={12}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                Vertical gutters
                            </div>
                        </CardHeader>
                        <CardBody>
                            <p><span class="text-danger">.gy-*</span> classes can be used to control the
                                vertical gutter widths. Like the
                                horizontal gutters, the vertical gutters can cause some overflow below the
                                .row
                                at the end of a page. If this occurs, you add a wrapper around <span
                                    class="text-danger">.row</span> with the
                                <span class="text-danger">.overflow-hidden</span> class:
                            </p>
                            <div class="container overflow-hidden">
                                <div class="row gy-5">
                                    <div class="col-6">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div class="col-6">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div class="col-6">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div class="col-6">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                </div>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={12}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                Horizontal & vertical gutters
                            </div>
                        </CardHeader>
                        <CardBody>
                            <p><span class="text-danger">.g-*</span> classes can be used to control the
                                horizontal gutter widths, for the
                                following example we use a smaller gutter width, so there won’t be a need to
                                add
                                the <span class="text-danger">.overflow-hidden</span> wrapper class.</p>
                            <div class="container">
                                <div class="row g-2">
                                    <div class="col-6">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div class="col-6">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div class="col-6">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div class="col-6">
                                        <div class="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                </div>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!-- End:: row-1 --> 

             <!-- Start:: row-2  --> 

            <Row>
            <Col xl={12}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                Row columns gutters
                            </div>
                        </CardHeader>
                        <CardBody>
                            <p>Gutter classes can also be added to <span class="text-danger">row
                                columns</span>.
                                In the following example, we use
                                responsive row columns and responsive gutter classes.
                            </p>
                            <div class="container">
                                <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div class="col">
                                        <div class="p-3 border bg-light">Row column</div>
                                    </div>
                                </div>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={12}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                No gutters
                            </div>
                        </CardHeader>
                        <CardBody>
                            <p>The gutters between columns in our predefined grid classes can be removed
                                with
                                <span class="text-danger"> .g-0</span>. This removes the negative <span
                                    class="text-danger">margins</span> from <span class="text-danger"> .row
                                </span> and the horizontal <span class="text-danger">padding </span>
                                from all immediate children columns.
                            </p>
                            <p>Need an edge-to-edge design? Drop the parent <span
                                class="text-danger">.container</span> or <span
                                    class="text-danger">.container-fluid</span> and
                                add <span class="text-danger">.mx-0</span> to the <span
                                    class="text-danger">.row</span> to prevent overflow.
                            </p>
                            <p>In practice, here’s how it looks. Note you can continue to use this with all
                                other predefined grid classes (including column widths, responsive tiers,
                                reorders, and more).</p>
                            <div class="row g-0">
                                <div class="col-sm-6 col-md-8 bd-example-grid">.col-sm-6 .col-md-8</div>
                                <div class="col-6 col-md-4 bd-example-grid">.col-6 .col-md-4</div>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>
            
             <!-- End:: row-2  -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/utilities/gutters/gutters.jsx

import MainLayout from "@/Layouts/layout";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const Gutters = () => {

    return (

        <Fragment>

            <Head title={"Gutters"} />

            <Pageheader title="Utilities" currentpage="Gutters" activepage="Gutters" />

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Horizontal gutters
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <p><span className="text-danger">.gx-*</span> classes can be used to control the
                                horizontal gutter widths. The <span className="text-danger">.container </span>
                                or <span className="text-danger"> .container-fluid</span> parent may need to be
                                adjusted if larger gutters are used
                                too to avoid unwanted overflow, using a matching padding utility. For
                                example,
                                in the following example we’ve increased the padding with <span
                                    className="text-danger">.px-4</span>:
                            </p>
                            <div className="container px-4 mb-3">
                                <div className="row gx-5 gy-3">
                                    <div className="col">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                </div>
                            </div>
                            <p>An alternative solution is to add a wrapper around the <span
                                className="text-danger">.row</span> with the <span
                                    className="text-danger">.overflow-hidden</span> class:
                            </p>
                            <div className="container overflow-hidden">
                                <div className="row gx-5 gy-3">
                                    <div className="col">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Vertical gutters
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <p><span className="text-danger">.gy-*</span> classes can be used to control the
                                vertical gutter widths. Like the
                                horizontal gutters, the vertical gutters can cause some overflow below the
                                .row
                                at the end of a page. If this occurs, you add a wrapper around <span
                                    className="text-danger">.row</span> with the
                                <span className="text-danger">.overflow-hidden</span> class:
                            </p>
                            <div className="container overflow-hidden">
                                <div className="row gy-5">
                                    <div className="col-6">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div className="col-6">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div className="col-6">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div className="col-6">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Horizontal & vertical gutters
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <p><span className="text-danger">.g-*</span> classes can be used to control the
                                horizontal gutter widths, for the
                                following example we use a smaller gutter width, so there won’t be a need to
                                add
                                the <span className="text-danger">.overflow-hidden</span> wrapper class.</p>
                            <div className="container">
                                <div className="row g-2">
                                    <div className="col-6">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div className="col-6">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div className="col-6">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                    <div className="col-6">
                                        <div className="p-3 border bg-light">Custom column padding</div>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-2  --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Row columns gutters
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <p>Gutter classes can also be added to <span className="text-danger">row
                                columns</span>.
                                In the following example, we use
                                responsive row columns and responsive gutter classes.
                            </p>
                            <div className="container">
                                <div className="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                    <div className="col">
                                        <div className="p-3 border bg-light">Row column</div>
                                    </div>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                No gutters
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <p>The gutters between columns in our predefined grid classes can be removed
                                with
                                <span className="text-danger"> .g-0</span>. This removes the negative <span
                                    className="text-danger">margins</span> from <span className="text-danger"> .row
                                </span> and the horizontal <span className="text-danger">padding </span>
                                from all immediate children columns.
                            </p>
                            <p>Need an edge-to-edge design? Drop the parent <span
                                className="text-danger">.container</span> or <span
                                    className="text-danger">.container-fluid</span> and
                                add <span className="text-danger">.mx-0</span> to the <span
                                    className="text-danger">.row</span> to prevent overflow.
                            </p>
                            <p>In practice, here’s how it looks. Note you can continue to use this with all
                                other predefined grid classes (including column widths, responsive tiers,
                                reorders, and more).</p>
                            <div className="row g-0">
                                <div className="col-sm-6 col-md-8 bd-example-grid">.col-sm-6 .col-md-8</div>
                                <div className="col-6 col-md-4 bd-example-grid">.col-6 .col-md-4</div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-2  --> */}

        </Fragment>
    )
};

// Assign layout
Gutters.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Gutters;
