// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/reusable-pages/blog/spk-searchcard.svelte
<script>
    import SpkTooltips from "@/shared/@spk/uielements/Tooltips/SpkTooltips.svelte";
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";

    export let search = {};
    export let cardClass = "";
</script>

<Card class={`custom-card shadow-none ${cardClass}`}>
    <CardBody>
        <div
            class="d-flex align-items-start flex-wrap gap-3 justify-content-between"
        >
            <div class="d-flex align-items-center">
                <div>
                    <span
                        class={`avatar avatar-lg avatar-rounded bg-${search.bgColor} bg-opacity-10 border`}
                    >
                        <Image src={search.imgSrc} alt="" />
                    </span>
                </div>
                <div class="ms-2">
                    <h6 class="fw-medium mb-0 d-flex align-items-center">
                        <a href="#!">{search.title}</a>
                    </h6>
                    <a href="#!">{search.subTitle}</a>
                </div>
            </div>
            <div class="btn-list">
                <!-- svelte-ignore a11y_consider_explicit_label -->
                <a
                    href="#!"
                    id={`SearcBook-${search.id}`}
                    class="btn btn-sm btn-icon btn-light"
                >
                    <span>
                        <i class="ri-heart-3-fill align-middle text-muted"></i>
                    </span>
                </a>
                <SpkTooltips
                    placement="top"
                    content="Add to favourite"
                    targetId={`SearcBook-${search.id}`}
                ></SpkTooltips>
                <!-- svelte-ignore a11y_consider_explicit_label -->
                <a
                    href="#!"
                    id={`Featured-${search.id}`}
                    class="btn btn-sm btn-icon btn-warning-light"
                >
                    <span>
                        <i class="ri-star-fill"></i>
                    </span>
                </a>
                <SpkTooltips
                    placement="top"
                    content="Featured Book"
                    targetId={`Featured-${search.id}`}
                ></SpkTooltips>
            </div>
        </div>
        <div class="popular-tags my-3">
            {#each search.tags ?? [] as tag}
                <a
                    href="#!"
                    class="badge rounded-pill bg-light text-default me-1"
                >
                    {tag}
                </a>
            {/each}
        </div>
        <div class="d-flex justify-content-between flex-wrap gap-2">
            <div>
                <span class="text-muted">Published On</span> -{" "}
                <span class="fw-medium mb-0">{search.date}</span>
            </div>
            <a href="#!" class="text-primary fw-semibold fs-14">
                Preview <i class="fe fe-arrow-right"></i>
            </a>
        </div>
    </CardBody>
</Card>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/reusable-pages/blog/spk-searchcard.jsx

import { Fragment } from "react";
import { Card } from "react-bootstrap";
import React from "react";
import SpkTooltips from "../../general-reusable/reusable-uielements/spk-tooltips";
import BaseLink from "@/shared/layouts-components/baselink/baselink";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import { Link } from "@inertiajs/react";


const SpkSearchCard = ({ search, cardClass = "" }) => {
    return (
        <Fragment>
            <Card className={`custom-card shadow-none ${cardClass}`}>
                <Card.Body>
                    <div className="d-flex align-items-start flex-wrap gap-3 justify-content-between">
                        <div className="d-flex align-items-center">
                            <div>
                                <span className={`avatar avatar-lg avatar-rounded bg-${search.bgColor} bg-opacity-10 border`}>
                                    <BaseImage src={search.imgSrc} alt="" />
                                </span>
                            </div>
                            <div className="ms-2">
                                <h6 className="fw-medium mb-0 d-flex align-items-center">
                                    <BaseLink href="#!">{search.title}</BaseLink>
                                </h6>
                                <BaseLink href="#!">{search.subTitle}</BaseLink>
                            </div>
                        </div>
                        <div className="btn-list">
                            <SpkTooltips placement="top" title="Add to favourite">
                                <Link onClick={(e) => {e.preventDefault()}} href="#!" className="btn btn-sm btn-icon btn-light">
                                    <span>
                                        <i className="ri-heart-3-fill align-middle text-muted"></i>
                                    </span>
                                </Link>
                            </SpkTooltips>
                            <SpkTooltips placement="top" title="Featured Book">
                                <Link href="#!" onClick={(e) => {e.preventDefault()}} className="btn btn-sm btn-icon btn-warning-light">
                                    <span>
                                        <i className="ri-star-fill"></i>
                                    </span>
                                </Link>
                            </SpkTooltips>
                        </div>
                    </div>
                    <div className="popular-tags my-3">
                        {search.tags.map((tag, index) => (
                            <BaseLink key={index} href="#!" className="badge rounded-pill bg-light text-default me-1">
                                {tag}
                            </BaseLink>
                        ))}
                    </div>
                    <div className="d-flex justify-content-between flex-wrap gap-2">
                        <div>
                            <span className="text-muted">Published On</span> -{" "}
                            <span className="fw-medium mb-0">{search.date}</span>
                        </div>
                        <BaseLink href="#!" className="text-primary fw-semibold fs-14">
                            Preview <i className="fe fe-arrow-right"></i>
                        </BaseLink>
                    </div>
                </Card.Body>
            </Card>
        </Fragment>
    );
};

export default SpkSearchCard;
