// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/reusable-pages/spk-profilecard.jsx

import { Fragment } from "react";
import { Card, Image } from "react-bootstrap";
import SpkButton from "../general-reusable/reusable-uielements/spk-buttons";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const SpkProfileCard = ({ profile, cardClass, bodyClass }) => {
  return (
    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className={bodyClass}>
          <div className="d-flex align-items-center gap-2 flex-wrap">
            <div className="lh-1">
              <span className="avatar avatar-lg avatar-rounded">
                <BaseImage src={profile.imgSrc} alt={profile.name} />
              </span>
            </div>
            <div className="flex-fill">
              <span className="fw-semibold d-block">{profile.name}</span>
              <span className="text-muted fs-13">{profile.mail}</span>
            </div>
            <div>
              <SpkButton Buttonvariant="" Customclass={`btn btn-${profile.color}-ghost`}><i className={`ri-user-${profile.icon}-line me-1`}></i>{profile.followers}</SpkButton>
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkProfileCard;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/reusable-pages/spk-profilecard.svelte
<script>
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";
    import SpkButton from "../uielements/Button/SpkButton.svelte";

    export let profile = {};
    export let cardClass = "";
    export let bodyClass = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class={bodyClass}>
        <div class="d-flex align-items-center gap-2 flex-wrap">
            <div class="lh-1">
                <span class="avatar avatar-lg avatar-rounded">
                    <Image src={profile.imgSrc} alt={profile.name} />
                </span>
            </div>
            <div class="flex-fill">
                <span class="fw-semibold d-block">{profile.name}</span>
                <span class="text-muted fs-13">{profile.mail}</span>
            </div>
            <div>
                <SpkButton
                    color=""
                    customClass={`btn btn-${profile.color}-ghost`}
                    ><i class={`ri-user-${profile.icon}-line me-1`}
                    ></i>{profile.followers}</SpkButton
                >
            </div>
        </div>
    </CardBody>
</Card>
