// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/reusable-pages/spk-testimonialcard.tsx

import { Fragment } from "react"
import { Card, Image } from "react-bootstrap";

interface Types {
    stars: any;
    description?: string;
    imgSrc?: any;
    title?: string;
    role?: string;
    name?:string;
}

interface SpkTestimonialcardProps {
    test: Types;
    cardClass?: string;
}

const SpkTestimonialcard: React.FC<SpkTestimonialcardProps> = ({ test, cardClass }) => {

    return (

        <Fragment>
            <Card className={`custom-card mb-0 ${cardClass}`}>
                <Card.Body className="p-5 pb-4">
                    <div className="d-flex align-items-center justify-content-between mb-3 flex-wrap">
                        <h5 className="fw-semibold mb-0">{test.title}</h5>
                        <div className="text-warning fs-14 my-auto">
                            {test.stars}
                        </div>
                    </div>
                    <p className="mb-3 text-muted">
                        {test.description}
                    </p>
                    <div className="d-flex align-items-start justify-content-end gap-2">
                        <div className="lh-1">
                            <span className="avatar avatar-md avatar-rounded">
                                <Image  src={test.imgSrc} alt="" />
                            </span>
                        </div>
                        <div>
                            <span className="d-block fw-semibold">{test.name}</span>
                            <span className="text-muted fs-13">{test.role}</span>
                        </div>
                    </div>
                </Card.Body>
            </Card>
        </Fragment>
    )

}
export default SpkTestimonialcard;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/reusable-pages/spk-testimonialcard.svelte
<script>
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";
    const basePath = __BASE_PATH__;

    export let test = {};
    export let cardClass = "";
</script>

<Card class={`custom-card mb-0 ${cardClass}`}>
    <CardBody class="p-5 pb-4">
        <div
            class="d-flex align-items-center justify-content-between mb-3 flex-wrap"
        >
            <h5 class="fw-semibold mb-0">{test.title}</h5>
            <div class="text-warning fs-14 my-auto">
                {@html test.stars}
            </div>
        </div>
        <p class="mb-3 text-muted">
            {test.description}
        </p>
        <div class="d-flex align-items-start justify-content-end gap-2">
            <div class="lh-1">
                <span class="avatar avatar-md avatar-rounded">
                    <Image src={`${basePath}${test.imgSrc}`} alt="" />
                </span>
            </div>
            <div>
                <span class="d-block fw-semibold">{test.name}</span>
                <span class="text-muted fs-13">{test.role}</span>
            </div>
        </div>
    </CardBody>
</Card>
