// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/pages/forms/form-elements/color-picker/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import { colorpicker1 } from "$lib/components/common/prism-code/formsprism";
    import { Input } from "@sveltestrap/sveltestrap";
    import { onMount } from "svelte";
    import ShowCode from "$lib/components/layout-components/showcode/ShowCode.svelte";

    //Classic method
    let pickrInstance;
    onMount(async () => {
        // Dynamically import Pickr only in the client-side environment
        if (typeof window !== "undefined") {
            const { default: Pickr } = await import("@simonwep/pickr");

            // Initialize Pickr once the component has mounted
            pickrInstance = Pickr.create({
                el: ".color-picker",
                theme: "classic", // or 'monolith', or 'nano'

                swatches: [
                    "rgba(244, 67, 54, 1)",
                    "rgba(233, 30, 99, 0.95)",
                    "rgba(156, 39, 176, 0.9)",
                    "rgba(103, 58, 183, 0.85)",
                    "rgba(63, 81, 181, 0.8)",
                    "rgba(33, 150, 243, 0.75)",
                    "rgba(3, 169, 244, 0.7)",
                    "rgba(0, 188, 212, 0.7)",
                    "rgba(0, 150, 136, 0.75)",
                    "rgba(76, 175, 80, 0.8)",
                    "rgba(139, 195, 74, 0.85)",
                    "rgba(205, 220, 57, 0.9)",
                    "rgba(255, 235, 59, 0.95)",
                    "rgba(255, 193, 7, 1)",
                ],

                components: {
                    preview: true,
                    opacity: true,
                    hue: true,

                    // Input / output Options
                    interaction: {
                        hex: true,
                        rgba: true,
                        hsla: true,
                        hsva: true,
                        cmyk: true,
                        input: true,
                        clear: true,
                        save: true,
                    },
                },
            });
        }
    });
    //Monolith method
    let colorPicker1:any;
    onMount(async () => {
        // Dynamically import Pickr only in the client-side environment
        const { default: Pickr } = await import("@simonwep/pickr");

        if (colorPicker1) {
            // Initialize Pickr once the component has mounted
            Pickr.create({
                el: colorPicker1,
                theme: "classic", // or 'monolith', or 'nano'
                default: "rgba(213, 221, 231, 1);",
                swatches: [
                    "rgba(244, 67, 54, 1)",
                    "rgba(233, 30, 99, 0.95)",
                    "rgba(156, 39, 176, 0.9)",
                    "rgba(103, 58, 183, 0.85)",
                    "rgba(63, 81, 181, 0.8)",
                    "rgba(33, 150, 243, 0.75)",
                    "rgba(3, 169, 244, 0.7)",
                    "rgba(0, 188, 212, 0.7)",
                    "rgba(0, 150, 136, 0.75)",
                    "rgba(76, 175, 80, 0.8)",
                    "rgba(139, 195, 74, 0.85)",
                    "rgba(205, 220, 57, 0.9)",
                    "rgba(255, 235, 59, 0.95)",
                    "rgba(255, 193, 7, 1)",
                ],
                components: {
                    preview: true,
                    opacity: true,
                    hue: false,
                    interaction: {
                        input: true,
                        clear: true,
                        save: true,
                    },
                },
            });
        }
    });
    //Nano Method
    let colorPicker2:any;
    onMount(async () => {
        // Dynamically import Pickr only in the client-side environment
        const { default: Pickr } = await import("@simonwep/pickr");

        if (colorPicker1) {
            // Initialize Pickr once the component has mounted
            Pickr.create({
                el: colorPicker2,
                theme: "nano", // or 'monolith', or 'nano'
                theme: "nano", // or 'monolith', or 'nano'
                default: "rgba(185, 93, 75, 1);",
                swatches: [
                    "rgba(244, 67, 54, 1)",
                    "rgba(233, 30, 99, 0.95)",
                    "rgba(156, 39, 176, 0.9)",
                    "rgba(103, 58, 183, 0.85)",
                    "rgba(63, 81, 181, 0.8)",
                    "rgba(33, 150, 243, 0.75)",
                    "rgba(3, 169, 244, 0.7)",
                    "rgba(0, 188, 212, 0.7)",
                    "rgba(0, 150, 136, 0.75)",
                    "rgba(76, 175, 80, 0.8)",
                    "rgba(139, 195, 74, 0.85)",
                    "rgba(205, 220, 57, 0.9)",
                    "rgba(255, 235, 59, 0.95)",
                    "rgba(255, 193, 7, 1)",
                ],

                components: {
                    preview: true,
                    opacity: true,
                    hue: false,

                    // Input / output Options
                    interaction: {
                        hex: true,
                        input: true,
                        clear: true,
                        save: true,
                    },
                },
            });
        }
    });
</script>

<!-- Page Title -->
<svelte:head>
    <title>ColorPicker | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Color Pickers"
   activepage="Forms"
    subTitle=" Form Elements"
    page="Color Pickers"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->
<div class="row">
    <div class="col-xl-12">
      <ShowCode title="Checks"  svelteCode={colorpicker1}>
        <Input type="color" class="form-control form-control-color border-0"
        id="exampleColorInput" value="#136ad0" title="Choose your color" />
      </ShowCode>
    </div>
    <div class="col-xl-12">
        <div class="card custom-card">
            <div class="card-header">
                <div class="card-title">
                    Classic
                </div>
            </div>
            <div class="card-body d-flex justify-content-between">
                <div>
                    <div class="color-picker"></div>
                </div>
                <div>
                  <div class="color-picker" bind:this={colorPicker1}></div>
                </div>
                <div>
                    <div class="theme-container2"></div>
                    <div class="color-picker" bind:this={colorPicker2}></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/forms/form-elements/color-picker/color-picker.jsx

import React, { Fragment, useState } from "react";
import { Card, Col, Form, Row } from "react-bootstrap";
import { ColorPicker, useColor } from "react-color-palette";

import { ChromePicker } from 'react-color';
import ShowCode from "../../../../../shared/layouts-components/showcode/showcode";
import { Colorpicker } from "../../../../../shared/data/prism-code/forms-prism";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../../shared/layouts-components/pageheader/pageheader";
import SpkButton from "../../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import MainLayout from "@/Layouts/layout";


const ColorPickers = () => {

    const [isVisible, setIsVisible] = useState(false);

    const toggleVisibility = () => {
        setIsVisible(!isVisible);
    };
    //color picker
    const [color, setColor] = useColor("#561ecb");

    //color picker
    const [color2, setColor2] = useState("#6c5ffc");
    const [showColorPicker, setShowColorPicker] = useState(false);
    const handleChangeComplete = (color) => {
        console.log(color);
    };

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Forms-Color Pickers" />

            <Pageheader title="Forms" subtitle="Form Elements" currentpage="Color Pickers" activepage="Color Pickers" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Classic
                            </div>
                        </Card.Header>
                        <Card.Body className="d-flex justify-content-between flex-wrap custom-form-color">
                            <Col xl={3} md={4} className="mt-2">
                                <SpkButton Buttonvariant="primary" onClickfunc={toggleVisibility} Customclass='btn !py-1 !px-2 mb-2 !text-[0.75rem] !m-0 !gap-0 !font-medium'>
                                    <i className="ri-palette-line"></i>
                                </SpkButton>
                                {isVisible && (
                                    <ColorPicker color={color} onChange={setColor} hideInput={["hex", "hsv"]} />
                                )}
                            </Col>
                            <Col xl={6} className="mt-2">
                                <SpkButton Buttonvariant="primary" Customclass='pcr-button btn-md mb-3' onClickfunc={() => setShowColorPicker(showColorPicker => !showColorPicker)}>{showColorPicker ? "Close Picker" : "Pick Color"}</SpkButton>
                                {showColorPicker && (<ChromePicker disableAlpha={true} color={color2} onChange={(updatedColor) => setColor2(updatedColor.hex)} onChangeComplete={handleChangeComplete} />
                                )}
                            </Col>

                        </Card.Body>
                    </Card>
                </Col>

                <Col xl={12}>
                    <ShowCode title="Bootstrap Color Picker" customCardClass="custom-card" customCardBodyClass="" reactCode={Colorpicker}>
                        <Form.Control type="color" className="form-control-color border-0" id="exampleColorInput" defaultValue="#136ad0" title="Choose your color" />
                    </ShowCode>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
ColorPickers.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ColorPickers;
