// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/dashboards/ecommerce/add-product.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import FilePond, { registerPlugin } from "svelte-filepond";
    import FilePondPluginImageExifOrientation from "filepond-plugin-image-exif-orientation";
    import FilePondPluginImagePreview from "filepond-plugin-image-preview";
    import "quill/dist/quill.snow.css";
    import {
        Card,
        CardBody,
        CardHeader,
        Col,
        Input,
        Label,
        Row,
    } from "@sveltestrap/sveltestrap";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import { Editor } from "@tadashi/svelte-editor-quill";
    import { DateInput } from "date-picker-svelte";
    import Select from "svelte-select";
    import {
        Availableselect,
        Brandselect,
        Categoryselect,
        Colorselect,
        Genderselect,
        Productselect,
        Publishselect,
        Sizeselect,
    } from "@/shared/data/dashboards/ecommerce/addproductsdata";

    // Register the plugins
    registerPlugin(
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
    );

    let date = null;
    let date1 = null;

    const options = {
        theme: "snow",
    };

    let data = `<h4><b class="ql-size-large">Quill Snow</b> is a free, open source <a href="https://github.com/quilljs/quill/" target="_blank">Quill Editor</a> built for the modern web. With its <a href="https://quilljs.com/docs/modules/" target="_blank">modular architecture</a> and expressive API, it is completely customizable to fit any need.</h4>
                                    <p><br></p>
                                    <ol>
                                        <li class="ql-size-normal">Write text select and edit with multiple options.</li>
                                        <li class="">This is quill snow editor.</li>
                                        <li class="">Easy to customize and flexible.</li>
                                    </ol>
                                    <p><br></p>
                                    <h4>Quill officially supports a standard toolbar theme <a href="https://github.com/quilljs/quill/" target="_blank">"Snow"</a> and a floating tooltip theme <a href="https://github.com/quilljs/quill/" target="_blank">"Bubble"</a></h4>
                                `;
    let text = "";
    let html = "";

    const onTextChange = (event) => {
        ({ text, html } = event?.detail ?? {});
        data = html;
    };

    let filterText = "";

    let value = [];

    let items = [
       
    ];

    function handleFilter(e) {
        if (value?.find((i) => i.label === filterText)) return;
        if (e.detail.length === 0 && filterText.length > 0) {
            const prev = items.filter((i) => !i.created);
            items = [
                ...prev,
                { value: filterText, label: filterText, created: true },
            ];
        }
    }

    function handleChange(e) {
        items = items.map((i) => {
            delete i.created;
            return i;
        });
    }

</script>

<!-- Page Title -->
<svelte:head>
    <title>AddProduct | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Add Product"
    subTitle="Ecommerce"
    activepage="Dashboards"
    page="Add Product"
/>
<!-- Page Header Close -->

<!-- Start:: row-1 -->

<Row>
    <Col xl={3}>
        <Row>
            <Col xl={12}>
                <Card class="custom-card">
                    <CardHeader>
                        <div class="card-title">Product Images</div>
                    </CardHeader>
                    <CardBody>
                        <FilePond
                            class="multiple-filepond"
                            name="filepond"
                            labelIdle={`Drag & Drop your file here or click`}
                            stylePanelLayout=" "
                            styleLoadIndicatorPosition="center bottom"
                            styleButtonRemoveItemPosition="center bottom"
                            allowMultiple={true}
                            maxFiles={6}
                        />
                        <!-- svelte-ignore a11y_label_has_associated_control -->
                        <label
                            class="form-label text-muted mt-1 fs-13 mb-0 fw-normal"
                            >Upload 6 images, ensuring uniform size (max 2MB).
                            Changes can be made after 24 hours.
                        </label>
                    </CardBody>
                </Card>
            </Col>
            <Col xl={12}>
                <Card class="custom-card">
                    <CardHeader>
                        <div class="card-title">Product Details</div>
                    </CardHeader>
                    <CardBody>
                        <Row class="gy-2">
                            <Col
                                xl={12}
                                class="custom-picker custom-date-picker"
                            >
                                <Label for="publish-date" class=""
                                    >Publish Date</Label
                                >
                                <DateInput
                                    bind:value={date}
                                    class="form-control "
                                    format="yy-MM-dd"
                                    placeholder="Choose date"
                                    closeOnSelection={true}
                                    dynamicPositioning={true}
                                />
                            </Col>
                            <Col
                                xl={12}
                                class="custom-picker custom-date-picker"
                            >
                                <Label for="publish-time" class=""
                                    >Publish Time</Label
                                >
                                <DateInput
                                    bind:value={date1}
                                    class="form-control "
                                    format="HH:mm"
                                    timePrecision="minute"
                                    placeholder="Choose Time"
                                    dynamicPositioning={true}
                                    closeOnSelection={true}
                                />
                            </Col>
                            <Col xl={12}>
                                <Label for="product-status-add" class=""
                                    >Published Status</Label
                                >
                                <Select
                                    items={Publishselect}
                                    class="basic-multi-select"
                                    clearable={false}
                                    showChevron={true}
                                />
                            </Col>
                            <Col xl={12}>
                                <Label for="product-tags" class=""
                                    >Product Tags</Label
                                >
                                <Select
                            on:change={handleChange}
                            multiple
                            on:filter={handleFilter}
                            bind:filterText
                            bind:value
                            {items}
                            showChevron={false}
                            clearable={false}
                            placeholder="Add New Tags"
                            placeholderAlwaysShow={true}
                        >
                            <div slot="item" let:item>
                                {item.created ? "Add new: " : ""}
                                {item.label}
                            </div>
                        </Select>
                            </Col>
                            <Col xl={12}>
                                <Label for="product-status-add1" class=""
                                    >Availability</Label
                                >
                                <Select
                                    items={Availableselect}
                                    class="basic-multi-select"
                                    searchable={false}
                                    clearable={false}
                                    showChevron={true}
                                />
                            </Col>
                        </Row>
                    </CardBody>
                </Card>
            </Col>
            <Col xl={12}>
                <Card class="custom-card">
                    <CardHeader>
                        <div class="card-title">Warrenty Documents</div>
                    </CardHeader>
                    <CardBody>
                        <FilePond
                            class="multiple-filepond"
                            name="filepond"
                            labelIdle={`Drag & Drop your file here or click`}
                            stylePanelLayout=" "
                            styleLoadIndicatorPosition="center bottom"
                            styleButtonRemoveItemPosition="center bottom"
                            allowMultiple={true}
                        />
                        <!-- svelte-ignore a11y_label_has_associated_control -->
                        <label
                            class="form-label text-muted mt-1 fs-13 fw-normal mb-0"
                            >Upload warranty document (PDF/DOC, max 5MB).</label
                        >
                    </CardBody>
                </Card>
            </Col>
        </Row>
    </Col>
    <Col xl={9}>
        <Card class="custom-card shadow-none mb-0 border-0">
            <CardBody class="p-0">
                <Row class="gy-3">
                    <Col xl={12}>
                        <Label for="product-name-add" class=""
                            >Product Name</Label
                        >
                        <Input
                            type="text"
                            class=""
                            id="product-name-add"
                            placeholder="Name"
                        />
                        <Label
                            for="product-name-add"
                            class=" mt-1 fs-12 fw-normal text-muted mb-0"
                            >*Product Name should not exceed 30 characters</Label
                        >
                    </Col>
                    <Col xl={6}>
                        <Label for="product-category-add" class=""
                            >Category</Label
                        >
                        <Select
                            items={Categoryselect}
                            class="basic-multi-select"
                            clearable={false}
                            showChevron={true}
                            placeholder="Category"
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="product-gender-add" class="">Gender</Label>
                        <Select
                            items={Genderselect}
                            class="basic-multi-select"
                            clearable={false}
                            showChevron={true}
                            placeholder="Select"
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="product-size-add" class="">Size</Label>
                        <Select
                            items={Sizeselect}
                            class="basic-multi-select"
                            clearable={false}
                            showChevron={true}
                            placeholder="Select"
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="product-brand-add" class="">Brand</Label>
                        <Select
                            items={Brandselect}
                            class="basic-multi-select"
                            clearable={false}
                            showChevron={true}
                            placeholder="Select"
                        />
                    </Col>
                    <Col xl={6} class="color-selection">
                        <Label for="product-color-add" class="">Colors</Label>
                        <Select
                            items={Colorselect}
                            class="basic-multi-select"
                            placeholder="Select"
                            multiFullItemClearable
                            multiple
                            showChevron={false}
                            clearable={false}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="product-cost-add" class="">Enter Cost</Label
                        >
                        <Input
                            type="text"
                            class=""
                            id="product-cost-add"
                            placeholder="Cost"
                        />
                        <Label
                            for="product-cost-add"
                            class=" mt-1 fs-12 fw-normal text-muted mb-0"
                            >*Mention final price of the product</Label
                        >
                    </Col>
                    <Col xl={12}>
                        <Label for="product-description-add" class=""
                            >Product Description</Label
                        >
                        <Input
                            type="textarea"
                            class=""
                            id="product-description-add"
                            rows={2}
                        />
                        <Label
                            for="product-description-add"
                            class=" mt-1 fs-12 fw-normal text-muted mb-0"
                            >*Description should not exceed 500 letters</Label
                        >
                    </Col>
                    <Col xl={12}>
                        <Label class="">Product Features</Label>
                        <div id="product-features">
                            <Editor
                                {options}
                                {data}
                                on:text-change={onTextChange}
                            />
                        </div>
                    </Col>
                    <Col xl={4}>
                        <Label for="product-actual-price" class=""
                            >Actual Price</Label
                        >
                        <Input
                            type="text"
                            class=""
                            id="product-actual-price"
                            placeholder="Actual Price"
                        />
                    </Col>
                    <Col xl={4}>
                        <Label for="product-dealer-price" class=""
                            >Dealer Price</Label
                        >
                        <Input
                            type="text"
                            class=""
                            id="product-dealer-price"
                            placeholder="Dealer Price"
                        />
                    </Col>
                    <Col xl={4}>
                        <Label for="product-discount" class="">Discount</Label>
                        <Input
                            type="text"
                            class=""
                            id="product-discount"
                            placeholder="Discount in %"
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="product-type" class="">Product Type</Label>
                        <Input
                            type="text"
                            class=""
                            id="product-type"
                            placeholder="Type"
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="product-discount" class=""
                            >Item Weight</Label
                        >
                        <Input
                            type="text"
                            class=""
                            id="product-discount1"
                            placeholder="Weight in gms"
                        />
                    </Col>
                </Row>
            </CardBody>
        </Card>
    </Col>
    <div
        class="px-4 py-3 border-top border-block-start-dashed d-sm-flex justify-content-end mt-3"
    >
        <SpkButton color="primary-light" customClass="me-2 mb-2 mb-sm-0"
            >Add Product<i class="bi bi-plus-lg ms-2"></i></SpkButton
        >
        <SpkButton color="success-light" customClass="mb-2 mb-sm-0"
            >Save Product<i class="bi bi-download ms-2"></i></SpkButton
        >
    </div>
</Row>

<!-- End:: row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/ecommerce/addproduct/Add-product.jsx

import React, { Fragment, useState } from "react";
import { Card, Col, Form, Row } from "react-bootstrap";
import { FilePond } from "react-filepond";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import SpkDatepickr from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-datepicker";
import SpkSelect from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import { Availableselect, Brandselect, Categoryselect, Colorselect, Genderselect, Productselect, Publishselect, Sizeselect } from "../../../../shared/data/dashboards/ecommerce/addproductsdata";
import SpkSunEditor from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-suneditor";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import MainLayout from "@/Layouts/layout";


const AddProduct = () => {

    const [files, setFiles] = useState([]);
    const [files1, setFiles1] = useState([]);

    const [dates, setDates] = useState({});
    const handleDateChange = (key, date) => {
        if (date) {
            setDates((prevDates) => ({
                ...prevDates,
                [key]: date,
            }));
        } else {
            setDates((prevDates) => {
                const { [key]: removedKey, ...rest } = prevDates;
                return rest;
            });
        }
    };

    return (
        <Fragment>


            {/* <!-- Page Header --> */}

            <Head title="Dashboards-Add Products" />

            <Pageheader title="Dashboards" subtitle="Ecommerce" currentpage="Add Product" activepage="Add Product" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={3}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Product Images
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <FilePond className="multiple-filepond" files={files} onupdatefiles={setFiles} allowMultiple={true} maxFiles={6} server="/api" name="files" labelIdle='Drag & Drop your file here or click' />
                            <label className="form-label text-muted mt-1 fs-13 mb-0 fw-normal">Upload 6 images, ensuring uniform size (max 2MB). Changes can be made after 24 hours. </label>
                        </Card.Body>
                    </Card>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Product Details
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <Row className="gy-2">
                                <Col xl={12} className="custom-picker">
                                    <Form.Label htmlFor="publish-date" className="">Publish Date</Form.Label>
                                    <SpkDatepickr className="form-control flatpickr-input" selected={dates["startDate"] ? new Date(dates["startDate"]) : null} onChange={(date) => handleDateChange("startDate", date)} placeholderText='Choose Date' />
                                </Col>
                                <Col xl={12} className="custom-picker">
                                    <Form.Label htmlFor="publish-time" className="">Publish Time</Form.Label>
                                    <SpkDatepickr className="form-control " selected={dates["limitPicker"] ? new Date(dates["limitPicker"]) : null} onChange={(date) => handleDateChange("limitPicker", date)} showTimeSelect showTimeSelectOnly timeIntervals={15} Caption="Time" dateFormat="h:mm aa" placeholderText='Choose Time' />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="product-status-add" className="">Published Status</Form.Label>
                                    <SpkSelect name="colors" option={Publishselect} mainClass="basic-multi-select" menuplacement='auto' classNameprefix="Select2" placeholder="Select" />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="product-tags" className="">Product Tags</Form.Label>
                                    <SpkSelect multi name="colors" option={Productselect}  mainClass="basic-multi-select" searchable menuplacement='auto' classNameprefix="Select2" placeholder="Select" />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="product-status-add1" className="">Availability</Form.Label>
                                    <SpkSelect name="colors" option={Availableselect} mainClass="basic-multi-select" menuplacement='auto' classNameprefix="Select2" placeholder="Select" />
                                </Col>
                            </Row>
                        </Card.Body>
                    </Card>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Warrenty Documents
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <FilePond className="multiple-filepond" files={files1} onupdatefiles={setFiles1} allowMultiple={true} maxFiles={6} server="/api" name="files" labelIdle='Drag & Drop your file here or click' />
                            <Form.Label className="form-label text-muted mt-1 fs-13 fw-normal mb-0">Upload warranty document (PDF/DOC, max 5MB).</Form.Label>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={9}>
                    <Card className="custom-card shadow-none mb-0 border-0">
                        <Card.Body className="p-0">
                            <Row className="gy-3">
                                <Col xl={12}>
                                    <Form.Label htmlFor="product-name-add" className="">Product Name</Form.Label>
                                    <Form.Control type="text" className="" id="product-name-add" placeholder="Name" />
                                    <Form.Label htmlFor="product-name-add" className=" mt-1 fs-12 fw-normal text-muted mb-0">*Product Name should not exceed 30 characters</Form.Label>
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="product-category-add" className="">Category</Form.Label>
                                    <SpkSelect name="colors" option={Categoryselect} mainClass="basic-multi-select" menuplacement='auto' classNameprefix="Select2" placeholder="Category" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="product-gender-add" className="">Gender</Form.Label>
                                    <SpkSelect name="colors" option={Genderselect} mainClass="basic-multi-select" menuplacement='auto' classNameprefix="Select2" placeholder="Select" />
                                </Col>
                                <Col xl={6}>
                                    <label htmlFor="product-size-add" className="">Size</label>
                                    <SpkSelect name="colors" option={Sizeselect} mainClass="basic-multi-select" menuplacement='auto' classNameprefix="Select2" placeholder="Select" />

                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="product-brand-add" className="">Brand</Form.Label>
                                    <SpkSelect name="colors" option={Brandselect} mainClass="basic-multi-select" menuplacement='auto' classNameprefix="Select2" placeholder="Select" />
                                </Col>
                                <Col xl={6} className="color-selection">
                                    <Form.Label htmlFor="product-color-add" className="">Colors</Form.Label>
                                    <SpkSelect multi name="colors" option={Colorselect} mainClass="basic-multi-select" menuplacement='auto' classNameprefix="Select2" placeholder="Select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="product-cost-add" className="">Enter Cost</Form.Label>
                                    <Form.Control type="text" className="" id="product-cost-add" placeholder="Cost" />
                                    <Form.Label htmlFor="product-cost-add" className="form-label mt-1 fs-12 op-5 text-muted mb-0">*Mention final price of the product</Form.Label>
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="product-description-add" className="">Product Description</Form.Label>
                                    <Form.Control as="textarea" className="" id="product-description-add" rows={2} />
                                    <Form.Label htmlFor="product-description-add" className=" form-label mt-1 fs-12 op-5 text-muted mb-0">*Description should not exceed 500 letters</Form.Label>
                                </Col>
                                <Col xl={12}>
                                    <Form.Label className="">Product Features</Form.Label>
                                    <div id="product-features">
                                        <SpkSunEditor height={'200px'} />
                                    </div>
                                </Col>
                                <Col xl={4}>
                                    <Form.Label htmlFor="product-actual-price" className="">Actual Price</Form.Label>
                                    <Form.Control type="text" className="" id="product-actual-price" placeholder="Actual Price" />
                                </Col>
                                <Col xl={4}>
                                    <Form.Label htmlFor="product-dealer-price" className="">Dealer Price</Form.Label>
                                    <Form.Control type="text" className="" id="product-dealer-price" placeholder="Dealer Price" />
                                </Col>
                                <Col xl={4}>
                                    <Form.Label htmlFor="product-discount" className="">Discount</Form.Label>
                                    <Form.Control type="text" className="" id="product-discount" placeholder="Discount in %" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="product-type" className="">Product Type</Form.Label>
                                    <Form.Control type="text" className="" id="product-type" placeholder="Type" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="product-discount" className="">Item Weight</Form.Label>
                                    <Form.Control type="text" className="" id="product-discount1" placeholder="Weight in gms" />
                                </Col>
                            </Row>
                        </Card.Body>
                    </Card>
                </Col>
                <div className="px-4 py-3 border-top border-block-start-dashed d-sm-flex justify-content-end mt-3">
                    <SpkButton Buttonvariant="primary-light" Customclass="me-2 mb-2 mb-sm-0">Add Product<i className="bi bi-plus-lg ms-2"></i></SpkButton>
                    <SpkButton Buttonvariant="success-light" Customclass="mb-2 mb-sm-0">Save Product<i className="bi bi-download ms-2"></i></SpkButton>
                </div>
            </Row>

            {/* <!-- End:: row-1 --> */}

        </Fragment>
    )
};

AddProduct.layout = (page) => <MainLayout>{page}</MainLayout>;
export default AddProduct;
