// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/jobs/job-post/job-post.jsx

import React, { Fragment } from "react";
import { Card, Col, Form, Row } from "react-bootstrap";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import SpkSelect from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import { CategoriesSelect, CountrySelect, Employeesname, Genderselect, JobSelect, Languagesselect, PrioritySelect, Qualificationselect, Salaryselect, Skillselect, Vacancieselect, WorkSelect } from "../../../../shared/data/dashboards/jobs/jobpostdata";
import SpkDatepickr from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-datepicker";
import MainLayout from "@/Layouts/layout";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const PostJob = () => {

    const today = new Date();
    const nextWeek = new Date();
    nextWeek.setDate(today.getDate() + 7);

    const [dateRange, setDateRange] = React.useState([today, nextWeek]);
    const [startDate, endDate] = dateRange;

    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Jobs-Job Post" />

            <Pageheader title="Dashboards" subtitle="Jobs" currentpage="Job Post" activepage="Job Post" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xxl={3} xl={4} className="">
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Assign To Employer</div>
                        </Card.Header>
                        <Card.Body>
                            <Col xl={12}>
                                <Form.Label className="form-label">Employer Name</Form.Label>
                                <SpkSelect option={Employeesname} mainClass="" defaultvalue={[Employeesname[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                            </Col>
                        </Card.Body>
                    </Card>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Company Details</div>
                        </Card.Header>
                        <Card.Body>
                            <Row className="gy-3">
                                <Col xl={12}>
                                    <Form.Label htmlFor="Company-Name" className="">Company Name</Form.Label>
                                    <Form.Control type="text" className="" id="Company-Name" placeholder="Company Name" defaultValue="Obligation Pvt.Ltd" />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="Company-Website" className="">Company Website</Form.Label>
                                    <Form.Control type="text" className="" id="Company-Website" placeholder="Company Website" defaultValue="http//www.obligationpvtltd.com" />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label className="">Country</Form.Label>
                                    <SpkSelect option={CountrySelect} mainClass="" defaultvalue={[CountrySelect[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="Company-Address" className="">Address</Form.Label>
                                    <Form.Control type="text" className="" id="Company-Address" placeholder="Company Address" defaultValue="USA" />
                                </Col>
                            </Row>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xxl={9} xl={8} className="">
                    <Card className="custom-card">
                        <Card.Header className="justify-content-between">
                            <div className="card-title">
                                Post New Job
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <Row className="gy-4 mb-4">
                                <Col xl={6}>
                                    <Form.Label htmlFor="job-title" className="">Job Title</Form.Label>
                                    <Form.Control type="text" className="" id="job-title" placeholder="Job Title" defaultValue="Web Developer" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Job Category</Form.Label>
                                    <SpkSelect option={CategoriesSelect} mainClass="" defaultvalue={[CategoriesSelect[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Working Experience</Form.Label>
                                    <SpkSelect option={WorkSelect} mainClass="" defaultvalue={[WorkSelect[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Job Type</Form.Label>
                                    <SpkSelect option={JobSelect} mainClass="" defaultvalue={[JobSelect[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Priority</Form.Label>
                                    <SpkSelect option={PrioritySelect} mainClass="" defaultvalue={[PrioritySelect[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Vacancies</Form.Label>
                                    <SpkSelect option={Vacancieselect} mainClass="" defaultvalue={[Vacancieselect[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Salary</Form.Label>
                                    <SpkSelect option={Salaryselect} mainClass="" defaultvalue={[Salaryselect[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="skills" className="">Skills :</Form.Label>
                                    <SpkSelect option={Skillselect} multi mainClass="" defaultvalue={[Skillselect[1], Skillselect[0], Skillselect[2]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6} className="job-deadline-column">
                                    <Form.Label htmlFor="job-deadline" className="">Job Deadline</Form.Label>
                                    <SpkDatepickr className="form-control breadcrumb-input datepicker-input" placeholderText="Choose date" startDate={startDate} endDate={endDate} selectsRange={true} onChange={(update) => setDateRange(update)} />

                                </Col>
                                <Col xl={6}>
                                    <Form.Label className="">Gender Requirement</Form.Label>
                                    <SpkSelect option={Genderselect} mainClass="" defaultvalue={[Genderselect[0]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="language" className="">Languages :</Form.Label>
                                    <SpkSelect option={Languagesselect} multi mainClass="" defaultvalue={[Languagesselect[0], Languagesselect[3]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={6}>
                                    <Form.Label htmlFor="qualification" className="">Qualification :</Form.Label>
                                    <SpkSelect option={Qualificationselect} multi mainClass="" defaultvalue={[Qualificationselect[0], Qualificationselect[3], Qualificationselect[2]]} menuplacement='auto' classNameprefix="Select2" name="Category-select" />
                                </Col>
                                <Col xl={12}>
                                    <Form.Label htmlFor="job-description" className="">Job Description :</Form.Label>
                                    <Form.Control as="textarea" className="form-control" id="job-description" rows={4} defaultValue={"Lorem ipsum dolor sit amet consectetur adipisicing elit. At sit impedit, officiis non minima saepe voluptates a magnam enim sequi porro veniam ea suscipit dolorum vel mollitia voluptate iste nemo!"} />
                                </Col>
                            </Row>
                        </Card.Body>
                        <Card.Footer className="text-end">
                            <BaseLink href="#!" className="btn btn-primary btn-wave waves-effect waves-light">
                                <i className="bi bi-plus-circle"></i> Post Job
                            </BaseLink>
                        </Card.Footer>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
PostJob.layout = (page) => <MainLayout>{page}</MainLayout>;
export default PostJob;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/dashboards/jobs/job-post/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import {
        CategoriesSelect,
        CountrySelect,
        Employeesname,
        Genderselect,
        JobSelect,
        Languagesselect,
        PrioritySelect,
        Qualificationselect,
        Salaryselect,
        Skillselect,
        Vacancieselect,
        WorkSelect,
    } from "$lib/data/dashboards/jobs/jobpostdata";
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Col,
        Input,
        Label,
        Row,
    } from "@sveltestrap/sveltestrap";
    import { DateInput } from "date-picker-svelte";
    import Select from "svelte-select";

    let date = new Date();
    let date1 = new Date();
</script>

<!-- Page Title -->
<svelte:head>
    <title>JobPost | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<!-- Page Header -->
<Pageheader
    homepage="Job Post"
    subTitle="Jobs"
    activepage="Dashboards"
    page="Job Post"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xxl={3} xl={4} class="">
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Assign To Employer</div>
            </CardHeader>
            <CardBody>
                <Col xl={12}>
                     <Label for="Company-Name" class="">Employer Name</Label>
                    <Select
                        items={Employeesname}
                        clearable={false}
                                    showChevron={true}
                        value={Employeesname[0]}

                    />
                </Col>
            </CardBody>
        </Card>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Company Details</div>
            </CardHeader>
            <CardBody>
                <Row class="gy-3">
                    <Col xl={12}>
                        <Label for="Company-Name" class="">Company Name</Label>
                        <Input
                            type="text"
                            class=""
                            id="Company-Name"
                            placeholder="Company Name"
                            defaultValue="Obligation Pvt.Ltd"
                        />
                    </Col>
                    <Col xl={12}>
                        <Label for="Company-Website" class=""
                            >Company Website</Label
                        >
                        <Input
                            type="text"
                            class=""
                            id="Company-Website"
                            placeholder="Company Website"
                            defaultValue="http//www.obligationpvtltd.com"
                        />
                    </Col>
                    <Col xl={12}>
                        <Label class="">Country</Label>
                        <Select
                            items={CountrySelect}
                            clearable={false}
                                    showChevron={true}
                            value={CountrySelect[0]}
                        />
                    </Col>
                    <Col xl={12}>
                        <Label for="Company-Address" class="">Address</Label>
                        <Input
                            type="text"
                            class=""
                            id="Company-Address"
                            placeholder="Company Address"
                            defaultValue="USA"
                        />
                    </Col>
                </Row>
            </CardBody>
        </Card>
    </Col>
    <Col xxl={9} xl={8} class="">
        <Card class="custom-card">
            <CardHeader class="justify-content-between">
                <div class="card-title">Post New Job</div>
            </CardHeader>
            <CardBody>
                <Row class="gy-4 mb-4">
                    <Col xl={6}>
                        <Label for="job-title" class="">Job Title</Label>
                        <Input
                            type="text"
                            class=""
                            id="job-title"
                            placeholder="Job Title"
                            defaultValue="Web Developer"
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Job Category</Label>
                        <Select
                            items={CategoriesSelect}
                            value={CategoriesSelect[0]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Working Experience</Label>
                        <Select
                            items={WorkSelect}
                            value={WorkSelect[0]}
                           clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Job Type</Label>
                        <Select
                            items={JobSelect}
                            value={JobSelect[0]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Priority</Label>
                        <Select
                            items={PrioritySelect}
                            value={PrioritySelect[0]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Vacancies</Label>
                        <Select
                            items={Vacancieselect}
                            value={Vacancieselect[0]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Salary</Label>
                        <Select
                            items={Salaryselect}
                            value={Salaryselect[0]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="skills" class="">Skills :</Label>
                        <Select
                            multiFullItemClearable
                            multiple
                            items={Skillselect}
                            value={[
                                Skillselect[1],
                                Skillselect[0],
                                Skillselect[2],
                            ]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6} class="job-deadline-column">
                        <Label for="job-deadline" class="">Job Deadline</Label>
                        <DateInput
                            bind:value={date}
                            class="form-control flatpickr-input custom-date-picker"
                            format="yy-MM-dd"
                            closeOnSelection={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label class="">Gender Requirement</Label>
                        <Select
                            items={Genderselect}
                            value={Genderselect[0]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="language" class="">Languages :</Label>
                        <Select
                            multiFullItemClearable
                            multiple
                            items={Languagesselect}
                            value={[Languagesselect[0], Languagesselect[3]]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={6}>
                        <Label for="qualification" class=""
                            >Qualification :</Label
                        >
                        <Select
                            multiFullItemClearable
                            multiple
                            items={Qualificationselect}
                            value={[
                                Qualificationselect[0],
                                Qualificationselect[3],
                                Qualificationselect[2],
                            ]}
                            clearable={false}
                                    showChevron={true}
                        />
                    </Col>
                    <Col xl={12}>
                        <Label for="job-description" class=""
                            >Job Description :</Label
                        >
                        <Input
                            type="textarea"
                            class="form-control"
                            id="job-description"
                            rows={4}
                            defaultValue={"Lorem ipsum dolor sit amet consectetur adipisicing elit. At sit impedit, officiis non minima saepe voluptates a magnam enim sequi porro veniam ea suscipit dolorum vel mollitia voluptate iste nemo!"}
                        />
                    </Col>
                </Row>
            </CardBody>
            <CardFooter class="text-end">
                <a
                    href="#!"
                    class="btn btn-primary btn-wave waves-effect waves-light"
                >
                    <i class="bi bi-plus-circle"></i> Post Job
                </a>
            </CardFooter>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->
