// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/ui-elements/breadcrumb/breadcrumb.jsx

import MainLayout from "@/Layouts/layout";
import SpkBreadcrumb from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-breadcrumb";
import { breadcrumb1, breadcrumb2, breadcrumb3, breadcrumb4, breadcrumb5, breadcrumb6, reusebreadcrumb1, reusebreadcrumb2, reusebreadcrumb3, reusebreadcrumb4, reusebreadcrumb5, reusebreadcrumb6 } from "../../../../shared/data/prism-code/uielements-prism";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Breadcrumb, Col, Row } from "react-bootstrap";

const Breadcrumbs = () => {

	return (

		<Fragment>

			{/* <!-- Page Header --> */}

			<Head title="Uielements-Breadcrumb" />

			<Pageheader title="Ui Elements" currentpage="Breadcrumb" activepage="Breadcrumb" />

			{/* <!-- Page Header Close --> */}

			{/* <!--ROW-START--> */}

			<Row>
				<Col xl={12}>
					<ShowCode title="Example" customCardClass="custom-card" reactCode={breadcrumb1} reusableCode={reusebreadcrumb1}>
						<SpkBreadcrumb>
							<Breadcrumb.Item active aria-current="page">Home</Breadcrumb.Item>
						</SpkBreadcrumb>
						<nav aria-label="breadcrumb">
							<SpkBreadcrumb>
								<Breadcrumb.Item href="#!">Home</Breadcrumb.Item>
								<Breadcrumb.Item active aria-current="page">Library</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>

						<nav aria-label="breadcrumb">
							<SpkBreadcrumb Customclass="custom-breadcrumb mb-0 custom-breadcrumb">
								<Breadcrumb.Item href="#!">Home</Breadcrumb.Item>
								<Breadcrumb.Item href="#!">Library</Breadcrumb.Item>
								<Breadcrumb.Item active aria-current="page">Data</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Example1" customCardClass="custom-card" reactCode={breadcrumb2} reusableCode={reusebreadcrumb2}>
						<nav aria-label="breadcrumb">
							<SpkBreadcrumb Customclass="custom-breadcrumb breadcrumb-example1">
								<Breadcrumb.Item active aria-current="page">Home</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>

						<nav aria-label="breadcrumb">
							<SpkBreadcrumb Customclass="custom-breadcrumb breadcrumb-example1">
								<Breadcrumb.Item href="#!">Home</Breadcrumb.Item>
								<Breadcrumb.Item active aria-current="page">Library</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>

						<nav aria-label="breadcrumb">
							<SpkBreadcrumb Customclass="custom-breadcrumb breadcrumb-example1 breadcrumb-second custom mb-0">
								<Breadcrumb.Item href="#!">Home</Breadcrumb.Item>
								<Breadcrumb.Item href="#!">Library</Breadcrumb.Item>
								<Breadcrumb.Item active aria-current="page">Data</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Dividers" customCardClass="custom-card" reactCode={breadcrumb5} reusableCode={reusebreadcrumb5}>
						<nav
							aria-label="breadcrumb" className='divider-breadcrumb'>
							<SpkBreadcrumb Customclass="custom-breadcrumb breadcrumb-second mb-0">
								<Breadcrumb.Item href="#!">Home</Breadcrumb.Item>
								<Breadcrumb.Item active className="active" aria-current="page">Library</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Embedded SVG icon" customCardClass="custom-card" reactCode={breadcrumb6} reusableCode={reusebreadcrumb6}>
						<nav className="embedded-svg-icon">
							<SpkBreadcrumb Customclass="custom-breadcrumb breadcrumb-second mb-0">
								<Breadcrumb.Item href="#!">Home</Breadcrumb.Item>
								<Breadcrumb.Item active className="embedded-breadcrumb" aria-current="page">Library</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Breadcrumb Style-1" customCardClass="custom-card" reactCode={breadcrumb3} reusableCode={reusebreadcrumb3}>
						<nav aria-label="breadcrumb">
							<SpkBreadcrumb Customclass="custom-breadcrumb breadcrumb-style1 breadcrumb-second mb-0">
								<Breadcrumb.Item href="#!">Home</Breadcrumb.Item>
								<Breadcrumb.Item href="#!">Library</Breadcrumb.Item>
								<Breadcrumb.Item active className="active" aria-current="page">Data</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Breadcrumb Style-2" customCardClass="custom-card" reactCode={breadcrumb4} reusableCode={reusebreadcrumb4}>
						<nav aria-label="breadcrumb">
							<SpkBreadcrumb Customclass="custom-breadcrumb breadcrumb-style2 breadcrumb-second mb-0">
								<Breadcrumb.Item href="#!"><i className="ti ti-home-2 me-1 fs-15 d-inline-block"></i>Home</Breadcrumb.Item>
								<Breadcrumb.Item href="#!"><i className="ti ti-apps me-1 fs-15 d-inline-block"></i>About</Breadcrumb.Item>
								<Breadcrumb.Item active className="active" aria-current="page">Services</Breadcrumb.Item>
							</SpkBreadcrumb>
						</nav>
					</ShowCode>
				</Col>
			</Row>

			{/* <!--ROW-END--> */}

		</Fragment>

	)
};
// Assign layout
Breadcrumbs.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Breadcrumbs;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/general/ui-elements/breadcrumb/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import ShowCode from "$lib/components/layout-components/Showcode/ShowCode.svelte";
    import SpkBreadcrumbs from "$lib/@spk/uielements/Breadcrumbs/SpkBreadcrumbs.svelte";
    import {
        breadcrumb1,
        breadcrumb2,
        breadcrumb3,
        breadcrumb4,
        breadcrumb5,
        breadcrumb6,
        breadcrumb7,
    } from "$lib/components/common/prism-code/uielementsprim";
    import { Col, Row } from "@sveltestrap/sveltestrap";
    const breadcrumbItems = [
        { label: "Home", href: "#home" },
        { label: "Library" },
    ];
    const breadcrumbItems2 = [
        { label: "Home", href: "#home" },
        { label: "Library", href: "#library" },
        { label: "Data" }, // No href provided for the active item
    ];

    const breadcrumbItems3 = [
        {
            label: `<i class="ti ti-home-2 me-1 fs-15 d-inline-block"></i>Home`,
            href: "#home",
        },
        {
            label: '<i class="ti ti-apps me-1 fs-15 d-inline-block"></i>About',
            href: "#library",
        },
        { label: "Services" }, // No href provided for the active item
    ];

    const breadcrumbSvgItems = [
        { label: "Home", href: "#home" },
        { label: "Library", itemsClass: "embedded-breadcrumb" },
    ];
</script>

<!-- Page Title -->
<svelte:head>
    <title>Breadcrumb | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<Pageheader homepage="Breadcrumb" activepage="UI Elements" page="Breadcrumb" />
<!--ROW-START-->
<Row>
    <Col xl={12}>
        <ShowCode title="Example" svelteCode={breadcrumb1}>
            <SpkBreadcrumbs label="Home" Single={true} />
            <SpkBreadcrumbs items={breadcrumbItems} activeItem="Library" />
            <SpkBreadcrumbs
                items={breadcrumbItems2}
                CustomClass="breadcrumb-lastchild"
                activeItem="Data"
            />
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Example1" svelteCode={breadcrumb2}>
            <SpkBreadcrumbs label="Home" Single={true} />
            <SpkBreadcrumbs
                items={breadcrumbItems}
                CustomClass="breadcrumb-example1"
                activeItem="Library"
            />
            <SpkBreadcrumbs
                items={breadcrumbItems2}
                CustomClass="breadcrumb-example1 breadcrumb-lastchild"
                activeItem="Data"
            />
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Dividers" svelteCode={breadcrumb3}>
            <SpkBreadcrumbs
                divider="~"
                items={breadcrumbItems}
                CustomClass="breadcrumb-lastchild"
                activeItem="Library"
            />
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Embedded SVG icon" svelteCode={breadcrumb4}>
            <SpkBreadcrumbs
                style="--bs-breadcrumb-divider: url(&quot;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&quot;);"
                items={breadcrumbSvgItems}
                CustomClass=" breadcrumb-lastchild"
                activeItem="Library"
            />
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Breadcrumb Style-1" svelteCode={breadcrumb5}>
            <SpkBreadcrumbs
                items={breadcrumbItems2}
                activeItem="Data"
                CustomClass="breadcrumb-style1 breadcrumb-lastchild"
            />
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode title="Breadcrumb Style-2" svelteCode={breadcrumb6}>
            <SpkBreadcrumbs
                items={breadcrumbItems3}
                activeItem="Services"
                CustomClass="breadcrumb-style2 breadcrumb-lastchild"
            ></SpkBreadcrumbs>
        </ShowCode>
    </Col>
</Row>
<!--ROW-END-->
