// Dashboard Template/vyzor-nextjs-ts-approuter/starterkit/shared/layouts-components/footer/footer.tsx
"use client"

import Link from 'next/link';
import React, { Fragment } from 'react'

interface FooterProps { }

const Footer: React.FC<FooterProps> = () => {

  return (
    <Fragment>

      {/* <!-- Footer Start --> */}

      <footer className="footer mt-auto py-3 text-center">
        <div className="container">
          <span className="text-muted"> Copyright © <span id="year"> 2025 </span> <Link scroll={false}
            href="#!;" className="text-dark fw-medium">Vyzor</Link>.
            Designed with <span className="bi bi-heart-fill text-danger"></span> by <Link scroll={false} target='_blank' href="https://spruko.com/">
              <span className="fw-medium text-primary">Spruko</span>
            </Link> All
            rights
            reserved
          </span>
        </div>
      </footer>

      {/* <!-- Footer End --> */}

    </Fragment>
  )
}

export default Footer;

// Dashboard Template/vyzor-laravel-svelte/starterkit/resources/js/components/footer/Footer.svelte
<script>
    // You can use Svelte's built-in date handling to get the current year.
    let currentYear = new Date().getFullYear();
</script>

<footer class="footer mt-auto py-3 text-center">
    <div class="container">
        <span class="text-muted">
            Copyright © <span id="year">{currentYear}</span>
            <a href="#!" class="text-dark fw-medium">Vyzor</a>. Designed with
            <span class="bi bi-heart-fill text-danger"></span>
            by
            <a href="https://spruko.com/" target="_blank">
                <span class="fw-medium text-primary">Spruko</span>
            </a> All rights reserved
        </span>
    </div>
</footer>
