// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/pages/forms/form-elements/checks-radios/+page.svelte
<script lang="ts">
    import {
        radio1,
        radio10,
        radio11,
        radio12,
        dataradio16,
        radio13,
        radio14,
        radio24,
        radio15,
        radio16,
        radio17,
        radio18,
        radio19,
        radio2,
        radio20,
        radio21,
        radio22,
        radio23,
        radio3,
        radio4,
        radio5,
        radio6,
        radio7,
        radio8,
        radio9,
    } from "$lib/components/common/prism-code/formsprism";
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import ShowCode from "$lib/components/layout-components/showcode/ShowCode.svelte";
    import { Col, Input, Label, Row } from "@sveltestrap/sveltestrap";
    import { Checkdata } from "$lib/data/forms/checks&radiosdata";
    import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";

    // svelteive state variables for each toggle button
    let primary1 = "on";
    let secondary1 = "on";
    let warning1 = "on";
    let info1 = "on";
    let success1 = "on";
    let danger1 = "on";
    let light1 = "on";
    let dark1 = "on";
    let primary2 = "on";
    let secondary2 = "on";
    let success2 = "on";
    // Toggle handler
    function toggle(state: string) {
        return state === "on" ? "off" : "on";
    }
    let radioChecked = "exampleRadios1";
    let selectedValue:null = null;
</script>

<!-- Page Title -->
<svelte:head>
    <title>ChecksRadios | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Checks & Radios"
    activepage="Forms"
    subTitle=" Form Elements"
    page="Checks & Radios"
/>
<!-- Page Header Close -->

<!-- Start:: row-1 -->
<Row >
    <Col xl={6} lg={6} md={6} sm={12} >
        <ShowCode title="Checks" svelteCode={radio1}>
            <Input
                type="checkbox"
                id="flexCheckDefault"
                label=" Default checkbox"
            />
            <Input
                type="checkbox"
                id="flexCheckChecked"
                label=" Checked checkbox"
                checked
            />
        </ShowCode>
    </Col>
    <Col xl={6} lg={6} md={6} sm={12}>
        <ShowCode title="Disabled" svelteCode={radio2}>
      <Input type="checkbox" disabled label="Disabled checkbox" />
      <Input
        type="checkbox"
        disabled
        label="Disabled checked checkbox"
        checked
      />
    </ShowCode>
    </Col>
    <Col xl={6} lg={6} md={6} sm={12}>
        <ShowCode title="Radios" svelteCode={radio3}>
      <Input type="radio" label="Default radio" name="example-radios1" />
      <Input
        type="radio"
        checked
        label="Default checked radio"
        name="example-radios1"
      />
    </ShowCode>
    </Col>
    <Col xl={6} lg={6} md={6} sm={12}>
        <ShowCode title="Disabled" svelteCode={radio4}>
      <Input type="radio" name="flexRadioDisabled" label="Disabled radio" disabled />
      <Input type="radio" name="flexRadioDisabled" disabled checked label="Disabled checked radio" />
    </ShowCode>
    </Col>
</Row>
<!-- End:: row-1 -->

<!-- Start:: row-2 -->
<Row>
    <Col xl={6} lg={6} md=12 sm={12}>
        <ShowCode title="Default (stacked)" svelteCode={radio5}>
      <Input type="checkbox" label="Default checkbox" />
      <Input type="checkbox" disabled label="Disabled checkbox" />
      <Input type="radio" name="exampleRadios" checked id="exampleRadios1" label="Default radio" />
      <Input type="radio"  bind:group={radioChecked} name="exampleRadios" id="exampleRadios3" disabled label="Disabled radio"  />
    </ShowCode>
    </Col>
    <Col xl={6} lg={6} md=12 sm={12}>
       <ShowCode title="Switches" svelteCode={radio6}>
      <Input type="switch" label="Default switch checkbox input" />
      <Input type="switch" checked label="Checked switch checkbox input" />
      <Input type="switch"  disabled label="Disabled switch checkbox input" />
      <Input
        type="switch"
        disabled
        checked
        label="Disabled checked switch checkbox input"
      />
    </ShowCode>
    </Col>
</Row>
<!-- End:: row-2 -->

<!-- Start:: row-3 -->
<Row>
    <Col xxl={12} xl={12} lg={12} md={12} sm={12}>
       <ShowCode
      title="Checkbox Sizes"
      customCardBodyClass="d-sm-flex align-items-center justify-content-between"
      svelteCode={radio7}
    >
      <Input type="checkbox" checked label="Default" />
      <Input
        class="form-check-md d-flex align-items-center"
        type="checkbox"
        checked
        id="checkebox-md"
        label="Medium"
      />
      <Input
        class="form-check-lg d-flex align-items-center"
        type="checkbox"
        checked
        id="checkebox-lg"
        label="Large"
      />
    </ShowCode>
    </Col>
    <Col xxl={12} xl={12} lg={12} md={12} sm={12}>
        <ShowCode
      title="Radio Sizes"
      customCardBodyClass="d-sm-flex align-items-center justify-content-between"
      svelteCode={radio8}
    >
      <Input type="radio" label="default" name="example-radios" />
      <Input
        type="radio"
        class="form-check-md"
        id="Radio-md"
        name="example-radios"
        label="Medium"
      />
      <Input
        type="radio"
        class="form-check-lg"
        name="example-radios"
        checked
        id="Radio-lg"
        label="Large"
      />
    </ShowCode>
    </Col>
    <Col xxl={12} xl={12} lg={12} md={12} sm={12}>
        <ShowCode
      title="Switch Sizes"
      customCardBodyClass="d-sm-flex align-item-center justify-content-between"
      svelteCode={radio9}
    >
      <Input type="switch" label="Default" />
      <Input
        type="switch"
        class="form-check-md form-switch"
        id="switch-md"
        label="Medium"
      />
      <Input
        type="switch"
        class="form-check-lg form-switch"
        id="switch-lg"
        label="Large"
      />
    </ShowCode>
    </Col>
</Row>
<!-- End:: row-3 -->

<!-- Start:: row-4 -->
<Row>
    <Col xl={6} lg={12} md={12} sm={12}>
        <ShowCode title="Inline" svelteCode={radio10}>
      <Input class="form-check-inline" type="checkbox" label="1" />
      <Input class="form-check-inline" type="checkbox" label="2" />
      <Input
        class="form-check-inline"
        disabled
        type="checkbox"
        label="3 (disabled)"
      />
      <Input class="form-check-inline" name="inlineRadioOptions" type="radio" label="1" bind:group={selectedValue}  />
      <Input class="form-check-inline" name="inlineRadioOptions" type="radio" label="2" bind:group={selectedValue} />
      <Input
        class="form-check-inline"
        disabled 
        type="radio"
        name="inlineRadioOptions"
        label="3 (disabled)"
        bind:group={radioChecked}
      />
    </ShowCode>
       <ShowCode title="Without labels" svelteCode={radio11}>
      <div class="d-flex">
        <Input class="me-4" type="checkbox" />
        <Input type="radio" />
      </div>
    </ShowCode>
    </Col>
    <Col xl={3} lg={12} md={12} sm={12} >
       <ShowCode title="Reverse" svelteCode={radio12}>
      <Input reverse class=" mb-3" type="checkbox" label="Reverse checkbox" />
      <Input
        reverse
        class=" mb-3"
        type="checkbox"
        disabled
        label="Disabled reverse checkbox"
      />
      <Input
        reverse
        class=" mb-3"
        type="switch"
        label=" Reverse switch checkbox input"
      />
    </ShowCode>
    </Col>
    <Col xl={3} lg={12} md={12} sm={12} >
        <ShowCode title="Outlined styles" svelteCode={radio13}>
      <input type="checkbox" class="btn-check" id="btn-check-outlined" />
      <label class="btn btn-outline-primary mb-3" for="btn-check-outlined"
        >Single toggle</label
      ><br />

      <input
        type="checkbox"
        class="btn-check"
        id="btn-check-2-outlined"
        checked
      />
      <label class="btn btn-outline-secondary mb-3" for="btn-check-2-outlined"
        >Checked</label
      ><br />

      <input
        type="radio"
        class="btn-check"
        name="options-outlined"
        id="success-outlined"
        checked
      />
      <label class="btn btn-outline-success m-1" for="success-outlined"
        >Checked success radio</label
      >

      <input
        type="radio"
        class="btn-check"
        name="options-outlined"
        id="danger-outlined"
      />
      <label class="btn btn-outline-danger m-1" for="danger-outlined"
        >Danger radio</label
      >
    </ShowCode>
    </Col>
</Row>
<!-- End:: row-4 -->

<!-- Start:: row-5 -->
<Row >
    <Col xl={6} lg={12} md={12} sm={12}>
        <ShowCode title="Radio toggle buttons" svelteCode={radio14}>
      <Input
        type="radio"
        class="btn-check"
        name="options"
        id="option1"
        checked
      />
      <SpkButton
        buttontype="button"
        color="primary"
        customClass="m-1"
        text="Checked"
      />
      <Input type="radio" class="btn-check" name="options" id="option2" />
      <SpkButton
        buttontype="button"
        color="primary"
        customClass="m-1"
        text="Radio"
      />
      <Input
        type="radio"
        class="btn-check"
        name="options"
        id="option3"
        disabled
      />
      <SpkButton
        disabled={true}
        buttontype="button"
        color="primary"
        customClass="m-1"
        text="Disabled"
      />
      <Input type="radio" class="btn-check" name="options" id="option4" />
      <SpkButton
        buttontype="button"
        color="primary"
        customClass="m-1"
        text="Radio"
      />
    </ShowCode>
    </Col>
    <Col xl={6} lg={12} md={12} sm={12}>
        <ShowCode title="Checkbox toggle buttons" svelteCode={radio15}>
      <Input type="checkbox" class="btn-check" id="btn-check" />
      <SpkButton
        buttontype="button"
        color="primary"
        customClass="m-1"
        text="Single toggle"
      />
      <Input type="checkbox" class="btn-check" id="btn-check-2" checked />
      <SpkButton
        buttontype="button"
        color="primary"
        customClass="m-1"
        text="Checked"
      />
      <Input type="checkbox" class="btn-check" id="btn-check-3" disabled />
      <SpkButton
        disabled={true}
        buttontype="button"
        color="primary"
        customClass="m-1"
        text="Disabled"
      />
    </ShowCode>
    </Col>
</Row>
<!-- End:: row-5 -->

<!-- Start:: row-6 -->
<Row class="row-cols-12">
    <Col md={6} lg={6} class="col-xl">
        <ShowCode
      title="Colored Checkboxes"
      svelteCode={radio16}
      dataCode={dataradio16}
    >
      {#each Checkdata as idx (idx.id)}
        <div class="form-check {idx.checkclass}">
          <input
            id={idx.id}
            class="form-check-input form-checked-{idx.checkcolor}"
            type="checkbox"
            checked
          />
          <label for={idx.lablefor}>{idx.text}</label>
        </div>
      {/each}
    </ShowCode>
    </Col>
    <Col md={6} lg={6} class="col-xl">
        <ShowCode
      title="Outline Checkboxes"
      svelteCode={radio17}
      dataCode={dataradio16}
    >
      {#each Checkdata as idx (idx.id)}
        <div class={`form-check ${idx.checkclass}`}>
          <input
            id={idx.id}
            class={`form-check-input form-checked-outline form-checked-${idx.checkcolor}`}
            type="checkbox"
            checked
          />
          <label for={idx.lablefor}>{idx.text}</label>
        </div>
      {/each}
    </ShowCode>
    </Col>
    <Col md={12} class="col-lg col-xl">
        <ShowCode
      title="Colored Radios"
      svelteCode={radio18}
      dataCode={dataradio16}
    >
      {#each Checkdata as idx (idx.id)}
        <div class="form-check {idx.checkclass}">
          <input
            id={idx.id}
            class="form-check-input form-checked-{idx.checkcolor}"
            type="radio"
            checked
          />
          <label for={idx.lablefor}>{idx.text}</label>
        </div>
      {/each}
    </ShowCode>
    </Col>
    <Col sm={6} class=" col-lg">
        <ShowCode
      title="Outline Radios"
      svelteCode={radio19}
      dataCode={dataradio16}
    >
      {#each Checkdata as idx (idx.id)}
        <div class={`form-check ${idx.checkclass}`}>
          <input
            id={idx.id}
            class={`form-check-input form-checked-outline form-checked-${idx.checkcolor}`}
            type="radio"
            checked
          />
          <label for={idx.lablefor}>{idx.text}</label>
        </div>
      {/each}
    </ShowCode>
    </Col>
    <Col sm={6} class="col col-lg">
        <ShowCode
      title="Switches Colors"
      svelteCode={radio20}
      dataCode={dataradio16}
    >
      {#each Checkdata as idx (idx.id)}
        <div class="form-check form-switch {idx.checkclass}">
          <input
            id={idx.id}
            class="form-check-input form-checked-{idx.checkcolor}"
            type="checkbox"
            role="switch"
            checked
          />
          <label for={idx.lablefor}>{idx.text}</label>
        </div>
      {/each}
    </ShowCode>
    </Col>
</Row>
<!-- End:: row-6 -->

<!-- Start:: row-7 -->
<Row >
    <Col xl={12} lg={12} md={12} sm={12}>
        <ShowCode title="Toggle Switches Style-1" svelteCode={radio21}>
      <Row class=" gy-1">
        <Col xl={4}>
          <div class="d-flex gap-2">
            <div
              class="toggle {primary1}"
              role="button"
              on:click={() => (primary1 = toggle(primary1))}
              tabindex="0"
              on:keydown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  () => (primary1 = toggle(primary1));
                }
              }}
            >
              <span></span>
            </div>
            primary
          </div>
        </Col>
        <Col xl={4}>
          <div class="d-flex gap-2">
            <div
              class="toggle mb-3 toggle-secondary {secondary1}"
              role="button"
              on:click={() => (secondary1 = toggle(secondary1))}
              tabindex="0"
              on:keydown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  () => (secondary1 = toggle(secondary1));
                }
              }}
            >
              <span></span>
            </div>
            Secondary
          </div>
        </Col>
        <Col xl={4}>
          <div class="d-flex gap-2">
            <div
              class="toggle mb-3 toggle-warning {warning1}"
              on:click={() => (warning1 = toggle(warning1))}
              role="button"
              tabindex="0"
              on:keydown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  () => (warning1 = toggle(warning1));
                }
              }}
            >
              <span></span>
            </div>
            Warning
          </div>
        </Col>
        <Col xl={4}>
          <div class="d-flex gap-2">
            <div
              class="toggle mb-3 toggle-info {info1}"
              on:click={() => (info1 = toggle(info1))}
              role="button"
              tabindex="0"
              on:keydown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  () => (info1 = toggle(info1));
                }
              }}
            >
              <span></span>
            </div>
            Info
          </div>
        </Col>
        <Col xl={4}>
          <div class="d-flex gap-2">
            <div
              class="toggle mb-3 toggle-success {success1}"
              on:click={() => (success1 = toggle(success1))}
              role="button"
              tabindex="0"
              on:keydown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  () => (success1 = toggle(success1));
                }
              }}
            >
              <span></span>
            </div>
            Success
          </div>
        </Col>
        <Col xl={4}>
          <div class="d-flex gap-2">
            <div
              class="toggle mb-3 toggle-danger {danger1}"
              on:click={() => (danger1 = toggle(danger1))}
              role="button"
              tabindex="0"
              on:keydown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  () => (danger1 = toggle(danger1));
                }
              }}
            >
              <span></span>
            </div>
            Danger
          </div>
        </Col>
        <Col xl={4}>
          <div class="d-flex gap-2">
            <div
              class="toggle mb-3 toggle-light {light1}"
              on:click={() => (light1 = toggle(light1))}
              role="button"
              tabindex="0"
              on:keydown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  () => (light1 = toggle(light1));
                }
              }}
            >
              <span></span>
            </div>
            light
          </div>
        </Col>
        <Col xl={4}>
          <div class="d-flex gap-2">
            <div
              class="toggle ms-sm-2 toggle-dark {dark1}"
              on:click={() => (dark1 = toggle(dark1))}
              role="button"
              tabindex="0"
              on:keydown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  () => (dark1 = toggle(dark1));
                }
              }}
            >
              <span></span>
            </div>
            Dark
          </div>
        </Col>
      </Row>
    </ShowCode>
    </Col>
    <Col xl={12} lg={12} md={12} sm={12}>
        <ShowCode
      title="Toggle Switches Style-2"
      svelteCode={radio22}
    >
      <Row class="gy-1">
        <Col xl={4}>
          <div class="custom-toggle-switch d-flex align-items-center mb-4">
            <input
              id="toggleswitchPrimary"
              name="toggleswitch001"
              type="checkbox"
              checked
            />
            <Label for="toggleswitchPrimary" class="label-primary"></Label><span
              class="ms-3">Primary</span
            >
          </div>
        </Col>
        <Col xl={4}>
          <div class="custom-toggle-switch d-flex align-items-center mb-4">
            <input
              id="toggleswitchSecondary"
              name="toggleswitch001"
              type="checkbox"
              checked
            />
            <Label for="toggleswitchSecondary" class="label-secondary"
            ></Label><span class="ms-3">Secondary</span>
          </div>
        </Col>
        <Col xl={4}>
          <div class="custom-toggle-switch d-flex align-items-center mb-4">
            <input
              id="toggleswitchWarning"
              name="toggleswitch001"
              type="checkbox"
              checked
            />
            <Label for="toggleswitchWarning" class="label-warning"></Label><span
              class="ms-3">Warning</span
            >
          </div>
        </Col>
        <Col xl={4}>
          <div class="custom-toggle-switch d-flex align-items-center mb-4">
            <input
              id="toggleswitchInfo"
              name="toggleswitch001"
              type="checkbox"
              checked
            />
            <Label for="toggleswitchInfo" class="label-info"></Label><span
              class="ms-3">Info</span
            >
          </div>
        </Col>
        <Col xl={4}>
          <div class="custom-toggle-switch d-flex align-items-center mb-4">
            <input
              id="toggleswitchSuccess"
              name="toggleswitch001"
              type="checkbox"
              checked
            />
            <Label for="toggleswitchSuccess" class="label-success"></Label><span
              class="ms-3">Success</span
            >
          </div>
        </Col>
        <Col xl={4}>
          <div class="custom-toggle-switch d-flex align-items-center mb-4">
            <input
              id="toggleswitchDanger"
              name="toggleswitch001"
              type="checkbox"
              checked
            />
            <Label for="toggleswitchDanger" class="label-danger"></Label><span
              class="ms-3">Danger</span
            >
          </div>
        </Col>
        <Col xl={4}>
          <div class="custom-toggle-switch d-flex align-items-center mb-4">
            <input
              id="toggleswitchLight"
              name="toggleswitch001"
              type="checkbox"
              checked
            />
            <Label for="toggleswitchLight" class="label-light"></Label><span
              class="ms-3">Light</span
            >
          </div>
        </Col>
        <Col xl={4}>
          <div class="custom-toggle-switch d-flex align-items-center mb-4">
            <input
              id="toggleswitchDark"
              name="toggleswitch001"
              type="checkbox"
              checked
            />
            <Label for="toggleswitchDark" class="label-dark"></Label><span
              class="ms-3">Dark</span
            >
          </div>
        </Col>
      </Row>
    </ShowCode>
    </Col>
</Row>
<!-- End:: row-7 -->

<!-- Start:: row-8 -->
<Row >
    <Col xl={12} lg={12} md={12} sm={12}>
        <ShowCode title="Toggle Switch-1 Sizes" svelteCode={radio23}>
      <div class="d-flex align-items-center flex-wrap mb-3">
        <div >
          <p class="text-muted m-0">
            Small size toggle switch <code>toggle-sm</code>
          </p>
        </div>
        <div
          class="toggle toggle-sm mb-0 {primary2}"
          on:click={() => (primary2 = toggle(primary2))}
          role="button"
          tabindex="0"
          on:keydown={(event) => {
            if (event.key === "Enter" || event.key === " ") {
              () => (primary2 = toggle(primary2));
            }
          }}
        >
          <span></span>
        </div>
      </div>
      <div class="d-flex align-items-center flex-wrap mb-3">
        <div >
          <p class="text-muted m-0">Default toggle switch <code></code></p>
        </div>
        <div
          class="toggle toggle-secondary mb-0 {secondary2}"
          on:click={() => (secondary2 = toggle(secondary2))}
          role="button"
          tabindex="0"
          on:keydown={(event) => {
            if (event.key === "Enter" || event.key === " ") {
              () => (secondary2 = toggle(secondary2));
            }
          }}
        >
          <span></span>
        </div>
      </div>
      <div class="d-flex align-items-center flex-wrap">
        <div >
          <p class="text-muted m-0">
            Large size toggle switch <code>toggle-lg</code>
          </p>
        </div>
        <div
          class="toggle toggle-lg toggle-success mb-0 {success2}"
          on:click={() => (success2 = toggle(success2))}
          role="button"
          tabindex="0"
          on:keydown={(event) => {
            if (event.key === "Enter" || event.key === " ") {
              () => (success2 = toggle(success2));
            }
          }}
        >
          <span></span>
        </div>
      </div>
    </ShowCode>
    </Col>
    <Col xl={12} lg={12} md={12} sm={12}>
        <ShowCode title="Toggle Switch-2 Sizes" svelteCode={radio24}>
      <div class="d-flex align-items-center flex-wrap mb-2">
        <div>
          <p class="text-muted">
            Small size toggle switch <code>toggle-sm</code>
          </p>
        </div>
        <div class="custom-toggle-switch toggle-sm ms-2">
          <input id="size-sm" name="toggleswitchsize" type="checkbox" checked />
          <Label for="size-sm" class="label-primary"></Label>
        </div>
      </div>
      <div class="d-flex align-items-center flex-wrap mb-4">
        <div ><p class="text-muted m-0">Default toggle switch</p></div>
        <div class="custom-toggle-switch ms-2">
          <input
            id="size-default"
            name="toggleswitchsize"
            type="checkbox"
            checked
          />
          <Label for="size-default" class="label-secondary mb-1"></Label>
        </div>
      </div>
      <div class="d-sm-flex d-block align-items-center flex-wrap">
        <div class="mb-sm-0 mb-2">
          <p class="text-muted m-0">
            Large size toggle switch <code>toggle-lg</code>
          </p>
        </div>
        <div class="custom-toggle-switch toggle-lg ms-sm-2 ms-0">
          <input id="size-lg" name="toggleswitchsize" type="checkbox" checked />
          <Label for="size-lg" class="label-success mb-2"></Label>
        </div>
      </div>
    </ShowCode>
    </Col>
</Row>
<!-- End:: row-8 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/forms/form-elements/checks-radios/checks-radios.jsx

import MainLayout from "@/Layouts/layout";
import SpkButton from "../../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import { radio1, radio10, radio11, radio12, radio13, radio14, radio15, radio16, radio17, radio18, radio19, radio2, radio20, radio21, radio22, radio23, radio24, radio3, radio4, radio5, radio6, radio7, radio8, radio9 } from "../../../../../shared/data/prism-code/forms-prism";
import Pageheader from "../../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment, useState } from "react";
import { Col, Form, Row } from "react-bootstrap";


const ChecksRadios = () => {

    const Checkdata1 = [
        { id: "1", class1: "mb-2", class2: "", text: "Primary" },
        { id: "2", class1: "mb-2", class2: "secondary", text: "Secondary" },
        { id: "3", class1: "mb-2", class2: "warning", text: "Warning" },
        { id: "4", class1: "mb-2", class2: "info", text: "Info" },
        { id: "5", class1: "mb-2", class2: "success", text: "Success" },
        { id: "6", class1: "mb-2", class2: "danger", text: "Danger" },
        { id: "7", class1: "mb-0", class2: "dark", text: "Dark" }
    ];

    const [secondary1, setsecondary1] = useState("on");
    const [success1, setsuccess1] = useState("on");
    const [dark1, setdark1] = useState("on");
    const [primary1, setprimary1] = useState("on");
    const [warning1, setwarning1] = useState("on");
    const [info1, setinfo1] = useState("on");
    const [danger1, setdanger1] = useState("on");
    const [light1, setlight1] = useState("on");

    //sizes
    const [primary2, setprimary2] = useState("on");
    const [secondary2, setsecondary2] = useState("on");
    const [success2, setsuccess2] = useState("on");

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Forms-Checks & Radios" />

            <Pageheader title="Forms" subtitle="Form Elements" currentpage="Checks & Radios" activepage="Checks & Radios" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Checks" customCardClass="custom-card" customCardBodyClass="" reactCode={radio1}>
                        <Form.Check label="Default checkbox" />
                        <Form.Check defaultChecked label="Checked checkbox" />
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Disabled" customCardClass="custom-card" customCardBodyClass="" reactCode={radio2}>
                        <Form.Check disabled label="Disabled checkbox" />
                        <Form.Check disabled defaultChecked label="Disabled checked checkbox" />
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Radios" customCardClass="custom-card" customCardBodyClass="" reactCode={radio3}>
                        <Form.Check type="radio" label="Default radio" name="example-radios1" />
                        <Form.Check type="radio" defaultChecked label="Default checked radio" name="example-radios1" />
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={6} sm={12} className="">
                    <ShowCode title="Disabled" customCardClass="custom-card" customCardBodyClass="" reactCode={radio4}>
                        <Form.Check type="radio" disabled label="Disabled radio" />
                        <Form.Check type="radio" disabled defaultChecked label="Disabled checked radio" />
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-2 --> */}

            <Row>
                <Col xl={6} lg={6} md={12} sm={12} className="">
                    <ShowCode title="Default (stacked)" customCardClass="custom-card" customCardBodyClass="" reactCode={radio5}>
                        <Form.Check label="Default checkbox" />
                        <Form.Check disabled label="Disabled checkbox" />
                        <Form.Check type="radio" defaultChecked label="Default radio" />
                        <Form.Check type="radio" disabled label="Disabled radio" />
                    </ShowCode>
                </Col>
                <Col xl={6} lg={6} md={12} sm={12} className="">
                    <ShowCode title="Switches" customCardClass="custom-card" customCardBodyClass="" reactCode={radio6}>
                        <Form.Check type="switch" label="Default switch checkbox input" />
                        <Form.Check type="switch" defaultChecked label="Checked switch checkbox input" />
                        <Form.Check type="switch" disabled label="Disabled switch checkbox input" />
                        <Form.Check type="switch" disabled defaultChecked label="Disabled checked switch checkbox input" />
                    </ShowCode>
                </Col>

            </Row>

            {/* <!-- End:: row-2 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xxl={12} xl={12} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Checkbox Sizes" customCardClass="custom-card" customCardBodyClass="d-sm-flex align-items-center justify-content-between" reactCode={radio13}>
                        <Form.Check type="checkbox" defaultChecked label="Default" />
                        <Form.Check className="form-check-md d-flex align-items-center"
                            type="checkbox" defaultChecked id="checkebox-md" label="Medium" />
                        <Form.Check className="form-check-lg d-flex align-items-center"
                            type="checkbox" defaultChecked id="checkebox-lg" label="Large" />
                    </ShowCode>
                </Col>
                <Col xxl={12} xl={12} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Radio Sizes" customCardClass="custom-card" customCardBodyClass="d-sm-flex align-items-center justify-content-between" reactCode={radio14}>
                        <Form.Check type="radio" label="Default" name="example-radios" />
                        <Form.Check type="radio" className="form-check-md" id="Radio-md" name="example-radios" label="Medium" />
                        <Form.Check type="radio" className="form-check-lg" name="example-radios"
                            defaultChecked id="Radio-lg" label="Large" />
                    </ShowCode>
                </Col>
                <Col xxl={12} xl={12} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Switch Sizes" customCardClass="custom-card" customCardBodyClass="d-sm-flex align-item-center justify-content-between" reactCode={radio15}>
                        <Form.Check type="switch" label="Default" />
                        <Form.Check type="switch" className="form-check-md form-switch" id="switch-md" label="Medium" />
                        <Form.Check type="switch" className="form-check-lg form-switch" id="switch-lg" label="Large" />
                    </ShowCode>
                </Col>

            </Row>

            {/* <!-- End:: row-3 --> */}

            {/* <!-- Start:: row-4 --> */}

            <Row>

                <Col xl={6} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Inline" customCardClass="custom-card" customCardBodyClass="" reactCode={radio9}>
                        <Form.Check className="form-check-inline" type="checkbox" label="1" />
                        <Form.Check className="form-check-inline" type="checkbox" label="2" />
                        <Form.Check className="form-check-inline" disabled type="checkbox" label="3 (disabled)" />
                        <Form.Check className="form-check-inline" type="radio" label="1" name='radio1' />
                        <Form.Check className="form-check-inline" type="radio" label="2" name='radio1' />
                        <Form.Check className="form-check-inline" disabled type="radio" label="3 (disabled)" />
                    </ShowCode>
                    <ShowCode title="Without labels" customCardClass="custom-card" customCardBodyClass="" reactCode={radio10}>
                        <div className="d-flex">
                            <Form.Check className="me-4" type="checkbox" />
                            <Form.Check className="" type="radio" />
                        </div>
                    </ShowCode>
                </Col>
                <Col xl={3} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Reverse" customCardClass="custom-card" customCardBodyClass="" reactCode={radio11}>
                        <Form.Check className="form-check-reverse mb-3" type="checkbox" label="Reverse checkbox" />
                        <Form.Check className="form-check-reverse mb-3" type="checkbox" disabled label="Disabled reverse checkbox" />
                        <Form.Check className="form-check-reverse mb-3" type="switch" label="Reverse switch checkbox input" />
                    </ShowCode>
                </Col>
                <Col xl={3} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Outlined styles" customCardClass="custom-card" customCardBodyClass="" reactCode={radio12}>
                        <Form.Control type="checkbox" className="btn-check" id="btn-check-outlined" />
                        <SpkButton Buttonvariant='outline-primary' Customclass="mb-3">Single toggle</SpkButton><br />
                        <input type="checkbox" className="btn-check" id="btn-check-2-outlined" defaultChecked />
                        <label className="btn btn-outline-secondary mb-3" htmlFor="btn-check-2-outlined">Checked</label>
                        <br />
                        <input type="radio" className="btn-check" name="options-outlined" id="success-outlined" defaultChecked />
                        <label className="btn btn-outline-success m-1" htmlFor="success-outlined">Checked success radio</label>
                        <input type="radio" className="btn-check" name="options-outlined" id="danger-outlined" />
                        <label className="btn btn-outline-danger m-1" htmlFor="danger-outlined">Danger radio</label>
                    </ShowCode>
                </Col>

            </Row>

            {/* <!-- End:: row-4 --> */}

            {/* <!-- Start:: row-5 --> */}

            <Row>
                <Col xl={6} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Radio toggle buttons" customCardClass="custom-card" customCardBodyClass="" reactCode={radio7}>
                        <Form.Check type="radio" className="btn-check" name="options" id="option1" defaultChecked />
                        <SpkButton Buttonvariant="primary" Customclass="m-1">Checked</SpkButton>
                        <Form.Check type="radio" className="btn-check" name="options" id="option2" />
                        <SpkButton Buttonvariant="primary" Customclass="m-1">Radio</SpkButton>
                        <Form.Check type="radio" className="btn-check" name="options" id="option3" disabled />
                        <SpkButton Disabled={true} Buttonvariant="primary" Customclass="m-1">Disabled</SpkButton>
                        <Form.Check type="radio" className="btn-check" name="options" id="option4" />
                        <SpkButton Buttonvariant="" Customclass="btn btn-primary m-1">Radio</SpkButton>
                    </ShowCode>
                </Col>
                <Col xl={6} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Checkbox toggle buttons" customCardClass="custom-card" customCardBodyClass="" reactCode={radio8}>
                        <Form.Check type="checkbox" className="btn-check" id="btn-check" />
                        <SpkButton Buttonvariant="primary" Customclass="m-1">Single toggle</SpkButton>
                        <Form.Check type="checkbox" className="btn-check" id="btn-check-2" defaultChecked />
                        <SpkButton Buttonvariant="primary" Customclass="m-1">Checked</SpkButton>
                        <Form.Check type="checkbox" className="btn-check" id="btn-check-3" disabled />
                        <SpkButton Disabled={true} Buttonvariant="primary" Customclass="m-1">Disabled</SpkButton>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-5 --> */}

            {/* <!-- Start:: row-6 --> */}

            <Row className="row-cols-12">
                <Col md={6} lg={6} className="col col-xl">
                    <ShowCode title="Colored Checkboxes" customCardClass="custom-card" customCardBodyClass="" reactCode={radio20}>
                        {Checkdata1.map((idx, index) => (
                            <div className={`form-check ${idx.class1}`} key={index}>
                                <input id={idx.id} className={`form-check-input form-checked-${idx.class2}`}
                                    type="checkbox" defaultChecked />
                                <label className=''>{idx.text}</label>
                            </div>
                        ))}
                    </ShowCode>
                </Col>
                <Col md={6} lg={6} className="col col-xl">
                    <ShowCode title="Outline Checkboxes" customCardClass="custom-card" customCardBodyClass="" reactCode={radio21}>
                        {Checkdata1.map((idx, index) => (
                            <div className={`form-check ${idx.class1}`} key={index}>
                                <input id={idx.id} className={`form-check-input form-checked-outline form-checked-${idx.class2}`}
                                    type="checkbox" defaultChecked />
                                <label className=''>{idx.text}</label>
                            </div>
                        ))}
                    </ShowCode>
                </Col>
                <Col md={12} className="col col-lg col-xl">
                    <ShowCode title="Colored Radios" customCardClass="custom-card" customCardBodyClass="" reactCode={radio22}>
                        {Checkdata1.map((idx, index) => (
                            <div className={`form-check ${idx.class1}`} key={index}>
                                <input className={`form-check-input form-checked form-checked-${idx.class2}`}
                                    type="radio" defaultChecked />
                                <label className=''>{idx.text}</label>
                            </div>
                        ))}
                    </ShowCode>
                </Col>
                <Col sm={6} className="col col-lg">
                    <ShowCode title="Outline Radios" customCardClass="custom-card" customCardBodyClass="" reactCode={radio23}>
                        {Checkdata1.map((idx, index) => (
                            <div className={`form-check ${idx.class1}`} key={index}>
                                <input className={`form-check-input form-checked-outline form-checked-${idx.class2}`}
                                    type="radio" defaultChecked />
                                <label className=''>{idx.text}</label>
                            </div>
                        ))}
                    </ShowCode>
                </Col>
                <Col sm={6} className="col col-lg">
                    <ShowCode title="Switches Colors" customCardClass="custom-card" customCardBodyClass="" reactCode={radio24}>
                        {Checkdata1.map((idx, index) => (
                            <div className={`form-check form-switch ${idx.class1}`} key={index}>
                                <input className={`form-check-input form-checked-${idx.class2}`}
                                    type="checkbox" defaultChecked />
                                <label className=''>{idx.text}</label>
                            </div>
                        ))}
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-6 --> */}

            {/* <!-- Start:: row-7 --> */}

            <Row>
                <Col xl={12} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Toggle Switches Style-1" customCardClass="custom-card" customCardBodyClass="" reactCode={radio16}>
                        <Row className="row gy-1">
                            <Col xl={4}>
                                <div className="d-flex gap-2">
                                    <div className={`toggle  ${primary1}`} onClick={() => { primary1 == "on" ? setprimary1("off") : setprimary1("on"); }}>
                                        <span></span>
                                    </div>
                                    Primary
                                </div>
                            </Col>

                            <Col xl={4}>
                                <div className="d-flex gap-2">
                                    <div className={`toggle mb-3 ms-sm-2 toggle-secondary ${secondary1}`} onClick={() => { secondary1 == "on" ? setsecondary1("off") : setsecondary1("on"); }}>
                                        <span></span>
                                    </div>
                                    Secondary
                                </div>
                            </Col>
                            <Col xl={4}>
                                <div className="d-flex gap-2">
                                    <div className={`toggle mb-3  toggle-warning ${warning1}`} onClick={() => { warning1 == "on" ? setwarning1("off") : setwarning1("on"); }} >
                                        <span></span>
                                    </div>
                                    Warning
                                </div>

                            </Col>
                            <Col xl={4}>
                                <div className="d-flex gap-2">
                                    <div className={`toggle mb-3  toggle-info ${info1}`} onClick={() => { info1 == "on" ? setinfo1("off") : setinfo1("on"); }} >
                                        <span></span>
                                    </div>
                                    Info
                                </div>


                            </Col>
                            <Col xl={4}>
                                <div className="d-flex gap-2">
                                    <div className={`toggle mb-3 ms-sm-2  toggle-success ${success1}`} onClick={() => { success1 == "on" ? setsuccess1("off") : setsuccess1("on"); }} >
                                        <span></span>
                                    </div>
                                    Success
                                </div>


                            </Col>
                            <Col xl={4}>
                                <div className="d-flex gap-2">
                                    <div className={`toggle mb-3  toggle-danger ${danger1}`} onClick={() => { danger1 == "on" ? setdanger1("off") : setdanger1("on"); }} >
                                        <span></span>
                                    </div>
                                    Danger
                                </div>

                            </Col>
                            <Col xl={4}>
                                <div className="d-flex gap-2">
                                    <div className={`toggle mb-3  toggle-light ${light1}`} onClick={() => { light1 == "on" ? setlight1("off") : setlight1("on"); }} >
                                        <span></span>
                                    </div>
                                    Light
                                </div>

                            </Col>
                            <Col xl={4}>
                                <div className="d-flex gap-2">
                                    <div className={`toggle ms-sm-2  toggle-dark ${dark1}`} onClick={() => { dark1 == "on" ? setdark1("off") : setdark1("on"); }}>
                                        <span></span>
                                    </div>
                                    Dark
                                </div>

                            </Col>
                        </Row>
                    </ShowCode>
                </Col>
                <Col xl={12} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Toggle Switches Style-2" customCardClass="custom-card" customCardBodyClass="" reactCode={radio17}>
                        <div className="row gy-1">
                            <Col xl={4}>
                                <div className="custom-toggle-switch d-flex align-items-center mb-4">
                                    <Form.Control id="toggleswitchPrimary" name="toggleswitch001" type="checkbox" defaultChecked />
                                    <Form.Label htmlFor="toggleswitchPrimary" className="m-0 label-primary"></Form.Label><span className="ms-3">Primary</span>
                                </div>
                            </Col>
                            <Col xl={4}>
                                <div className="custom-toggle-switch d-flex align-items-center mb-4">
                                    <Form.Control id="toggleswitchSecondary" name="toggleswitch001" type="checkbox" defaultChecked />
                                    <Form.Label htmlFor="toggleswitchSecondary" className="m-0 label-secondary"></Form.Label><span className="ms-3">Secondary</span>
                                </div>
                            </Col>
                            <Col xl={4}>
                                <div className="custom-toggle-switch d-flex align-items-center mb-4">
                                    <Form.Control id="toggleswitchWarning" name="toggleswitch001" type="checkbox" defaultChecked />
                                    <Form.Label htmlFor="toggleswitchWarning" className="m-0 label-warning"></Form.Label><span className="ms-3">Warning</span>
                                </div>
                            </Col>
                            <Col xl={4}>
                                <div className="custom-toggle-switch d-flex align-items-center mb-4">
                                    <Form.Control id="toggleswitchInfo" name="toggleswitch001" type="checkbox" defaultChecked />
                                    <Form.Label htmlFor="toggleswitchInfo" className="m-0 label-info"></Form.Label><span className="ms-3">Info</span>
                                </div>
                            </Col>
                            <Col xl={4}>
                                <div className="custom-toggle-switch d-flex align-items-center mb-4">
                                    <Form.Control id="toggleswitchSuccess" name="toggleswitch001" type="checkbox" defaultChecked />
                                    <Form.Label htmlFor="toggleswitchSuccess" className="m-0 label-success"></Form.Label><span className="ms-3">Success</span>
                                </div>
                            </Col>
                            <Col xl={4}>
                                <div className="custom-toggle-switch d-flex align-items-center mb-4">
                                    <Form.Control id="toggleswitchDanger" name="toggleswitch001" type="checkbox" defaultChecked />
                                    <Form.Label htmlFor="toggleswitchDanger" className="m-0 label-danger"></Form.Label><span className="ms-3">Danger</span>
                                </div>
                            </Col>
                            <Col xl={4}>
                                <div className="custom-toggle-switch d-flex align-items-center mb-4">
                                    <Form.Control id="toggleswitchLight" name="toggleswitch001" type="checkbox" defaultChecked />
                                    <Form.Label htmlFor="toggleswitchLight" className="m-0 label-light"></Form.Label><span className="ms-3">Light</span>
                                </div>
                            </Col>
                            <Col xl={4}>
                                <div className="custom-toggle-switch d-flex align-items-center mb-4">
                                    <Form.Control id="toggleswitchDark" name="toggleswitch001" type="checkbox" defaultChecked />
                                    <Form.Label htmlFor="toggleswitchDark" className="m-0 label-dark"></Form.Label><span className="ms-3">Dark</span>
                                </div>
                            </Col>
                        </div>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-7 --> */}

            {/* <!-- Start:: row-8 --> */}

            <Row>
                <Col xl={12} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Toggle Switch-1 Sizes" customCardClass="custom-card" customCardBodyClass="" reactCode={radio18}>
                        <div className="d-flex align-items-center flex-wrap mb-3">
                            <div className=""> <p className="text-muted m-0">Small size toggle switch <code>toggle-sm</code></p></div>

                            <div className={`toggle  toggle-sm mb-0 ${primary2}`} onClick={() => { primary2 == "on" ? setprimary2("off") : setprimary2("on"); }}>
                                <span></span>
                            </div>
                        </div>
                        <div className="d-flex align-items-center flex-wrap mb-3">
                            <div className=""> <p className="text-muted m-0">Default toggle switch <code></code></p></div>

                            <div className={`toggle mb-0  toggle-secondary ${secondary2}`} onClick={() => { secondary2 == "on" ? setsecondary2("off") : setsecondary2("on"); }}>
                                <span></span>
                            </div>
                        </div>
                        <div className="d-flex align-items-center flex-wrap">
                            <div className=""> <p className="text-muted m-0">Large size toggle switch <code>toggle-lg</code></p></div>

                            <div className={`toggle toggle-lg mb-0  toggle-success ${success2}`} onClick={() => { success2 == "on" ? setsuccess2("off") : setsuccess2("on"); }} >
                                <span></span>
                            </div>
                        </div>
                    </ShowCode>
                </Col>
                <Col xl={12} lg={12} md={12} sm={12} className="">
                    <ShowCode title="Toggle Switch-2 Sizes" customCardClass="custom-card" customCardBodyClass="" reactCode={radio19}>
                        <div className="d-flex align-items-center flex-wrap mb-4">
                            <div className=""><p className="text-muted m-0">Small size toggle switch <code>toggle-sm</code></p></div>
                            <div className="custom-toggle-switch toggle-sm ms-2">
                                <Form.Control id="size-sm" name="toggleswitchsize" type="checkbox" defaultChecked />
                                <Form.Label htmlFor="size-sm" className="label-primary m-0"></Form.Label>
                            </div>
                        </div>
                        <div className="d-flex align-items-center flex-wrap mb-4">
                            <div className=""><p className="text-muted m-0">Default toggle switch</p></div>
                            <div className="custom-toggle-switch ms-2">
                                <Form.Control id="size-default" name="toggleswitchsize" type="checkbox" defaultChecked />
                                <Form.Label htmlFor="size-default" className="label-secondary mb-1"></Form.Label>
                            </div>
                        </div>
                        <div className="d-sm-flex d-block align-items-center flex-wrap">
                            <div className="mb-sm-0 mb-2"><p className="text-muted m-0">Large size toggle switch <code>toggle-lg</code></p></div>
                            <div className="custom-toggle-switch toggle-lg ms-sm-2 ms-0">
                                <Form.Control id="size-lg" name="toggleswitchsize" type="checkbox" defaultChecked />
                                <Form.Label htmlFor="size-lg" className="label-success mb-2"></Form.Label>
                            </div>
                        </div>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-8 --> */}

        </Fragment>
    )
};
// Assign layout
ChecksRadios.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ChecksRadios;
