// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/dashboards/projects/projects-list/+page.svelte
<script lang="ts">
    import SpkTablescomponent from "$lib/@spk/SpkTablescomponent.svelte";
    import SpkBadge from "$lib/@spk/uielements/badge/SpkBadge.svelte";
    import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";
    import SpkDropdown from "$lib/@spk/uielements/Dropdown/SpkDropdown.svelte";

    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import {
        AvatarImages,
        projectData,
        Projectselectdata,
    } from "$lib/data/dashboards/projects/projectlistdata";
    import { projectListDropdown } from "$lib/data/uielements/dropdowndata";
    import {
        Card,
        CardBody,
        CardFooter,
        Col,
        Image,
        Input,
        Pagination,
        PaginationItem,
        PaginationLink,
        Row,
    } from "@sveltestrap/sveltestrap";
    import Select from "svelte-select";
    import { base } from "$app/paths";
    const basePath = base;
    const statusBadgeClass: any = {
        "In Progress": "bg-info-transparent",
        Completed: "bg-success-transparent",
        Delayed: "bg-warning-transparent",
        "Not Started": "bg-light text-default",
    };

    const priorityColorClass = {
        High: "text-danger",
        Medium: "text-info",
        Low: "text-primary",
    };
</script>

<!-- Page Title -->
<svelte:head>
    <title>ProjectsList | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Projects List"
    subTitle="Projects"
    activepage="Dashboards"
    page="Projects List"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={12}>
        <Card class="custom-card">
            <CardBody class="p-3">
                <div
                    class="d-flex align-items-center justify-content-between flex-wrap gap-3"
                >
                    <div class="d-flex gap-1 project-list-main flex-wrap">
                        <a
                            href={`${basePath}/dashboards/projects/create-project`}
                            class="btn btn-primary me-2 custom-project-list"
                            ><i class="ri-add-line me-1 fw-medium align-middle"
                            ></i>New Project</a
                        >
                        <Select
                            items={Projectselectdata}
                            placeholder="Sort By"
                            class="projects-sort basic-multi-select custom-project-list"
                            clearable={false}
                                    showChevron={true}
                        />
                    </div>
                    <div class="avatar-list-stacked">
                        {#each AvatarImages as src, index}
                            <span class="avatar avatar-sm avatar-rounded">
                                <Image {src} alt={`avatar-${index + 1}`} />
                            </span>
                        {/each}
                        <a
                            class="avatar avatar-sm bg-primary avatar-rounded text-fixed-white"
                            href="#!"
                        >
                            +8
                        </a>
                    </div>
                    <div class="d-flex" role="search">
                        <Input
                            class="me-2"
                            type="search"
                            placeholder="Search Project"
                            aria-label="Search"
                        />
                        <SpkButton
                            color="light"
                            customClass="btn"
                            buttontype="submit">Search</SpkButton
                        >
                    </div>
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!-- End::row-1 -->

<!-- Start::row-2 -->

<Row>
    <Col xl={12}>
        <Card class="custom-card overflow-hidden">
            <CardBody class="p-0">
               <SpkTablescomponent
                    Responsive={true}
                        tableClass="text-nowrap"
                        header={[
                            { title: "Project Name" },
                            { title: "Client Name" },
                            { title: "Start Date" },
                            { title: "End Date" },
                            { title: "Status" },
                            { title: "Budget (USD)" },
                            { title: "Assigned Team" },
                            { title: "Priority" },
                            { title: "Actions" },
                        ]}
                    >
                        {#each projectData as project}
                            <tr>
                                <td>{project.name}</td>
                                <td>
                                    <div
                                        class="d-flex align-items-center gap-1"
                                    >
                                        <div class="lh-1">
                                            <span
                                                class="avatar avatar-sm avatar-rounded"
                                            >
                                                <Image
                                                    width={20}
                                                    height={20}
                                                    src={project.companyLogo}
                                                    alt="logo"
                                                />
                                            </span>
                                        </div>
                                        <div>{project.companyName}</div>
                                    </div>
                                </td>
                                <td>{project.startDate}</td>
                                <td>{project.endDate}</td>
                                <td>
                                    <SpkBadge
                                        Color=""
                                        CustomClass={`${statusBadgeClass[project.status]}`}
                                    >
                                        {project.status}
                                    </SpkBadge>
                                </td>
                                <td>{project.budget}</td>
                                <td>
                                    <div class="avatar-list-stacked">
                                        {#each project.team ?? [] as avatar}
                                            <span
                                                class="avatar avatar-sm avatar-rounded"
                                            >
                                                <Image src={avatar} alt="img" />
                                            </span>
                                        {/each}
                                        {#if project.extraTeam > 0}
                                            <a
                                                class="avatar avatar-sm bg-primary avatar-rounded text-fixed-white"
                                                href="#!"
                                            >
                                                +{project.extraTeam}
                                            </a>
                                        {/if}
                                    </div>
                                </td>
                                <td>
                                    <span
                                        class={`${priorityColorClass[project.priority]} d-flex align-items-center`}
                                    >
                                        <i
                                            class="ri-circle-fill me-1 fs-10 lh-1"
                                        ></i>{project.priority}
                                    </span>
                                </td>
                                <td>
                                    <SpkDropdown
                                        option={projectListDropdown}
                                        ToggleClass="btn btn-icon btn-sm btn-light no-caret"
                                        Caret={false}
                                        parent={`<i class="fe fe-more-vertical"></i>`}
                                    />
                                </td>
                            </tr>
                        {/each}
                    </SpkTablescomponent>
            </CardBody>
            <CardFooter class="border-top-0">
                <div class="d-flex align-items-center">
                    <div>
                        Showing 10 Entries <i
                            class="bi bi-arrow-right ms-2 fw-semibold"
                        ></i>
                    </div>
                    <div class="ms-auto">
                        <nav
                            aria-label="Page navigation"
                            class="pagination-style-2"
                        >
                            <Pagination class="mb-0 flex-wrap customPaginationPageBottom">
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >Prev</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >1</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem active>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >2</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >...</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >17</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        class="text-primary"
                                        >Next</PaginationLink
                                    >
                                </PaginationItem>
                            </Pagination>
                        </nav>
                    </div>
                </div>
            </CardFooter>
        </Card>
    </Col>
</Row>

<!-- End::row-2 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/projects/projects-list/projects-list.jsx

import React, { Fragment } from "react";
import { Card, Col, Dropdown, Form, Image, Pagination, Row } from "react-bootstrap";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Link, Head } from "@inertiajs/react";
import SpkSelect from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import { AvatarImages, projectData, Projectselectdata } from "../../../../shared/data/dashboards/projects/projectlistdata";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import SpkTables from "../../../../shared/@spk-reusable-components/reusable-tables/spk-tables";
import SpkBadge from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import SpkDropdown from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-dropdown";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const ProjectsList = () => {

    const statusBadgeClass = {
        "In Progress": "bg-info-transparent",
        "Completed": "bg-success-transparent",
        "Delayed": "bg-warning-transparent",
        "Not Started": "bg-light text-default"
    };

    const priorityColorClass = {
        High: "text-danger",
        Medium: "text-info",
        Low: "text-primary"
    };

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Projects-Projects List" />

            <Pageheader title="Dashboards" subtitle="Projects" currentpage="Projects List" activepage="Projects List" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Body className="p-3">
                            <div className="d-flex align-items-center justify-content-between flex-wrap gap-3">
                                <div className="d-flex flex-wrap gap-1 project-list-main">
                                    <Link href={`${__APP_BASE_PATH__}/dashboards/projects/create-project`} className="btn btn-primary me-2"><i className="ri-add-line me-1 fw-medium align-middle"></i>New Project</Link>
                                    <SpkSelect name="colors" option={Projectselectdata} mainClass="projects-sort basic-multi-select" menuplacement='auto' classNameprefix="Select2" placeholder="Sort By" />
                                </div>
                                <div className="avatar-list-stacked">
                                    {AvatarImages.map((src, index) => (
                                        <span className="avatar avatar-sm avatar-rounded" key={index}>
                                            <BaseImage src={src} alt={`avatar-${index + 1}`} />
                                        </span>
                                    ))}
                                    <BaseLink className="avatar avatar-sm bg-primary avatar-rounded text-fixed-white" href="#!">
                                        +8
                                    </BaseLink>
                                </div>
                                <div className="d-flex custom-search-list" role="search">
                                    <Form.Control className="me-2" type="search" placeholder="Search Project" aria-label="Search" />
                                    <SpkButton Buttonvariant="light" Customclass="btn" Buttontype="submit">Search</SpkButton>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End::row-1 --> */}

            {/* <!-- Start::row-2 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card overflow-hidden">
                        <Card.Body className="p-0">
                            <div className="table-responsive">
                                <SpkTables tableClass="text-nowrap" header={[{ title: 'Project Name' }, { title: "Client Name" }, { title: 'Start Date' }, { title: 'End Date' }, { title: 'Status' }, { title: 'Budget (USD)' }, { title: 'Assigned Team' }, { title: 'Priority' }, { title: 'Actions' }]} >
                                    {projectData.map((project, index) => (
                                        <tr key={index}>
                                            <td>{project.name}</td>
                                            <td>
                                                <div className="d-flex align-items-center gap-1">
                                                    <div className="lh-1">
                                                        <span className="avatar avatar-sm avatar-rounded">
                                                            <BaseImage width={20} height={20} src={project.companyLogo} alt="logo" />
                                                        </span>
                                                    </div>
                                                    <div>{project.companyName}</div>
                                                </div>
                                            </td>
                                            <td>{project.startDate}</td>
                                            <td>{project.endDate}</td>
                                            <td>
                                                <SpkBadge variant="" Customclass={`${statusBadgeClass[project.status]}`}>
                                                    {project.status}
                                                </SpkBadge>
                                            </td>
                                            <td>{project.budget}</td>
                                            <td>
                                                <div className="avatar-list-stacked">
                                                    {project.team.map((avatar, idx) => (
                                                        <span key={idx} className="avatar avatar-sm avatar-rounded">
                                                            <BaseImage src={avatar} alt="img" />
                                                        </span>
                                                    ))}
                                                    {project.extraTeam > 0 && (
                                                        <BaseLink className="avatar avatar-sm bg-primary avatar-rounded text-fixed-white" href="#!">
                                                            +{project.extraTeam}
                                                        </BaseLink>
                                                    )}
                                                </div>
                                            </td>
                                            <td>
                                                <span className={`${priorityColorClass[project.priority]} d-flex align-items-center`}>
                                                    <i className="ri-circle-fill me-1 fs-10 lh-1"></i>{project.priority}
                                                </span>
                                            </td>
                                            <td>
                                                <SpkDropdown toggleas="a" Icon={true} Customtoggleclass="btn btn-icon btn-sm btn-light no-caret" IconClass="fe fe-more-vertical">
                                                    <Dropdown.Item href="#!"><i className="ti ti-eye me-1 d-inline-block"></i>View</Dropdown.Item>
                                                    <Dropdown.Item href="#!"><i className="ti ti-edit me-1 d-inline-block"></i>Edit</Dropdown.Item>
                                                    <Dropdown.Item href="#!"><i className="ti ti-trash me-1 d-inline-block"></i>Delete</Dropdown.Item>
                                                </SpkDropdown>
                                            </td>
                                        </tr>
                                    ))}
                                </SpkTables>
                            </div>
                        </Card.Body>
                        <Card.Footer>
                            <div className="d-flex align-items-center">
                                <div> Showing 10 Entries <i className="bi bi-arrow-right ms-2 fw-semibold"></i> </div>
                                <div className="ms-auto">
                                    <nav aria-label="Page navigation" className="pagination-style-2">
                                        <Pagination className="mb-0 flex-wrap">
                                            <Pagination.Prev disabled>Prev</Pagination.Prev>
                                            <Pagination.Item>1</Pagination.Item>
                                            <Pagination.Item active>2</Pagination.Item>
                                            <Pagination.Item><i className='bi bi-three-dots'></i></Pagination.Item>
                                            <Pagination.Item>17</Pagination.Item>
                                            <Pagination.Next className="text-primary">Next</Pagination.Next>
                                        </Pagination>
                                    </nav>
                                </div>
                            </div>
                        </Card.Footer>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End::row-2 --> */}
        </Fragment>
    )
};
// Assign layout
ProjectsList.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ProjectsList;
