// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/advanced-ui/swiper-js/swiper-js.jsx

import * as swiperdata from "../../../../shared/data/general/adavanec-ui/swiperjsdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment, useState } from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination } from "swiper/modules";
import { Card, Col, Row } from "react-bootstrap";
import SpkSwiperJs from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-swiperjs";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const SwiperJs = () => {

	const [thumbsSwiper, setThumbsSwiper] = useState(null);
	const pagination = {
		clickable: true,
		renderBullet: function (index, className) {
			return '<span class="' + className + '">' + (index + 1) + '</span>';
		},
	};

	return (

		<Fragment>

			{/* <!-- Page Header --> */}

			<Head title={"Swiper Js"} />

			<Pageheader title="Advanced Ui" currentpage="Swiper Js" activepage="Swiper Js" />

			{/* <!-- Page Header Close --> */}

			{/* <!-- Start::row-1 --> */}

			<Row>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Basic Swiper
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Basicdata} spaceBetween={30} centeredSlides={true} autoplay={true} className="mySwiper swiper-basic" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Swiper With Navigation
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Navigationdata} spaceBetween={30} centeredSlides={true} navigation={true} autoplay={true} className="mySwiper swiper-navigation" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Swiper with Pagination
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Paginationdata} spaceBetween={30} centeredSlides={true} pagination={{ dynamicBullets: true, clickable: true }} autoplay={true} className="mySwiper" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Dynamic Pagination
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Dynamicdata} spaceBetween={30} centeredSlides={true} pagination={{ dynamicBullets: true, clickable: true }} autoplay={true} className="mySwiper" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Pagination With Progress
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Progressdata} pagination={{ type: 'progressbar' }} navigation={true} autoplay={true} className="mySwiper" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Pagination Fraction
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Fractiondata} pagination={{ type: 'fraction' }} navigation={true} autoplay={true} className="mySwiper pagination-fraction" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Custom Pagination
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Customdata} pagination={pagination} autoplay={true} className="mySwiper swiper custom-pagination" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Scrollbar Swiper
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Scrollbardata} scrollbar={{ hide: true, }} autoplay={true} className="mySwiper swiper scrollbar-swiper" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card custom-v-swiper custom-swipe">
						<Card.Header>
							<Card.Title>
								Vertical Swiper
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Verticaldata} direction={"vertical"} pagination={{ clickable: true }} autoplay={true} className="mySwiper vertical swiper-vertical" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card custom-mouse-wheel">
						<Card.Header>
							<Card.Title>
								Mouse Wheel Control
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Mousewheeldata} direction={"vertical"} slidesPerView={1} spaceBetween={30} pagination={{ clickable: true }} autoplay={true} className="mySwiper vertical vertical-mouse-control" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Keyboard Control
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Keyboarddata} pagination={{ dynamicBullets: true, clickable: true }} autoplay={true} slidesPerView={1} spaceBetween={30} navigation={true} keyboard={{ enabled: true }} className="mySwiper" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>Nested Swiper</Card.Title>
						</Card.Header>
						<Card.Body>
							<Swiper className="mySwiper swiper-h swiper swiper-horizontal1" spaceBetween={50} pagination={{ clickable: true, }} modules={[Pagination]}>
								<SwiperSlide><BaseImage src="/build/assets/images/media/media-30.jpg" alt="" /></SwiperSlide>
								<SwiperSlide>
									<Swiper className="mySwiper2 swiper-v swiper vertical swiper-vertical1" direction={"vertical"} spaceBetween={50} pagination={{ clickable: true, }}
										modules={[Pagination]}>
										<SwiperSlide><BaseImage src="/build/assets/images/media/media-25.jpg" alt="" /></SwiperSlide>
										<SwiperSlide><BaseImage src="/build/assets/images/media/media-31.jpg" alt="" /></SwiperSlide>
										<SwiperSlide><BaseImage src="/build/assets/images/media/media-32.jpg" alt="" /></SwiperSlide>
									</Swiper>
								</SwiperSlide>
								<SwiperSlide><BaseImage src="/build/assets/images/media/media-28.jpg" alt="" /></SwiperSlide>
								<SwiperSlide><BaseImage src="/build/assets/images/media/media-29.jpg" alt="" /></SwiperSlide>
							</Swiper>
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Effect Cube
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Effectcubedata} spaceBetween={30} cubeEffect={{ shadow: true, slideShadows: true, shadowOffset: 20, shadowScale: 0.94 }} effect={"cube"} navigation={true} pagination={{ dynamicBullets: true, clickable: true }} autoplay={true} className="mySwiper swiper swiper-fade cube-custom" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Effect Fade
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Effectfadedata} effect={"fade"} pagination={{ dynamicBullets: true, clickable: true }} navigation={true} autoplay={true} className="mySwiper swiper-fade" />
						</Card.Body>
					</Card>
				</Col>
				<Col xl={4} lg={6} md={6} sm={12} className="">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Effect Flip
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Effectflipdata} effect={"flip"} grabCursor={true} pagination={{ dynamicBullets: true, clickable: true }} navigation={true} autoplay={true} className="mySwiper" />
						</Card.Body>
					</Card>
				</Col>
			</Row>

			{/* <!--End::row-1 --> */}

			{/* <!-- Start:: row-2 --> */}

			<Row>
				<div className="col-xl-12">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Effect Coverflow
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Effectcovberflowdata} effect={"coverflow"} grabCursor={true} centeredSlides={false} slidesPerView={4} pagination={{ dynamicBullets: true, clickable: true }} autoplay={true} coverflowEffect={{ rotate: 50, stretch: 0, depth: 100, modifier: 1, slideShadows: true }} className="mySwiper" />
						</Card.Body>
					</Card>
				</div>
			</Row>

			{/* <!-- End:: row-2 --> */}

			{/* <!-- Start:: row-3 --> */}

			<Row>
				<div className="col-xl-12">
					<Card className="custom-card">
						<Card.Header>
							<Card.Title>
								Thumbs Gallery
							</Card.Title>
						</Card.Header>
						<Card.Body>
							<SpkSwiperJs slides={swiperdata.Thumbdata} navigation={true} autoplay={true} thumb={{ swiper: thumbsSwiper && !thumbsSwiper.destroyed ? thumbsSwiper : null }} className="mySwiper bd-gray-100 product-details-page" />
							<SpkSwiperJs slides={swiperdata.Thumbdata} onswiper={setThumbsSwiper} spaceBetween={10} slidesPerView={4} freemode={true} autoplay={true} watchslide={true} className="swiper-view-details mt-2 swiper-view" />
						</Card.Body>
					</Card>
				</div>
			</Row>

			{/* <!-- End:: row-3 --> */}

		</Fragment>
	)
};
// Assign layout
SwiperJs.layout = (page) => <MainLayout>{page}</MainLayout>;
export default SwiperJs;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/general/advanced-ui/swiper-js/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import SpkBasicCard from "$lib/@spk/SpkBasicCard.svelte";
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import { Col, Row } from "@sveltestrap/sveltestrap";
    import { register } from "swiper/element/bundle";
onMount(()=>{
register()
})
    const custompagination = {
        el: ".swiper-pagination",
        clickable: true,
        renderBullet: (index: any, className: any) => {
            return `<span class="${className}">${index + 1}</span>`;
        },
    };
    let thumbsSwiper:any; // This will store the swiper instance
    let autoplayConfig = { delay: 2500, disableOnInteraction: false };
    // Function to handle the swiper instance assignment
    const setThumbsSwiper = (swiper: any) => {
        thumbsSwiper = swiper;
    };
</script>

<!-- Page Title -->
<svelte:head>
    <title>SwiperJs | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader homepage="Swiper" activepage="Advanced Ui" page="Swiper" />
<!-- Page Header Close -->

<!-- Start::row-1 -->
<Row>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle=" Basic Swiper">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container class="swiper swiper-basic" autoplay={autoplayConfig}>
          <swiper-slide class="swiper-slide"
            ><img  loading="lazy" src="../../images/media/media-27.jpg" alt="" /></swiper-slide
          >
          <swiper-slide class="swiper-slide"
            ><img  loading="lazy" src="../../images/media/media-26.jpg" alt="" /></swiper-slide
          >
          <swiper-slide class="swiper-slide"
            ><img  loading="lazy" src="../../images/media/media-25.jpg" alt="" /></swiper-slide
          >
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="Swiper With Navigation">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper swiper-navigation"
          spaceBetween={30}
          centeredSlides={true}
          navigation={true}
        >
          <swiper-slide class="swiper-slide"
            ><img  loading="lazy" src="../../images/media/media-29.jpg" alt="" /></swiper-slide
          >
          <swiper-slide class="swiper-slide"
            ><img  loading="lazy" src="../../images/media/media-28.jpg" alt="" /></swiper-slide
          >
          <swiper-slide class="swiper-slide"
            ><img  loading="lazy" src="../../images/media/media-30.jpg" alt="" /></swiper-slide
          >
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard
      cardProps="custom-card"
      headerTitle="  Swiper with Pagination"
    >
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper pagination mySwiper custom-swiper"
          spaceBetween={30}
          centeredSlides={true}
          autoplay={autoplayConfig}
          pagination={{ clickable: true }}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-32.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-31.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-33.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="  Dynamic Pagination">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper pagination-dynamic mySwiper"
          autoplay={autoplayConfig}
          pagination={{ dynamicBullets: true, clickable: true }}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-21.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-17.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-16.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard
      cardProps="custom-card"
      headerTitle="  Pagination With Progress"
    >
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper pagination-progress mySwiper"
          pagination={{ type: "progressbar" }}
          spaceBetween={30}
          Navigation={true}
          centeredSlides={true}
          autoplay={autoplayConfig}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-12.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-8.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-5.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle=" Pagination Fraction">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper mySwiper pagination-fraction"
          pagination={{ type: "fraction" }}
          spaceBetween={30}
          Navigation={true}
          centeredSlides={true}
          autoplay={autoplayConfig}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-12.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-8.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-5.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="  Custom Paginatioin">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper custom-pagination mySwiper"
          Pagination={custompagination}
          spaceBetween={30}
          Navigation={true}
          centeredSlides={true}
          autoplay={autoplayConfig}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-25.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-5.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-33.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="Scrollbar Swiper">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper scrollbar-swiper mySwiper"
          scrollbar={{ hide: true }}
          autoplay={autoplayConfig}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-30.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-28.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-29.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle=" Vertical Swiper">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper vertical swiper-vertical mySwiper"
          direction={"vertical"}
          pagination={{ clickable: true }}
          autoplay={autoplayConfig}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-8.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-32.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-17.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="  Mouse Wheel Control">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper vertical vertical-mouse-control mySwiper"
          direction={"vertical"}
          slidesPerView={1}
          spaceBetween={30}
          mousewheel={true}
          pagination={{ clickable: true }}
          autoplay={autoplayConfig}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-28.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-30.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-32.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="  Keyboard Control">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper keyboard-control mySwiper"
          slidesPerView={1}
          spaceBetween={30}
          keyboard={{ enabled: true }}
          pagination={{ clickable: true }}
          autoplay={autoplayConfig}
          navigation={true}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-31.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-12.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-8.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="Nested Swiper">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper mySwiper1 swiper-h swiper swiper-horizontal1"
          spaceBetween={50}
          pagination={{ clickable: true }}
        >
          <!-- Slide 1 -->
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-30.jpg" alt="" /></swiper-slide
          >

          <!-- Slide 2 with Nested Swiper -->
          <swiper-slide>
            <swiper-container
              class="swiper mySwiper2 swiper-v swiper vertical swiper-vertical1"
              direction={"vertical"}
              spaceBetween={50}
              pagination={{ clickable: true }}
            >
              <!-- Nested Swiper Slides -->
              <swiper-slide
                ><img  loading="lazy" src="../../images/media/media-28.jpg" alt="" /></swiper-slide
              >
              <swiper-slide
                ><img  loading="lazy" src="../../images/media/media-30.jpg" alt="" /></swiper-slide
              >
              <swiper-slide
                ><img  loading="lazy" src="../../images/media/media-32.jpg" alt="" /></swiper-slide
              >
              <!-- Add more slides as needed -->
            </swiper-container>
          </swiper-slide>

          <!-- Slide 3 -->
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-28.jpg" alt="" /></swiper-slide
          >

          <!-- Slide 4 -->
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-29.jpg" alt="" /></swiper-slide
          >
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="Effect Cube">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper swiper-effect-cube mySwiper"
          effect={"cube"}
          grabCursor={true}
          cubeEffect={{
            shadow: true,
            slideShadows: true,
            shadowOffset: 20,
            shadowScale: 0.94,
          }}
          autoplay={autoplayConfig}
          pagination={true}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-62.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-63.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-64.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="Effect Fade">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper swiper-effect-cube mySwiper"
          spaceBetween={30}
          effect={"fade"}
          navigation={true}
          pagination={{ clickable: true }}
          autoplay={autoplayConfig}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-18.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-19.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-20.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
  <Col xl={4} lg={6} md={6} sm={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="  Effect Flip">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper swiper-effect-cube mySwiper"
          effect={"flip"}
          grabCursor={true}
          pagination={true}
          navigation={true}
          autoplay={autoplayConfig}
        >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-20.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-62.jpg" alt="" /></swiper-slide
          >
          <swiper-slide
            ><img  loading="lazy" src="../../images/media/media-63.jpg" alt="" /></swiper-slide
          >
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
</Row>
<!--End::row-1 -->

<!-- Start:: row-2 -->
<Row>
  <Col xl={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle="    Effect Coverflow">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper swiper-overflow mySwiper"
          effect={"coverflow"}
          grabCursor={true}
          slidesPerView={4}
          autoplay={autoplayConfig}
          coverflowEffect={{
            rotate: 50,
            stretch: 0,
            depth: 100,
            modifier: 1,
            slideShadows: true,
          }}
          pagination={{ clickable: true }}
        >
          <swiper-slide>
            <img
              class="img-fluid"
              src="../../images/media/media-40.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid"
              src="../../images/media/media-41.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid"
              src="../../images/media/media-42.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid"
              src="../../images/media/media-43.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid"
              src="../../images/media/media-44.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid"
              src="../../images/media/media-59.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid"
              src="../../images/media/media-46.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid"
              src="../../images/media/media-61.jpg"
              alt="img"
            />
          </swiper-slide>
          <div class="swiper-pagination"></div>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
</Row>
<!-- End:: row-2 -->

<!-- Start:: row-3 -->
<Row>
  <Col xl={12}>
    <SpkBasicCard cardProps="custom-card" headerTitle=" Thumbs Gallery">
      <div slot="customheader"></div>
      <div slot="content">
        <swiper-container
          class="swiper mySwiper1 mb-2"
          thumbs-swiper=".my-thumbs"
          spaceBetween={10}
          navigation={true}
          thumbs={{ swiper: thumbsSwiper }}
          autoplay={autoplayConfig}
        >
          <swiper-slide>
            <img
              class="img-fluid rounded w-100"
              src="../../images/media/media-1.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid rounded w-100"
              src="../../images/media/media-2.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid rounded w-100"
              src="../../images/media/media-3.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid rounded w-100"
              src="../../images/media/media-6.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid rounded w-100"
              src="../../images/media/media-7.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid rounded w-100"
              src="../../images/media/media-10.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide>
            <img
              class="img-fluid rounded w-100"
              src="../../images/media/media-11.jpg"
              alt="img"
            />
          </swiper-slide>
        </swiper-container>
        <swiper-container
          class="swiper swiper-view my-thumbs"
          onSwiper={setThumbsSwiper}
          spaceBetween={10}
          slidesPerView={4}
          freeMode={true}
          watchSlidesProgress={true}
        >

          <swiper-slide class="swiper-slide">
            <img
              class="img-fluid"
              src="../../images/media/media-1.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide class="swiper-slide">
            <img
              class="img-fluid"
              src="../../images/media/media-2.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide class="swiper-slide">
            <img
              class="img-fluid"
              src="../../images/media/media-3.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide class="swiper-slide">
            <img
              class="img-fluid"
              src="../../images/media/media-6.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide class="swiper-slide">
            <img
              class="img-fluid"
              src="../../images/media/media-7.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide class="swiper-slide">
            <img
              class="img-fluid"
              src="../../images/media/media-10.jpg"
              alt="img"
            />
          </swiper-slide>
          <swiper-slide class="swiper-slide">
            <img
              class="img-fluid"
              src="../../images/media/media-11.jpg"
              alt="img"
            />
          </swiper-slide>
        </swiper-container>
      </div>
    </SpkBasicCard>
  </Col>
</Row>
<!-- End:: row-3 -->
