// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/reusable-pages/spk-pricecard.svelte
<script>
    import { Card, CardBody } from "@sveltestrap/sveltestrap";
    import SpkBadge from "../uielements/badge/SpkBadge.svelte";
    import SpkButton from "../uielements/Button/SpkButton.svelte";

    export let price = {};
    export let cardClass = "";
</script>

<Card
    class={`custom-card dashboard-main-card pricing-card pricing-${price.color} ${cardClass}`}
>
    <CardBody class="p-4">
        {#if price.badge}
            <SpkBadge
                Color=""
                CustomClass="bg-dark text-white pricing-recommended-badge"
            >
                Recommended
            </SpkBadge>
        {/if}
        <div class="lh-1 mb-3">
            <span
                class={`avatar avatar-lg avatar-rounded bg-${price.color}-transparent svg-${price.color}`}
            >
                {@html price.svgIcon}
            </span>
        </div>
        <h5 class="fw-semibold">{price.title}</h5>
        <p class="text-muted">{price.description}</p>
        <div class="pricing-count">
            <span class="fs-13 d-block mb-1">Start at</span>
            <div class="d-flex align-items-end gap-2">
                <h2 class="fw-semibold mb-0 lh-1">{price.price}</h2>
                <span class="fs-13">/ {price.user} per user</span>
            </div>
        </div>

        <hr class="section-devider my-4" />

        <ul class="list-unstyled pricing-features-list">
            {#each price.features ?? [] as item}
                <li>
                    {#if typeof item === "string"}
                        {item}
                    {:else}
                        <span class="fw-medium">{item.label}</span> {item.value}
                    {/if}
                </li>
            {/each}
        </ul>
        <div class="d-grid mt-4">
            <SpkButton
                color=""
                customClass={`btn btn-lg btn-${price.btnColor}`}
            >
                Get Started
            </SpkButton>
        </div>
    </CardBody>
</Card>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/reusable-pages/spk-pricecard.jsx
import { Fragment } from "react";
import { Card } from "react-bootstrap";
import SpkButton from "../general-reusable/reusable-uielements/spk-buttons";
import SpkBadge from "../general-reusable/reusable-uielements/spk-badge";



const SpkPriceCard = ({ price, cardClass }) => {
    return (
        <Fragment>
            <Card className={`custom-card dashboard-main-card pricing-card pricing-${price.color} ${cardClass}`}>
                <Card.Body className="p-4">
                    {price.badge && (
                        <SpkBadge variant="" Customclass="bg-dark text-white pricing-recommended-badge">
                            Recommended
                        </SpkBadge>
                    )}
                    <div className="lh-1 mb-3">
                        <span className={`avatar avatar-lg avatar-rounded bg-${price.color}-transparent svg-${price.color}`}>
                            {price.svgIcon}
                        </span>
                    </div>
                    <h5 className="fw-semibold">{price.title}</h5>
                    <p className="text-muted">{price.description}</p>
                    <div className="pricing-count">
                        <span className="fs-13 d-block mb-1">Start at</span>
                        <div className="d-flex align-items-end gap-2">
                            <h2 className="fw-semibold mb-0 lh-1">{price.price}</h2>
                            <span className="fs-13">/ {price.user} per user</span>
                        </div>
                    </div>

                    <hr className="section-devider my-4" />

                    <ul className="list-unstyled pricing-features-list">
                        {price.features.map((item, index) => (
                            <li key={index}>
                                {typeof item === "string" ? (
                                    item
                                ) : (
                                    <>
                                        <span className="fw-medium">{item.label}</span> {item.value}
                                    </>
                                )}
                            </li>
                        ))}
                    </ul>
                    <div className="d-grid mt-4">
                        <SpkButton Buttonvariant="" Customclass={`btn btn-lg btn-${price.btnColor}`}>
                            Get Started
                        </SpkButton>
                    </div>
                </Card.Body>
            </Card>
        </Fragment>
    );
};

export default SpkPriceCard;
