// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/reusable-pages/spk-timelinecard.svelte
<script>
    import SpkBadge from "../uielements/badge/SpkBadge.svelte";

    export let timeline = {};
</script>

<div class="timeline-step">
    <div
        class="timeline-content"
        data-toggle="popover"
        data-placement="top"
        title=""
        data-content="And here's some amazing content. It's very engaging. Right?"
        data-original-title={timeline.date}
    >
        <div class="timeline-date_time-container">
            <SpkBadge Color="" CustomClass={`bg-${timeline.bgColor}`}
                >{timeline.date}</SpkBadge
            >
        </div>
        <div class={`inner-circle ${timeline.bgColor}`}></div>
        <p class="fw-medium mt-3 mb-1">{timeline.title}</p>
        <p class="text-muted mb-0 mb-lg-0">{timeline.description}</p>
    </div>
</div>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/reusable-pages/spk-timelinecard.jsx
import { Fragment } from "react";
import SpkBadge from "../general-reusable/reusable-uielements/spk-badge";



const SpkTimelineCard = ({ timeline }) => {
  return (
    <Fragment>
      <div className="timeline-step">
        <div className="timeline-content" data-toggle="popover" data-placement="top" title="" data-content="And here's some amazing content. It's very engaging. Right?" data-original-title={timeline.date}>
          <div className="timeline-date_time-container">
            <SpkBadge variant="" Customclass={`bg-${timeline.bgColor}`}>{timeline.date}</SpkBadge>
          </div>
          <div className={`inner-circle ${timeline.bgColor}`}></div>
          <p className="fw-medium mt-3 mb-1">{timeline.title}</p>
          <p className="text-muted mb-0 mb-lg-0">{timeline.description}</p>
        </div>
      </div>
    </Fragment>
  );
};

export default SpkTimelineCard;
