// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/reusable-pages/spk-teamcard.svelte
<script>
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";
    import SpkButton from "../uielements/Button/SpkButton.svelte";
    const basePath = __BASE_PATH__;

    export let member = {};

    const Icons = [
        {
            platform: "facebook",
            icon: "facebook-circle",
            url: member.socials?.facebook,
        },
        {
            platform: "twitter",
            icon: "twitter-x",
            url: member.socials?.twitter,
        },
        {
            platform: "linkedin",
            icon: "linkedin-box",
            url: member.socials?.linkedin,
        },
    ];
</script>

<Card class="custom-card">
    <Image
        src={`${basePath}${member.imgSrc}`}
        alt={member.name}
        class="card-img-top"
    />
    <CardBody class="text-center">
        <h6 class="fw-semibold mb-0">{member.name}</h6>
        <span class="text-muted fs-13">{member.role}</span>
        <div class="btn-list mt-3 justify-content-center d-flex gap-2">
            {#each Icons as idx}
                {#if idx.url}
                    <SpkButton
                        color=""
                        customClass="btn btn-light btn-icon rounded-circle border"
                    >
                        <i class={`ri-${idx.icon}-fill lh-1`}></i>
                    </SpkButton>
                {/if}
            {/each}
        </div>
    </CardBody>
</Card>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/reusable-pages/spk-teamcard.jsx

import { Fragment } from "react";
import { Card, Image } from "react-bootstrap";
import SpkButton from "../general-reusable/reusable-uielements/spk-buttons";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const SpkTeamCard = ({ member }) => {
  const Icons = [
    { platform: "facebook", icon: "facebook-circle", url: member.socials?.facebook },
    { platform: "twitter", icon: "twitter-x", url: member.socials?.twitter },
    { platform: "linkedin", icon: "linkedin-box", url: member.socials?.linkedin },
  ];

  return (
    <Fragment>
      <Card className="custom-card">
          <BaseImage src={member.imgSrc} alt={member.name}  className="card-img-top" style={{ borderTopLeftRadius: "0.5rem", borderTopRightRadius: "0.5rem" }}/>
        <Card.Body className="text-center">
          <h6 className="fw-semibold mb-0">{member.name}</h6>
          <span className="text-muted fs-13">{member.role}</span>
          <div className="mt-3 justify-content-center d-flex gap-2">
            {Icons.map((idx, index) =>
              idx.url ? (
                <SpkButton Buttonvariant="" key={index} Customclass="btn btn-light btn-icon rounded-circle border">
                  <i className={`ri-${idx.icon}-fill lh-1`}></i>
                </SpkButton>
              ) : null
            )}
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkTeamCard;
