// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/reusable-pages/spk-basicpricecard.svelte
<script>
    import { Card, CardBody } from "@sveltestrap/sveltestrap";
    import SpkBadge from "../uielements/badge/SpkBadge.svelte";
    import SpkButton from "../uielements/Button/SpkButton.svelte";

    export let price = {};
    export let cardClass = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class="p-4 text-center">
        <h5 class={`fw-semibold mb-3 ${price.titleColor}`}>{price.title}</h5>
        <div class="d-flex align-items-end justify-content-center gap-1 mb-4">
            <h2 class={`fw-semibold mb-0 lh-1 text-${price.priceColor}`}>
                {price.price}
            </h2>
            <span class="fs-13">/ {price.year}</span>
        </div>
        <ul class="list-unstyled pricing-features-list-1 mx-5 text-start mb-4">
            {#each price.features ?? [] as item}
                <li>
                    {typeof item === "string" ? item : item.value}
                </li>
            {/each}
        </ul>
        <div>
            <SpkBadge
                Color=""
                CustomClass={`bg-${price.badgeColor}-transparent py-1 px-3 fs-13 rounded-pill fw-normal`}
            >
                {price.percent} Off</SpkBadge
            >
            <div class="d-grid mt-3">
                <SpkButton color={price.btnColor} customClass="btn btn-lg"
                    >Choose Plan</SpkButton
                >
            </div>
        </div>
    </CardBody>
</Card>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/reusable-pages/spk-basicpricecard.jsx
import { Fragment } from "react";
import { Card } from "react-bootstrap";
import SpkButton from "../general-reusable/reusable-uielements/spk-buttons";
import SpkBadge from "../general-reusable/reusable-uielements/spk-badge";





const SpkBasicPriceCard = ({ price, cardClass = "" }) => {
  return (
    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className="p-4 text-center">
          <h5 className={`fw-semibold mb-3 ${price.titleColor}`}>{price.title}</h5>
          <div className="d-flex align-items-end justify-content-center gap-1 mb-4">
            <h2 className={`fw-semibold mb-0 lh-1 text-${price.priceColor}`}>{price.price}</h2>
            <span className="fs-13">/ {price.year}</span>
          </div>
          <ul className="list-unstyled pricing-features-list-1 mx-5 text-start mb-4">
            {price.features.map((item, index) => (
              <li key={index}>
                {typeof item === "string" ? item : item.value}
              </li>
            ))}
          </ul>
          <div>
            <SpkBadge variant="" Customclass={`bg-${price.badgeColor}-transparent py-1 px-3 fs-13 rounded-pill fw-normal`}> {price.percent} Off</SpkBadge>
            <div className="d-grid mt-3">
              <SpkButton Buttonvariant={price.btnColor} Customclass="btn btn-lg">Choose Plan</SpkButton>
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkBasicPriceCard;
