// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/forms/form-elements/input-group/input-group.jsx

import MainLayout from "@/Layouts/layout";
import SpkButton from "../../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import SpkDropdown from "../../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-dropdown";
import { inputgroup1, inputgroup10, inputgroup11, inputgroup2, inputgroup3, inputgroup4, inputgroup5, inputgroup6, inputgroup7, inputgroup8, inputgroup9 } from "../../../../../shared/data/prism-code/forms-prism";
import Pageheader from "../../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col, Dropdown, Form, InputGroup, Row } from "react-bootstrap";


const InputGroups = () => {

	return (

		<Fragment>

			{/* <!-- Page Header --> */}

			<Head title="Forms-inputgroup" />

			<Pageheader title="Forms" subtitle="Form Elements" currentpage="Input Group" activepage="Input Group" />

			{/* <!-- Page Header Close --> */}

			{/* <!-- Start:: row-1 --> */}

			<Row>
				<Col xl={12}>
					<ShowCode title="Input Groups" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup1}>
						<InputGroup className="mb-3">
							<InputGroup.Text className="" id="basic-addon1">@</InputGroup.Text>
							<Form.Control type="text" className="" placeholder="Username"
								aria-label="Username" aria-describedby="basic-addon1" />
						</InputGroup>
						<InputGroup className="mb-3">
							<Form.Control type="text" className="" placeholder="Recipient's username"
								aria-label="Recipient's username" aria-describedby="basic-addon2" />
							<InputGroup.Text className="" id="basic-addon2">@example.com</InputGroup.Text>
						</InputGroup>
						<Form.Label htmlFor="basic-url" className="form-label">Your vanity URL</Form.Label>
						<InputGroup className="mb-3">
							<InputGroup.Text className=""
								id="basic-addon3">https://example.com/</InputGroup.Text>
							<Form.Control type="text" className="" id="basic-url"
								aria-describedby="basic-addon3" />
						</InputGroup>
						<InputGroup className="mb-3">
							<InputGroup.Text className="">$</InputGroup.Text>
							<Form.Control type="text" className=""
								aria-label="Amount (to the nearest dollar)" />
							<InputGroup.Text className="">.00</InputGroup.Text>
						</InputGroup>
						<InputGroup className="mb-3">
							<Form.Control type="text" className="" placeholder="Username"
								aria-label="Username" />
							<InputGroup.Text className="">@</InputGroup.Text>
							<Form.Control type="text" className="" placeholder="Server"
								aria-label="Server" />
						</InputGroup>
						<InputGroup>
							<InputGroup.Text className="">With textarea</InputGroup.Text>
							<Form.Control as="textarea" className="" aria-label="With textarea" />
						</InputGroup>
					</ShowCode>
				</Col>
			</Row>

			{/* <!-- End:: row-1 --> */}

			{/* <!-- Start:: row-2 --> */}

			<Row>
				<Col xl={12}>
					<Row>
						<Col xl={12}>
							<ShowCode title="Multiple inputs" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup6}>
								<InputGroup>
									<InputGroup.Text className="custom-multi-input">First and last name</InputGroup.Text>
									<Form.Control type="text" aria-label="First name" className="" />
									<Form.Control type="text" aria-label="Last name" className="" />
								</InputGroup>
							</ShowCode>
						</Col>
						<Col xl={12}>
							<ShowCode title="Checkboxes and radios" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup7}>
								<InputGroup className="mb-3">
									<InputGroup.Text className="">
										<Form.Check className=" mt-0" type="checkbox" value=""
											aria-label="Checkbox for following text input" />
									</InputGroup.Text>
									<Form.Control type="text" className=""
										aria-label="Text input with checkbox" />
								</InputGroup>
								<InputGroup>
									<InputGroup.Text className="">
										<Form.Check className=" mt-0" type="radio" value=""
											aria-label="Radio button for following text input" />
									</InputGroup.Text>
									<Form.Control type="text" className=""
										aria-label="Text input with radio button" />
								</InputGroup>
							</ShowCode>
						</Col>
						<Col xl={12}>
							<ShowCode title="Multiple addons" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup8}>
								<InputGroup className="mb-3">
									<InputGroup.Text className="">
										<Form.Check className="mt-0" type="checkbox" value=""
											aria-label="Checkbox for following text input" />
									</InputGroup.Text>
									<Form.Control type="text" className=""
										aria-label="Text input with checkbox" />
								</InputGroup>
								<InputGroup>
									<InputGroup.Text className="">
										<Form.Check className="mt-0" type="radio" value=""
											aria-label="Radio button for following text input" />
									</InputGroup.Text>
									<Form.Control type="text" className=""
										aria-label="Text input with radio button" />
								</InputGroup>
							</ShowCode>
						</Col>
						<Col xl={12}>
							<ShowCode title="Segmented buttons" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup9}>
								<div className="input-group mb-3 segmented-custom">
									<SpkButton Buttontype="button" Buttonvariant="primary" >Action</SpkButton>
									<SpkDropdown toggleas="a" Togglevariant=""  Customtoggleclass="btn btn btn-primary dropdown-toggle dropdown-toggle-split no-caret dropdown-toggle fs-14 rounded-0"
										Arrowicon={true} Menuclass="dropdown-menu" Align="start">
										<Dropdown.Item >Action</Dropdown.Item>
										<Dropdown.Item >Another action</Dropdown.Item>
										<Dropdown.Item >Something else here</Dropdown.Item>
										<Dropdown.Divider />
										<Dropdown.Item >Separated link</Dropdown.Item>
									</SpkDropdown>
									<input type="text" className="form-control" aria-label="Text input with segmented dropdown button" />
								</div>
								<InputGroup>
									<Form.Control type="text" className=""
										aria-label="Text input with segmented dropdown button" />
									<SpkButton Buttontype="button" Buttonvariant="primary" >Action</SpkButton>
									<SpkDropdown toggleas="a" Togglevariant=""  Customtoggleclass="btn btn-primary dropdown-toggle dropdown-toggle-split no-caret"
										Arrowicon={true} Menuclass="dropdown-menu-end" Align="end">
										<Dropdown.Item >Action</Dropdown.Item>
										<Dropdown.Item >Another action</Dropdown.Item>
										<Dropdown.Item >Something else here</Dropdown.Item>
										<Dropdown.Divider />
										<Dropdown.Item >Separated link</Dropdown.Item>
									</SpkDropdown>
								</InputGroup>
							</ShowCode>
						</Col>
						<Col xl={12}>
							<ShowCode title="Custom select" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup10}>
								<InputGroup className="mb-3">
									<label className="input-group-text" htmlFor="inputGroupSelect01">Options</label>
									<Form.Select className="form-select" id="inputGroupSelect03" aria-label="Example select with button addon">
										<option>Choose...</option>
										<option value="1">One</option>
										<option value="2">Two</option>
										<option value="3">Three</option>
									</Form.Select>
								</InputGroup>
								<InputGroup className="mb-3">
									<Form.Select className="form-select" id="inputGroupSelect02">
										<option >Choose...</option>
										<option value="1">One</option>
										<option value="2">Two</option>
										<option value="3">Three</option>
									</Form.Select>
									<label className="input-group-text" htmlFor="inputGroupSelect02">Options</label>
								</InputGroup>
								<InputGroup className="mb-3">
									<SpkButton Buttonvariant='primary' Buttontype="button">Button</SpkButton>
									<Form.Select className="form-select" id="inputGroupSelect03" aria-label="Example select with button addon">
										<option>Choose...</option>
										<option value="1">One</option>
										<option value="2">Two</option>
										<option value="3">Three</option>
									</Form.Select>
								</InputGroup>
								<InputGroup>
									<Form.Select className="form-select" id="inputGroupSelect04" aria-label="Example select with button addon">
										<option>Choose...</option>
										<option value="1">One</option>
										<option value="2">Two</option>
										<option value="3">Three</option>
									</Form.Select>
									<SpkButton Buttonvariant='primary' Buttontype="button">Button</SpkButton>
								</InputGroup>
							</ShowCode>
						</Col>
					</Row>
				</Col>
			</Row>

			{/* <!-- End:: row-2 --> */}

			{/* <!-- Start:: row-3 --> */}

			<Row>
				<Col xl={12}>
					<ShowCode title="Sizing" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup2}>
						<InputGroup className="input-group-sm mb-3">
							<InputGroup.Text className="" id="inputGroup-sizing-sm">Small</InputGroup.Text>
							<Form.Control type="text" className="form-control"
								aria-label="Sizing example input"
								aria-describedby="inputGroup-sizing-sm" />
						</InputGroup>
						<InputGroup className="mb-3">
							<InputGroup.Text className=""
								id="inputGroup-sizing-default">Default</InputGroup.Text>
							<Form.Control type="text" className="form-control"
								aria-label="Sizing example input"
								aria-describedby="inputGroup-sizing-default" />
						</InputGroup>
						<InputGroup className="input-group-lg">
							<InputGroup.Text className="" id="inputGroup-sizing-lg">Large</InputGroup.Text>
							<Form.Control type="text" className="form-control"
								aria-label="Sizing example input"
								aria-describedby="inputGroup-sizing-lg" />
						</InputGroup>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Buttons addons" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup3}>
						<InputGroup className="mb-3">
							<SpkButton Buttonvariant='primary' Buttontype="button"
								Id="button-addon1">Button</SpkButton>
							<Form.Control type="text" placeholder=""
								aria-label="Example text with button addon"
								aria-describedby="button-addon1" />
						</InputGroup>
						<InputGroup className="mb-3">
							<SpkButton Buttonvariant='primary' Buttontype="button"
								Id="button-addon2">Button</SpkButton>
							<Form.Control type="text" placeholder="Recipient's username"
								aria-label="Recipient's username" aria-describedby="button-addon2" />
						</InputGroup>
						<InputGroup className="mb-3">
							<SpkButton Buttonvariant='primary' Buttontype="button" Customclass="custom-multi-input">Button</SpkButton>
							<SpkButton Buttonvariant='primary' Buttontype="button" Customclass="custom-multi-input">Button</SpkButton>
							<Form.Control type="text" placeholder=""
								aria-label="Example text with two button addons" />
						</InputGroup>
						<InputGroup>
							<Form.Control type="text" placeholder="Recipient's username"
								aria-label="Recipient's username with two button addons" />
							<SpkButton Buttonvariant='primary' Buttontype="button" Customclass="custom-multi-input">Button</SpkButton>
							<SpkButton Buttonvariant='primary' Buttontype="button" Customclass="custom-multi-input">Button</SpkButton>
						</InputGroup>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Buttons with dropdowns" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup4}>
						<InputGroup className="mb-3">
							<SpkDropdown Togglevariant="" Customtoggleclass="btn btn-primary dropdown-toggle" Toggletext="Dropdown">
								<Dropdown.Item >Action</Dropdown.Item>
								<Dropdown.Item >Another action</Dropdown.Item>
								<Dropdown.Item >Something else here</Dropdown.Item>
								<Dropdown.Divider>
								</Dropdown.Divider>
								<Dropdown.Item >Separated link</Dropdown.Item>
							</SpkDropdown>
							<Form.Control type="text" className="form-control"
								aria-label="Text input with dropdown button" />
						</InputGroup>
						<InputGroup className="mb-3">
							<Form.Control type="text" className="form-control"
								aria-label="Text input with dropdown button" />
							<div className="dropdown">
								<SpkDropdown Togglevariant="" Customtoggleclass="btn btn-outline-primary dropdown-toggle rounded-0 rounded-end-1 " Toggletext="Dropdown">
									<Dropdown.Item >Action</Dropdown.Item>
									<Dropdown.Item >Another action</Dropdown.Item>
									<Dropdown.Item >Something else here</Dropdown.Item>
									<Dropdown.Divider>
									</Dropdown.Divider>
									<Dropdown.Item >Separated link</Dropdown.Item>
								</SpkDropdown>
							</div>

						</InputGroup>
						<InputGroup>
							<SpkDropdown Togglevariant="" Arrowicon={true} Customtoggleclass="btn btn-primary-transparent dropdown-toggle no-caret custom-form-group" Toggletext="Dropdown">
								<Dropdown.Item >Action</Dropdown.Item>
								<Dropdown.Item >Another action</Dropdown.Item>
								<Dropdown.Item >Something else here</Dropdown.Item>
								<Dropdown.Divider>
								</Dropdown.Divider>
								<Dropdown.Item >Separated link</Dropdown.Item>
							</SpkDropdown>
							<Form.Control type="text" className="custom-input-group"
								aria-label="Text input with 2 dropdown buttons " />
							<div className="dropdown ">
								<SpkDropdown Togglevariant="" Arrowicon={true} Customtoggleclass="btn btn-primary-transparent dropdown-toggle rounded-0 rounded-end-1 no-caret custom-form-group" Toggletext="Dropdown" >
									<Dropdown.Item >Action</Dropdown.Item>
									<Dropdown.Item >Another action</Dropdown.Item>
									<Dropdown.Item >Something else here</Dropdown.Item>
									<Dropdown.Divider>
									</Dropdown.Divider>
									<Dropdown.Item >Separated link</Dropdown.Item>
								</SpkDropdown>
							</div>
						</InputGroup>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Custom file input" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup5}>
						<InputGroup className="mb-3">
							<label className="input-group-text" htmlFor="inputGroupFile01">Upload</label>
							<Form.Control type="file" className="form-control" id="inputGroupFile01" />
						</InputGroup>

						<InputGroup className="mb-3">
							<Form.Control type="file" className="form-control" id="inputGroupFile02" />
							<label className="input-group-text" htmlFor="inputGroupFile02">Upload</label>
						</InputGroup>

						<InputGroup className="mb-3">
							<SpkButton Buttonvariant='primary' Buttontype="button"
								Id="inputGroupFileAddon03">Button</SpkButton>
							<Form.Control type="file" className="form-control" id="inputGroupFile03"
								aria-describedby="inputGroupFileAddon03" aria-label="Upload" />
						</InputGroup>

						<InputGroup>
							<Form.Control type="file" className="form-control" id="inputGroupFile04"
								aria-describedby="inputGroupFileAddon04" aria-label="Upload" />
							<SpkButton Buttonvariant='primary' Buttontype="button"
								Id="inputGroupFileAddon04">Button</SpkButton>
						</InputGroup>
					</ShowCode>
				</Col>
				<Col xl={12}>
					<ShowCode title="Wrapping" customCardClass="custom-card" customCardBodyClass="" reactCode={inputgroup11}>
						<InputGroup className="flex-nowrap">
							<InputGroup.Text className="" id="addon-wrapping">@</InputGroup.Text>
							<Form.Control type="text" className="" placeholder="Username"
								aria-label="Username" aria-describedby="addon-wrapping" />
						</InputGroup>
					</ShowCode>
				</Col>
			</Row>

			{/* <!-- End:: row-3 --> */}

		</Fragment>
	)
};
// Assign layout
InputGroups.layout = (page) => <MainLayout>{page}</MainLayout>;
export default InputGroups;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/pages/forms/form-elements/input-group/+page.svelte
<script lang="ts">
  import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
  import {
    inputgroup1,
    inputgroup10,
    inputgroup11,
    inputgroup2,
    inputgroup3,
    inputgroup4,
    inputgroup5,
    inputgroup6,
    inputgroup7,
    inputgroup8,
    inputgroup9,
  } from "$lib/components/common/prism-code/formsprism";
  import {
    Col,
    Row,
    InputGroup,
    InputGroupText,
    Input,
    Label,
  } from "@sveltestrap/sveltestrap";
  import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";
  import SpkDropdown from "$lib/@spk/uielements/Dropdown/SpkDropdown.svelte";
  import ShowCode from "$lib/components/layout-components/showcode/ShowCode.svelte";
  import { Dropdownoption } from "$lib/data/uielements/dropdowndata";
</script>

<!-- Page Title -->
<svelte:head>
  <title>InputGroup | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
  homepage="Input Group"
  activepage="Forms"
  subTitle=" Form Elements"
  page="Input Group"
/>
<!-- Page Header Close -->

<!-- Start:: row-1 -->
<Row>
  <Col xl={12}>
    <ShowCode title="Input Groups" svelteCode={inputgroup1}>
      <InputGroup class="mb-3">
        <InputGroupText id="basic-addon1">@</InputGroupText>
        <Input
          type="text"
          class="form-control"
          placeholder="Username"
          aria-label="Username"
          aria-describedby="basic-addon1"
        />
      </InputGroup>
      <InputGroup class="mb-3">
        <Input
          type="text"
          class="form-control"
          placeholder="Recipient's username"
          aria-label="Recipient's username"
          aria-describedby="basic-addon2"
        />
        <InputGroupText id="basic-addon2">@example.com</InputGroupText>
      </InputGroup>
      <Label for="basic-url" class="form-label">Your vanity URL</Label>
      <InputGroup class="mb-3">
        <InputGroupText class="" id="basic-addon3"
          >https://example.com/</InputGroupText
        >
        <Input
          type="text"
          class="form-control"
          id="basic-url"
          aria-describedby="basic-addon3"
        />
      </InputGroup>
      <InputGroup class="mb-3">
        <InputGroupText class="">$</InputGroupText>
        <Input
          type="text"
          class="form-control"
          aria-label="Amount (to the nearest dollar)"
        />
        <InputGroupText>.00</InputGroupText>
      </InputGroup>
      <InputGroup class="mb-3">
        <Input
          type="text"
          class="form-control"
          placeholder="Username"
          aria-label="Username"
        />
        <InputGroupText class="">@</InputGroupText>
        <Input
          type="text"
          class="form-control"
          placeholder="Server"
          aria-label="Server"
        />
      </InputGroup>
      <InputGroup class="">
        <InputGroupText class="">With textarea</InputGroupText>
        <Input
          type="textarea"
          class="form-control"
          aria-label="With textarea"
        />
      </InputGroup>
    </ShowCode>
  </Col>
</Row>
<!-- End:: row-1 -->

<!-- Start:: row-2 -->
<Row>
  <Col xl={12} class="col-xl-12">
    <Row class="row">
      <Col xl={12}>
        <ShowCode title="Multiple inputs" svelteCode={inputgroup7}>
          <InputGroup>
            <InputGroupText>First, last name</InputGroupText>
            <Input type="text" aria-label="First name" />
            <Input type="text" aria-label="Last name" />
          </InputGroup>
        </ShowCode>
      </Col>
      <Col xl={12}>
        <ShowCode title="Checkboxes and radios" svelteCode={inputgroup8}>
          <InputGroup class="mb-3 custom-form-input">
            <InputGroupText>
              <Input
                class=" mt-0"
                type="checkbox"
                aria-label="Checkbox for following text input"
              />
            </InputGroupText>
            <Input type="text" aria-label="Text input with checkbox" />
          </InputGroup>
          <InputGroup class="custom-form-input">
            <InputGroupText>
              <Input
                class="mt-0"
                type="radio"
                value=""
                aria-label="checkbox button for following text input"
              />
            </InputGroupText>
            <Input type="text" aria-label="Text input with radio button" />
          </InputGroup>
        </ShowCode>
      </Col>
      <Col xl={12}>
        <ShowCode title="Multiple addons" svelteCode={inputgroup9}>
          <InputGroup class="mb-3 custom-form-input">
            <InputGroupText>
              <Input
                class="mt-0"
                type="checkbox"
                value=""
                aria-label="Checkbox for following text input"
              />
            </InputGroupText>
            <Input type="text" aria-label="Text input with checkbox" />
          </InputGroup>
          <InputGroup class="custom-form-input">
            <InputGroupText>
              <Input
                class="mt-0"
                type="radio"
                value=""
                aria-label="Radio button for following text input"
              />
            </InputGroupText>
            <Input type="text" aria-label="Text input with radio button" />
          </InputGroup>
        </ShowCode>
      </Col>
      <Col xl={12}>
        <ShowCode title="Segmented buttons" svelteCode={inputgroup10}>
          <InputGroup class="mb-3 segment-group">
            <SpkButton color="primary" buttontype="button" text="Action" />
            <SpkDropdown
              Color="primary custom-form-btn"
              Caret={true}
              parent=""
              option={Dropdownoption}
            />
            <Input
              type="text"
              class=""
              aria-label="Text input with segmented dropdown button"
            />
          </InputGroup>
          <InputGroup class="segment-left-group">
            <Input
              type="text"
              aria-label="Text input with segmented dropdown button"
            />
            <SpkButton color="primary" buttontype="button" text="Action" />
            <SpkDropdown
              Color="primary custom-form-btn1"
              Caret={true}
              parent=""
              option={Dropdownoption}
            />
          </InputGroup>
        </ShowCode>
      </Col>
      <Col xl={12}>
        <ShowCode
          title="Custom select"
          customCardBodyClass=""
          svelteCode={inputgroup11}
        >
          <InputGroup class="mb-3">
            <label class="input-group-text" for="inputGroupSelect01"
              >Options</label
            >
            <Input
              type="select"
              class="form-select"
              id="inputGroupSelect03"
              aria-label="Example select with button addon"
            >
              <option>Choose...</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </Input>
          </InputGroup>
          <InputGroup class="mb-3">
            <Input type="select" class="form-select" id="inputGroupSelect02">
              <option>Choose...</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </Input>
            <label class="input-group-text" for="inputGroupSelect02"
              >Options</label
            >
          </InputGroup>
          <InputGroup class="mb-3">
            <SpkButton color="primary" buttontype="button" text="Button" />
            <Input
              type="select"
              class="form-select"
              id="inputGroupSelect03"
              aria-label="Example select with button addon"
            >
              <option>Choose...</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </Input>
          </InputGroup>
          <InputGroup>
            <Input
              type="select"
              class="form-select"
              id="inputGroupSelect04"
              aria-label="Example select with button addon"
            >
              <option>Choose...</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </Input>
            <SpkButton color="primary" buttontype="button" text="Button" />
          </InputGroup>
        </ShowCode>
      </Col>
    </Row>
  </Col>
  <Col xl={12}>
    <Row>
      <Col xl={12}>
        <ShowCode title="Sizing" svelteCode={inputgroup3}>
          <InputGroup class="input-group-sm mb-3">
            <InputGroupText class="" id="inputGroup-sizing-sm"
              >Small</InputGroupText
            >
            <Input
              type="text"
              class="form-control"
              aria-label="Sizing example input"
              aria-describedby="inputGroup-sizing-sm"
            />
          </InputGroup>
          <InputGroup class="mb-3">
            <InputGroupText class="" id="inputGroup-sizing-default"
              >Default</InputGroupText
            >
            <Input
              type="text"
              class="form-control"
              aria-label="Sizing example input"
              aria-describedby="inputGroup-sizing-default"
            />
          </InputGroup>
          <InputGroup class="input-group-lg">
            <InputGroupText class="" id="inputGroup-sizing-lg"
              >Large</InputGroupText
            >
            <Input
              type="text"
              class="form-control"
              aria-label="Sizing example input"
              aria-describedby="inputGroup-sizing-lg"
            />
          </InputGroup>
        </ShowCode>
      </Col>
      <Col xl={12}>
        <ShowCode title="Buttons addons" svelteCode={inputgroup4}>
          <InputGroup class="mb-3">
            <SpkButton
              color="primary"
              buttontype="button"
              id="button-addon1"
              text="Button"
            />
            <Input
              type="text"
              placeholder=""
              aria-label="Example text with button addon"
              aria-describedby="button-addon1"
            />
          </InputGroup>
          <InputGroup class="mb-3">
            <Input
              type="text"
              placeholder="Recipient's username"
              aria-label="Recipient's username"
              aria-describedby="button-addon2"
            />
            <SpkButton
              color="primary"
              buttontype="button"
              id="button-addon1"
              text="Button"
            />
          </InputGroup>
          <InputGroup class="mb-3">
            <SpkButton
              color="primary"
              buttontype="button"
              id="button-addon1"
              text="Button"
            />
            <SpkButton
              color="primary"
              buttontype="button"
              id="button-addon1"
              text="Button"
            />
            <Input
              type="text"
              placeholder=""
              aria-label="Example text with two button addons"
            />
          </InputGroup>
          <InputGroup>
            <Input
              type="text"
              placeholder="Recipient's username"
              aria-label="Recipient's username with two button addons"
            />
            <SpkButton
              color="primary"
              buttontype="button"
              id="button-addon1"
              text="Button"
            />
            <SpkButton
              color="primary"
              buttontype="button"
              id="button-addon1"
              text="Button"
            />
          </InputGroup>
        </ShowCode>
      </Col>
      <Col xl={12}>
        <ShowCode title="Buttons with dropdowns" svelteCode={inputgroup5}>
          <InputGroup class="mb-3 btn-dropdown-grp custom-drop">
            <SpkDropdown
              Color="primary"
              Caret={true}
              parent={`Dropdown`}
              option={Dropdownoption}
            />
            <Input
              type="text"
              class="form-control"
              aria-label="Text input with dropdown button"
            />
          </InputGroup>
          <InputGroup class="mb-3 btn-dropdown-grp custom-drop1">
            <Input
              type="text"
              class="form-control"
              aria-label="Text input with dropdown button"
            />
            <SpkDropdown
              Color="outline-primary"
              Caret={true}
              parent={`Dropdown`}
              option={Dropdownoption}
            />
          </InputGroup>
          <InputGroup class="flex-nowrap btn-dropdown-grp ">
            <SpkDropdown
              Color="primary-transparent px-2 px-sm-3 custom-drop2"
              Caret={true}
              parent={`Dropdown`}
              option={Dropdownoption}
            />
            <Input
              type="text"
              class=""
              aria-label="Text input with 2 dropdown buttons"
            />
            <SpkDropdown
              Color="primary-transparent px-2 px-sm-3 custom-drop3"
              Caret={true}
              parent={`Dropdown`}
              option={Dropdownoption}
            />
          </InputGroup>
        </ShowCode>
      </Col>
      <Col xl={12}>
        <ShowCode title="Custom file input" svelteCode={inputgroup6}>
          <InputGroup class="mb-3 custom-upload">
            <InputGroupText class="input-group-text" for="inputGroupFile01"
              >Upload</InputGroupText
            >
            <Input type="file" class="form-control" id="inputGroupFile01" />
          </InputGroup>
          <InputGroup class="mb-3 custom-upload">
            <Input type="file" class="form-control" id="inputGroupFile02" />
            <InputGroupText class="input-group-text" for="inputGroupFile02"
              >Upload</InputGroupText
            >
          </InputGroup>

          <InputGroup class="mb-3 custom-upload">
            <SpkButton
              color="primary"
              buttontype="button"
              id="inputGroupFileAddon03"
              text="Button"
            />
            <Input
              type="file"
              class="form-control"
              id="inputGroupFile03"
              aria-describedby="inputGroupFileAddon03"
              aria-label="Upload"
            />
          </InputGroup>
          <InputGroup class="custom-upload">
            <Input
              type="file"
              class="form-control"
              id="inputGroupFile04"
              aria-describedby="inputGroupFileAddon04"
              aria-label="Upload"
            />
            <SpkButton
              color="primary"
              buttontype="button"
              id="inputGroupFileAddon04"
              text="Button"
            />
          </InputGroup>
        </ShowCode>
      </Col>
    </Row>
  </Col>
</Row>
<!-- End:: row-2 -->

<!-- Start:: row-3 -->
<Row>
  <Col xl={12}>
    <ShowCode title="Warpping" svelteCode={inputgroup2}>
      <InputGroup class="flex-nowrap">
        <InputGroupText id="addon-wrapping">@</InputGroupText>
        <Input
          type="text"
          placeholder="Username"
          aria-label="Username"
          aria-describedby="addon-wrapping"
        />
      </InputGroup>
    </ShowCode>
  </Col>
</Row>
<!-- End:: row-3 -->
