// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/applications/task/list-view/list-view.jsx

import { Listviewassigneddata, Prioritydata, Statusdata, taskData, Taskstable } from "../../../../shared/data/applications/task/listviewdata";
import React, { Fragment, useState } from "react";
import { Card, Col, Dropdown, Form, Modal, Pagination, Row } from "react-bootstrap";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import SpkListCard from "../../../../shared/@spk-reusable-components/application-reusable/spk-listcard";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import SpkDatepickr from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-datepicker";
import SpkSelect from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import SpkDropdown from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-dropdown";
import SpkBadge from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import SpkTooltips from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-tooltips";
import SpkTables from "../../../../shared/@spk-reusable-components/reusable-tables/spk-tables";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";


const TaskListView = () => {

    function getStatusColor(status) {
        switch (status) {
            case 'Completed':
                return 'success';
            case 'In Progress':
                return 'orange';
            case 'Pending':
                return 'info';
            default:
                return 'secondary';
        }
    }

    function getPriorityClass(priority) {
        switch (priority) {
            case 'High':
                return 'bg-danger-transparent';
            case 'Medium':
                return 'bg-warning-transparent';
            case 'Low':
                return 'bg-teal-transparent';
            default:
                return 'bg-secondary';
        }
    }

    const [show, setShow] = useState(false);

    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);

    const [dates, setDates] = useState({});
    const handleDateChange = (key, date) => {
        if (date) {
            setDates((prevDates) => ({
                ...prevDates,
                [key]: date,
            }));
        } else {
            setDates((prevDates) => {
                const { [key]: removedKey, ...rest } = prevDates;
                return rest;
            });
        }
    };

    const [allData, setAllData] = useState(Taskstable)

    const handleRemove = (id) => {
        const newList = allData.filter((idx) => idx.id !== id)
        setAllData(newList)
    }
    const [selectedTasks, setSelectedTasks] = useState(
        Taskstable.map((_, index) => index === 1 || index === 4 || index === 5 || index === 7)
    );
    const handleCheckboxChange = (index) => {
        const updatedSelectedTasks = [...selectedTasks];
        updatedSelectedTasks[index] = !updatedSelectedTasks[index];
        setSelectedTasks(updatedSelectedTasks);
    };
    const handleSelectAll = () => {
        const areAllSelected = selectedTasks.every((selected) => selected);
        setSelectedTasks(Taskstable.map(() => !areAllSelected));
    };
    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Tasks-List View" />

            <Pageheader title="Applications" subtitle="Tasks" currentpage="List View" activepage="List View" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-2 --> */}

            <Row>
                <Col xl={12}>
                    <Row>
                        {taskData.map((idx, index) => (
                            <Col xl={3} lg={6} key={index}>
                                <SpkListCard titleClass="mb-2 fs-12" listCard={true} cardClass={idx.cardClass} list={idx} />
                            </Col>
                        ))}
                    </Row>
                </Col>
            </Row>
            <Col xxl={12} xl={12} className="">
                <Card className="custom-card">
                    <Card.Header className="justify-content-between">
                        <div className="card-title">
                            Total Tasks
                        </div>
                        <div className="d-flex custom-task">
                            <SpkButton Buttonvariant="primary" onClickfunc={handleShow} Customclass="btn btn-sm btn-wave waves-light me-1" data-bs-toggle="modal" data-bs-target="#create-task"><i className="ri-add-line fw-medium align-middle me-1"></i> Create Task</SpkButton>
                            <Modal show={show} onHide={handleClose} className="modal fade" id="create-task" tabIndex={-1} centered>
                                <Modal.Header>
                                    <h6 className="modal-title">Add Task</h6>
                                    <button type="button" onClick={handleClose} className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </Modal.Header>
                                <Modal.Body>
                                    <Row className=" gy-2">
                                        <Col xl={6}>
                                            <Form.Label htmlFor="task-name" className="">Task Name</Form.Label>
                                            <Form.Control type="text" className="" id="task-name" placeholder="Task Name" />
                                        </Col>
                                        <Col xl={6}>
                                            <Form.Label htmlFor="task-id" className="">Task ID</Form.Label>
                                            <Form.Control type="text" className="" id="task-id" placeholder="Task ID" />
                                        </Col>
                                        <Col xl={6}>
                                            <Form.Label className="">Assigned Date</Form.Label>
                                            <div className="form-group">
                                                <div className="input-group flex-nowrap">
                                                    <div className="input-group-text text-muted"> <i className="ri-calendar-line"></i> </div>
                                                    <SpkDatepickr className="form-control" Timeinput="Time:" dateFormat="yy/MM/dd h:mm aa" selected={dates["startDate"] ? new Date(dates["startDate"]) : null} onChange={(date) => handleDateChange("startDate", date)} placeholderText='Choose date and time' showTimeInput />
                                                </div>
                                            </div>
                                        </Col>
                                        <Col xl={6}>
                                            <Form.Label>Due Date</Form.Label>
                                            <div className="form-group">
                                                <div className="input-group flex-nowrap">
                                                    <div className="input-group-text text-muted"> <i className="ri-calendar-line"></i> </div>
                                                    <SpkDatepickr className="form-control" Timeinput="Time:" dateFormat="yy/MM/dd h:mm aa" selected={dates["dueDate"] ? new Date(dates["dueDate"]) : null} onChange={(date) => handleDateChange("dueDate", date)} placeholderText='Choose date and time' showTimeInput />
                                                </div>
                                            </div>
                                        </Col>
                                        <Col xl={6}>
                                            <Form.Label>Status</Form.Label>
                                            <SpkSelect name="state" option={Statusdata} mainClass="js-example-placeholder-multiple w-full js-states" menuplacement='auto' classNameprefix="Select2" defaultvalue={[Statusdata[0]]} />
                                        </Col>
                                        <Col xl={6}>
                                            <Form.Label>Priority</Form.Label>
                                            <SpkSelect name="state" option={Prioritydata} mainClass="js-example-placeholder-multiple w-full js-states" menuplacement='auto' classNameprefix="Select2" defaultvalue={[Prioritydata[0]]} />
                                        </Col>
                                        <Col xl={12}>
                                            <Form.Label>Assigned To</Form.Label>
                                            <SpkSelect multi name="state" option={Listviewassigneddata} mainClass="js-example-placeholder-multiple w-full js-states"
                                                menuplacement='auto' classNameprefix="Select2" />
                                        </Col>
                                    </Row>
                                </Modal.Body>
                                <div className="modal-footer">
                                    <SpkButton Buttontype="button" onClickfunc={handleClose} Buttonvariant="light" Customclass="" Buttondismiss="modal">
                                        Cancel
                                    </SpkButton>
                                    <SpkButton Buttontype="button" Buttonvariant="primary" Customclass="" >
                                        Add Task
                                    </SpkButton>
                                </div>
                                {/* </div> */}
                            </Modal>
                            <SpkDropdown toggleas="a"  Customtoggleclass="btn btn-icon btn-secondary-light btn-sm btn-wave waves-light no-caret" IconClass="ti ti-dots-vertical" Icon={true}>
                                <li><Dropdown.Item >New Tasks</Dropdown.Item></li>
                                <li><Dropdown.Item >Pending Tasks</Dropdown.Item></li>
                                <li><Dropdown.Item >Completed Tasks</Dropdown.Item></li>
                                <li><Dropdown.Item >Inprogress Tasks</Dropdown.Item></li>
                            </SpkDropdown>
                        </div>
                    </Card.Header>
                    <Card.Body className="p-0">
                        <div className="table-responsive">
                            <SpkTables tableClass="text-nowrap" headerClass="table-light" checked={selectedTasks.every((selected) => selected)} onChange={handleSelectAll} showCheckbox={true} header={[{ title: 'Task' }, { title: 'Task ID' }, { title: 'Assigned Date' }, { title: 'Status' }, { title: 'Due Date' }, { title: 'Priority' }, { title: 'Assigned To' }, { title: 'Action' }]} >
                                {allData.map((task, index) => (
                                    <tr className="task-list" key={task.id}>
                                        <td className="task-checkbox">
                                            <input className="form-check-input" type="checkbox" aria-label="..." checked={selectedTasks[index]} onChange={() => handleCheckboxChange(index)} />
                                        </td>
                                        <td>
                                            <BaseLink href="#!" className="fw-medium" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                                                {task.title}
                                            </BaseLink>
                                        </td>
                                        <td><span className="fw-medium">{task.code}</span></td>
                                        <td>{task.startDate}</td>
                                        <td>
                                            <span className={`fw-medium text-${getStatusColor(task.status)}`}>
                                                {task.status}
                                            </span>
                                        </td>
                                        <td>{task.dueDate}</td>
                                        <td>
                                            <SpkBadge variant="" Customclass={`badge ${getPriorityClass(task.priority)}`}>
                                                {task.priority}
                                            </SpkBadge>
                                        </td>
                                        <td>
                                            <div className="avatar-list-stacked">
                                                {task.avatars.map((src, idx) => (
                                                    <span className="avatar avatar-sm avatar-rounded" key={idx}>
                                                        <BaseImage src={src} alt="img" />
                                                    </span>
                                                ))}
                                                {task.extraMembers > 0 && (
                                                    <BaseLink className="avatar avatar-sm bg-primary avatar-rounded text-fixed-white" href="#!">
                                                        +{task.extraMembers}
                                                    </BaseLink>
                                                )}
                                            </div>
                                        </td>
                                        <td>
                                            <SpkTooltips placement="top" title="Edit">
                                                <SpkButton Buttonvariant="" Customclass="btn btn-primary-light btn-icon btn-sm">
                                                    <i className="ri-edit-line"></i>
                                                </SpkButton>
                                            </SpkTooltips>
                                            <SpkButton Buttonvariant="" onClickfunc={() => handleRemove(task.id)} Customclass="btn btn-danger-light btn-icon ms-1 btn-sm task-delete-btn">
                                                <i className="ri-delete-bin-5-line"></i>
                                            </SpkButton>
                                        </td>
                                    </tr>
                                ))}
                            </SpkTables>
                        </div>
                    </Card.Body>
                    <Card.Footer>
                        <div className="d-flex align-items-center">
                            <div> Showing 10 Entries <i className="bi bi-arrow-right ms-2 fw-semibold"></i> </div>
                            <div className="ms-auto">
                                <nav aria-label="Page navigation" className="pagination-style-2">
                                    <Pagination className="mb-0 flex-wrap">
                                        <Pagination.Prev disabled>Prev</Pagination.Prev>
                                        <Pagination.Item>1</Pagination.Item>
                                        <Pagination.Item active>2</Pagination.Item>
                                        <Pagination.Item><i className="bi bi-three-dots"></i></Pagination.Item>
                                        <Pagination.Item>17</Pagination.Item>
                                        <Pagination.Next className="text-primary">Next</Pagination.Next>
                                    </Pagination>
                                </nav>
                            </div>
                        </div>
                    </Card.Footer>
                </Card>
            </Col>

            {/* <!--End:: row - 2 -- > */}

        </Fragment >
    )
};
// Assign layout
TaskListView.layout = (page) => <MainLayout>{page}</MainLayout>;
export default TaskListView;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/applications/task/list-view.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import SpkListcard from "@/shared/@spk/application-reusable/spk-listcard.svelte";
    import SpkTablescomponent from "@/shared/@spk/SpkTablescomponent.svelte";
    import SpkBadge from "@/shared/@spk/uielements/badge/SpkBadge.svelte";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import SpkDropdown from "@/shared/@spk/uielements/Dropdown/SpkDropdown.svelte";
    import SpkTooltips from "@/shared/@spk/uielements/Tooltips/SpkTooltips.svelte";
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import {
        Listviewassigneddata,
        Prioritydata,
        Statusdata,
        taskData,
        Taskstable,
    } from "@/shared/data/applications/task/listviewdata";
    import { DropdownNewTasks } from "@/shared/data/uielements/dropdowndata";
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Col,
        Image,
        Input,
        Label,
        Modal,
        ModalBody,
        ModalHeader,
        Pagination,
        PaginationItem,
        PaginationLink,
        Row,
    } from "@sveltestrap/sveltestrap";
    import { DateInput } from "date-picker-svelte";
    import Select from "svelte-select";

    function getStatusColor(status) {
        switch (status) {
            case "Completed":
                return "success";
            case "In Progress":
                return "orange";
            case "Pending":
                return "info";
            default:
                return "secondary";
        }
    }

    function getPriorityClass(priority) {
        switch (priority) {
            case "High":
                return "bg-danger-transparent";
            case "Medium":
                return "bg-warning-transparent";
            case "Low":
                return "bg-teal-transparent";
            default:
                return "bg-secondary";
        }
    }

    let date = new Date();
    let date1 = new Date();

    let allData = Taskstable;

    const handleRemove = (id) => {
        allData = allData.filter((idx) => idx.id !== id);
    };

    let modals = {};

    // Function to open the modal
    const handleModalOpen = (modalName) => {
        modals[modalName] = true;
    };

    // Function to close the modal
    const handleModalClose = (modalName) => {
        modals[modalName] = false;
    };
</script>

<!-- Page Title -->
<svelte:head>
    <title>ListView | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Task List View"
    activepage="Applications"
    subTitle="Task"
    page="Task List View"
/>
<!-- Page Header Close -->

<Row>
    <Col xl={12}>
        <Row>
            {#each taskData as idx}
                <Col xl={3} lg={6}>
                    <SpkListcard
                        titleClass="mb-2 fs-12"
                        listCard={true}
                        cardClass={idx.cardClass}
                        list={idx}
                        countUp={false}
                    />
                </Col>
            {/each}
        </Row>
    </Col>
</Row>
<Col xxl={12} xl={12} class="">
    <Card class="custom-card">
        <CardHeader class="justify-content-between">
            <div class="card-title">Total Tasks</div>
            <div class="d-flex">
                <SpkButton
                    color="primary"
                    onclickfunc={() => handleModalOpen("addmodal")}
                    customClass="btn btn-sm btn-wave waves-light me-1"
                    ><i class="ri-add-line fw-medium align-middle me-1"></i> Create
                    Task</SpkButton
                >
                <Modal
                    isOpen={modals["addmodal"]}
                    toggle={() => handleModalClose("addmodal")}
                    fade
                    id="create-task"
                    tabindex={-1}
                    centered
                >
                    <ModalHeader toggle={() => handleModalClose("addmodal")}>
                        <h6 class="modal-title">Add Task</h6>
                    </ModalHeader>
                    <ModalBody>
                        <Row class=" gy-2">
                            <Col xl={6}>
                                <Label for="task-name" class="">Task Name</Label
                                >
                                <Input
                                    type="text"
                                    class=""
                                    id="task-name"
                                    placeholder="Task Name"
                                />
                            </Col>
                            <Col xl={6}>
                                <Label for="task-id" class="">Task ID</Label>
                                <Input
                                    type="text"
                                    class=""
                                    id="task-id"
                                    placeholder="Task ID"
                                />
                            </Col>
                            <Col xl={6}>
                                <Label class="">Assigned Date</Label>
                                <div class="form-group custom-date-picker">
                                    <div
                                        class="input-group custom-input-group flex-nowrap"
                                    >
                                        <div
                                            class="input-group-text text-muted"
                                        >
                                            <i class="ri-calendar-line"></i>
                                        </div>
                                        <DateInput
                                            bind:value={date}
                                            class="form-control"
                                            format="yy-MM-dd HH:MM"
                                            closeOnSelection={true}
                                            timePrecision="minute"
                                            dynamicPositioning={true}
                                        />
                                    </div>
                                </div>
                            </Col>
                            <Col xl={6}>
                                <Label>Due Date</Label>
                                <div class="form-group custom-date-picker">
                                    <div
                                        class="input-group custom-input-group flex-nowrap"
                                    >
                                        <div
                                            class="input-group-text text-muted"
                                        >
                                            <i class="ri-calendar-line"></i>
                                        </div>
                                        <DateInput
                                            bind:value={date1}
                                            class="form-control"
                                            format="yy-MM-dd HH:MM"
                                            closeOnSelection={true}
                                            timePrecision="minute"
                                            dynamicPositioning={true}
                                        />
                                    </div>
                                </div>
                            </Col>
                            <Col xl={6}>
                                <Label>Status</Label>
                                <Select
                                    items={Statusdata}
                                    value={Statusdata[0]}
                                    clearable={false}
                                    showChevron={true}
                                />
                            </Col>
                            <Col xl={6}>
                                <Label>Priority</Label>
                                <Select
                                    items={Prioritydata}
                                    value={Prioritydata[0]}
                                    clearable={false}
                                    showChevron={true}
                                />
                            </Col>
                            <Col xl={12}>
                                <Label>Assigned To</Label>
                                <Select
                                    items={Listviewassigneddata}
                                    multiFullItemClearable
                                    multiple
                                />
                            </Col>
                        </Row>
                    </ModalBody>
                    <div class="modal-footer">
                        <SpkButton
                            buttontype="button"
                            onclickfunc={() => handleModalClose("addmodal")}
                            color="light"
                            customClass=""
                        >
                            Cancel
                        </SpkButton>
                        <SpkButton
                            buttontype="button"
                            color="primary"
                            customClass=""
                        >
                            Add Task
                        </SpkButton>
                    </div>
                    <!-- {/* </div> */} -->
                </Modal>
                <SpkDropdown
                    option={DropdownNewTasks}
                    ToggleClass="btn btn-icon btn-secondary-light btn-sm btn-wave waves-light waves-effect waves-light"
                    Caret={false}
                    parent={`<i class="ti ti-dots-vertical"></i>`}
                />
            </div>
        </CardHeader>
        <CardBody class="p-0">
            <SpkTablescomponent
                tableClass="text-nowrap"
                headerClass="table-light"
                showCheckbox={true}
                Responsive={true}
                header={[
                    { title: "Task" },
                    { title: "Task ID" },
                    { title: "Assigned Date" },
                    { title: "Status" },
                    { title: "Due Date" },
                    { title: "Priority" },
                    { title: "Assigned To" },
                    { title: "Action" },
                ]}
            >
                {#each allData as task}
                    <tr class="task-list">
                        <td class="task-checkbox">
                            <input
                                class="form-check-input"
                                type="checkbox"
                                aria-label="..."
                                defaultChecked={task.completed}
                            />
                        </td>
                        <td>
                            <a
                                href="#!"
                                class="fw-medium"
                                data-bs-toggle="offcanvas"
                                data-bs-target="#offcanvasRight"
                                aria-controls="offcanvasRight"
                            >
                                {task.title}
                            </a>
                        </td>
                        <td><span class="fw-medium">{task.code}</span></td>
                        <td>{task.startDate}</td>
                        <td>
                            <span
                                class={`fw-medium text-${getStatusColor(task.status)}`}
                            >
                                {task.status}
                            </span>
                        </td>
                        <td>{task.dueDate}</td>
                        <td>
                            <SpkBadge
                                Color=""
                                CustomClass={`badge ${getPriorityClass(task.priority)}`}
                            >
                                {task.priority}
                            </SpkBadge>
                        </td>
                        <td>
                            <div class="avatar-list-stacked">
                                {#each task.avatars as src}
                                    <span
                                        class="avatar avatar-sm avatar-rounded"
                                    >
                                        <Image {src} alt="img" />
                                    </span>
                                {/each}
                                {#if task.extraMembers > 0}
                                    <a
                                        class="avatar avatar-sm bg-primary avatar-rounded text-fixed-white"
                                        href="#!"
                                    >
                                        +{task.extraMembers}
                                    </a>
                                {/if}
                            </div>
                        </td>
                        <td>
                            <SpkButton
                                color=""
                                id={`edit-${task.id}`}
                                customClass="btn btn-primary-light btn-icon btn-sm"
                            >
                                <i class="ri-edit-line"></i>
                            </SpkButton>
                            <SpkTooltips
                                placement="top"
                                content="Edit"
                                targetId={`edit-${task.id}`}
                            ></SpkTooltips>
                            <SpkButton
                                color=""
                                onclickfunc={() => handleRemove(task.id)}
                                customClass="btn btn-danger-light btn-icon ms-1 btn-sm task-delete-btn"
                            >
                                <i class="ri-delete-bin-5-line"></i>
                            </SpkButton>
                        </td>
                    </tr>
                {/each}
            </SpkTablescomponent>
        </CardBody>
        <CardFooter class="border-top-0">
            <div class="d-flex align-items-center">
                <div>
                    Showing 10 Entries <i
                        class="bi bi-arrow-right ms-2 fw-semibold"
                    ></i>
                </div>
                <div class="ms-auto">
                    <nav
                        aria-label="Page navigation"
                        class="pagination-style-2"
                    >
                        <Pagination class="customPaginationPageBottom">
                            <PaginationItem>
                                <PaginationLink
                                    on:click={(e) => e.preventDefault()}
                                    href="#">Prev</PaginationLink
                                >
                            </PaginationItem>
                            <PaginationItem>
                                <PaginationLink
                                    on:click={(e) => e.preventDefault()}
                                    href="#">1</PaginationLink
                                >
                            </PaginationItem>
                            <PaginationItem active>
                                <PaginationLink
                                    on:click={(e) => e.preventDefault()}
                                    href="#">2</PaginationLink
                                >
                            </PaginationItem>
                            <PaginationItem>
                                <PaginationLink
                                    on:click={(e) => e.preventDefault()}
                                    href="#"
                                    ><i class="bi bi-three-dots"
                                    ></i></PaginationLink
                                >
                            </PaginationItem>
                            <PaginationItem>
                                <PaginationLink
                                    on:click={(e) => e.preventDefault()}
                                    href="#">17</PaginationLink
                                >
                            </PaginationItem>
                            <PaginationItem>
                                <PaginationLink
                                    on:click={(e) => e.preventDefault()}
                                    href="#"
                                    class="text-primary">Next</PaginationLink
                                >
                            </PaginationItem>
                        </Pagination>
                    </nav>
                </div>
            </div>
        </CardFooter>
    </Card>
</Col>
