// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/column-chart/column-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import * as columndata from "../../../../shared/data/charts/apexcharts/columnchartdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const ColumnChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Apex Column Charts"} />

            <Pageheader title="Apex Charts" currentpage="Apex Column Charts" subtitle="Apex Charts" activepage="Apex Column Charts" />


            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Basic Column Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="column-basic">
                                <Spkapexcharts chartOptions={columndata.Columnbasicoptions} chartSeries={columndata.Columnbasicseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Column Chart With Datalabels</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="column-datalabels">
                                <Spkapexcharts chartOptions={columndata.Columnchartoptions} chartSeries={columndata.Columnchartseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Stacked Column Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="column-stacked">
                                <Spkapexcharts chartOptions={columndata.Stackcolumnoptions} chartSeries={columndata.Stackcolumnseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">100% Stacked Column Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="column-stacked-full">
                                <Spkapexcharts chartOptions={columndata.Columnstack1options} chartSeries={columndata.Columnstack1series} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Column Chart With Markers</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="column-markers">
                                <Spkapexcharts chartOptions={columndata.Columnmakeroptions} chartSeries={columndata.Columnmakerseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Column Chart With Rotated Labels</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="column-rotated-labels">
                                <Spkapexcharts chartOptions={columndata.Columnrotateoptions} chartSeries={columndata.Columnrotateseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Column Chart With Negative Values</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="column-negative">
                                <Spkapexcharts chartOptions={columndata.Columnvalueoptions} chartSeries={columndata.Columnvalueseries} type="bar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Range Column Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="column-range">
                                <Spkapexcharts chartOptions={columndata.Columnoptions} chartSeries={columndata.Columnseries} type="rangeBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Distributed Columns Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="columns-distributed">
                                <Spkapexcharts chartOptions={columndata.Column1options} chartSeries={columndata.Column1series} type="bar" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
ColumnChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ColumnChart;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/column-chart/+page.svelte

<script lang="ts">
     import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import { Card, CardBody, CardHeader, Col, Row } from "@sveltestrap/sveltestrap";
    import * as columndata from "$lib/data/charts/apexcharts/columnchartsdata"
</script>

<!-- Page Title -->
<svelte:head>
    <title>ColumnChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader homepage='Apex Column Charts' activepage='Charts' subTitle="Apex Charts" page='Apex Column Charts' />
<!-- Page Header Close -->

<!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Basic Column Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="column-basic">
                                <Spkapexcharts id="column-basic" options={columndata.Columnbasicoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Column Chart With Datalabels</div>
                        </CardHeader>
                        <CardBody>
                            <div id="column-datalabels">
                                <Spkapexcharts id="column-datalabels" options={columndata.Columnchartoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Stacked Column Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="column-stacked">
                                <Spkapexcharts id="column-stacked" options={columndata.Stackcolumnoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">100% Stacked Column Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="column-stacked-full">
                                <Spkapexcharts id="column-stacked-full" options={columndata.Columnstack1options} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Column Chart With Markers</div>
                        </CardHeader>
                        <CardBody>
                            <div id="column-markers">
                                <Spkapexcharts id="column-markers" options={columndata.Columnmakeroptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Column Chart With Rotated Labels</div>
                        </CardHeader>
                        <CardBody>
                            <div id="column-rotated-labels">
                                <Spkapexcharts id="column-rotated-labels" options={columndata.Columnrotateoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Column Chart With Negative Values</div>
                        </CardHeader>
                        <CardBody>
                            <div id="column-negative">
                                <Spkapexcharts id="column-negative" options={columndata.Columnvalueoptions}  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Range Column Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="column-range">
                                <Spkapexcharts id="column-range" options={columndata.Columnoptions} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Distributed Columns Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="columns-distributed">
                                <Spkapexcharts id="columns-distributed" options={columndata.Column1options} />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

            <!--End::row-1 -->
