// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/empty/empty.jsx

import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../shared/layouts-components/pageheader/pageheader";
import MainLayout from "@/Layouts/layout";


const Empty = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Pages-Empty" />

            <Pageheader title="Pages" currentpage="Empty" activepage="Empty" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card ">
                        <Card.Body>
                            <h6 className="mb-0 ">Empty Card</h6>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
Empty.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Empty;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/pages/empty.svelte

<script context="module">
    import MainLayout from '@/layouts/MainLayout.svelte';
    export const layout = MainLayout; 
</script>
<script>
    import { Card, CardBody, Col, Row } from "@sveltestrap/sveltestrap";
    import Pageheader from "@/components/page-header/Pageheader.svelte";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Empty | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<!-- Page Header -->
<Pageheader homepage="Empty" activepage="Pages" page="Empty" />
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={12}>
        <Card class="custom-card">
            <CardBody>
                <h6 class="mb-0">Empty Card</h6>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->
