// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/team/team.jsx

import MainLayout from "@/Layouts/layout";
import SpkTeamCard from "../../../shared/@spk-reusable-components/reusable-pages/spk-teamcard";
import { TeamMembers } from "../../../shared/data/pages/teamdata";
import Pageheader from "../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Row } from "react-bootstrap";


const Team = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Team" />

            <Pageheader title="Pages" currentpage="Team" activepage="Team" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row className="row-cols-xxl-5 row-cols-xl-4 row-cols-lg-3 row-cols-md-3 row-cols-sm-2 row-cols-1">
                {TeamMembers.map((idx, index) => (
                    <div className="col" key={index}>
                        <SpkTeamCard member={idx} />
                    </div>
                ))}
            </Row>

            {/* <!-- End:: row-1 --> */}

        </Fragment>
    )
};
// Assign layout
Team.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Team;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/pages/team.svelte

<script context="module">
    import MainLayout from '@/layouts/MainLayout.svelte';
    export const layout = MainLayout; 
</script>
<script>
    import SpkTeamcard from "@/shared/@spk/reusable-pages/spk-teamcard.svelte";
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import { TeamMembers } from "@/shared/data/pages/teamdata";
    import { Row } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Team | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader homepage="Team" activepage="Pages" page="Team" />
<!-- Page Header Close -->

<!-- Start:: row-1 -->

<Row
    class="row-cols-xxl-5 row-cols-xl-4 row-cols-lg-3 row-cols-md-3 row-cols-sm-2 row-cols-1"
>
    {#each TeamMembers as idx}
        <div class="col">
            <SpkTeamcard member={idx} />
        </div>
    {/each}
</Row>

<!-- End:: row-1 -->
