// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/dashboards/projects/dashboard.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Spkapexcharts from "@/shared/@spk/charts/Spkapexcharts.svelte";
    import SpkDashboardcard from "@/shared/@spk/dashboards-reusable/projects/spk-dashboardcard.svelte";
    import SpkTablescomponent from "@/shared/@spk/SpkTablescomponent.svelte";
    import SpkBadge from "@/shared/@spk/uielements/badge/SpkBadge.svelte";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import SpkDropdown from "@/shared/@spk/uielements/Dropdown/SpkDropdown.svelte";
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import {
        dashboardCards,
        ProjectOptions,
        ProjectsSummary,
        Recentupdates,
        TaskList,
        TaskOptions,
        Transactions,
        UrgentTasks,
    } from "@/shared/data/dashboards/projects/projectdashboardata";
    import {
        SortByDropdown,
        WeekDropdown,
    } from "@/shared/data/uielements/dropdowndata";
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Col,
        Image,
        Input,
        ListGroup,
        ListGroupItem,
        Pagination,
        PaginationItem,
        PaginationLink,
        Row,
    } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Dashboard | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Dashboard"
    subTitle="Projects"
    activepage="Dashboards"
    page="Dashboard"
/>
<!-- Page Header Close -->

<!-- Start:: row-1 -->

<Row>
    <Col xxl={9}>
        <Row>
            {#each dashboardCards as idx}
                <Col xl={3}>
                    <SpkDashboardcard cardClass={idx.cardClass} project={idx} />
                </Col>
            {/each}
            <Col xl={12}>
                <Card class="custom-card">
                    <CardHeader>
                        <div class="card-title">Projects Overview</div>
                    </CardHeader>
                    <CardBody>
                        <div id="projects-overview">
                            <Spkapexcharts
                                id="projects-overview"
                                options={ProjectOptions}
                            />
                        </div>
                    </CardBody>
                </Card>
            </Col>
        </Row>
    </Col>
    <Col xxl={3}>
        <Card class="custom-card overflow-hidden">
            <CardHeader>
                <div class="card-title">Task Activity</div>
            </CardHeader>
            <CardBody>
                <div id="task-activity">
                    <Spkapexcharts id="task-activity" options={TaskOptions} />
                </div>
            </CardBody>
            <CardFooter class="p-0">
                <ListGroup class="list-group-flush project-task-activity-list">
                    {#each TaskList as task}
                        <ListGroupItem>
                            <div class="d-flex align-items-start gap-2">
                                <div class="flex-fill">
                                    <span
                                        class={`d-block fw-semibold task-type ${task.className}`}
                                    >
                                        {task.type}
                                    </span>
                                    <span class="fs-12 text-muted">
                                        {task.trend === "increase"
                                            ? "Increased"
                                            : "Decreased"} by{" "}
                                        <span
                                            class={`mx-1 ${task.trend === "increase" ? "text-success" : "text-danger"}`}
                                        >
                                            {task.percentage}
                                        </span>
                                        This year
                                    </span>
                                </div>
                                <div class="fw-semibold">{task.count}</div>
                            </div>
                        </ListGroupItem>
                    {/each}
                </ListGroup>
            </CardFooter>
        </Card>
    </Col>
</Row>

<!-- End:: row-1 -->

<!-- Start:: row-2 -->

<Row>
    <Col xxl={3}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Recent Activity</div>
            </CardHeader>
            <CardBody>
                <ul class="list-unstyled projects-recent-activity-list">
                    {#each Recentupdates as item}
                        <li>
                            <div class="d-flex align-items-start gap-3">
                                <div>
                                    <span
                                        class={`avatar avatar-md avatar-rounded ${item.status}`}
                                    >
                                        <Image
                                            width={40}
                                            height={40}
                                            src={item.avatar}
                                            alt={item.name}
                                        />
                                    </span>
                                </div>
                                <div class="flex-fill">
                                    <div
                                        class="d-flex align-items-start justify-content-between mb-1 flex-wrap"
                                    >
                                        <div class="d-block fw-semibold">
                                            {item.name}
                                        </div>
                                        <SpkBadge
                                            Color=""
                                            CustomClass="bg-light text-muted border"
                                            >{item.date}</SpkBadge
                                        >
                                    </div>
                                    <div class="descrption mb-1">
                                        {item.description}
                                    </div>
                                    {#if item.file}
                                        <div
                                            class="p-1 border border-dotted rounded position-relative"
                                        >
                                            <!-- svelte-ignore a11y_consider_explicit_label -->
                                            <!-- svelte-ignore element_invalid_self_closing_tag -->
                                            <a
                                                href="#!"
                                                class="stretched-link"
                                            />
                                            <div
                                                class="d-flex align-items-center gap-2"
                                            >
                                                <SpkBadge
                                                    Color=""
                                                    CustomClass="bg-success"
                                                    >{item.file.type}</SpkBadge
                                                >
                                                <span class="fs-11"
                                                    >{item.file.name}</span
                                                >
                                            </div>
                                        </div>
                                    {/if}
                                </div>
                            </div>
                        </li>
                    {/each}
                </ul>
            </CardBody>
        </Card>
    </Col>
    <Col xxl={6}>
        <Card class="custom-card overflow-hidden custom-table-tasks">
            <CardHeader class="justify-content-between">
                <div class="card-title">Urgent Tasks</div>
                <SpkDropdown
                    option={WeekDropdown}
                    ToggleClass="fs-12 text-muted no-caret border-0"
                    Caret={false}
                    parent={`Today <i class="ri-arrow-down-s-line align-middle ms-1 d-inline-block"></i>`}
                />
            </CardHeader>
            <CardBody class="p-0 custom-project-avatar">
                <SpkTablescomponent
                    Responsive={true}
                    tableClass="text-nowrap"
                    header={[
                        { title: "Task" },
                        { title: "Deadline" },
                        { title: "Assigned To" },
                        { title: "Priority" },
                        { title: "Status" },
                    ]}
                >
                    {#each UrgentTasks as task, index}
                        <tr>
                            <td
                                class={index === UrgentTasks.length - 1
                                    ? "border-bottom-0"
                                    : ""}
                            >
                                <div class="d-flex align-items-center gap-2">
                                    <div class="form-check mb-0">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            id={task.id}
                                        />
                                    </div>
                                    <a href="#!" class="urgent-task-title"
                                        >{task.title}</a
                                    >
                                </div>
                            </td>
                            <td
                                class={index === UrgentTasks.length - 1
                                    ? "border-bottom-0"
                                    : ""}
                            >
                                {task.dueDate}
                            </td>
                            <td
                                class={index === UrgentTasks.length - 1
                                    ? "border-bottom-0"
                                    : ""}
                            >
                                <div class="avatar-list-stacked mb-0">
                                    {#each task.avatars ?? [] as imgSrc}
                                        <span
                                            class="avatar avatar-xs avatar-rounded"
                                        >
                                            <Image src={imgSrc} alt="img" />
                                        </span>
                                    {/each}
                                </div>
                            </td>
                            <td
                                class={index === UrgentTasks.length - 1
                                    ? "border-bottom-0"
                                    : ""}
                            >
                                {task.priority}
                            </td>
                            <td
                                class={index === UrgentTasks.length - 1
                                    ? "border-bottom-0"
                                    : ""}
                            >
                                <SpkBadge
                                    Color=""
                                    CustomClass={`${task.statusClass}`}
                                >
                                    {task.status}
                                </SpkBadge>
                            </td>
                        </tr>
                    {/each}
                </SpkTablescomponent>
            </CardBody>
            <CardFooter>
                <div class="d-flex align-items-center">
                    <div>
                        Showing 6 Entries <i
                            class="bi bi-arrow-right ms-2 fw-semibold"
                        ></i>
                    </div>
                    <div class="ms-auto">
                        <nav
                            aria-label="Page navigation"
                            class="pagination-style-2"
                        >
                            <Pagination
                                class="mb-0 flex-wrap customPaginationPageBottom"
                            >
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >Prev</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >1</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem active>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >2</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        ><i class="bi bi-three-dots"></i></PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >17</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        class="text-primary"
                                        >Next</PaginationLink
                                    >
                                </PaginationItem>
                            </Pagination>
                        </nav>
                    </div>
                </div>
            </CardFooter>
        </Card>
    </Col>
    <Col xxl={3}>
        <Card class="custom-card overflow-hidden">
            <CardHeader>
                <div class="card-title">Recent Transactions</div>
            </CardHeader>
            <CardBody>
                <ul class="list-unstyled projects-recent-transactions-list">
                    {#each Transactions as tx}
                        <li>
                            <div class="d-flex align-items-center gap-2">
                                <div class="lh-1">
                                    <span
                                        class={`avatar avatar-md avatar-rounded bg-${tx.avatarColor}-transparent`}
                                    >
                                        {tx.name.charAt(0)}
                                    </span>
                                </div>
                                <div class="flex-fill">
                                    <span class="d-block fw-semibold"
                                        >{tx.name}</span
                                    >
                                    <span class="fs-13 text-muted"
                                        >{tx.dateTime}</span
                                    >
                                </div>
                                <div class="text-end">
                                    <span class="d-block fw-semibold"
                                        >{tx.amount}</span
                                    >
                                    <span
                                        class={`fw-medium fs-13 ${tx.status === "Completed" ? "text-success" : tx.status === "Pending" ? "text-warning" : "text-danger"}`}
                                    >
                                        {tx.status}
                                    </span>
                                </div>
                            </div>
                        </li>
                    {/each}
                </ul>
            </CardBody>
        </Card>
    </Col>
</Row>

<!-- End:: row-2 -->

<!-- Start:: row-3 -->

<Row>
    <Col xl={12}>
        <Card class="custom-card custom-table-tasks">
            <CardHeader class="justify-content-between">
                <div class="card-title">Projects Summary</div>
                <div class="d-flex flex-wrap gap-2">
                    <div>
                        <Input
                            class="form-control-sm"
                            type="text"
                            placeholder="Search Here"
                            aria-label=".form-control-sm example"
                        />
                    </div>
                    <SpkDropdown
                        option={SortByDropdown}
                        ToggleClass="btn-primary btn-sm btn-wave waves-effect waves-light"
                        Caret={true}
                        parent="Sort By"
                    />
                </div>
            </CardHeader>
            <CardBody class="p-0 custom-project-avatar">
                <SpkTablescomponent
                    Responsive={true}
                    tableClass="text-nowrap"
                    showCheckbox={true}
                    header={[
                        { title: "Project Name" },
                        { title: "Start Date" },
                        { title: "End Date" },
                        { title: "Status" },
                        { title: "Progress" },
                        { title: "Team" },
                        { title: "Budget" },
                        { title: "Actions" },
                    ]}
                >
                    {#each ProjectsSummary as project}
                        <tr>
                            <td class={project.borderBottom}>
                                <input
                                    class="form-check-input"
                                    type="checkbox"
                                    id={project.id}
                                    aria-label="..."
                                />
                            </td>
                            <td class={project.borderBottom}>{project.name}</td>
                            <td class={project.borderBottom}
                                >{project.startDate}</td
                            >
                            <td class={project.borderBottom}
                                >{project.endDate}</td
                            >
                            <td class={project.borderBottom}>
                                <SpkBadge
                                    Color=""
                                    CustomClass={`bg-${project.status === "Completed" ? "success" : "primary"}-transparent`}
                                >
                                    {project.status}
                                </SpkBadge>
                            </td>
                            <td class={project.borderBottom}>
                                <div class="d-flex align-items-center">
                                    <div
                                        class="progress progress-animate progress-xs w-100"
                                        role="progressbar"
                                        aria-valuenow={project.progress}
                                        aria-valuemin={0}
                                        aria-valuemax={100}
                                    >
                                        <!-- svelte-ignore element_invalid_self_closing_tag -->
                                        <div
                                            class={`progress-bar progress-bar-striped progress-bar-animated bg-${project.progressColor}`}
                                            style="width: {project.progress}%;"
                                        />
                                    </div>
                                    <div class="ms-2">
                                        {project.progress}%
                                    </div>
                                </div>
                            </td>
                            <td class={project.borderBottom}>
                                <div class="avatar-list-stacked">
                                    {#each project.avatars as avatar}
                                        <span
                                            class="avatar avatar-xs avatar-rounded"
                                        >
                                            <Image
                                                src={`../../images/faces/${avatar}`}
                                                alt="avatar"
                                            />
                                        </span>
                                    {/each}
                                    {#if project.moreAvatars}
                                        <a
                                            class="avatar avatar-xs bg-primary avatar-rounded text-fixed-white"
                                            href="#!"
                                        >
                                            +{project.moreAvatars}
                                        </a>
                                    {/if}
                                </div>
                            </td>
                            <td class={project.borderBottom}
                                >{project.amount}</td
                            >
                            <td class={project.borderBottom}>
                                <div class="btn-list">
                                    <SpkButton
                                        color=""
                                        customClass="btn btn-sm btn-icon btn-primary-light btn-wave"
                                    >
                                        <i class="ri-edit-line"></i>
                                    </SpkButton>
                                    <SpkButton
                                        color=""
                                        customClass="btn btn-sm btn-icon btn-danger-light btn-wave"
                                    >
                                        <i class="ri-delete-bin-line"></i>
                                    </SpkButton>
                                </div>
                            </td>
                        </tr>
                    {/each}
                </SpkTablescomponent>
            </CardBody>
            <CardFooter>
                <div class="d-flex align-items-center">
                    <div>
                        Showing 6 Entries <i
                            class="bi bi-arrow-right ms-2 fw-semibold"
                        ></i>
                    </div>
                    <div class="ms-auto">
                        <nav
                            aria-label="Page navigation"
                            class="pagination-style-2"
                        >
                            <Pagination
                                class="mb-0 flex-wrap customPaginationPageBottom"
                            >
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >Prev</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >1</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem active>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >2</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        ><i class="bi bi-three-dots"></i></PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        >17</PaginationLink
                                    >
                                </PaginationItem>
                                <PaginationItem>
                                    <PaginationLink
                                        href="#"
                                        on:click={(e) => e.preventDefault()}
                                        class="text-primary"
                                        >Next</PaginationLink
                                    >
                                </PaginationItem>
                            </Pagination>
                        </nav>
                    </div>
                </div>
            </CardFooter>
        </Card>
    </Col>
</Row>

<!-- End:: row-3 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/crm/dashboard/dashboard.jsx

import React, { Fragment } from "react";
import { Card, Col, ListGroup, Pagination, Nav, Row, Tab, Image } from "react-bootstrap";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { CrmOptions, CrmSeries, Deals, LeadOptions, LeadSeries, Overviewtable, StatCards, StaticOptions, StaticSeries, Tasks, TopdealsTable, TrafficSources, Upcoming } from "../../../../shared/data/dashboards/crm/crmdashboarddata";
import SpkEmployeeStatCard from "../../../../shared/@spk-reusable-components/reusable-widgets/spk-employeecard";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import SpkTooltips from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-tooltips";
import SpkBadge from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import SpkTables from "../../../../shared/@spk-reusable-components/reusable-tables/spk-tables";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import { Head } from "@inertiajs/react";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const CRM = () => {

    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Dashboards-CRM" />

            <Pageheader title="Dashboards" subtitle="CRM" currentpage="Dashboard" activepage="CRM" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xxl={5}>
                    <Row>
                        {StatCards.map((idx, index) => (
                            <Col lg={6} key={index}>
                                <SpkEmployeeStatCard widget={idx} />
                            </Col>
                        ))}
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Revenue Analytics
                                    </div>
                                </Card.Header>
                                <Card.Body className="pb-0">
                                    <div id="crm-revenue-analytics">
                                        <Spkapexcharts height={315} width={"100%"} type={"line"} chartOptions={CrmOptions} chartSeries={CrmSeries} />
                                    </div>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>
                </Col>
                <Col xxl={4}>
                    <Row>
                        <Col xl={12}>
                            <Card className="custom-card overflow-hidden">
                                <Tab.Container defaultActiveKey={"upcoming"}>
                                    <Card.Header className="justify-content-between">
                                        <div className="card-title">
                                            Tasks List
                                        </div>
                                        <Nav className="nav-tabs justify-content-end nav-tabs-header card-headertabs" role="tablist">
                                            <Nav.Item role="presentation">
                                                <Nav.Link eventKey={"today"} className="" data-bs-toggle="tab" role="tab" aria-current="page"  aria-selected="false" tabIndex={-1}>Today</Nav.Link>
                                            </Nav.Item>
                                            <Nav.Item role="presentation">
                                                <Nav.Link eventKey={"upcoming"} className="" data-bs-toggle="tab" role="tab" aria-current="page"  aria-selected="true">Upcoming</Nav.Link>
                                            </Nav.Item>
                                        </Nav>
                                    </Card.Header>
                                    <Card.Body className="todo-tab p-0">
                                        <Tab.Content>
                                            <Tab.Pane eventKey={"today"} className="border-0" id="today" role="tabpanel">
                                                <ul className="list-unstyled task-list-tab">
                                                    {Tasks.map((task) => (
                                                        <li key={task.id}>
                                                            <div className="d-flex align-items-start gap-2 flex-wrap">
                                                                <div className="mb-3 form-check">
                                                                    <input type="checkbox" className="form-check-input" defaultChecked={task.completed} />
                                                                </div>
                                                                <div className="flex-fill">
                                                                    <div className="d-flex align-items-center gap-2 mb-1">
                                                                        <BaseLink href="#!" className="crm-task-name">
                                                                            {task.title}
                                                                        </BaseLink>
                                                                        <SpkTooltips title={task.status} placement="top">
                                                                            <div className="lh-1">
                                                                                <span className="avatar avatar-xs avatar-rounded bg-light border text-muted fw-semibold" data-bs-toggle="tooltip" >
                                                                                    <i className="ti ti-info-circle fs-11"></i>
                                                                                </span>
                                                                            </div>
                                                                        </SpkTooltips>
                                                                    </div>
                                                                    <div className="d-flex align-items-center gap-2 lh-1">
                                                                        <BaseLink href="#!" className="fs-12">
                                                                            {task.code}
                                                                        </BaseLink>
                                                                        <div className="vr"></div>
                                                                        <span className="text-muted mb-0 fs-12">
                                                                            <i className="ti ti-user me-1 fw-medium"></i>
                                                                            {task.assignee}
                                                                        </span>
                                                                        <div className="vr"></div>
                                                                        <SpkBadge variant="" Customclass={`${task.priority === 'High' ? 'bg-danger-transparent' : task.priority === 'Medium' ? 'bg-warning-transparent' : 'bg-success-transparent'}`}>
                                                                            {task.priority}
                                                                        </SpkBadge>
                                                                    </div>
                                                                </div>
                                                                <div className="text-end">
                                                                    <span className="d-block fw-medium">{task.dueTime}</span>
                                                                    <span className="d-block fs-12 text-muted">Due Time</span>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    ))}
                                                </ul>
                                            </Tab.Pane>
                                            <Tab.Pane eventKey={"upcoming"} className="border-0" id="Upcoming" role="tabpanel">
                                                <ul className="list-unstyled task-list-tab">
                                                    {Upcoming.map((task) => (
                                                        <li key={task.id}>
                                                            <div className="d-flex align-items-start gap-2 flex-wrap">
                                                                <div className="mb-3 form-check">
                                                                    <input type="checkbox" className="form-check-input" defaultChecked={task.completed} />
                                                                </div>
                                                                <div className="flex-fill">
                                                                    <div className="d-flex align-items-center gap-2 mb-1">
                                                                        <BaseLink href="#!" className="crm-task-name">
                                                                            {task.title}
                                                                        </BaseLink>
                                                                        <SpkTooltips placement="top" title="Not Started">
                                                                            <div className="lh-1">
                                                                                <span className="avatar avatar-xs avatar-rounded bg-light border text-muted fw-semibold" data-bs-toggle="tooltip" title={task.status}>
                                                                                    <i className="ti ti-info-circle fs-11"></i>
                                                                                </span>
                                                                            </div>
                                                                        </SpkTooltips>
                                                                    </div>
                                                                    <div className="d-flex align-items-center gap-2 lh-1">
                                                                        <BaseLink href="#!" className="fs-12">{task.code}</BaseLink>
                                                                        <div className="vr"></div>
                                                                        <span className="text-muted mb-0 fs-12">
                                                                            <i className="ti ti-user me-1 fw-medium"></i>{task.assignee}
                                                                        </span>
                                                                        <div className="vr"></div>
                                                                        <SpkBadge variant="" Customclass={`${task.priority === 'High' ? 'bg-danger-transparent' : task.priority === 'Medium' ? 'bg-warning-transparent' : 'bg-success-transparent'}`}>
                                                                            {task.priority}
                                                                        </SpkBadge>
                                                                    </div>
                                                                </div>
                                                                <div className="text-end">
                                                                    <span className="d-block fw-medium">{task.dueDate}</span>
                                                                    <span className="d-block fs-12 text-muted">Due Date</span>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    ))}
                                                </ul>
                                            </Tab.Pane>
                                        </Tab.Content>
                                    </Card.Body>
                                </Tab.Container>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Body>
                                    <div className="d-flex align-items-center justify-content-between flex-wrap gap-3 gap-sm-0">
                                        <div className="lead-title total">Total Leads</div>
                                        <div className="lead-title target">Leads Target</div>
                                    </div>
                                    <div className="progress-stacked progress-animate progress-sm my-3">
                                        <div className="progress-bar" role="progressbar" style={{ width: "68%" }} aria-valuenow={68} aria-valuemin={0} aria-valuemax={100}></div>
                                        <div className="progress-bar bg-success" role="progressbar" style={{ width: "32%" }} aria-valuenow={32} aria-valuemin={0} aria-valuemax={100}></div>
                                    </div>
                                    <div className="d-flex align-items-center gap-3 justify-content-between flex-wrap">
                                        <div><span className="text-success fw-medium me-2"><i className="ti ti-arrow-up me-1"></i>3.25%</span> Compared to last week</div>
                                        <div><BaseLink href="#!" className="link-primary text-decoration-underline">Leads Report <i className="ti ti-arrow-narrow-right"></i></BaseLink></div>
                                    </div>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>
                </Col>
                <Col xxl={3}>
                    <Card className="custom-card overflow-hidden">
                        <Card.Header>
                            <div className="card-title">
                                Leads By Source
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <div id="leads-source">
                                <Spkapexcharts height={205} type="polarArea" width={"100%"} chartOptions={LeadOptions} chartSeries={LeadSeries} />
                            </div>
                        </Card.Body>
                        <Card.Footer className="p-0">
                            <ListGroup as="ul" className="list-group-flush leads-source-list">
                                {TrafficSources.map((source, index) => (
                                    <ListGroup.Item as="li" className="" key={index}>
                                        <div className="d-flex align-items-center justify-content-between">
                                            <div className="fw-semibold">{source.name}</div>
                                            <div className="lh-1 text-end">
                                                <span className="d-block fw-semibold mb-0">
                                                    <span className={`d-inline-flex align-items-center fw-medium me-2 fs-12 ${source.trend === 'up' ? 'text-success' : 'text-danger'}`}>
                                                        <i className={`ti ti-arrow-${source.trend} me-1`}></i>
                                                        {source.percentage}
                                                    </span>
                                                    {source.count.toLocaleString()}
                                                </span>
                                            </div>
                                        </div>
                                    </ListGroup.Item>
                                ))}
                            </ListGroup>
                        </Card.Footer>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-2 --> */}

            <Row>
                <Col xxl={3}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Top Deals
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <ul className="list-unstyled crm-top-deals">
                                {Deals.map((user, index) => (
                                    <li key={index}>
                                        <div className="d-flex align-items-top flex-wrap">
                                            <div className="me-2">
                                                <span className="avatar avatar-sm avatar-rounded fw-semibold bg-primary-transparent">
                                                    {user.avatar ? (
                                                        <BaseImage src={user.avatar} alt={user.name} />
                                                    ) : (
                                                        user.initials
                                                    )}
                                                </span>
                                            </div>
                                            <div className="flex-fill">
                                                <p className="fw-semibold mb-0">{user.name}</p>
                                                <span className="text-muted fs-12">{user.email}</span>
                                            </div>
                                            <div className="fw-semibold fs-15">{user.amount}</div>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xxl={3}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Deals Statistics
                            </div>
                        </Card.Header>
                        <Card.Body className="py-0">
                            <div id="deals-statistics">
                                <Spkapexcharts height={351} type={"bar"} chartOptions={StaticOptions} chartSeries={StaticSeries} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xxl={6}>
                    <Card className="custom-card overflow-hidden">
                        <Card.Header>
                            <div className="card-title">
                                Leads Overview
                            </div>
                        </Card.Header>
                        <Card.Body className="p-0">
                            <div className="table-responsive">
                                <SpkTables tableClass="text-nowrap" header={[{ title: 'Lead Name' }, { title: 'Company' }, { title: 'Status' }, { title: 'Source' }]}>
                                    {Overviewtable.map((lead, index) => (
                                        <tr key={index}>
                                            <td>
                                                <div className="d-flex align-items-center gap-2">
                                                    <div className="lh-1">
                                                        <span className="avatar avatar-sm avatar-rounded">
                                                            <BaseImage src={lead.avatar} alt={lead.name} />
                                                        </span>
                                                    </div>
                                                    <div>{lead.name}</div>
                                                </div>
                                            </td>
                                            <td>{lead.company}</td>
                                            <td>
                                                <SpkBadge variant="" Customclass={`${lead.status.colorClass}`}>{lead.status.label}</SpkBadge>
                                            </td>
                                            <td>{lead.source}</td>
                                        </tr>
                                    ))}
                                </SpkTables>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-2 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card overflow-hidden">
                        <Card.Header>
                            <div className="card-title">
                                Top Deals
                            </div>
                        </Card.Header>
                        <Card.Body className="p-0">
                            <div className="table-responsive">
                                <SpkTables tableClass="text-nowrap" header={[{ title: 'Deal ID' }, { title: 'Deal Name' }, { title: 'Client Name' }, { title: 'Deal Amount' }, { title: 'Status' }, { title: 'Closing Date' }, { title: 'Sales Rep' }, { title: 'Priority' }, { title: 'Actions' }]}>
                                    {TopdealsTable.map((deal, idx) => (
                                        <tr key={idx}>
                                            <td><BaseLink href="#!">{deal.id}</BaseLink></td>
                                            <td>{deal.title}</td>
                                            <td>
                                                <div className="d-flex align-items-center gap-2 position-relative">
                                                    <BaseLink href="#!" className="stretched-link"></BaseLink>
                                                    <div className="lh-1">
                                                        <span className="avatar avatar-sm avatar-rounded">
                                                            <BaseImage width={28} height={28} src={deal.companyLogo} alt={deal.companyName} />
                                                        </span>
                                                    </div>
                                                    <div>{deal.companyName}</div>
                                                </div>
                                            </td>
                                            <td>{deal.amount}</td>
                                            <td><SpkBadge variant="" Customclass={`${deal.status.colorClass}`}>{deal.status.label}</SpkBadge></td>
                                            <td>{deal.closeDate}</td>
                                            <td>{deal.owner}</td>
                                            <td>{deal.priority}</td>
                                            <td>
                                                <div className="btn-list">
                                                    <SpkButton Buttonvariant="" Customclass="btn btn-icon btn-primary-light btn-sm">
                                                        <i className="ti ti-edit"></i>
                                                    </SpkButton>
                                                    <SpkButton Buttonvariant="" Customclass="btn btn-icon btn-danger-light btn-sm">
                                                        <i className="ti ti-trash"></i>
                                                    </SpkButton>
                                                </div>
                                            </td>
                                        </tr>
                                    ))}
                                </SpkTables>
                            </div>
                        </Card.Body>
                        <Card.Footer className="">
                            <div className="d-flex align-items-center flex-wrap">
                                <div> Showing 6 Entries <i className="bi bi-arrow-right ms-2 fw-semibold"></i> </div>
                                <div className="ms-auto">
                                    <nav aria-label="Page navigation" className="pagination-style-2">
                                        <Pagination className="mb-0">
                                            <Pagination.Prev disabled>Prev</Pagination.Prev>
                                            <Pagination.Item >{1}</Pagination.Item>
                                            <Pagination.Item active>{2}</Pagination.Item>
                                            <Pagination.Item><i className="bi bi-three-dots"></i></Pagination.Item>
                                            <Pagination.Item >{17}</Pagination.Item>
                                            <Pagination.Next className="text-primary">Next</Pagination.Next>
                                        </Pagination>
                                    </nav>
                                </div>
                            </div>
                        </Card.Footer>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-3 --> */}

        </Fragment>
    )
};

CRM.layout = (page) => <MainLayout>{page}</MainLayout>;
export default CRM;
