// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/radar-chart/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import { Card, CardBody, CardHeader, CardTitle, Col, Row } from "@sveltestrap/sveltestrap";
    import { Multioptions, Polygonoptions, Radaroptions } from "$lib/data/charts/apexcharts/radarchartdata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>RadarChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Radar Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Radar Charts"
/>
<!-- Page Header Close -->

 <!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Basic Radar Chart</CardTitle>
                        </CardHeader>
                        <CardBody class="">
                            <div id="radar-basic">
                                <Spkapexcharts options={Radaroptions} id="radar-basic" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Radar Chart-Multiple Series</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <div id="radar-multiple">
                                <Spkapexcharts options={Multioptions} id="radar-multiple" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Radar Chart Polygon Fill</CardTitle>
                        </CardHeader>
                        <CardBody class="">
                            <div id="radar-polygon">
                                <Spkapexcharts options={Polygonoptions} id="radar-polygon"  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/radar-chart/radar-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import { Multioptions, Multiseries, Ploygonseries, Polygonoptions, Radaroptions, Radarseries } from "../../../../shared/data/charts/apexcharts/radardata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const RadarChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Radar Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Radar Charts" activepage="Apex Radar Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Radar Chart</Card.Title>
                        </Card.Header>
                        <Card.Body className="">
                            <div id="radar-basic">
                                <Spkapexcharts chartOptions={Radaroptions} chartSeries={Radarseries} type="radar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Radar Chart-Multiple Series</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="radar-multiple">
                                <Spkapexcharts chartOptions={Multioptions} chartSeries={Multiseries} type="radar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card custom-chart">
                        <Card.Header>
                            <Card.Title>Radar Chart Polygon Fill</Card.Title>
                        </Card.Header>
                        <Card.Body className="">
                            <div id="radar-polygon">
                                <Spkapexcharts chartOptions={Polygonoptions} chartSeries={Ploygonseries} type="radar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
RadarChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default RadarChart;
