// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/forms/form-elements/form-select/form-select.jsx

import { formselect2, formselect3, formselect4, formselect7, formselect8, formselect9 } from "../../../../../shared/data/prism-code/forms-prism";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../../shared/layouts-components/showcode/showcode";
import CreatableSelect from 'react-select/creatable';
import React, { Fragment, useState } from "react";
import { Card, Col, Row } from "react-bootstrap";
import Pageheader from "../../../../../shared/layouts-components/pageheader/pageheader";
import { MultiGroup, Multipleselectdata, Multipleselectdata1, Optionwithnosearch, SingleGroup } from "../../../../../shared/data/pages/forms/formselectdata";
import SpkSelect from "../../../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import SpkMultiselect from "../../../../../shared/@spk-reusable-components/reusable-plugins/spk-multiselect";
import MainLayout from "@/Layouts/layout";


const FormSelect = () => {

    const [_valuesA, setValuesA] = useState()
    const [_valuesB, setValuesB] = useState()
    const components = {
        DropdownIndicator: null,
    };

    const createOption = (label) => ({
        label,
        value: label,
    });

    const [inputValue, setInputValue] = useState('');
    const [value, setValue] = useState([
        createOption("one"),
        createOption("two"),
        createOption("three")
    ]);
    const handleKeyDown = (event) => {
        if (!inputValue) return;
        switch (event.key) {
            case 'Enter':
            case 'Tab':
                setValue((prev) => [...prev, createOption(inputValue)]);
                setInputValue('');
                event.preventDefault();
        }
    };
    const [inputValue1, setInputValue1] = useState('');
    const [value1, setValue1] = useState([
        createOption("child-1"),
        createOption("child-2")
    ]);

    const handleKeyDown1 = (event) => {
        if (!inputValue1) return;
        switch (event.key) {
            case 'Enter':
            case 'Tab':
                setValue1((prev) => [...prev, createOption(inputValue1)]);
                setInputValue1('');
                event.preventDefault();
        }
    };

    const isValidEmail = (email) => {
        const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
        return emailRegex.test(email);
    };

    const createOption1 = (email) => ({
        label: email,
        value: email,
    });

    const [inputValue2, setInputValue2] = useState("");
    const [value2, setValue2] = useState([createOption1("abc@hotmail.com")]);
    const [_error, setError] = useState("");

    const handleKeyDown2 = (event) => {
        if (!inputValue2) return;

        switch (event.key) {
            case "Enter":
            case "Tab":
                if (isValidEmail(inputValue2) && !value2.some(option => option.value === inputValue2)) {
                    setValue2((prev) => [...prev, createOption1(inputValue2)]);
                    setError("");
                } else {
                    setError("Please enter a valid email address or avoid duplicates.");
                }
                setInputValue2("");
                event.preventDefault();
                break;
            default:
                break;
        }
    };

    const defaults = [Multipleselectdata[5]];

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Forms-Formselect" />

            <Pageheader title="Forms" subtitle="Form Elements" currentpage="Form- Select" activepage="Form- Select" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header className="d-flex align-items-center justify-content-between">
                            <h6 className="card-title">Multiple Select</h6>
                        </Card.Header>
                        <Card.Body>
                            <p className="fw-medium mb-2">Default</p>
                            <div className="choices mb-4">
                                <SpkMultiselect multi options={Multipleselectdata} mainClass="default basic-multi-select custom-multi "
                                    values={[Multipleselectdata[0]]} onChange={(valuesA) => setValuesA(valuesA)} disabledLabel={defaults.length} />
                            </div>
                            <p className="fw-medium mb-2">With Remove Button</p>
                            <div className="choices mb-4">
                                <SpkMultiselect multi options={Multipleselectdata1} mainClass="basic-multi-select custom-multi"
                                    values={[Multipleselectdata1[0]]} onChange={(valuesB) => setValuesB(valuesB)} />
                            </div>
                            <p className="fw-medium mb-2">Option groups</p>
                            <div className="choices">
                                <MultiGroup />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header className="">
                            <div className="card-title">
                                Passing Through Options
                            </div>
                        </Card.Header>
                        <Card.Body id="form-select-unique">
                            <CreatableSelect components={components} classNamePrefix='react-select' inputValue={inputValue} isClearable isMulti menuIsOpen={false} onChange={(newValue) => {
                                if (Array.isArray(newValue)) {
                                    setValue(newValue);
                                } else {
                                    setValue([]);
                                }
                            }} onInputChange={(newValue) => setInputValue(newValue)} onKeyDown={handleKeyDown} placeholder="Type something and press enter..." value={value} />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header className="">
                            <div className="card-title">
                                Options added via config with no search
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <SpkSelect name="colors" option={Optionwithnosearch} menuplacement='auto' classNameprefix="Select2" defaultvalue={[Optionwithnosearch[5]]}
                            />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header className="d-flex align-items-center justify-content-between">
                            <h6 className="card-title">Single Select</h6>
                        </Card.Header>
                        <Card.Body>
                            <p className="fw-medium mb-2">Default</p>
                            <SpkSelect option={Multipleselectdata} mainClass="mb-4 default basic-multi-select" id="choices-multiple-default"
                                menuplacement='auto' classNameprefix="Select2" defaultvalue={[Multipleselectdata[0]]}
                            />
                            <p className="fw-medium mb-2">Option groups</p>
                            <SingleGroup />
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- Start:: row-1 --> */}

            {/* <!-- Start:: row-2 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header className="">
                            <div className="card-title">
                                Email Address Only
                            </div>
                        </Card.Header>
                        <Card.Body id="form-select-unique">
                            <CreatableSelect components={{}} classNamePrefix='react-select' inputValue={inputValue2} isClearable isMulti menuIsOpen={false} onChange={(newValue) => {
                                if (Array.isArray(newValue)) {
                                    setValue2(newValue);
                                } else {
                                    setValue2([]);
                                }
                            }} onInputChange={(newValue) => setInputValue2(newValue)} onKeyDown={handleKeyDown2} placeholder="Type an email and press enter..." value={value2} />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header className="">
                            <div className="card-title">
                                Passing Unique Values
                            </div>
                        </Card.Header>
                        <Card.Body id="form-select-unique">
                            <CreatableSelect components={components} classNamePrefix='react-select' inputValue={inputValue1} isClearable isMulti menuIsOpen={false} onChange={(newValue) => {
                                if (Array.isArray(newValue)) {
                                    setValue1(newValue);
                                } else {
                                    setValue1([]);
                                }
                            }} onInputChange={(newValue) => setInputValue1(newValue)} onKeyDown={handleKeyDown1} placeholder="Type something and press enter..." value={value1} />
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-2 --> */}

            {/* <!-- Start::row-3 --> */}

            <Row>
                <Col xl={4}>
                    <ShowCode title="Default Select" customCardClass="custom-card" customCardBodyClass="" reactCode={formselect2}>

                        <select className="form-select" aria-label="Default select example">
                            <option selected>Open this select menu
                            </option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                    </ShowCode>
                </Col>
                <Col xl={4}>
                    <ShowCode title=" Disabled Select" customCardClass="custom-card" customCardBodyClass="" reactCode={formselect7}>
                        <select className="form-select" aria-label="Disabled select example" disabled>
                            <option selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                    </ShowCode>
                </Col>
                <Col xl={4}>
                    <ShowCode title="Rounded Select" customCardClass="custom-card" customCardBodyClass="" reactCode={formselect3}>

                        <select className="form-select rounded-pill" aria-label="Default select example">
                            <option selected>Open this select menu
                            </option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                    </ShowCode>
                </Col>

            </Row>

            {/* <!--End::row-3 --> */}

            {/* <!-- Start:: row-4 --> */}

            <Row>
                <Col xl={6}>
                    <ShowCode title="Multiple Attribute Select" customCardClass="custom-card" customCardBodyClass="" reactCode={formselect9}>
                        <select className="form-select custom-form-select1" multiple aria-label="multiple select example">
                            <option selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                    </ShowCode>
                </Col>
                <Col xl={6}>
                    <ShowCode title=" Using Size Attribute" customCardClass="custom-card" customCardBodyClass="" reactCode={formselect8}>
                        <select className="form-select" size={4} aria-label="size 3 select example">
                            <option selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                            <option value="4">Four</option>
                            <option value="5">Five</option>
                        </select>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-4 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xl={12}>
                    <ShowCode title="Select Sizes" customCardClass="custom-card" customCardBodyClass="" reactCode={formselect4}>

                        <select className="form-select form-select-sm mb-3" aria-label=".form-select-sm example">
                            <option selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select><select className="form-select mb-3" aria-label="Default select">
                            <option selected>Open this select menu
                            </option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                        <select className="form-select form-select-lg"
                            aria-label=".form-select-lg example">
                            <option selected>Open this select menu</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                        </select>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-3 --> */}

        </Fragment>
    )
};
// Assign layout
FormSelect.layout = (page) => <MainLayout>{page}</MainLayout>;
export default FormSelect;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/pages/forms/form-elements/form-select/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import { Col, Input, Row } from "@sveltestrap/sveltestrap";
    import Select from "svelte-select";
    import SpkBasicCard from "$lib/@spk/SpkBasicCard.svelte";
    import {
        formselect2,
        formselect1,
        formselect3,
        formselect5,
        formselect6,
        formselect4,
    } from "$lib/components/common/prism-code/formsprism";
    import {
        Multipleselectdata,
        Multipleselectdata1,
        groupeddata,
        Optionwithnosearch,
    } from "$lib/data/forms/formselectdata";
    import ShowCode from "$lib/components/layout-components/showcode/ShowCode.svelte";

    interface Item {
        value: string;
        label: string;
        created?: boolean;
    }

    let items: Item[] = [
        { value: "one", label: "One" },
        { value: "two", label: "Two" },
        { value: "three", label: "Three" },
    ];

    let valuesPassing: Item[] = [items[0], items[1], items[2]];
    let filterText: string = "";

    function handleFilter(e: CustomEvent<Item[]>) {
        const exists = items.some(
            (i) => i.label.toLowerCase() === filterText.toLowerCase()
        );

        if (exists) return;

        if (e.detail.length === 0 && filterText.length > 0) {
            const newItem: Item = {
                value: filterText,
                label: filterText,
                created: true,
            };
            items = [...items, newItem];
        }
    }

    function handleChange(e: CustomEvent<Item[]>) {
        items = items.map(({ created, ...rest }) => rest);
    }
    interface Item1 {
        value: string;
        label: string;
        created?: boolean;
    }

    let items1: Item1[] = [
        { value: "one", label: "One" },
        { value: "two", label: "Two" },
        { value: "three", label: "Three" },
    ];

    let selectedValues: Item1[] = [];
    let filterText1: string = "";

    function handleFilter1(e: CustomEvent<Item1[]>) {
        const exists = items1.some(
            (i) => i.label.toLowerCase() === filterText1.toLowerCase(),
        );
        if (exists) return;

        if (e.detail.length === 0 && filterText1.length > 0) {
            const newItem: Item1 = {
                value: filterText1,
                label: filterText1,
                created: true,
            };
            items1 = [...items1, newItem];
        }
    }

    function handleChange1(e: CustomEvent<Item1[]>) {
        items1 = items1.map(({ created, ...rest }) => rest);
    }

    //  unique Email

    type EmailOption = {
        value: string;
        label: string;
        created?: boolean;
    };

    let filterTextEmail: string = "";
    let valueEmail: EmailOption[] = [
        { value: "abc@hotmail.com", label: "abc@hotmail.com" },
    ];

    let itemsEmail: EmailOption[] = [
        { value: "abc@hotmail.com", label: "abc@hotmail.com" },
    ];

    function isValidEmail(email: string): boolean {
        return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
    }

    function handleFilterEmail(e: CustomEvent<EmailOption[]>) {
        const alreadyExists = itemsEmail.some(
            (i) => i.label === filterTextEmail,
        );
        const alreadySelected = valueEmail?.some(
            (i) => i.label === filterTextEmail,
        );

        if (
            !alreadyExists &&
            !alreadySelected &&
            isValidEmail(filterTextEmail)
        ) {
            itemsEmail = [
                ...itemsEmail.filter((i) => !i.created),
                {
                    value: filterTextEmail,
                    label: filterTextEmail,
                    created: true,
                },
            ];
        }
    }

    function handleChangeEmail(e: CustomEvent<EmailOption[]>) {
        valueEmail = e.detail;

        for (const v of valueEmail) {
            const exists = itemsEmail.find((i) => i.label === v.label);
            if (!exists) {
                itemsEmail = [...itemsEmail, { ...v, created: true }];
            }
        }

        itemsEmail = itemsEmail.map((i) => {
            delete i.created;
            return i;
        });
    }
</script>

<!-- Page Title -->
<svelte:head>
    <title>FormSelect | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Form- Select"
    activepage="Forms"
    subTitle=" Form Elements"
    page="Form- Select"
/>
<!-- Page Header Close -->

<!-- Start:: row-4 -->
<h6 class="fw-medium mb-2">Choices:</h6>
<Row>
    <Col xl={12}>
        <Row>
            <Col xl={12}>
                <SpkBasicCard
                    cardProps="custom-card"
                    headerTitle="Multiple Select"
                    Headerprops="d-flex align-items-center justify-content-between"
                >
                    <div slot="customheader"></div>
                    <div slot="content">
                        <p class="fw-semibold mb-2">Default</p>
                        <Select
                            multiple
                            items={Multipleselectdata}
                            class="mb-2"
                            clearable={false}
                            multiFullItemClearable
                            value={[
                                Multipleselectdata[0].value,
                                Multipleselectdata[1].value,
                            ]}
                            name="choices-multiple-default"
                            id="choices-multiple-default"
                        />
                        <p class="fw-semibold mb-2">With Remove Button</p>
                        <Select
                            multiple
                            items={Multipleselectdata1}
                            class="mb-2"
                            showChevron={false}
                            clearable={false}
                            value={Multipleselectdata1[0].value}
                            name="choices-multiple-remove-button"
                            id="choices-multiple-remove-button"
                        />
                        <p class="fw-semibold mb-2">Option groups</p>
                        <Select
                            multiple
                            items={groupeddata}
                            class="mb-2"
                            multiFullItemClearable
                            value={groupeddata[0].value}
                            
                            name="choices-multiple-groups"
                            id="choices-multiple-groups"
                        />
                    </div>
                </SpkBasicCard>
            </Col>
            <Col xl={12}>
                <SpkBasicCard
                    cardProps="custom-card"
                    headerTitle="Passing Through Options"
                >
                    <div slot="customheader"></div>
                    <div slot="content">
                        <Select
    on:change={handleChange}
    on:filter={handleFilter}
    bind:filterText
    bind:value={valuesPassing}
    {items}
    id="choices-text-preset-values"
    multiFullItemClearable
    multiple
>
    <div slot="item" let:item>
        {item.created ? "Add new: " : ""}
        {item.label}
    </div>
</Select>
                    </div>
                </SpkBasicCard>
            </Col>
            <Col xl={12}>
                <SpkBasicCard
                    cardProps="custom-card"
                    headerTitle="Options added via config with no search"
                >
                    <div slot="customheader"></div>
                    <div slot="content">
                        <Select
                            items={Optionwithnosearch}
                            class="mb-2"
                            clearable={false}
                            value={Optionwithnosearch[0].value}
                            name="choices-single-no-search"
                            id="choices-single-no-search"
                            showChevron={true}
                        />
                    </div>
                </SpkBasicCard>
            </Col>
        </Row>
    </Col>
    <Col xl={12}>
        <Row>
            <Col xl={12}>
                <SpkBasicCard
                    cardProps="custom-card"
                    headerTitle="Single Select"
                    Headerprops="d-flex align-items-center justify-content-between"
                >
                    <div slot="customheader"></div>
                    <div slot="content">
                        <p class="fw-semibold mb-2">Default</p>
                        <Select
                            items={Multipleselectdata}
                            class="mb-2"
                            clearable={false}
                            showChevron={true}
                            value={Multipleselectdata[0].value}
                            name="choices-single-default"
                            id="choices-single-default"
                        />
                        <p class="fw-semibold mb-2">Option groups</p>
                        <Select
                            items={groupeddata}
                            class="mb-2 form-control"
                            
                            showChevron={true}
                            clearable={false}
                            value={groupeddata[0].value}
                            name="choices-single-groups"
                            id="choices-single-groups"
                        />
                    </div>
                </SpkBasicCard>
            </Col>
            <Col xl={12}>
                <SpkBasicCard
                    cardProps="custom-card"
                    headerTitle="Email Address Only"
                >
                    <div slot="customheader"></div>
                    <div slot="content">
                        <Select
                            on:change={handleChangeEmail}
                            multiple
                            on:filter={handleFilterEmail}
                            bind:filterText={filterTextEmail}
                            bind:value={valueEmail}
                            items={itemsEmail}
                        >
                            <div slot="item" let:item>
                                {item.created ? "Add new email: " : ""}
                                {item.label}
                            </div>
                        </Select>
                    </div>
                </SpkBasicCard>
            </Col>
            <Col xl={12}>
                <SpkBasicCard
                    cardProps="custom-card"
                    headerTitle="  Passing Unique Values"
                >
                    <div slot="customheader"></div>
                    <div slot="content">
                        <Select
                            on:change={handleChange1}
                            multiFullItemClearable
                            multiple
                            on:filter={handleFilter1}
                            bind:filterText={filterText1}
                            bind:value={selectedValues}
                            items={items1}
                            id="choices-text-preset-values"
                        >
                            <div slot="item" let:item>
                                {item.created ? "Add new: " : ""}
                                {item.label}
                            </div>
                        </Select>
                    </div>
                </SpkBasicCard>
            </Col>
        </Row>
    </Col>
</Row>
<!-- End:: row-4 -->

<!-- Start::row-1 -->
<Row>
    <Col xl={4}>
        <ShowCode title="Default Select" svelteCode={formselect1}>
            <Input type="select" aria-label="Default select example">
                <option>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </Input>
        </ShowCode>
    </Col>
    <Col xl={4}>
        <ShowCode title="Disabled Select" svelteCode={formselect2}>
            <Input
                type="select"
                aria-label="Default select example"
                disabled={true}
            >
                <option>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </Input>
        </ShowCode>
    </Col>
    <Col xl={4}>
        <ShowCode title="Rounded Select" svelteCode={formselect3}>
            <Input
                type="select"
                class="form-select rounded-pill"
                aria-label="Default select example"
            >
                <option>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </Input>
        </ShowCode>
    </Col>
</Row>
<!--End::row-1 -->

<!-- Start:: row-2 -->
<Row>
    <Col xl={6}>
        <ShowCode title="Multiple Attribute Select" svelteCode={formselect4}>
            <select
                class="form-select"
                multiple
                aria-label="multiple select example"
            >
                <option selected>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </ShowCode>
    </Col>
    <Col xl={6}>
        <ShowCode title="Using Size Attribute" svelteCode={formselect5}>
            <select
                class="form-select"
                size="4"
                aria-label="size 3 select example"
            >
                <option selected>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
                <option value="4">Four</option>
                <option value="5">Five</option>
            </select>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-2 -->

<!-- Start:: row-3 -->
<Row>
    <Col xl={12}>
        <ShowCode title="Select Sizes" svelteCode={formselect6}>
            <Input
                type="select"
                class="form-select form-select-sm mb-3"
                aria-label=".form-select-sm example"
            >
                <option selected>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </Input>
            <Input
                type="select"
                class="form-select mb-3"
                aria-label="Default select"
            >
                <option selected>Open this select menu </option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </Input>
            <Input
                type="select"
                class="form-select form-select-lg"
                aria-label=".form-select-lg example"
            >
                <option selected>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </Input>
        </ShowCode>
    </Col>
</Row>
<!-- End:: row-3 -->
