// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/pages/forms/form-elements/file-uploads/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import FilePond, { registerPlugin } from "svelte-filepond";
    import FilePondPluginImageExifOrientation from "filepond-plugin-image-exif-orientation";
    import FilePondPluginImagePreview from "filepond-plugin-image-preview";
    import { Col, FormGroup, Label, Input } from "@sveltestrap/sveltestrap";
    import ShowCode from "$lib/components/layout-components/showcode/ShowCode.svelte";
    import { fileupload1 } from "$lib/components/common/prism-code/formsprism";

    // Register the plugins
    registerPlugin(
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
    );
</script>

<!-- Page Title -->
<svelte:head>
    <title>FileUploads | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="File Uploads"
    activepage="Forms"
    subTitle=" Form Elements"
    page="File Uploads"
/>
<!-- Page Header Close -->

<!-- Start:: row-1 -->
<div class="row">
    <Col xl={12}>
        <ShowCode title="Bootstrap File Input" svelteCode={fileupload1}>
          <FormGroup  class="mb-3 custom-file1">
            <Label>Default file input example</Label>
            <Input type="file" />
          </FormGroup >
          <FormGroup  class="mb-3 custom-file1">
            <Label>Multiple files input example</Label>
            <Input type="file" multiple />
          </FormGroup >
          <FormGroup   class="mb-3">
            <Label>Disabled file input example</Label>
            <Input type="file" disabled />
          </FormGroup >
          <FormGroup  class="mb-3 custom-file2">
            <Label>Small file input example</Label>
            <Input type="file" bsSize="sm" />
          </FormGroup >
          <FormGroup  class="mb-3">
            <Label>Large file input example</Label>
            <Input type="file" bsSize="lg" />
          </FormGroup >
        </ShowCode>
      </Col>
    <div class="col-xl-12">
        <h6 class="mb-3">Filepond:</h6>
        <div class="row">
            <div class="col-xl-12">
                <div class="card custom-card">
                    <div class="card-header">
                        <div class="card-title">
                            Multiple Upload
                        </div>
                    </div>
                    <div class="card-body">
                        <FilePond class="multiple-filepond" name="filepond" labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
                            stylePanelLayout=' ' styleLoadIndicatorPosition='center bottom'
                            styleButtonRemoveItemPosition='center bottom'  allowMultiple={true}  />
                    </div>  
                </div>
            </div>
            <div class="col-xl-12">
                <div class="card custom-card">
                    <div class="card-header">
                        <div class="card-title">
                            Single Upload
                        </div>
                    </div>
                    <div class="card-body">
                        <FilePond class="single-fileupload" labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
                            stylePanelLayout='compact circle' styleLoadIndicatorPosition='center bottom'
                            styleButtonRemoveItemPosition='center bottom' />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End:: row-1 -->

<!-- Start:: row-2 -->
<div class="row">
    <div class="col-xl-12">
        <div class="card custom-card">
            <div class="card-header">
                <div class="card-title">
                    Dropzone
                </div>
            </div>
            <div class="card-body">
                <FilePond class=""  labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
                allowMultiple={true}   />
            </div>
        </div>
    </div>
</div>
<!-- End:: row-2 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/pages/forms/form-elements/file-uploads/file-uploads.jsx

import React, { Fragment, useState } from "react";
import { FilePond, registerPlugin } from "react-filepond";
import FilePondPluginImageExifOrientation from "filepond-plugin-image-exif-orientation";
import FilePondPluginImagePreview from "filepond-plugin-image-preview";
import ShowCode from "../../../../../shared/layouts-components/showcode/showcode";
import { Card, Col, Form, Row } from "react-bootstrap";
import { fileupload1 } from "../../../../../shared/data/prism-code/forms-prism";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../../shared/layouts-components/pageheader/pageheader";
import MainLayout from "@/Layouts/layout";

registerPlugin(FilePondPluginImagePreview, FilePondPluginImageExifOrientation);


const FileUploads = () => {

    const [files, setFiles] = useState([]);
    const [files1, setFiles1] = useState([]);
    const [files2, setFiles2] = useState([]);

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Forms-File Uploads" />

            <Pageheader title="Forms" subtitle="Form Elements" currentpage="File Uploads" activepage="File Uploads" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={12}>
                    <ShowCode title="Bootstrap File Input" customCardClass="custom-card" customCardBodyClass="" reactCode={fileupload1}>
                        <Form.Group controlId="formFile" className="mb-3">
                            <Form.Label>Default file input example</Form.Label>
                            <Form.Control type="file" />
                        </Form.Group>
                        <Form.Group controlId="formFileMultiple" className="mb-3">
                            <Form.Label>Multiple files input example</Form.Label>
                            <Form.Control type="file" multiple />
                        </Form.Group>
                        <Form.Group controlId="formFileDisabled" className="mb-3">
                            <Form.Label>Disabled file input example</Form.Label>
                            <Form.Control type="file" disabled />
                        </Form.Group>
                        <Form.Group controlId="formFileSm" className="mb-3">
                            <Form.Label>Small file input example</Form.Label>
                            <Form.Control type="file" size="sm" />
                        </Form.Group>
                        <Form.Group controlId="formFileLg" className="mb-3">
                            <Form.Label>Large file input example</Form.Label>
                            <Form.Control type="file" size="lg" />
                        </Form.Group>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-2 --> */}

            <h6 className="mb-3">Filepond:</h6>
            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Multiple Upload
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <FilePond className="multiple-filepond" files={files} onupdatefiles={setFiles} allowMultiple={true} maxFiles={3} server="/api" name="files" labelIdle='Drag & Drop your file here or click ' />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Single Upload
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <FilePond className="multiple-filepond single-fileupload" stylePanelLayout={"compact circle"} files={files1} onupdatefiles={setFiles1} allowMultiple={true} maxFiles={1} server="/api" name="files" labelIdle='Drag & Drop your file here or click ' />
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-2 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Dropzone
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <FilePond className="multiple-filepond" files={files2} onupdatefiles={setFiles2} allowMultiple={true} maxFiles={3} server="/api" name="files" labelIdle='Drag & Drop your file here or click ' />
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-3 --> */}

        </Fragment>
    )
};
// Assign layout
FileUploads.layout = (page) => <MainLayout>{page}</MainLayout>;
export default FileUploads;
