// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/general/utilities/additional-content/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import { Card, CardBody, CardHeader, Col, Image, Row } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>AdditionalContent | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<!-- Page Header -->
<Pageheader
    homepage="Additional Content"
    activepage="Utilities"
    page="Additional Content"
/>
<!-- Page Header Close -->

 <!-- Start:: row-1 --> 

            <Row>
                <Col xl={6}>
                    <Row>
                        <Col xl={12}>
                            <Card class="custom-card">
                                <CardHeader>
                                    <div class="card-title">
                                        Vertical alignment With table cells
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div class="table-responsive">
                                        <table style="height: 100px">
                                            <tbody>
                                                <tr>
                                                    <td class="align-baseline">baseline</td>
                                                    <td class="align-top">top</td>
                                                    <td class="align-middle">middle</td>
                                                    <td class="align-bottom">bottom</td>
                                                    <td class="align-text-top">text-top</td>
                                                    <td class="align-text-bottom">text-bottom</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </CardBody>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card class="custom-card">
                                <CardHeader>
                                    <div class="card-title">
                                        Vertical alignment With inline elements
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <span class="align-baseline">baseline</span>
                                    <span class="align-top"> top</span>
                                    <span class="align-middle"> middle</span>
                                    <span class="align-bottom"> bottom</span>
                                    <span class="align-text-top"> text-top</span>
                                    <span class="align-text-bottom"> text-bottom</span>
                                </CardBody>
                            </Card>
                        </Col>
                    </Row>
                </Col>

                <Col xl={6}>
                    <Row>
                        <Col xl={12}>
                            <Card class="custom-card">
                                <CardHeader>
                                    <div class="card-title">
                                        Opacity
                                    </div>
                                </CardHeader>
                                <div class="card-body d-sm-flex">
                                    <div class="opacity-100 p-3 m-2 bg-primary text-fixed-white fw-bold rounded">100%
                                    </div>
                                    <div class="opacity-75 p-3 m-2 bg-primary text-fixed-white fw-bold rounded">75%</div>
                                    <div class="opacity-50 p-3 m-2 bg-primary text-fixed-white fw-bold rounded">50%</div>
                                    <div class="opacity-25 p-3 m-2 bg-primary text-fixed-white fw-bold rounded">25%</div>
                                </div>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card class="custom-card">
                                <CardHeader>
                                    <div class="card-title">
                                        Horizontal centering
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div class="mx-auto" style="width: 200px; padding: 10px; border-radius: 4px; background-color: rgba(86,61,124,.15);">
                                        Centered element
                                    </div>
                                </CardBody>
                            </Card>
                        </Col>
                    </Row>
                </Col>
            </Row>
             <!-- End:: row-1 --> 

             <!-- Start:: row-2 --> 
            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                Relative to the parent
                            </div>
                        </CardHeader>
                        <CardBody class="overflow-x-auto">
                            <div class="mb-5">
                                <div class="w-25 p-3 bg-light">Width 25%</div>
                                <div class="w-50 p-3 bg-light">Width 50%</div>
                                <div class="w-75 p-3 bg-light">Width 75%</div>
                                <div class="w-100 p-3 bg-light">Width 100%</div>
                                <div class="w-auto p-3 bg-light">Width auto</div>
                            </div>
                            <div
          style="height: 100px; background-color: rgba(255,0,0,0.1);"
          class="d-flex"
        >
          <div
            class="h-25 d-inline-block"
            style="width: 120px; background-color: rgba(0,0,255,.1);padding-inline:10px;"
          >
            Height 25%
          </div>
          <div
            class="h-50 d-inline-block"
            style="width: 120px; background-color: rgba(0,0,255,.1);padding:10px;"
          >
            Height 50%
          </div>
          <div
            class="h-75 d-inline-block"
            style="width: 120px; background-color: rgba(0,0,255,.1);padding:10px;"
          >
            Height 75%
          </div>
          <div
            class="h-100 d-inline-block"
            style="width: 120px; background-color: rgba(0,0,255,.1);padding:10px;"
          >
            Height 100%
          </div>
          <div
            class="h-auto d-inline-block d-none d-sm-block"
            style="width: 120px; background-color: rgba(0,0,255,.1);padding:10px;"
          >
            Height auto
          </div>
        </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                You can also use <span class="text-danger"> max-width: 100%;</span> and <span
                                    class="text-danger">max-height: 100%;</span> utilities as needed.
                            </div>
                        </CardHeader>
                        <CardBody>
                            <Image class="bd-placeholder-img mw-100 card-img" src="../../images/media/media-7.jpg" alt="..." />
                            <div style="height: 100px; background-color: rgba(255,0,0,.1);" class="mt-3">
                                <div class="mh-100"
                                    style="width: 100px; height: 200px; background-color: rgba(0,0,255,.1); padding:10px;">
                                    Max-height 100%</div>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!-- End:: row-2 --> 

            <Row>
                <Col xl={4}>
                    <Col xl={12}>
                        <Card class="custom-card">
                            <CardHeader>
                                <div class="card-title">
                                    Display Inline
                                </div>
                            </CardHeader>
                            <CardBody>
                                <div class="d-inline p-2 bg-primary text-fixed-white rounded m-1">d-inline</div>
                                <div class="d-inline p-2 bg-primary-transparent text-primary rounded m-1">d-inline</div>
                            </CardBody>
                        </Card>
                    </Col>
                    <Col xl={12}>
                        <Card class="custom-card">
                            <CardHeader>
                                <div class="card-title">
                                    D-block
                                </div>
                            </CardHeader>
                            <CardBody>
                                <span class="d-block p-2 bg-secondary-transparent mb-1 rounded">d-block</span>
                                <span class="d-block p-2 bg-primary-transparent mb-1 rounded">d-block</span>
                                <span class="d-block p-2 bg-success-transparent mb-1 rounded">d-block</span>
                            </CardBody>
                        </Card>
                    </Col>
                </Col>
                <Col xl={4}>
                    <Row>
                        <Col xl={12}>
                            <Card class="custom-card">
                                <CardHeader>
                                    <div class="card-title">
                                        Float
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div class="float-start p-2 bg-primary rounded text-fixed-white mb-2">Float start</div><br />
                                    <div class="float-end p-2 bg-primary rounded text-fixed-white">Float end</div><br />
                                    <div class="float-none p-2 bg-primary rounded text-fixed-white mt-4">Don't float</div>
                                </CardBody>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card class="custom-card">
                                <CardHeader>
                                    <div class="card-title">
                                        Float Responsive
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <div class="float-sm-start p-1 bg-light">Float sm
                                    </div>
                                    <br />
                                    <div class="float-md-end p-1 bg-light">Float md
                                    </div>
                                    <br />
                                    <div class="float-lg-start p-1 bg-light">Float lg
                                    </div>
                                    <br />
                                    <div class="float-xl-end p-1 bg-light">Float  xl
                                    </div>
                                </CardBody>
                            </Card>
                        </Col>
                    </Row>
                </Col>
                <Col xl={4}>
                    <Row>
                        <Col xl={12}>
                            <Card class="custom-card">
                                <CardHeader>
                                    <div class="card-title">
                                        Text selection
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <p class="user-select-all">This paragraph will be entirely selected when clicked
                                        by
                                        the user.
                                    </p>
                                    <p class="user-select-auto">This paragraph has default select behavior.</p>
                                    <p class="user-select-none mb-0">This paragraph will not be selectable when clicked
                                        by
                                        the user.
                                    </p>
                                </CardBody>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card class="custom-card">
                                <CardHeader>
                                    <div class="card-title">
                                        Pointer events
                                    </div>
                                </CardHeader>
                                <CardBody>
                                    <p><a href="#!" class="pe-none" tabIndex={-1} aria-disabled="false"><code class="text-primary fw-medium">This link</code> </a>
                                        can
                                        not be clicked.
                                    </p>
                                    <p><a href="#!" class="pe-auto"><code class="text-primary fw-medium">This link</code></a> can be clicked (this is default
                                        behavior).
                                    </p>
                                    <p class="pe-none mb-0"><a href="#!" tabIndex={-1} aria-disabled="false"><code>This link</code> </a>
                                        can
                                        not be clicked because the <code class="text-primary fw-medium">pointer-events</code> property is inherited
                                        from its parent. However, <a href="#!" class="pe-auto">this link</a> has a
                                        <code>pe-auto</code> class and can be clicked.
                                    </p>
                                </CardBody>
                            </Card>
                        </Col>
                    </Row>
                </Col>
            </Row>

             <!-- Start:: row-4 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                Gap
                            </div>
                        </CardHeader>
                        <CardBody>
                            <div class="d-grid gap-3">
                                <div class="p-2 bg-light border">Grid item 1</div>
                                <div class="p-2 bg-light border">Grid item 2</div>
                                <div class="p-2 bg-light border">Grid item 3</div>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                Examples
                            </div>
                        </CardHeader>
                        <CardBody>
                            <div class="shadow-none p-3 mb-4 bg-light rounded">No shadow</div>
                            <div class="shadow-sm p-3 mb-4 bg-body rounded">Small shadow</div>
                            <div class="shadow p-3 mb-4 bg-body rounded">Regular shadow</div>
                            <div class="shadow-lg p-3 mb-4 bg-body rounded">Larger shadow</div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!-- End:: row-4 --> 

             <!-- Start:: row-5 --> 

            <Row>
                <Col xl={12}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">
                                Overflow
                            </div>
                        </CardHeader>
                        <div class="card-body d-md-flex">
                            <div class="overflow-auto p-3 mb-3 mb-md-0 me-md-3 bg-light"
                                style="max-width: 260px; max-height: 100px;">
                                This is an example of using <code>.overflow-auto</code> on an element with
                                set width and height dimensions. By design, this content will vertically
                                scroll.
                            </div>
                            <div class="overflow-hidden p-3 mb-3 mb-md-0 me-md-3 bg-light"
                                style="max-width: 260px; max-height: 100px;">
                                This is an example of using <code>.overflow-hidden</code> on an element with
                                set width and height dimensions.
                            </div>
                            <div class="overflow-visible p-3 mb-3 mb-md-0 me-md-3 bg-light"
                                style="max-width: 260px; max-height: 100px;">
                                This is an example of using <code>.overflow-visible</code> on an element
                                with set width and height dimensions.
                            </div>
                            <div class="overflow-scroll p-3 bg-light"
                                style="max-width: 260px; max-height: 100px;">
                                This is an example of using <code>.overflow-scroll</code> on an element with
                                set width and height dimensions.
                            </div>
                        </div>
                    </Card>
                </Col>
            </Row>

             <!-- End:: row-5 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/utilities/additional-content/additional-content.jsx
import BaseLink from "@/shared/layouts-components/baselink/baselink";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Image, Row } from "react-bootstrap";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";

const AdditionalContent = () => {

    return (

        <Fragment>

            <Head title={"Additional Content"} />

            <Pageheader title="Utilities" currentpage="Additional Content" activepage="Additional Content" />

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Row>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Vertical alignment With table cells
                                    </div>
                                </Card.Header>
                                <Card.Body>
                                    <div className="table-responsive">
                                        <table style={{ height: "100px" }}>
                                            <tbody>
                                                <tr>
                                                    <td className="align-baseline">baseline</td>
                                                    <td className="align-top">top</td>
                                                    <td className="align-middle">middle</td>
                                                    <td className="align-bottom">bottom</td>
                                                    <td className="align-text-top">text-top</td>
                                                    <td className="align-text-bottom">text-bottom</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </Card.Body>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Vertical alignment With inline elements
                                    </div>
                                </Card.Header>
                                <Card.Body>
                                    <span className="align-baseline">baseline</span>
                                    <span className="align-top"> top</span>
                                    <span className="align-middle"> middle</span>
                                    <span className="align-bottom"> bottom</span>
                                    <span className="align-text-top"> text-top</span>
                                    <span className="align-text-bottom"> text-bottom</span>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>
                </Col>

                <Col xl={6}>
                    <Row>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Opacity
                                    </div>
                                </Card.Header>
                                <div className="card-body d-sm-flex">
                                    <div className="opacity-100 p-3 m-2 bg-primary text-fixed-white fw-bold rounded">100%
                                    </div>
                                    <div className="opacity-75 p-3 m-2 bg-primary text-fixed-white fw-bold rounded">75%</div>
                                    <div className="opacity-50 p-3 m-2 bg-primary text-fixed-white fw-bold rounded">50%</div>
                                    <div className="opacity-25 p-3 m-2 bg-primary text-fixed-white fw-bold rounded">25%</div>
                                </div>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Horizontal centering
                                    </div>
                                </Card.Header>
                                <Card.Body>
                                    <div className="mx-auto" style={{ width: "200px", padding: "10px", borderRadius: "4px", backgroundColor: "rgba(86,61,124,.15)" }}>
                                        Centered element
                                    </div>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>
                </Col>
            </Row>
            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-2 --> */}
            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Relative to the parent
                            </div>
                        </Card.Header>
                        <Card.Body className="overflow-x-auto">
                            <div className="mb-5">
                                <div className="w-25 p-3 bg-light">Width 25%</div>
                                <div className="w-50 p-3 bg-light">Width 50%</div>
                                <div className="w-75 p-3 bg-light">Width 75%</div>
                                <div className="w-100 p-3 bg-light">Width 100%</div>
                                <div className="w-auto p-3 bg-light">Width auto</div>
                            </div>
                            <div style={{ height: "100px", backgroundColor: "rgba(255,0,0,0.1)" }} className="d-flex">
                                <div className="h-25 d-inline-block"
                                    style={{ width: "120px", backgroundColor: "rgba(0,0,255,.1)", paddingInline: "10px" }}>H 25%
                                </div>
                                <div className="h-50 d-inline-block"
                                    style={{ width: "120px", backgroundColor: "rgba(0,0,255,.1)", padding: "10px" }}>H 50%
                                </div>
                                <div className="h-75 d-inline-block"
                                    style={{ width: "120px", backgroundColor: "rgba(0,0,255,.1)", padding: "10px" }}>H 75%
                                </div>
                                <div className="h-100 d-inline-block"
                                    style={{ width: "120px", backgroundColor: "rgba(0,0,255,.1)", padding: "10px" }}>H 100%
                                </div>
                                <div className="h-auto d-sm-inline-block d-none"
                                    style={{ width: "120px", backgroundColor: "rgba(0,0,255,.1)", padding: "10px" }}>H auto
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                You can also use <span className="text-danger"> max-width: 100%;</span> and <span
                                    className="text-danger">max-height: 100%;</span> utilities as needed.
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <BaseImage className="bd-placeholder-img mw-100 card-img" src="/build/assets/images/media/media-7.jpg" alt="..." />
                            <div style={{ height: "100px", backgroundColor: "rgba(255,0,0,.1)" }} className="mt-3">
                                <div className="mh-100"
                                    style={{ width: "100px", height: "200px", backgroundColor: "rgba(0,0,255,.1)", padding: "10px" }}>
                                    Max-height 100%</div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-2 --> */}

            <Row>
                <Col xl={4}>
                    <Col xl={12}>
                        <Card className="custom-card">
                            <Card.Header>
                                <div className="card-title">
                                    Display Inline
                                </div>
                            </Card.Header>
                            <Card.Body>
                                <div className="d-inline p-2 bg-primary text-fixed-white rounded m-1">d-inline</div>
                                <div className="d-inline p-2 bg-primary-transparent text-primary rounded m-1">d-inline</div>
                            </Card.Body>
                        </Card>
                    </Col>
                    <Col xl={12}>
                        <Card className="custom-card">
                            <Card.Header>
                                <div className="card-title">
                                    D-block
                                </div>
                            </Card.Header>
                            <Card.Body>
                                <span className="d-block p-2 bg-secondary-transparent mb-1 rounded">d-block</span>
                                <span className="d-block p-2 bg-primary-transparent mb-1 rounded">d-block</span>
                                <span className="d-block p-2 bg-success-transparent mb-1 rounded">d-block</span>
                            </Card.Body>
                        </Card>
                    </Col>
                </Col>
                <Col xl={4}>
                    <Row>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Float
                                    </div>
                                </Card.Header>
                                <Card.Body>
                                    <div className="float-start p-2 bg-primary rounded text-fixed-white mb-2">Float start</div><br />
                                    <div className="float-end p-2 bg-primary rounded text-fixed-white">Float end</div><br />
                                    <div className="float-none p-2 bg-primary rounded text-fixed-white mt-4">Don't float</div>
                                </Card.Body>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Float Responsive
                                    </div>
                                </Card.Header>
                                <Card.Body>
                                    <div className="float-sm-start p-1 bg-light">Float sm
                                    </div>
                                    <br />
                                    <div className="float-md-end p-1 bg-light">Float md
                                    </div>
                                    <br />
                                    <div className="float-lg-start p-1 bg-light">Float lg
                                    </div>
                                    <br />
                                    <div className="float-xl-end p-1 bg-light">Float  xl
                                    </div>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>
                </Col>
                <Col xl={4}>
                    <Row>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Text selection
                                    </div>
                                </Card.Header>
                                <Card.Body>
                                    <p className="user-select-all">This paragraph will be entirely selected when clicked
                                        by
                                        the user.
                                    </p>
                                    <p className="user-select-auto">This paragraph has default select behavior.</p>
                                    <p className="user-select-none mb-0">This paragraph will not be selectable when clicked
                                        by
                                        the user.
                                    </p>
                                </Card.Body>
                            </Card>
                        </Col>
                        <Col xl={12}>
                            <Card className="custom-card">
                                <Card.Header>
                                    <div className="card-title">
                                        Pointer events
                                    </div>
                                </Card.Header>
                                <Card.Body>
                                    <p><BaseLink href="#!" className="pe-none" tabIndex={-1} aria-disabled="false"><code className="text-primary fw-medium">This link</code> </BaseLink>
                                        can
                                        not be clicked.
                                    </p>
                                    <p><BaseLink href="#!" className="pe-auto"><code className="text-primary fw-medium">This link</code></BaseLink> can be clicked (this is default
                                        behavior).
                                    </p>
                                    <p className="pe-none mb-0"><BaseLink href="#!" tabIndex={-1} aria-disabled="false"><code>This link</code> </BaseLink>
                                        can
                                        not be clicked because the <code className="text-primary fw-medium">pointer-events</code> property is inherited
                                        from its parent. However, <BaseLink href="#!" className="pe-auto">this link</BaseLink> has a
                                        <code>pe-auto</code> class and can be clicked.
                                    </p>
                                </Card.Body>
                            </Card>
                        </Col>
                    </Row>
                </Col>
            </Row>

            {/* <!-- Start:: row-4 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Gap
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <div className="d-grid gap-3">
                                <div className="p-2 bg-light border">Grid item 1</div>
                                <div className="p-2 bg-light border">Grid item 2</div>
                                <div className="p-2 bg-light border">Grid item 3</div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Examples
                            </div>
                        </Card.Header>

                        <Card.Body>
                            <div className="shadow-none p-3 mb-4 bg-light rounded">No shadow</div>
                            <div className="shadow-sm p-3 mb-4 bg-body rounded">Small shadow</div>
                            <div className="shadow p-3 mb-4 bg-body rounded">Regular shadow</div>
                            <div className="shadow-lg p-3 mb-4 bg-body rounded">Larger shadow</div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-4 --> */}

            {/* <!-- Start:: row-5 --> */}

            <Row>
                <Col xl={12}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Overflow
                            </div>
                        </Card.Header>
                        <div className="card-body d-md-flex">
                            <div className="overflow-auto p-3 mb-3 mb-md-0 me-md-3 bg-light"
                                style={{ maxWidth: "260px", maxHeight: "100px" }}>
                                This is an example of using <code>.overflow-auto</code> on an element with
                                set width and height dimensions. By design, this content will vertically
                                scroll.
                            </div>
                            <div className="overflow-hidden p-3 mb-3 mb-md-0 me-md-3 bg-light"
                                style={{ maxWidth: "260px", maxHeight: "100px" }}>
                                This is an example of using <code>.overflow-hidden</code> on an element with
                                set width and height dimensions.
                            </div>
                            <div className="overflow-visible p-3 mb-3 mb-md-0 me-md-3 bg-light"
                                style={{ maxWidth: "260px", maxHeight: "100px" }}>
                                This is an example of using <code>.overflow-visible</code> on an element
                                with set width and height dimensions.
                            </div>
                            <div className="overflow-scroll p-3 bg-light"
                                style={{ maxWidth: "260px", maxHeight: "100px" }}>
                                This is an example of using <code>.overflow-scroll</code> on an element with
                                set width and height dimensions.
                            </div>
                        </div>
                    </Card>
                </Col>
            </Row>

            {/* <!-- End:: row-5 --> */}

        </Fragment>

    )
};
// Assign layout
AdditionalContent.layout = (page) => <MainLayout>{page}</MainLayout>;
export default AdditionalContent;
