// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/general/ui-elements/images-figures/+page.svelte

<script lang="ts">
      import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
  import ShowCode from "$lib/components/layout-components/ShowCode/ShowCode.svelte";
  import {
    image1,
    image2,
    image3,
    image4,
    image5,
    image6,
    image7,
    image8,
    image9,
  } from "$lib/components/common/prism-code/uielementsprim";
  import { Col, Image, Row } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>ImagesFigures | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<Pageheader
  homepage="Images & Figures"
  activepage="UI Elements"
  page="Images & Figures"
/>
<!-- Start:: row-1 -->
                    <Row>
                        <Col xl={6}>
                            <ShowCode title="Responsive image" svelteCode={image1}>
      <p class="card-title mb-3">
        Use <code> .img-fluid </code> class to the img tag to get responsive
        image.
      </p>
      <div class="text-center">
        <Image src="../../images/media/media-48.jpg" class="img-fluid" alt="..." />
      </div>
    </ShowCode>
                        </Col>
                        <Col xl={6}>
                            <ShowCode title="Image With Radius" svelteCode={image2}>
      <p class="card-title mb-3">
        Use <code>.rounded</code> class along with <code>.img-fluid</code> to get
        border radius.
      </p>
      <div class="text-center">
        <Image
          src="../../images/media/media-49.jpg"
          class="img-fluid rounded"
          alt="..."
        />
      </div>
    </ShowCode>
                        </Col>
                        <Col xl={6}>
                            <ShowCode title="Rounded Image" svelteCode={image3}>
      <p class="card-title mb-3">
        Use <code>.rounded-pill</code> class to <code>img</code> tag to get rounded
        image.
      </p>
      <div class="text-center">
        <Image
          src="../../images/media/media-50.jpg"
          class="img-fluid rounded-pill"
          alt="..."
        />
      </div>
    </ShowCode>
                        </Col>
                        <Col xl={6}>
                            <ShowCode title="Image Left Align" svelteCode={image4}>
      <div class="d-inline-block">
        <Image
          class="rounded float-start"
          src="../../images/media/media-53.jpg"
          alt="..."
        />
      </div>
    </ShowCode>
                        </Col>
                        <Col xl={6}>
                            <ShowCode title="Image Center Align" svelteCode={image5}>
      <Image
        class="rounded mx-auto d-block"
        src="../../images/media/media-55.jpg"
        alt="..."
      />
    </ShowCode>
                        </Col>
                        <Col xl={6}>
                            <ShowCode title="Image Right Align" svelteCode={image6}>
      <div class="">
        <Image
          class="rounded float-end"
          src="../../images/media/media-54.jpg"
          alt="..."
        />
      </div>
    </ShowCode>
                        </Col>
                        <Col xl={6}>
                             <ShowCode
      title="Figures"
      customCardBodyClass="d-flex justify-content-between gap-2"
      svelteCode={image7}
    >
      <figure class="figure me-2">
        <Image
          class="bd-placeholder-img figure-img img-fluid rounded card-img"
          src="../../images/media/media-56.jpg"
          alt="..."
        />
        <figcaption class="figure-caption mt-2">
          A caption for the above image.
        </figcaption>
      </figure>
      <figure class="figure float-end">
        <Image
          class="bd-placeholder-img figure-img img-fluid rounded card-img"
          src="../../images/media/media-57.jpg"
          alt="..."
        />
        <figcaption class="figure-caption text-end mt-2">
          A caption for the above image.
        </figcaption>
      </figure>
    </ShowCode>
                        </Col>
                        <Col xl={3}>
                           <ShowCode title="Image Thumbnail" svelteCode={image8}>
      <p class="card-title mb-3">
        Use <code> .img-thumbnail </code> to give an image a rounded 1px border.
      </p>
      <div class="text-center">
        <Image src="../../images/media/media-51.jpg" class="img-thumbnail" alt="..." />
      </div>
    </ShowCode>
                        </Col>
                        <Col xl={3}>
                           <ShowCode title="Rounded Thumbnail" svelteCode={image9}>
      <p class="card-title mb-3">
        Use <code> .rounded-pill </code> along with
        <code> .img-thummbnail </code> to get radius.
      </p>
      <div class="text-center">
        <Image
          src="../../images/media/media-52.jpg"
          class="img-thumbnail rounded-pill"
          alt="..."
        />
      </div>
    </ShowCode>
                        </Col>
                    </Row>
                    <!-- End:: row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/ui-elements/images-figures/images-figures.jsx

import { image1, image2, image3, image4, image5, image6, image7, image8, image9 } from "../../../../shared/data/prism-code/uielements-prism";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col, Image, Row } from "react-bootstrap";

import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const ImagesFigures = () => {

	return (

		<Fragment>

			{/* <!-- Page Header --> */}

			<Head title="Images&Figures" />

			<Pageheader title="Ui Elements" currentpage="Images & Figures" activepage="Images & Figures" />

			{/* <!-- Page Header Close --> */}

			{/* <!-- Start:: row-1 --> */}

			<Row>
				<Col xl={6}>
					<ShowCode title="Responsive image" customCardClass="custom-card" customCardBodyClass="" reactCode={image5}>
						<p className="card-title mb-3">Use <code> .img-fluid </code>class to the img tag to get responsive image.</p>
						<div className="text-center">
							<BaseImage src="/build/assets/images/media/media-48.jpg" className="img-fluid" alt="..." />
						</div>
					</ShowCode>
				</Col>
				<Col xl={6}>
					<ShowCode title="Image With Radius" customCardClass="custom-card" customCardBodyClass="" reactCode={image4}>
						<p className="card-title mb-3">Use <code>.rounded</code> class along with <code>.img-fluid</code> to get border radius.</p>
						<div className="text-center">
							<BaseImage src="/build/assets/images/media/media-49.jpg" className="img-fluid rounded" alt="..." />
						</div>
					</ShowCode>
				</Col>
				<Col xl={6}>
					<ShowCode title="Rounded Image" customCardClass="custom-card" customCardBodyClass="" reactCode={image6}>
						<p className="card-title mb-3">Use <code>.rounded-pill</code> class to <code>img</code> tag to get rounded image.</p>
						<div className="text-center">
							<BaseImage src="/build/assets/images/media/media-50.jpg" className="img-fluid rounded-pill" alt="..." />
						</div>
					</ShowCode>
				</Col>
				<Col xl={6}>
					<ShowCode title="Image Left Align" customCardClass="custom-card" customCardBodyClass="" reactCode={image3}>
						<p className="card-title mb-3">Use <code>.float-start</code> class to <code>img</code> tag to get left align image.</p>
						<BaseImage className="rounded float-start" src="/build/assets/images/media/media-53.jpg" alt="..." />
					</ShowCode>
				</Col>
				<Col xl={6}>
					<ShowCode title="Image Center Align" customCardClass="custom-card" customCardBodyClass="" reactCode={image1}>
						<BaseImage className="rounded mx-auto d-block" src="/build/assets/images/media/media-55.jpg" alt="..." />
					</ShowCode>
				</Col>
				<Col xl={6}>
					<ShowCode title="Image Right Align" customCardClass="custom-card" customCardBodyClass="" reactCode={image2}>
						<BaseImage className="rounded float-end" src="/build/assets/images/media/media-54.jpg" alt="..." />
					</ShowCode>
				</Col>
				<Col xl={6}>
					<ShowCode title="Figures" reactCode={image9} customCardClass="custom-card" customCardBodyClass="d-flex justify-content-between gap-4 card-body flex-wrap pb-4">
						<figure className="figure">
							<BaseImage className="bd-placeholder-img figure-img img-fluid rounded card-img" src="/build/assets/images/media/media-56.jpg" alt="..." />
							<figcaption className="figure-caption mt-2">A caption for the above image.
							</figcaption>
						</figure>
						<figure className="figure float-end">
							<BaseImage className="bd-placeholder-img figure-img img-fluid rounded card-img" src="/build/assets/images/media/media-57.jpg" alt="..." />
							<figcaption className="figure-caption text-end mt-2">A caption for the above image.
							</figcaption>
						</figure>
					</ShowCode>
				</Col>
				<Col xl={3}>
					<ShowCode title="Image Thumbnail" customCardClass="custom-card" customCardBodyClass="" reactCode={image7}>
						<p className="card-title mb-3">Use <code> .img-thumbnail </code>to give an image a rounded 1px border.</p>
						<div className="text-center">
							<BaseImage src="/build/assets/images/media/media-51.jpg" className="img-thumbnail" alt="..." />
						</div>
					</ShowCode>
				</Col>
				<Col xl={3}>
					<ShowCode title="Rounded Thumbnail" customCardClass="custom-card" customCardBodyClass="" reactCode={image8}>
						<p className="card-title mb-3">Use <code> .rounded-pill </code>along with <code> .img-thummbnail </code> to get radius.</p>
						<div className="text-center">
							<BaseImage src="/build/assets/images/media/media-52.jpg" className="img-thumbnail rounded-pill" alt="..." />
						</div>
					</ShowCode>
				</Col>
			</Row>

			{/* <!-- End:: row-1 --> */}

		</Fragment>
	)
};
// Assign layout
ImagesFigures.layout = (page) => <MainLayout>{page}</MainLayout>;
export default ImagesFigures;
