// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/applications/full-calendar/full-calendar.jsx


import React, { Fragment, useEffect, useRef, useState } from "react";
import listPlugin from "@fullcalendar/list";
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin, { Draggable } from '@fullcalendar/interaction';
import SimpleBar from "simplebar-react";
import { Card, Col, Form, Modal, Row } from "react-bootstrap";
import Pageheader from "../../../shared/layouts-components/pageheader/pageheader";
import SpkBadge from "../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-badge";
import SpkButton from "../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import SpkSelect from "../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import SpkDatepickr from "../../../shared/@spk-reusable-components/reusable-plugins/spk-datepicker";
import MainLayout from "@/Layouts/layout";
import BaseLink from "../../../shared/layouts-components/baselink/baselink";
import { Head } from "@inertiajs/react";


const Fullcalendar = () => {
    const [dates, setDates] = useState({});
    const handleDateChange = (key, date) => {
        if (date) {
            setDates((prevDates) => ({
                ...prevDates,
                [key]: date,
            }));
        } else {
            setDates((prevDates) => {
                const { [key]: removedKey, ...rest } = prevDates;
                return rest;
            });
        }
    };
    let eventGuid = 0;
    const todayStr = new Date().toISOString().replace(/T.*$/, ""); // YYYY-MM-DD of today
    const INITIAL_EVENTS = [
        {
            id: createEventId(),
            title: "Meeting",
            start: todayStr,
        },
        {
            id: createEventId(),
            title: "Meeting Time",
            start: todayStr + "T16:00:00",
        },
        {
            title: "Rendezvous",
            start: getDate("YEAR-MONTH-07"),
            end: getDate("YEAR-MONTH-10"),
          },
    ];

    function createEventId() {
        return String(eventGuid++);
    }
    const initialstate1 = {
        calendarEvents: [
            {
                title: "Atlanta Monster",
                start: new Date("2025-08-04 00:00"),
                id: "1001",
            },
            {
                title: "Atlanta Monster",
                start: new Date("2025-08-04 00:00"),
                id: "1001",
            },
            {
                title: "My Favorite Murder",
                start: new Date("2025-08-05 00:00"),
                id: "1002",
            },
        ],

        events: [
            {
                title: "Calendar Events",
                id: "1",
                bg: "primary",
                bgColor: 'text-primary',
            },
            {
                title: "Birthday Events",
                id: "2",
                bg: "secondary",
                bgColor: 'text-secondary',
            },
            {
                title: "Holiday Calendar",
                id: "3",
                bg: "success",
                bgColor: 'text-success',
            },
            {
                title: "Office Events",
                id: "4",
                bg: "info",
                bgColor: 'text-info',
                border: "border-info-transparent",
            },
            {
                title: "Other Events",
                id: "5",
                bg: "warning",
                bgColor: 'text-warning',
            },
            {
                title: "Festival Events",
                id: "6",
                bg: "danger",
                bgColor: 'text-danger',
            },
            {
                title: "Timeline Events",
                id: "7",
                bg: "teal",
                bgColor: 'text-teal',
            },
        ],
    };
    function getDate(dayString) {
        const today = new Date();
        const year = today.getFullYear().toString();
        let month = (today.getMonth() + 1).toString();

        if (month.length === 1) {
          month = "0" + month;
        }

        return dayString.replace("YEAR", year).replace("MONTH", month);
      }
    const [state] = useState(initialstate1);

    const externalEventsRef = useRef(null);

    useEffect(() => {
        const draggableEl = externalEventsRef.current;
        new Draggable(draggableEl, {
            itemSelector: ".fc-event",
            eventData: function (eventEl) {
                const title = eventEl.getAttribute("title");
                const id = eventEl.getAttribute("data");
                const classValue = eventEl.getAttribute("class");
                return {
                    title: title,
                    id: id,
                    className: classValue,
                };
            },
        });
    }, []);

    function renderEventContent(eventInfo) {
        return (
            <>
                <b>{eventInfo.timeText}</b>
                <i>{eventInfo.event.title}</i>
            </>
        );
    }
    const handleEventClick = (clickInfo) => {
        if (
            window.confirm(
                `Are you sure you want to delete the event '${clickInfo.event.title}'`
            )
        ) {
            clickInfo.event.remove();
        }
    };
    const handleEvents = () => { };

    const handleDateSelect = (selectInfo) => {
        const title = prompt("Please enter a new title for your event");
        const calendarApi = selectInfo.view.calendar;

        calendarApi.unselect();

        if (title) {
            calendarApi.addEvent({
                id: createEventId(),
                title,
                start: selectInfo.startStr,
                end: selectInfo.endStr,
                allDay: selectInfo.allDay,
            });
        }
    };



    const SchoolEvents = [
        {
            title: "Annual School Day",
            date: "02 Mar, 2025",
            description:
                "A celebration of the school year with various events and activities for students and staff.",
            badgeColor: "bg-primary",
        },
        {
            title: "Science Fair",
            date: "17 Mar, 2025",
            description:
                "Students will showcase their science projects. Open to all parents and students.",
            badgeColor: "bg-secondary",
        },
        {
            title: "Parent-Teacher Meeting",
            date: "15 Mar, 2025",
            description:
                "An important event where parents meet teachers to discuss the progress of their children.",
            badgeColor: "bg-warning",
        },
        {
            title: "Spring Break",
            date: "13 Mar,2025",
            description:
                "The students get a break for the spring holidays. No school during this period.",
            badgeColor: "bg-info",
        },
        {
            title: "Holiday Celebrations",
            date: "Due Date",
            description:
                "Celebrating the upcoming national holiday with various cultural activities and festivities.",
            badgeColor: "bg-success",
        },
    ];

    const EventSelect = [
        { value: 'Primary', label: 'Primary' },
        { value: 'Secondary', label: 'Secondary' },
        { value: 'Success', label: 'Success' },
        { value: 'Info', label: 'Info' },
        { value: 'Warning', label: 'Warning' },
        { value: 'Danger', label: 'Danger' },
        { value: 'Teal', label: 'Teal' }
    ]

    //Modal
    const [show, setShow] = useState(false);
    const handleShow = () => setShow(true);
    const handleClose = () => setShow(false);

    return (
        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Applications-Full Calendar" />

            <Pageheader title="Applications" currentpage="Full Calendar" activepage="Full Calendar" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xxl={3}>
                    <Card className="custom-card">
                        <Card.Header className="justify-content-between">
                            <div className="card-title">All Events</div>
                            <button onClick={handleShow} className="btn btn-primary btn-wave" data-bs-toggle="modal"
                                data-bs-target="#addEvent"><i className="ri-add-line align-middle me-1 fw-medium d-inline-block"></i>Create New Event</button>
                        </Card.Header>
                        <Card.Body className="">
                            <div id="external-events" ref={externalEventsRef} className="">
                                {state.events.map((event, index) => (
                                    <div key={index} className={`fc-event fc-h-event fc-daygrid-event fc-daygrid-block-event bg-${event.bg}`}
                                        title={event.title} >
                                        <div className={`fc-event-main text-fixed-white ${event.bgColor}`}>
                                            {event.title}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </Card.Body>
                    </Card>
                    <Card className="custom-card">
                        <Card.Body className="p-0">
                            <div className="p-3">
                                <div className="d-flex align-items-center justify-content-between">
                                    <h6 className="fw-medium mb-0">
                                        Upcoming Events
                                    </h6>
                                    <BaseLink href="#!" className="fs-13 text-muted text-decoration-underline">View All<i className="ti ti-arrow-narrow-right"></i></BaseLink>
                                </div>
                            </div>
                            <SimpleBar className="p-3" id="full-calendar-activity">
                                <ul className="list-unstyled mb-0 fullcalendar-events-activity">
                                    {SchoolEvents.map((event, index) => (
                                        <li key={index}>
                                            <div className="d-flex align-items-center justify-content-between flex-wrap">
                                                <p className="mb-1 fw-medium">{event.title}</p>
                                                <SpkBadge variant="" Customclass={`${event.badgeColor} mb-1`}>{event.date}</SpkBadge>
                                            </div>
                                            <p className="mb-0 text-muted fs-13">{event.description}</p>
                                        </li>
                                    ))}
                                </ul>
                            </SimpleBar>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xxl={9}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Full Calendar</div>
                        </Card.Header>
                        <Card.Body>
                            <div id='calendar'>
                                <FullCalendar plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin, listPlugin]}
                                    headerToolbar={{ left: "prev,next today", center: "title", right: "dayGridMonth,timeGridWeek,timeGridDay,listWeek" }}
                                    initialView="dayGridMonth" editable={true} selectable={true} selectMirror={true} dayMaxEvents={true}
                                    initialEvents={INITIAL_EVENTS} select={handleDateSelect} eventContent={renderEventContent} eventClick={handleEventClick}
                                    eventsSet={handleEvents}
                                />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!-- Add Event Modal --> */}

            <Modal show={show} onHide={handleClose} className="fade" id="addEvent" tabIndex={-1} aria-labelledby="addEventLabel" aria-hidden="true">
                <Modal.Header>
                    <h6 className="modal-title" id="addEventLabel1">Add Event</h6>
                    <SpkButton Buttonvariant="" Buttontype="button" onClickfunc={handleClose} Customclass="btn-close" data-bs-dismiss="modal" aria-label="Close"></SpkButton>
                </Modal.Header>
                <Modal.Body>
                    <Row className="gy-3">
                        <Col md={12}>
                            <div className="form-group">
                                <Form.Label className="" htmlFor="eventType">Event Type:</Form.Label>
                                <SpkSelect name="state" option={EventSelect} mainClass="basic-multi-select " menuplacement='auto' classNameprefix="Select2" defaultvalue={[EventSelect[0]]} />
                            </div>
                        </Col>
                        <Col md={12}>
                            <div className="form-group">
                                <Form.Label className="" htmlFor="eventName">Event Name:</Form.Label>
                                <Form.Control type="text" className="" placeholder="Enter event" id="eventName" />
                            </div>
                        </Col>
                        <Col md={6}>
                            <div className="form-group">
                                <Form.Label className="" htmlFor="fromDate">From:</Form.Label>
                                <SpkDatepickr className="form-control" dateFormat="yy/MM/dd" selected={dates["FromDate"] ? new Date(dates["FromDate"]) : null} onChange={(date) => handleDateChange("FromDate", date)} placeholderText='From Date' />
                            </div>
                        </Col>
                        <Col md={6}>
                            <div className="form-group custom-calendar">
                                <Form.Label className="" htmlFor="toDate">To:</Form.Label><br></br>
                                <SpkDatepickr className="form-control" dateFormat="yy/MM/dd" selected={dates["ToDate"] ? new Date(dates["ToDate"]) : null} onChange={(date) => handleDateChange("ToDate", date)} placeholderText='To Date' />

                            </div>
                        </Col>
                        <Col xl={12}>
                            <div className="form-group">
                                <Form.Label className="" htmlFor="description">Description:</Form.Label>
                                <Form.Control as="textarea" className="" id="event-description" rows={3} />
                            </div>
                        </Col>
                    </Row>
                </Modal.Body>
                <Modal.Footer>
                    <SpkButton Buttonvariant="primary" Buttontype="button" onClickfunc={handleClose} Customclass="btn">Add Event</SpkButton>
                </Modal.Footer>
            </Modal>

            {/* <!-- Add Event Modal --> */}

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
Fullcalendar.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Fullcalendar;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/applications/full-calendar.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import { onMount } from "svelte";
    import FullCalendar from "svelte-fullcalendar/src/FullCalendar.svelte";
    import timeGridPlugin from "@fullcalendar/timegrid";
    import listPlugin from "@fullcalendar/list";
    import dayGridPlugin from "@fullcalendar/daygrid";
    import CalendarEventsList from "@/shared/data/applications/calender";
    import interactionPlugin, { Draggable } from "@fullcalendar/interaction";
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        Col,
        Input,
        Label,
        Modal,
        ModalBody,
        ModalFooter,
        ModalHeader,
        Row,
    } from "@sveltestrap/sveltestrap";
    import SpkBadge from "@/shared/@spk/uielements/badge/SpkBadge.svelte";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import Select from "svelte-select";

    let eventGuid = 0;
    function createEventId() {
        return String(eventGuid++);
    }

    let options = {
        dateClick: handleDateClick,
        eventClick: handleEventClick,
        eventDrop: handleEventDrop,
        plugins: [dayGridPlugin, interactionPlugin, timeGridPlugin, listPlugin],
        droppable: true,
        editable: true,
        events: CalendarEventsList.events,
        dayMaxEvents: true,
        headerToolbar: {
            left: "prev,next today",
            center: "title",
            right: "dayGridMonth,dayGridWeek,dayGridDay,listWeek",
        },
        weekends: true,
    };
    let calendarComponentRef;
    let eventData$ = [
        {
            title: "Calendar Events",
            id: "1",
            bg: "primary",
            bgColor: "text-primary",
        },
        {
            title: "Birthday Events",
            id: "2",
            bg: "secondary",
            bgColor: "text-secondary",
        },
        {
            title: "Holiday Calendar",
            id: "3",
            bg: "success",
            bgColor: "text-success",
        },
        {
            title: "Office Events",
            id: "4",
            bg: "info",
            bgColor: "text-info",
            border: "border-info-transparent",
        },
        {
            title: "Other Events",
            id: "5",
            bg: "warning",
            bgColor: "text-warning",
        },
        {
            title: "Festival Events",
            id: "6",
            bg: "danger",
            bgColor: "text-danger",
        },
        {
            title: "Timeline Events",
            id: "7",
            bg: "teal",
            bgColor: "text-teal",
        },
    ];

    // function handleDateClick(event) {
    //     const title = prompt("Please enter a new title for your event");
    //     if (title) {
    //         const newEvent = {
    //             id: createEventId(),
    //             title,
    //             start: event.date,
    //             allDay: event.allDay,
    //         };

    //         options.events = [...options.events, newEvent];
    //         event.view.calendar.addEvent(newEvent);
    //     }
    // }

    // function handleEventClick(info) {
    //     if (
    //         window.confirm(
    //             `Are you sure you want to delete the event '${info.event.title}'?`,
    //         )
    //     ) {
    //         options.events = options.events.filter(
    //             (event) => event.id !== info.event.id,
    //         );
    //         info.event.remove();
    //     }
    // }

    function handleEventDrop(info) {
        const updatedEvent = info.event;

        options.events = options.events.map((event) => {
            if (event.id === updatedEvent.id) {
                return {
                    ...event,
                    start: updatedEvent.start,
                    end: updatedEvent.end,
                };
            }
            return event;
        });

        calendarComponentRef.getAPI().refetchEvents();
    }

    let mounted = false;

    onMount(() => {
        const draggableEl = document.getElementById("external-events");
        const { events } = options;
        if (draggableEl) {
            new Draggable(draggableEl, {
                itemSelector: ".fc-event",
                eventData: function (eventEl) {
                    const title = eventEl.getAttribute("title");
                    const id = createEventId();
                    const classValue = eventEl.getAttribute("class");
                    return {
                        title: title,
                        id: id,
                        className: classValue,
                    };
                },
            });
        }
        mounted = true;
    });

    const SchoolEvents = [
        {
            title: "Annual School Day",
            date: "02 Mar, 2025",
            description:
                "A celebration of the school year with various events and activities for students and staff.",
            badgeColor: "bg-primary",
        },
        {
            title: "Science Fair",
            date: "17 Mar, 2025",
            description:
                "Students will showcase their science projects. Open to all parents and students.",
            badgeColor: "bg-secondary",
        },
        {
            title: "Parent-Teacher Meeting",
            date: "15 Mar, 2025",
            description:
                "An important event where parents meet teachers to discuss the progress of their children.",
            badgeColor: "bg-warning",
        },
        {
            title: "Spring Break",
            date: "13 Mar,2025",
            description:
                "The students get a break for the spring holidays. No school during this period.",
            badgeColor: "bg-info",
        },
        {
            title: "Holiday Celebrations",
            date: "Due Date",
            description:
                "Celebrating the upcoming national holiday with various cultural activities and festivities.",
            badgeColor: "bg-success",
        },
    ];

    const EventSelect = [
        { value: "bg-primary", label: "Primary" },
        { value: "bg-secondary", label: "Secondary" },
        { value: "bg-success", label: "Success" },
        { value: "bg-info", label: "Info" },
        { value: "bg-warning", label: "Warning" },
        { value: "bg-danger", label: "Danger" },
        { value: "bg-teal", label: "Teal" },
    ];

    let selectedDate = null;

    // Modal form fields
    let eventTitle = "";
    let eventType = EventSelect[0];
    let fromDate = "";
    let toDate = "";
    let description = "";
    // THIS is the variable to store the dateClick info
    let modalInfo = null;

    function handleDateClick(info) {
        selectedDate = info.date;
        show = true;
        modalInfo = info;
    }

    function addEvent() {
        if (!eventTitle) return;

        // Use date from modal or clicked cell
        const startDate = fromDate || modalInfo.date;
        const endDate = toDate || modalInfo.date;

        const today = new Date();
        today.setHours(0, 0, 0, 0); // reset time for comparison

        const start = new Date(startDate);
        const end = new Date(endDate);

        // Disable past dates
        if (start < today || end < today) {
            alert("You can only create events for today or future dates.");
            return;
        }

        // Create event object
        const newEvent = {
            id: createEventId(),
            title: eventTitle,
            start: startDate,
            end: endDate,
            allDay: true,
            className: eventType.value,
            borderColor: mapEventColor(eventType.value),    
        };

        console.log(newEvent)

        // Add event to calendar
        modalInfo.view.calendar.addEvent(newEvent);

        // Update local events state
        options.events = [...options.events, newEvent];

        // Reset modal
        eventTitle = "";
        eventType = EventSelect[0];
        fromDate = "";
        toDate = "";
        description = "";
        show = false;
    }

    function mapEventColor(type) {
        switch (type) {
            case "Primary":
                return "#0d6efd";
            case "Secondary":
                return "#6c757d";
            case "Success":
                return "#198754";
            case "Info":
                return "#0dcaf0";
            case "Warning":
                return "#ffc107";
            case "Danger":
                return "#dc3545";
            case "Teal":
                return "#20c997";
            default:
                return "#0d6efd";
        }
    }

    function handleEventClick(info) {
        if (
            window.confirm(
                `Are you sure you want to delete the event '${info.event.title}'?`,
            )
        ) {
            options.events = options.events.filter(
                (event) => event.id !== info.event.id,
            );
            info.event.remove();
        }
    }

    let show = false;

    const handleShow = () => {
        show = true;
    };

    const handleClose = () => {
        show = false;
    };
</script>

<!-- Page Title -->
<svelte:head>
    <title>FullCalendar | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Full Calendar"
    activepage="Applications"
    page="Full Calendar"
/>

<!-- Start::row-1 -->

<Row>
    <Col xxl={3}>
        <Card class="custom-card">
            <CardHeader class="justify-content-between">
                <div class="card-title">All Events</div>
                <button
                    class="btn btn-primary btn-wave"
                    onclick={handleShow}
                    data-bs-toggle="modal"
                    data-bs-target="#addEvent"
                    ><i
                        class="ri-add-line align-middle me-1 fw-medium d-inline-block"
                    ></i>Create New Event</button
                >
            </CardHeader>
            <CardBody class="">
                <div id="external-events" class="">
                    {#each eventData$ as { title, id, bg, bgColor }}
                        <div
                            class={`fc-event fc-h-event fc-daygrid-event fc-daygrid-block-event bg-${bg}`}
                            data-id={id}
                            {title}
                        >
                            <div
                                class={`fc-event-main text-fixed-white ${bgColor}`}
                            >
                                {title}
                            </div>
                        </div>
                    {/each}
                </div>
            </CardBody>
        </Card>
        <Card class="custom-card">
            <CardBody class="p-0">
                <div class="p-3">
                    <div
                        class="d-flex align-items-center justify-content-between"
                    >
                        <h6 class="fw-medium mb-0">Upcoming Events</h6>
                        <a
                            href="#!"
                            class="fs-13 text-muted text-decoration-underline"
                            >View All<i class="ti ti-arrow-narrow-right"></i></a
                        >
                    </div>
                </div>
                <div
                    class="p-3 overflow-y-scroll customfullcalederheight"
                    id="full-calendar-activity "
                >
                    <ul class="list-unstyled mb-0 fullcalendar-events-activity">
                        {#each SchoolEvents as event}
                            <li>
                                <div
                                    class="d-flex align-items-center justify-content-between flex-wrap"
                                >
                                    <p class="mb-1 fw-medium">{event.title}</p>
                                    <SpkBadge
                                        Color=""
                                        CustomClass={`${event.badgeColor} mb-1`}
                                        >{event.date}</SpkBadge
                                    >
                                </div>
                                <p class="mb-0 text-muted fs-13">
                                    {event.description}
                                </p>
                            </li>
                        {/each}
                    </ul>
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xxl={9}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Full Calendar</div>
            </CardHeader>
            <CardBody>
                <div id="calendar">
                    {#if mounted}
                        <FullCalendar
                            bind:this={calendarComponentRef}
                            {options}
                        />
                    {/if}
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!-- Add Event Modal -->

<!-- Add Event Modal -->

<Modal isOpen={show} toggle={() => (show = false)}>
    <ModalHeader toggle={() => (show = false)}>Add Event</ModalHeader>
    <ModalBody>
        <div class="form-group">
            <Label>Event Type:</Label>
            <Select
                items={EventSelect}
                bind:value={eventType}
                showChevron={true}
                clearable={false}
            />
        </div>
        <div class="form-group">
            <Label>Event Name:</Label>
            <Input
                type="text"
                bind:value={eventTitle}
                placeholder="Enter event"
            />
        </div>
        <div class="form-group">
            <Label>From:</Label>
            <Input type="date" bind:value={fromDate} />
        </div>
        <div class="form-group">
            <Label>To:</Label>
            <Input type="date" bind:value={toDate} />
        </div>
        <div class="form-group">
            <Label>Description:</Label>
            <Input type="textarea" bind:value={description} rows={3} />
        </div>
    </ModalBody>
    <ModalFooter>
        <SpkButton color="primary" onclickfunc={addEvent}>Add Event</SpkButton>
    </ModalFooter>
</Modal>

<!-- Add Event Modal -->
