// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/range-area-chart/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
    import {
        Basicrangeoptions,
        Rangecombooptions,
    } from "$lib/data/charts/apexcharts/rangechartdata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>RangeAreaChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Range Area Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Range Area Charts"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Basic Range Area Chart</div>
            </CardHeader>
            <CardBody>
                <div id="rangearea-basic">
                    <Spkapexcharts
                        options={Basicrangeoptions}
                        id="rangearea-basic"
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Combo Range Area Chart</div>
            </CardHeader>
            <CardBody>
                <div id="rangearea-combo">
                    <Spkapexcharts
                        options={Rangecombooptions}
                        id="rangearea-combo"
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/range-area-chart/range-area-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import { Basicrangeoptions, Basicrangeseries, Rangecombooptions, Rangecomboseries } from "../../../../shared/data/charts/apexcharts/rangeareadata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const RangeAreaChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Apex Range Area Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Range Area Charts" activepage="Apex Range Area Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Basic Range Area Chart
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <div id="rangearea-basic">
                                <Spkapexcharts chartOptions={Basicrangeoptions} chartSeries={Basicrangeseries} type="rangeArea" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Combo Range Area Chart
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <div id="rangearea-combo">
                                <Spkapexcharts chartOptions={Rangecombooptions} chartSeries={Rangecomboseries} type="rangeArea" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
RangeAreaChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default RangeAreaChart;
