// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/dashboards-reusable/projects/spk-dashboardcard.tsx
import React, { Fragment, type JSX } from "react";
import { Card } from "react-bootstrap";

interface Project {
  title: string;
  price: string | number;
  svgColor: string;
  svgIcon: JSX.Element;
}

interface SpkDashboardCardProps {
  project: Project; 
  cardClass?: string;
  bodyClass?: string;
}

const SpkDashboardCard: React.FC<SpkDashboardCardProps> = ({ project, cardClass, bodyClass }) => {

  return (
    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className={bodyClass}>
          <div className="d-flex align-items-start gap-3">
            <div className="lh-1">
              <span className={`avatar avatar-md bg-${project.svgColor}-transparent svg-${project.svgColor}`}>
                {project.svgIcon}
              </span>
            </div>
            <div>
              <span className="d-block text-muted mb-1">{project.title}</span>
              <h5 className="fw-semibold mb-0">{project.price}</h5>
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkDashboardCard;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/dashboards-reusable/projects/spk-dashboardcard.svelte
<script>
    import { Card, CardBody } from "@sveltestrap/sveltestrap";
    export let project = {};
    export let cardClass = "";
    export let bodyClass = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class={bodyClass}>
        <div class="d-flex align-items-start gap-3">
            <div class="lh-1">
                <span
                    class={`avatar avatar-md bg-${project.svgColor}-transparent svg-${project.svgColor}`}
                >
                    {@html project.svgIcon}
                </span>
            </div>
            <div>
                <span class="d-block text-muted mb-1">{project.title}</span>
                <h5 class="fw-semibold mb-0">{project.price}</h5>
            </div>
        </div>
    </CardBody>
</Card>
