// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/general/utilities/borders.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import ShowCode from "@/components/showcode/ShowCode.svelte";
    import {
        border1,
        border2,
        border3,
        border4,
        border5,
        border6,
        border7,
        border8,
    } from "@/shared/data/prism-code/utilitiesprism";
    import { Col, Image, Row } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>Borders | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader homepage="Borders" activepage="Utilities" page="Borders" />
<!-- Page Header Close -->

<!-- {/* Start:: row-1 */} -->

<Row>
    <Col xl={12}>
        <ShowCode
            title="Borders"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={border1}
        >
            <span class="border border-container"></span>
            <span class="border-top border-container"></span>
            <span class="border-end border-container"></span>
            <span class="border-bottom border-container"></span>
            <span class="border-start border-container"></span>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode
            title="Remove borders"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={border2}
        >
            <span class="border-0 border-container"></span>
            <span class="border border-top-0 border-container"></span>
            <span class="border border-end-0 border-container"></span>
            <span class="border border-bottom-0 border-container"></span>
            <span class="border border-start-0 border-container"></span>
        </ShowCode>
    </Col>
</Row>

<!-- {/* End:: row-1 */} -->

<!-- {/* Start:: row-2 */} -->

<Row>
    <Col xl={12}>
        <ShowCode
            title="Border Widths"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={border3}
        >
            <span class="border border-container border-1"></span>
            <span class="border border-container border-2"></span>
            <span class="border border-container border-3"></span>
            <span class="border border-container border-4"></span>
            <span class="border border-container border-5"></span>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode
            title="Border colors"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={border4}
        >
            <span class="border border-container border-primary"></span>
            <span class="border border-container border-secondary"></span>
            <span class="border border-container border-success"></span>
            <span class="border border-container border-danger"></span>
            <span class="border border-container border-warning"></span>
            <span class="border border-container border-info"></span>
            <span class="border border-container border-light"></span>
            <span class="border border-container border-dark"></span>
            <span class="border border-container border-white"></span>
        </ShowCode>
    </Col>
</Row>

<!-- {/* End:: row-2 */} -->

<!-- {/* Start:: row-4 */} -->

<Row>
    <Col xl={12}>
        <ShowCode
            title="Border color Styling"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={border5}
        >
            <div class="mb-4">
                <label for="exampleFormControlInput1" class="form-label"
                    >Email address</label
                >
                <input
                    type="email"
                    class="form-control border-success"
                    id="exampleFormControlInput1"
                    placeholder="name@example.com"
                />
            </div>
            <div class="h4 pb-3 mb-4 text-danger border-bottom border-danger">
                Below Shows Danger Border
            </div>
            <div
                class="p-3 bg-info bg-opacity-10 border border-info border-start-0 rounded-end mb-1"
            >
                Customizing borders with background colors
            </div>
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode
            title="Border with opacity"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={border6}
        >
            <div class="border border-success p-2 mb-2">
                This is default success border
            </div>
            <div class="border border-success p-2 mb-2 border-opacity-75">
                This is 75% opacity success border
            </div>
            <div class="border border-success p-2 mb-2 border-opacity-50">
                This is 50% opacity success border
            </div>
            <div class="border border-success p-2 mb-2 border-opacity-25">
                This is 25% opacity success border
            </div>
            <div class="border border-success p-2 border-opacity-10">
                This is 10% opacity success border
            </div>
        </ShowCode>
    </Col>
</Row>

<!-- {/* End:: row-4 */} -->

<!-- {/* Start:: row-3 */} -->

<Row>
    <Col xl={12}>
        <ShowCode
            title="Border Radius"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={border7}
        >
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img rounded"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img rounded-top"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img rounded-end"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img rounded-bottom"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img rounded-start"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img rounded-circle"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img  rounded-pill"
                alt="..."
            />
        </ShowCode>
    </Col>
    <Col xl={12}>
        <ShowCode
            title="Sizes"
            customCardClass="custom-card"
            customCardBodyClass=""
            svelteCode={border8}
        >
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img bd-placeholder-img rounded-0"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img bd-placeholder-img rounded-1"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img bd-placeholder-img rounded-2"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img bd-placeholder-img rounded-3"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img bd-placeholder-img rounded-4"
                alt="..."
            />
            <Image
                src="../../images/media/media-58.jpg"
                class="bd-placeholder-img bd-placeholder-img rounded-5"
                alt="..."
            />
        </ShowCode>
    </Col>
</Row>

<!-- /* End:: row-3 */ -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/general/utilities/borders/borders.jsx

import { border1, border2, border3, border4, border5, border6, border7, border8 } from "../../../../shared/data/prism-code/utilities-prism";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import ShowCode from "../../../../shared/layouts-components/showcode/showcode";
import React, { Fragment } from "react";
import { Col, Image, Row } from "react-bootstrap";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";

const Borders = () => {

    return (
        <Fragment>

            <Head title={"Borders"} />

            <Pageheader title="Utilities" currentpage="Borders" activepage="Borders" />

            {/* <!-- Start:: row-1 --> */}

            <Row>
                <Col xl={12}>
                    <ShowCode title="Borders" customCardClass="custom-card" customCardBodyClass="" reactCode={border1}>
                        <span className="border border-container"></span>
                        <span className="border-top border-container"></span>
                        <span className="border-end border-container"></span>
                        <span className="border-bottom border-container"></span>
                        <span className="border-start border-container"></span>
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Remove borders" customCardClass="custom-card" customCardBodyClass="" reactCode={border2}>
                        <span className="border-0 border-container"></span>
                        <span className="border border-top-0 border-container"></span>
                        <span className="border border-end-0 border-container"></span>
                        <span className="border border-bottom-0 border-container"></span>
                        <span className="border border-start-0 border-container"></span>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-1 --> */}

            {/* <!-- Start:: row-2 --> */}

            <Row>
                <Col xl={12}>
                    <ShowCode title="Border Widths" customCardClass="custom-card" customCardBodyClass="" reactCode={border3}>
                        <span className="border border-container border-1"></span>
                        <span className="border border-container border-2"></span>
                        <span className="border border-container border-3"></span>
                        <span className="border border-container border-4"></span>
                        <span className="border border-container border-5"></span>
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Border colors" customCardClass="custom-card" customCardBodyClass="" reactCode={border4}>
                        <span className="border border-container border-primary"></span>
                        <span className="border border-container border-secondary"></span>
                        <span className="border border-container border-success"></span>
                        <span className="border border-container border-danger"></span>
                        <span className="border border-container border-warning"></span>
                        <span className="border border-container border-info"></span>
                        <span className="border border-container border-light"></span>
                        <span className="border border-container border-dark"></span>
                        <span className="border border-container border-white"></span>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-2 --> */}

            {/* <!-- Start:: row-4 --> */}

            <Row>
                <Col xl={12}>
                    <ShowCode title="Border color Styling" customCardClass="custom-card" customCardBodyClass="" reactCode={border5}>
                        <div className="mb-4">
                            <label htmlFor="exampleFormControlInput1" className="form-label">Email
                                address</label>
                            <input type="email" className="form-control border-success"
                                id="exampleFormControlInput1" placeholder="name@example.com" />
                        </div>
                        <div className="h4 pb-3 mb-4 text-danger border-bottom border-danger">
                            Below Shows Danger Border
                        </div>
                        <div
                            className="p-3 bg-info bg-opacity-10 border border-info border-start-0 rounded-end mb-1">
                            Customizing borders with background colors
                        </div>
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Border with opacity" customCardClass="custom-card" customCardBodyClass="" reactCode={border6}>
                        <div className="border border-success p-2 mb-2">This is default success border</div>
                        <div className="border border-success p-2 mb-2 border-opacity-75">This is 75%
                            opacity
                            success border
                        </div>
                        <div className="border border-success p-2 mb-2 border-opacity-50">This is 50%
                            opacity
                            success border
                        </div>
                        <div className="border border-success p-2 mb-2 border-opacity-25">This is 25%
                            opacity
                            success border
                        </div>
                        <div className="border border-success p-2 border-opacity-10">This is 10% opacity
                            success
                            border
                        </div>
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-4 --> */}

            {/* <!-- Start:: row-3 --> */}

            <Row>
                <Col xl={12}>
                    <ShowCode title="Border Radius" customCardClass="custom-card" customCardBodyClass="" reactCode={border7}>
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img rounded" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img rounded-top" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img rounded-end" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img rounded-bottom" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img rounded-start" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img rounded-circle" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img  rounded-pill" alt="..." />
                    </ShowCode>
                </Col>
                <Col xl={12}>
                    <ShowCode title="Sizes" customCardClass="custom-card" customCardBodyClass="" reactCode={border8}>
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img bd-placeholder-img rounded-0" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img bd-placeholder-img rounded-1" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img bd-placeholder-img rounded-2" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img bd-placeholder-img rounded-3" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img bd-placeholder-img rounded-4" alt="..." />
                        <BaseImage src="/build/assets/images/media/media-58.jpg" className="bd-placeholder-img bd-placeholder-img rounded-5" alt="..." />
                    </ShowCode>
                </Col>
            </Row>

            {/* <!-- End:: row-3 --> */}

        </Fragment>
    )
};
// Assign layout
Borders.layout = (page) => <MainLayout>{page}</MainLayout>;
export default Borders;
