// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/timeline-chart/+page.svelte

<script lang="ts">
        import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import * as timelinedata from  "$lib/data/charts/apexcharts/timelinechartsdata";
    import {
        Card,
        CardBody,
        CardHeader,
        CardTitle,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>TimelineChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->


<!-- Page Header -->
<Pageheader
    homepage="Timeline Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Timeline Charts"
/>
<!-- Page Header Close -->

 <!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Basic Timeline Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="timeline-basic">
                                <Spkapexcharts options={timelinedata.Timelineoptions} id="timeline-basic" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Multiple Colored Timeline Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="timeline-colors">
                                <Spkapexcharts options={timelinedata.Timecoloroptions} id="timeline-colors" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Multi Series Timeline Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="timeline-multi">
                                <Spkapexcharts options={timelinedata.Timemultioptions}  id="timeline-multi"  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Advanced Timeline Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="timeline-advanced">
                                <Spkapexcharts options={timelinedata.Timeadvanceoptions} id="timeline-advanced"/>
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Timeline-Grouped Rows</div>
                        </CardHeader>
                        <CardBody>
                            <div id="timeline-grouped">
                                <Spkapexcharts options={timelinedata.Timegroupoptions} id="timeline-grouped"  />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <div class="card-title">Dumbbell Chart</div>
                        </CardHeader>
                        <CardBody>
                            <div id="dumbbell-chart">
                                <Spkapexcharts options={timelinedata.Timedumbeloptions} id="dumbbell-chart" />
                            </div>
                        </CardBody>
                    </Card>
                </Col>
            </Row>

             <!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/timeline-chart/timeline-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import * as timelinedata from "../../../../shared/data/charts/apexcharts/timelinechartdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const TimelineChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Apex Timeline Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Timeline Charts" activepage="Apex Timeline Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Basic Timeline Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="timeline-basic">
                                <Spkapexcharts chartOptions={timelinedata.Timelineoptions} chartSeries={timelinedata.Timelineseries} type="rangeBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Multiple Colored Timeline Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="timeline-colors">
                                <Spkapexcharts chartOptions={timelinedata.Timecoloroptions} chartSeries={timelinedata.Timecolorseries} type="rangeBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Multi Series Timeline Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="timeline-multi">
                                <Spkapexcharts chartOptions={timelinedata.Timemultioptions} chartSeries={timelinedata.Timemultiseries} type="rangeBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Advanced Timeline Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="timeline-advanced">
                                <Spkapexcharts chartOptions={timelinedata.Timeadvanceoptions} chartSeries={timelinedata.Timeadvanceseries} type="rangeBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Timeline-Grouped Rows</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="timeline-grouped">
                                <Spkapexcharts chartOptions={timelinedata.Timegroupoptions} chartSeries={timelinedata.Timegroupseries} type="rangeBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">Dumbbell Chart</div>
                        </Card.Header>
                        <Card.Body>
                            <div id="dumbbell-chart">
                                <Spkapexcharts chartOptions={timelinedata.Timedumbeloptions} chartSeries={timelinedata.Timedumbelseries} type="rangeBar" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
TimelineChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default TimelineChart;
