// Dashboard Template/vyzor-svelte/final/src/lib/@spk/reusable-pages/spk-friendscard.svelte
<script lang="ts">
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";
    import SpkDropdown from "../uielements/Dropdown/SpkDropdown.svelte";
    import { dropdown1 } from "$lib/data/pages/profiledata";
    import SpkButton from "../uielements/Button/SpkButton.svelte";

    interface Types {
        name?: string;
        mail?: string;
        imgSrc?: string;
    }

    export let obj: Types = {};
    export let cardClass: string = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class="p-4 text-center">
        <SpkDropdown
            CustomClass="profile-friends-actions"
            Color="light"
            option={dropdown1}
            ToggleClass="tn btn-icon rounded-circle border no-caret"
            Caret={false}
            parent={`<i class="fe fe-more-vertical"></i>`}
        />
        <div class="lh-1 mb-2">
            <span class="avatar avatar-xxl avatar-rounded">
                <Image src={obj.imgSrc} alt="" />
            </span>
        </div>
        <div class="mb-3">
            <span class="d-block fw-semibold">{obj.name}</span>
            <span class="text-muted fs-13">{obj.mail}</span>
        </div>
        <div class="btn-list">
            <SpkButton
                color=""
                customClass="btn btn-icon btn-facebook btn-wave rounded-circle waves-effect waves-light"
            >
                <i class="ri-facebook-line"></i>
            </SpkButton>
            <SpkButton
                color=""
                customClass="btn btn-icon btn-twitter btn-wave rounded-circle waves-effect waves-light"
            >
                <i class="ri-twitter-x-line"></i>
            </SpkButton>
            <SpkButton
                color=""
                customClass="btn btn-icon btn-instagram btn-wave rounded-circle waves-effect waves-light"
            >
                <i class="ri-instagram-line"></i>
            </SpkButton>
        </div>
    </CardBody>
</Card>

// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/reusable-pages/spk-friendscard.tsx

import { Fragment } from "react"
import SpkDropdown from "../general-reusable/reusable-uielements/spk-dropdown";
import { Card, Dropdown, Image } from "react-bootstrap";
import SpkButton from "../general-reusable/reusable-uielements/spk-buttons";

interface Types {
    name?: string;
    mail?: string;
    imgSrc:string
}

interface SpkFriendscardProps {
    obj: Types;
    cardClass?: string;
}

const SpkFriendscard: React.FC<SpkFriendscardProps> = ({ obj, cardClass }) => {

    return (
        <Fragment>
            <Card className={`custom-card ${cardClass}`}>
                <Card.Body className="p-4 text-center">
                    <SpkDropdown Id="dropdownMenuButton1" Customclass="profile-friends-actions" Togglevariant="light" Menulabel="dropdownMenuButton1" Icon={true} IconClass="fe fe-more-vertical" Customtoggleclass="btn btn-icon rounded-circle border no-caret">
                        <Dropdown.Item as="li" href="#!"><i className="ri-edit-line me-2"></i> Edit</Dropdown.Item>
                        <Dropdown.Item as="li" href="#!"><i className="ri-delete-bin-line me-2"></i> Delete</Dropdown.Item>
                    </SpkDropdown>
                    <div className="lh-1 mb-2">
                        <span className="avatar avatar-xxl avatar-rounded">
                            <Image  src={obj.imgSrc} alt="" />
                        </span>
                    </div>
                    <div className="mb-3">
                        <span className="d-block fw-semibold">{obj.name}</span>
                        <span className="text-muted fs-13">{obj.mail}</span>
                    </div>
                    <div className="btn-list">
                        <SpkButton Buttonvariant="" Customclass="btn btn-icon btn-facebook btn-wave rounded-circle waves-effect waves-light">
                            <i className="ri-facebook-line"></i>
                        </SpkButton>
                        <SpkButton Buttonvariant="" Customclass="btn btn-icon btn-twitter btn-wave rounded-circle waves-effect waves-light">
                            <i className="ri-twitter-x-line"></i>
                        </SpkButton>
                        <SpkButton Buttonvariant="" Customclass="btn btn-icon btn-instagram btn-wave rounded-circle waves-effect waves-light">
                            <i className="ri-instagram-line"></i>
                        </SpkButton>
                    </div>
                </Card.Body>
            </Card>
        </Fragment>
    )
}
export default SpkFriendscard;
