// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/echart-charts/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import * as echartsdata from "$lib/data/charts/echartdata";
    import SpkEChart from "$lib/@spk/charts/SpkEChart.svelte";
    import { Card, CardBody, CardHeader, CardTitle, Col, Row } from "@sveltestrap/sveltestrap";
</script>

<!-- Page Title -->
<svelte:head>
    <title>EchartCharts | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader homepage="Echart Charts" activepage="Charts" page="Echart Charts" />
<!-- Page Header Close -->

<!-- Start::row-1 --> 

            <Row>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Basic Line Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Lineoption} chartId="echart-basic-line" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Smoothed Line Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Smoothoption}  chartId="echart-smoothed-line" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>
                                Basic Area Chart
                            </CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Basicoption}  chartId="echart-area-line" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Stacked Line Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Stackoption}  chartId="echart-stacked-line" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Stacked Area Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Stackareaoption}  chartId="echart-stacked-area" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Step Line Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Stepoption}  chartId="echart-step-line" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Basic Bar Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Baroption}  chartId="echart-bar-basic" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Bar With Background Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Backoption}  chartId="echart-bar-background" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Style For a Single Bar Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Styleoption}  chartId="echart-bar-single" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Water Fall Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Wateroption}  chartId="echart-waterfall" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Bar With Negative Values Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Negativeoption}  chartId="echart-negative-values" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Bar With Labels Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.BarWithLabels}  chartId="echart-bar-labels" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Horizontal Bar Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Horizontaloption}  chartId="echart-bar-horizontal" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Horizontal Stacked Bar Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.HoriStackoption}  chartId="echart-stacked-horizontal" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Pie Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Pieoption} chartId="echart-pie" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Doughnut Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Doughnutoption}  chartId="echart-doughnut" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Basic Scatter Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Scattoption}  chartId="echart-scatter" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Bubble Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Bubbleoption} chartId="echart-bubble" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Candlestick Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Candleoption}  chartId="echart-candlestick" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Basic Radar Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Radaroption}  chartId="echart-basic-radar" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Heatmap Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Heatoption} chartId="echart-heatmap" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Treemap Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Treeoption} chartId="echart-treemap" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Funnel Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Funneloption} chartId="echart-funnel" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Basic Gauge Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Gaugeoption} chartId="echart-gauge-basic" />
                        </CardBody>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card class="custom-card">
                        <CardHeader>
                            <CardTitle>Simple Graph Chart</CardTitle>
                        </CardHeader>
                        <CardBody>
                            <SpkEChart option={echartsdata.Graphoption} chartId="echart-simple-graph" />
                        </CardBody>
                    </Card>
                </Col>
            </Row>

            <!--End::row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/echart-charts/echart-charts.jsx

import MainLayout from "@/Layouts/layout";
import SpkEcharts from "../../../shared/@spk-reusable-components/reusable-plugins/spk-echarts";
import * as echartsdata from "../../../shared/data/charts/echartsdata";
import Pageheader from "../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const EchartCharts = () => {

    return (

        <Fragment>

            <Head title={"Echarts"} />

            <Pageheader title="Charts" currentpage="Echart Charts" activepage="Echart Charts" />

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Line Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Lineoption} chartSeries={echartsdata.Lineseries} id="echart-basic-line" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Smoothed Line Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Smoothoption} chartSeries={echartsdata.Smoothseries} id="echart-smoothed-line" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>
                                Basic Area Chart
                            </Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Basicoption} chartSeries={echartsdata.Basicseries} id="echart-area-line" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Stacked Line Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Stackoption} chartSeries={echartsdata.Stackseries} id="echart-stacked-line" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Stacked Area Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Stackareaoption} chartSeries={echartsdata.Stackareaseries} id="echart-stacked-area" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Step Line Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Stepoption} chartSeries={echartsdata.Stepseries} id="echart-step-line" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Bar Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Baroption} chartSeries={echartsdata.Barseries} id="echart-bar-basic" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Bar With Background Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Backoption} chartSeries={echartsdata.Backseries} id="echart-bar-background" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Style For a Single Bar Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Styleoption} chartSeries={echartsdata.Styleseries} id="echart-bar-single" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Water Fall Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Wateroption} chartSeries={echartsdata.Waterseries} id="echart-waterfall" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Bar With Negative Values Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Negativeoption} chartSeries={echartsdata.Negativeseries} id="echart-negative-values" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Horizontal Bar Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Horizontaloption} chartSeries={echartsdata.Horizontalseries} id="echart-bar-horizontal" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Horizontal Stacked Bar Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.HoriStackoption} chartSeries={echartsdata.HoriStackseries} id="echart-stacked-horizontal" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Pie Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Pieoption} chartSeries={echartsdata.Pieseries} id="echart-pie" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Doughnut Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Doughnutoption} chartSeries={echartsdata.Doughnutseries} id="echart-doughnut" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Scatter Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Scattoption} chartSeries={echartsdata.Scattseries} id="echart-scatter" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Bubble Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Bubbleoption} chartSeries={echartsdata.Bubbleseries} id="echart-bubble" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Candlestick Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Candleoption} chartSeries={echartsdata.Candleseries} id="echart-candlestick" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Radar Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Radaroption} chartSeries={echartsdata.Radarseries} id="echart-basic-radar" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Heatmap Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Heatoption} chartSeries={echartsdata.Heatseries} id="echart-heatmap" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Treemap Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Treeoption} chartSeries={echartsdata.Treeseries} id="echart-treemap" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Funnel Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Funneloption} chartSeries={echartsdata.Funnelseries} id="echart-funnel" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Gauge Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Gaugeoption} chartSeries={echartsdata.Gaugeseries} id="echart-gauge-basic" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Simple Graph Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <SpkEcharts chartOptions={echartsdata.Graphoption} chartSeries={echartsdata.Graphseries} id="echart-simple-graph" mainClass="echart-charts" />
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
EchartCharts.layout = (page) => <MainLayout>{page}</MainLayout>;
export default EchartCharts;
