// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/pie-chart/pie-chart.jsx

import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import { Basicpieoptions, Basicpieseries, Donutoptions, Donutseries, Piechartoptions, Piechartseries, Piegardientoptions, Piegradientseries, Pieimgoptions, Pieimgseries, Piemonooptions, Piemonoseries, Updatedoptions, Updatedseries } from "../../../../shared/data/charts/apexcharts/piechartdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment, useState } from "react";
import { Card, Col, Row } from "react-bootstrap";
import MainLayout from "@/Layouts/layout";


const PieChart = () => {

    const [state, setState] = useState({ series: Updatedseries });

    const appendData = () => {
        const newSeries = [...state.series, Math.floor(Math.random() * 100) + 1];
        setState({ series: newSeries });
    };

    const removeData = () => {
        if (state.series.length > 1) {
            const newSeries = state.series.slice(0, -1);
            setState({ series: newSeries });
        }
    };

    const randomize = () => {
        const newSeries = state.series.map(() => Math.floor(Math.random() * 100) + 1);
        setState({ series: newSeries });
    };

    const reset = () => {
        setState({ series: Updatedseries });
    };

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Pie Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Pie Charts" activepage="Apex Pie Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Pie Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="pie-basic">
                                <Spkapexcharts chartOptions={Basicpieoptions} chartSeries={Basicpieseries} type="pie" width={"100%"} height={300} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Simple Donut Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="donut-simple">
                                <Spkapexcharts chartOptions={Donutoptions} chartSeries={Donutseries} type="donut" width={"100%"} height={300} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Updating Donut Chart</Card.Title>
                        </Card.Header>
                        <div className="card-body mx-auto">
                            <div id="donut-update">
                                <Spkapexcharts chartOptions={Updatedoptions} chartSeries={state.series} type="donut" width={"100%"} height={250} />
                                <div className="text-center mt-4">
                                    <SpkButton Size="sm" Buttonvariant="primary" Customclass="m-1" onClickfunc={appendData}>
                                        + ADD
                                    </SpkButton>
                                    &nbsp;
                                    <SpkButton Size="sm" Buttonvariant="primary" Customclass="m-1" onClickfunc={removeData}>
                                        - REMOVE
                                    </SpkButton>
                                    &nbsp;
                                    <SpkButton Size="sm" Buttonvariant="primary" Customclass="m-1" onClickfunc={randomize}>
                                        RANDOMIZE
                                    </SpkButton>
                                    &nbsp;
                                    <SpkButton Size="sm" Buttonvariant="primary" Customclass="m-1" onClickfunc={reset}>
                                        RESET
                                    </SpkButton>
                                </div>
                            </div>
                        </div>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Monochrome Pie Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="pie-monochrome">
                                <Spkapexcharts chartOptions={Piemonooptions} chartSeries={Piemonoseries} type="pie" width={"100%"} height={310} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Gradient Donut Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="donut-gradient">
                                <Spkapexcharts chartOptions={Piegardientoptions} chartSeries={Piegradientseries} type="donut" width={"100%"} height={300} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>

                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Image Filled Pie Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="pie-image">
                                <Spkapexcharts chartOptions={Pieimgoptions} chartSeries={Pieimgseries} type="pie" width={"100%"} height={300} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Donut Chart With Patterns</Card.Title>
                        </Card.Header>
                        <div className="card-body mx-auto">
                            <div id="donut-pattern">
                                <Spkapexcharts chartOptions={Piechartoptions} chartSeries={Piechartseries} type="donut" width={"100%"} height={250} />
                            </div>
                        </div>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
PieChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default PieChart;

// Dashboard Template/vyzor-svelte/final/src/routes/(common-layout)/charts/apex-charts/pie-chart/+page.svelte
<script lang="ts">
    import Pageheader from "$lib/components/layout-components/page-header/Pageheader.svelte";
    import Spkapexcharts from "$lib/@spk/charts/Spkapexcharts.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        CardTitle,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
    import {
        Basicpieoptions,
        Donutoptions,
        Piechartoptions,
        Piegardientoptions,
        Pieimgoptions,
        Piemonooptions,
        Updatedoptions,
    } from "$lib/data/charts/apexcharts/piechartdata";
    import SpkButton from "$lib/@spk/uielements/Button/SpkButton.svelte";
    
    let Updatedseries = Updatedoptions.series;
    let series = [...Updatedseries];

    // Append a random value
    function appendData() {
        series = [...series, Math.floor(Math.random() * 100) + 1];
    }

    // Remove the last value
    function removeData() {
        if (series.length > 1) {
            series = series.slice(0, -1);
        }
    }

    // Randomize all values
    function randomize() {
        series = series.map(() => Math.floor(Math.random() * 100) + 1);
    }

    // Reset to initial state
    function reset() {
        series = [...Updatedseries];
    }
</script>

<!-- Page Title -->
<svelte:head>
    <title>PieChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Pie Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Pie Charts"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Basic Pie Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="pie-basic">
                    <Spkapexcharts id="pie-basic" options={Basicpieoptions} />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Simple Donut Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="donut-simple">
                    <Spkapexcharts id="donut-simple" options={Donutoptions} />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Updating Donut Chart</CardTitle>
            </CardHeader>
            <div class="card-body mx-auto">
                <div id="donut-update">
                    <Spkapexcharts
                        options={Updatedoptions}
                        id="donut-update"
                    />
                    <div class="text-center mt-4">
                        <SpkButton
                            size="sm"
                            color="primary"
                            customClass="m-1"
                            onclickfunc={appendData}
                        >
                            + ADD
                        </SpkButton>
                        &nbsp;
                        <SpkButton
                            size="sm"
                            color="primary"
                            customClass="m-1"
                            onclickfunc={removeData}
                        >
                            - REMOVE
                        </SpkButton>
                        &nbsp;
                        <SpkButton
                            size="sm"
                            color="primary"
                            customClass="m-1"
                            onclickfunc={randomize}
                        >
                            RANDOMIZE
                        </SpkButton>
                        &nbsp;
                        <SpkButton
                            size="sm"
                            color="primary"
                            customClass="m-1"
                            onclickfunc={reset}
                        >
                            RESET
                        </SpkButton>
                    </div>
                </div>
            </div>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Monochrome Pie Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="pie-monochrome">
                    <Spkapexcharts
                    id="pie-monochrome"
                        options={Piemonooptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Gradient Donut Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="donut-gradient">
                    <Spkapexcharts
                        options={Piegardientoptions} id="donut-gradient"
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Donut Chart With Patterns</CardTitle>
            </CardHeader>
            <div class="card-body">
                <div id="donut-pattern">
                    <Spkapexcharts
                        options={Piechartoptions} id="donut-pattern"
                    />
                </div>
            </div>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Image Filled Pie Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="pie-image">
                    <Spkapexcharts
                        options={Pieimgoptions}  id="pie-image"
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->
