// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/dashboards/crypto/buy-sell.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import SpkListcard from "@/shared/@spk/application-reusable/spk-listcard.svelte";
    import Spkapexcharts from "@/shared/@spk/charts/Spkapexcharts.svelte";
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import {
        AccountSummary,
        Buycards,
        SellCrypto,
        SellCrypto1,
        Selloptions,
    } from "@/shared/data/dashboards/crypto/buyselldata";
    import {
        Card,
        CardBody,
        CardHeader,
        Col,
        Image,
        Input,
        Nav,
        NavItem,
        NavLink,
        TabContent,
        TabPane,
    } from "@sveltestrap/sveltestrap";
    import Select from "svelte-select";
    let activeTab = 1;
</script>

<!-- Page Title -->
<svelte:head>
    <title>BuySell | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Buy & Sell"
    subTitle="Crypto"
    activepage="Dashboards"
    page="Buy & Sell"
/>
<!-- Page Header Close -->

<!-- Start:: row-1 -->

<div class="row">
    {#each Buycards as idx}
        <Col xl={4}>
            <SpkListcard
                cardClass={idx.cardClass}
                bodyClass="p-4"
                listCard={true}
                titleClass="d-block text-muted mb-1"
                list={idx}
            />
        </Col>
    {/each}
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader class="justify-content-between">
                <div class="card-title">Buy & Sell Statistics</div>
                <div
                    class="btn-group flex-wrap"
                    role="group"
                    aria-label="Basic example"
                >
                    <SpkButton
                        color=""
                        buttontype="button"
                        customClass="btn btn-primary btn-sm btn-wave waves-effect waves-light"
                        >1D</SpkButton
                    >
                    <SpkButton
                        color=""
                        buttontype="button"
                        customClass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light"
                        >1W</SpkButton
                    >
                    <SpkButton
                        color=""
                        buttontype="button"
                        customClass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light"
                        >1M</SpkButton
                    >
                    <SpkButton
                        color=""
                        buttontype="button"
                        customClass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light"
                        >3M</SpkButton
                    >
                    <SpkButton
                        color=""
                        buttontype="button"
                        customClass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light"
                        >6M</SpkButton
                    >
                    <SpkButton
                        color=""
                        buttontype="button"
                        customClass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light"
                        >1Y</SpkButton
                    >
                </div>
            </CardHeader>
            <CardBody class="p-0">
                <div
                    class="d-flex flex-wrap align-items-center border-bottom border-block-end-dashed mb-3 p-4 gap-5 justify-content-sm-center"
                >
                    {#each AccountSummary as item}
                        <div>
                            <span class="d-block fs-12">{item.label}</span>
                            <span
                                class={`d-block fw-medium fs-15 text-${item.color}`}
                            >
                                {item.value}
                            </span>
                        </div>
                    {/each}
                    <div></div>
                </div>
                <div id="buy_sell-statistics" class="px-3">
                    <Spkapexcharts
                        id="buy_sell-statistics"
                        options={Selloptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={3}>
        <Card class="custom-card">
            <CardHeader>
                <div class="card-title">Quick Secure Transfer</div>
            </CardHeader>
            <CardBody>
                <div
                    class="tab-pane border-0 p-0"
                    id="sell-crypto"
                    role="tabpanel"
                    aria-labelledby="sell-crypto"
                >
                    <div class="mb-3">
                        <span class="form-label">Crypto Value :</span>
                        <div class="position-relative">
                            <!-- svelte-ignore a11y_consider_explicit_label -->
                            <a href="#!" class="stretched-link"></a>
                            <div
                                class="p-2 border rounded d-flex align-items-center flex-wrap justify-content-between gap-3 mt-1"
                            >
                                <div class="gap-2 d-flex align-items-center">
                                    <div class="lh-1">
                                        <span class="avatar bg-light p-2">
                                            <Image
                                                src="../../images/crypto-currencies/regular/Bitcoin.svg"
                                                alt=""
                                            />
                                        </span>
                                    </div>
                                    <div class="fw-medium">Bitcoin - BTC</div>
                                </div>
                                <div class="text-end">
                                    <span class="fw-medium d-block"
                                        >0.374638535 BTC</span
                                    >
                                    <span class="text-muted">$5,364.65</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <span class="form-label">Deposit To :</span>
                        <div class="position-relative">
                            <!-- svelte-ignore a11y_consider_explicit_label -->
                            <a href="#!" class="stretched-link"></a>
                            <div
                                class="p-2 border rounded d-flex align-items-center gap-2 mt-1"
                            >
                                <div class="lh-1">
                                    <span class="avatar bg-light p-2">
                                        <i class="ri-bank-line text-info fs-20"
                                        ></i>
                                    </span>
                                </div>
                                <div>
                                    <span class="fw-medium d-block"
                                        >Banking</span
                                    >
                                    <span class="text-muted">Checking ...</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <span class="d-block fw-medium">Amount :</span>
                        <div
                            class="d-flex align-items-center justify-content-between text-muted"
                        >
                            <div>Weekly Bank Limit</div>
                            <div>$10,000 remaining</div>
                        </div>
                    </div>
                    <div class="input-group mb-3 flex-nowrap custom-crypto">
                        <Input
                            type="text"
                            class=""
                            aria-label="crypto buy select"
                        />
                        <Select
                            items={SellCrypto1}
                            clearable={false}
                            showChevron={true}
                            value={SellCrypto1[0]}
                        />
                    </div>
                    <div>
                        <div class="fs-14 py-2">
                            <div class="d-inline-flex">
                                <span class="fw-medium text-dark">Price:</span
                                ><span class="text-muted ms-2 fs-14"
                                    >6.003435</span
                                >
                            </div>
                            <span class="text-dark fw-medium float-end"
                                >BTC</span
                            >
                        </div>
                        <div class="fs-14 py-2">
                            <div class="d-inline-flex">
                                <span class="fw-medium text-dark">Amount:</span
                                ><span class="text-muted ms-2 fs-14"
                                    >2,34,4543.00</span
                                >
                            </div>
                            <span class="text-dark fw-medium float-end"
                                >LTC</span
                            >
                        </div>
                    </div>
                    <div class="d-grid mt-4">
                        <SpkButton
                            color="success"
                            buttontype="button"
                            customClass="btn btn-wave btn-lg"
                            >Transfer</SpkButton
                        >
                    </div>
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={3}>
        <Card class="custom-card">
            <CardHeader class="justify-content-between pb-2">
                <div class="card-title">Buy & Sell Crypto</div>
                <Nav
                    class="nav-tabs tab-style-8 scaleX"
                    id="myTab4"
                    role="tablist"
                >
                    <NavItem role="presentation">
                        <NavLink
                            on:click={(e) => {
                                (activeTab = 1), e.preventDefault();
                            }}
                            active={activeTab == 1}
                            class=""
                            id="buy-crypto-tab"
                            data-bs-toggle="tab"
                            data-bs-target="#buy-crypto-tab-pane"
                            type="button"
                            role="tab"
                            aria-controls="buy-crypto-tab-pane"
                            aria-selected="true">Buy</NavLink
                        >
                    </NavItem>
                    <NavItem role="presentation">
                        <NavLink
                            on:click={(e) => {
                                (activeTab = 2), e.preventDefault();
                            }}
                            active={activeTab == 2}
                            class=""
                            id="sell-crypto-tab"
                            data-bs-toggle="tab"
                            data-bs-target="#sell-crypto-tab-pane"
                            type="button"
                            role="tab"
                            aria-controls="sell-crypto-tab-pane"
                            aria-selected="false">Sell</NavLink
                        >
                    </NavItem>
                </Nav>
            </CardHeader>
            <CardBody>
                <TabContent class="" id="custmbuySell_dash">
                    <TabPane
                        class={`border-0 p-0 ${activeTab == 1 ? "active" : ""}`}
                        id="buy-crypto-tab-pane"
                        role="tabpanel"
                        aria-labelledby="buy-crypto-tab"
                        tabindex={0}
                    >
                        <div class="input-group mb-3 flex-nowrap custom-crypto">
                            <Input
                                type="text"
                                class=""
                                aria-label="crypto buy select"
                                placeholder="Select Value"
                            />
                            <Select
                                items={SellCrypto}
                                class="basic-multi-select buysell custom-buy-sell"
                                clearable={false}
                                showChevron={true}
                                value={SellCrypto[0]}
                            />
                        </div>
                        <div class="input-group mb-3 flex-nowrap custom-crypto">
                            <Input
                                type="text"
                                class=""
                                aria-label="crypto buy select"
                                placeholder="Amount Obtained"
                            />
                            <Select
                                items={SellCrypto1}
                                class="basic-multi-select buysell custom-buy-sell"
                                clearable={false}
                                showChevron={true}
                                value={SellCrypto1[0]}
                            />
                        </div>
                        <!-- svelte-ignore a11y_label_has_associated_control -->
                        <div>
                            <div class="fs-14 py-2">
                                <span class="fw-medium text-dark">Price:</span
                                ><span
                                    class="text-muted ms-2 fs-14 d-inline-block"
                                    >6.003435</span
                                ><span class="text-dark fw-medium float-end"
                                    >BTC</span
                                >
                            </div>
                            <div class="fs-14 py-2">
                                <span class="fw-medium text-dark">Amount:</span
                                ><span
                                    class="text-muted ms-2 fs-14 d-inline-block"
                                    >2,34,4543.00</span
                                ><span class="text-dark fw-medium float-end"
                                    >LTC</span
                                >
                            </div>
                            <div class="fw-medium fs-14 py-2">
                                Total: <span class="fs-14 d-inline-block"
                                    >22.00 BTC</span
                                >
                            </div>
                            <div class="fs-12 text-success">
                                Additional Charges: 0.32%(0.0001231 BTC)
                            </div>
                            <label class="fw-medium fs-12 mt-4 mb-3"
                                >SELECT PAYMENT METHOD :</label
                            >
                            <div class="row g-2">
                                <Col xxl={6}>
                                    <div class="p-2 border rounded">
                                        <div class="form-check mb-0">
                                            <input
                                                class="form-check-input"
                                                type="radio"
                                                name="flexRadioDefault"
                                                id="flexRadioDefault1"
                                                defaultChecked
                                            />
                                            <label
                                                class="form-check-label fs-12"
                                                for="flexRadioDefault1"
                                            >
                                                Credit / Debit Cards
                                            </label>
                                        </div>
                                    </div>
                                </Col>
                                <Col xxl={6}>
                                    <div class="p-2 border rounded">
                                        <div class="form-check mb-0">
                                            <input
                                                class="form-check-input"
                                                type="radio"
                                                name="flexRadioDefault"
                                                id="flexRadioDefault2"
                                            />
                                            <label
                                                class="form-check-label fs-12"
                                                for="flexRadioDefault2"
                                            >
                                                Paypal
                                            </label>
                                        </div>
                                    </div>
                                </Col>
                                <Col xl={12}>
                                    <div class="p-2 border rounded">
                                        <div class="form-check mb-0">
                                            <input
                                                class="form-check-input"
                                                type="radio"
                                                name="flexRadioDefault"
                                                id="flexRadioDefault3"
                                            />
                                            <label
                                                class="form-check-label fs-12"
                                                for="flexRadioDefault3"
                                            >
                                                Wallet
                                            </label>
                                        </div>
                                    </div>
                                </Col>
                            </div>
                        </div>
                        <div class="d-grid mt-3 pt-1">
                            <SpkButton
                                color="primary"
                                buttontype="button"
                                customClass="btn btn-wave btn-lg"
                                >BUY CRYPTO</SpkButton
                            >
                        </div>
                    </TabPane>
                    <TabPane
                        class={`overflow-hidden border-0 p-0 ${activeTab == 2 ? "active" : ""}`}
                        id="sell-crypto-tab-pane"
                        role="tabpanel"
                        aria-labelledby="sell-crypto-tab"
                        tabindex={0}
                    >
                        <div class="input-group mb-3 flex-nowrap custom-crypto">
                            <Input
                                type="text"
                                class=""
                                aria-label="crypto buy select"
                                placeholder="Select Value"
                            />
                            <Select
                                items={SellCrypto}
                                class="basic-multi-select buysell custom-buy-sell"
                                clearable={false}
                                showChevron={true}
                                value={SellCrypto[0]}
                            />
                        </div>
                        <div class="input-group mb-3 flex-nowrap custom-crypto">
                            <Input
                                type="text"
                                class=""
                                aria-label="crypto buy select"
                                placeholder=""
                            />
                            <Select
                                items={SellCrypto1}
                                class="basic-multi-select buysell custom-buy-sell"
                                clearable={false}
                                showChevron={true}
                                value={SellCrypto1[0]}
                            />
                        </div>
                        <div class="mb-3">
                            <span class="form-label">Crypto Value :</span>
                            <div class="position-relative">
                                <div
                                    class="p-2 border rounded d-flex align-items-center justify-content-between gap-3 mt-1 flex-wrap"
                                >
                                    <div
                                        class="gap-2 d-flex align-items-center"
                                    >
                                        <div class="lh-1">
                                            <span class="avatar bg-light p-2">
                                                <Image
                                                    src="../../images/crypto-currencies/regular/Bitcoin.svg"
                                                    alt=""
                                                />
                                            </span>
                                        </div>
                                        <div class="fw-medium">
                                            Bitcoin - BTC
                                        </div>
                                    </div>
                                    <div class="text-end">
                                        <span class="fw-medium d-block"
                                            >0.374638535 BTC</span
                                        >
                                        <span class="text-muted">$5,364.65</span
                                        >
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <span class="form-label">Deposit To :</span>
                            <div class="position-relative">
                                <div
                                    class="p-2 border rounded d-flex align-items-center gap-2 mt-1"
                                >
                                    <div class="lh-1">
                                        <span class="avatar bg-light p-2">
                                            <i
                                                class="ri-bank-line text-info fs-20"
                                            ></i>
                                        </span>
                                    </div>
                                    <div>
                                        <span class="fw-medium d-block"
                                            >Banking</span
                                        >
                                        <span class="text-muted"
                                            >Checking ...</span
                                        >
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="fs-14 py-2">
                                <div class="d-inline-flex">
                                    <span class="fw-medium text-dark"
                                        >Price:</span
                                    ><span class="text-muted ms-2 fs-14"
                                        >6.003435</span
                                    >
                                </div>
                                <span class="text-dark fw-medium float-end"
                                    >BTC</span
                                >
                            </div>
                            <div class="fs-14 py-2">
                                <div class="d-inline-flex">
                                    <span class="fw-medium text-dark"
                                        >Amount:</span
                                    ><span class="text-muted ms-2 fs-14"
                                        >2,34,4543.00</span
                                    >
                                </div>
                                <span class="text-dark fw-medium float-end"
                                    >LTC</span
                                >
                            </div>
                        </div>
                        <div class="d-grid mt-3">
                            <SpkButton
                                color="danger"
                                buttontype="button"
                                customClass="btn btn-wave btn-lg"
                                >SELL CRYPTO</SpkButton
                            >
                        </div>
                    </TabPane>
                </TabContent>
            </CardBody>
        </Card>
    </Col>
</div>

<!-- End:: row-1 -->

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/dashboards/crypto/buy-sell/buy-sell.jsx

import React, { Fragment } from "react";
import { Card, Col, Form,  Nav, Tab } from "react-bootstrap";
import { Head } from "@inertiajs/react";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { AccountSummary, Buycards, SellCrypto, SellCrypto1, Selloptions, SellSeries } from "../../../../shared/data/dashboards/crypto/buyselldata";
import SpkListCard from "../../../../shared/@spk-reusable-components/application-reusable/spk-listcard";
import SpkButton from "../../../../shared/@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import SpkSelect from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-reactselect";
import MainLayout from "@/Layouts/layout";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";
import BaseLink from "@/shared/layouts-components/baselink/baselink";

const BuySell = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title="Dashboards-Buy & Sell" />

            <Pageheader title="Dashboards" subtitle="Crypto" currentpage="Buy & Sell" activepage="Buy & Sell" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start:: row-1 --> */}

            <div className="row">
                {Buycards.map((idx, index) => (
                    <Col xl={4} key={index}>
                        <SpkListCard cardClass={idx.cardClass} listCard={true} titleClass="d-block text-muted mb-1" list={idx} />
                    </Col>
                ))}
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header className="justify-content-between">
                            <div className="card-title">
                                Buy & Sell Statistics
                            </div>
                            <div className="btn-group flex-wrap" role="group" aria-label="Basic example">
                                <SpkButton Buttonvariant="" Buttontype="button" Customclass="btn btn-primary btn-sm btn-wave waves-effect waves-light">1D</SpkButton>
                                <SpkButton Buttonvariant="" Buttontype="button" Customclass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light">1W</SpkButton>
                                <SpkButton Buttonvariant="" Buttontype="button" Customclass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light">1M</SpkButton>
                                <SpkButton Buttonvariant="" Buttontype="button" Customclass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light">3M</SpkButton>
                                <SpkButton Buttonvariant="" Buttontype="button" Customclass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light">6M</SpkButton>
                                <SpkButton Buttonvariant="" Buttontype="button" Customclass="btn btn-primary-light btn-sm btn-wave waves-effect waves-light">1Y</SpkButton>
                            </div>
                        </Card.Header>
                        <Card.Body className="p-0">
                            <div className="d-flex flex-wrap align-items-center border-bottom border-block-end-dashed mb-3 p-4 gap-5 justify-content-sm-center">
                                {AccountSummary.map((item, index) => (
                                    <div key={index}>
                                        <span className="d-block fs-12">{item.label}</span>
                                        <span className={`d-block fw-medium fs-15 text-${item.color}`}>
                                            {item.value}
                                        </span>
                                    </div>
                                ))}
                                <div></div>
                            </div>
                            <div id="buy_sell-statistics" className="px-3">
                                <Spkapexcharts type={"bar"} height={370} width={"100%"} chartOptions={Selloptions} chartSeries={SellSeries} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={3}>
                    <Card className="custom-card">
                        <Card.Header>
                            <div className="card-title">
                                Quick Secure Transfer
                            </div>
                        </Card.Header>
                        <Card.Body>
                            <div className="tab-pane border-0 p-0" id="sell-crypto" role="tabpanel"
                                aria-labelledby="sell-crypto">
                                <div className="mb-3">
                                    <span className="form-label">Crypto Value :</span>
                                    <div className="position-relative">
                                        <BaseLink href="#!" className="stretched-link"></BaseLink>
                                        <div className="p-2 border rounded d-flex align-items-center flex-wrap justify-content-between gap-3 mt-1">
                                            <div className="gap-2 d-flex align-items-center">
                                                <div className="lh-1">
                                                    <span className="avatar bg-light p-2">
                                                        <BaseImage src="/build/assets/images/crypto-currencies/regular/Bitcoin.svg" alt="" />
                                                    </span>
                                                </div>
                                                <div className="fw-medium">Bitcoin - BTC</div>
                                            </div>
                                            <div className="text-end">
                                                <span className="fw-medium d-block">0.374638535 BTC</span>
                                                <span className="text-muted">$5,364.65</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="mb-3">
                                    <span className="form-label">Deposit To :</span>
                                    <div className="position-relative">
                                        <BaseLink href="#!" className="stretched-link"></BaseLink>
                                        <div className="p-2 border rounded d-flex align-items-center gap-2 mt-1">
                                            <div className="lh-1">
                                                <span className="avatar bg-light p-2">
                                                    <i className="ri-bank-line text-info fs-20"></i>
                                                </span>
                                            </div>
                                            <div>
                                                <span className="fw-medium d-block">Banking</span>
                                                <span className="text-muted">Checking ...</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="mb-3">
                                    <span className="d-block fw-medium">Amount :</span>
                                    <div className="d-flex align-items-center justify-content-between text-muted">
                                        <div>Weekly Bank Limit</div>
                                        <div>$10,000 remaining</div>
                                    </div>
                                </div>
                                <div className="input-group mb-3 flex-nowrap custom-crypto">
                                    <Form.Control type="text" className="" aria-label="crypto buy select" />
                                    <SpkSelect name="colors" option={SellCrypto1} mainClass="basic-multi-select buysell custom-buy-sell" placeholder="USD" menuplacement='auto' classNameprefix="Select2" />
                                </div>
                                <div>
                                    <div className="fs-14 py-2">
                                        <div className="d-inline-flex">
                                            <span className="fw-medium text-dark">Price:</span><span className="text-muted ms-2 fs-14">6.003435</span>
                                        </div>
                                        <span className="text-dark fw-medium float-end">BTC</span>
                                    </div>
                                    <div className="fs-14 py-2">
                                        <div className="d-inline-flex">
                                            <span className="fw-medium text-dark">Amount:</span><span className="text-muted ms-2 fs-14">2,34,4543.00</span>
                                        </div>
                                        <span className="text-dark fw-medium float-end">LTC</span>
                                    </div>
                                </div>
                                <div className="d-grid mt-4">
                                    <SpkButton Buttonvariant="success" Buttontype="button" Customclass="btn btn-wave btn-lg">Transfer</SpkButton>
                                </div>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={3}>
                    <Card className="custom-card">
                        <Tab.Container defaultActiveKey={"buy"}>
                            <Card.Header className="justify-content-between pb-2">
                                <div className="card-title">
                                    Buy & Sell Crypto
                                </div>
                                <Nav className="nav-tabs tab-style-8 scaleX" id="myTab4" role="tablist">
                                    <Nav.Item role="presentation">
                                        <Nav.Link eventKey={"buy"} className="" id="buy-crypto-tab" data-bs-toggle="tab"
                                            data-bs-target="#buy-crypto-tab-pane" type="button" role="tab"
                                            aria-controls="buy-crypto-tab-pane" aria-selected="true">Buy</Nav.Link>
                                    </Nav.Item>
                                    <Nav.Item role="presentation">
                                        <Nav.Link eventKey={"sell"} className="" id="sell-crypto-tab" data-bs-toggle="tab"
                                            data-bs-target="#sell-crypto-tab-pane" type="button" role="tab"
                                            aria-controls="sell-crypto-tab-pane" aria-selected="false">Sell</Nav.Link>
                                    </Nav.Item>
                                </Nav>
                            </Card.Header>
                            <Card.Body>
                                <Tab.Content className="" id="myTabContent3">
                                    <Tab.Pane eventKey={"buy"} className="overflow-hidden border-0 p-0" id="buy-crypto-tab-pane"
                                        role="tabpanel" aria-labelledby="buy-crypto-tab" tabIndex={0}>
                                        <div>
                                            <div className="input-group mb-3 flex-nowrap custom-crypto">
                                                <Form.Control type="text" className="" aria-label="crypto buy select" placeholder="Enter Value" />
                                                <SpkSelect name="colors" option={SellCrypto} mainClass="basic-multi-select buysell custom-buy-sell" placeholder="BTC" menuplacement='auto' classNameprefix="Select2" />
                                            </div>
                                            <div className="input-group mb-3 flex-nowrap custom-crypto">
                                                <Form.Control type="text" className="" aria-label="crypto buy select" placeholder="Amount Obtained" />
                                                <SpkSelect name="colors" option={SellCrypto1} mainClass="basic-multi-select buysell custom-buy-sell" placeholder="USD" menuplacement='auto' classNameprefix="Select2" />
                                            </div>
                                            <div>
                                                <div className="fs-14 py-2"><span className="fw-medium text-dark">Price:</span><span className="text-muted ms-2 fs-14 d-inline-block">6.003435</span><span className="text-dark fw-medium float-end">BTC</span></div>
                                                <div className="fs-14 py-2"><span className="fw-medium text-dark">Amount:</span><span className="text-muted ms-2 fs-14 d-inline-block">2,34,4543.00</span><span className="text-dark fw-medium float-end">LTC</span></div>
                                                <div className="fw-medium fs-14 py-2">Total: <span className="fs-14 d-inline-block">22.00 BTC</span></div>
                                                <div className="fs-12 text-success">Additional Charges: 0.32%(0.0001231 BTC)</div>
                                                <label className="fw-medium fs-12 mt-4 mb-3">SELECT PAYMENT METHOD :</label>
                                                <div className="row g-2">
                                                    <Col xl={6}>
                                                        <div className="p-2 border rounded">
                                                            <div className="form-check mb-0">
                                                                <input className="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" defaultChecked />
                                                                <label className="form-check-label fs-12" htmlFor="flexRadioDefault1">
                                                                    Credit / Debit Cards
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </Col>
                                                    <Col xl={6}>
                                                        <div className="p-2 border rounded">
                                                            <div className="form-check mb-0">
                                                                <input className="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" />
                                                                <label className="form-check-label fs-12" htmlFor="flexRadioDefault2">
                                                                    Paypal
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </Col>
                                                    <Col xl={12}>
                                                        <div className="p-2 border rounded">
                                                            <div className="form-check mb-0">
                                                                <input className="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3" />
                                                                <label className="form-check-label fs-12" htmlFor="flexRadioDefault3">
                                                                    Wallet
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </Col>
                                                </div>
                                            </div>
                                            <div className="d-grid mt-3 pt-1">
                                                <SpkButton Buttonvariant="primary" Buttontype="button" Customclass="btn btn-wave btn-lg">BUY CRYPTO</SpkButton>
                                            </div>
                                        </div>
                                    </Tab.Pane>
                                    <Tab.Pane eventKey={"sell"} className="overflow-hidden border-0 p-0" id="sell-crypto-tab-pane" role="tabpanel"
                                        aria-labelledby="sell-crypto-tab" tabIndex={0}>
                                        <div className="input-group mb-3 flex-nowrap custom-crypto">
                                            <Form.Control type="text" className="" aria-label="crypto buy select" placeholder="Select Value" />
                                            <SpkSelect name="colors" option={SellCrypto} mainClass="basic-multi-select buysell custom-buy-sell" placeholder="BTC" menuplacement='auto' classNameprefix="Select2" />
                                        </div>
                                        <div className="input-group mb-3 flex-nowrap custom-crypto">
                                            <Form.Control type="text" className="" aria-label="crypto buy select" placeholder="" />
                                            <SpkSelect name="colors" option={SellCrypto1} mainClass="basic-multi-select buysell custom-buy-sell" placeholder="USD" menuplacement='auto' classNameprefix="Select2" />
                                        </div>
                                        <div className="mb-3">
                                            <span className="form-label">Crypto Value :</span>
                                            <div className="position-relative">
                                                <div className="p-2 border rounded d-flex align-items-center justify-content-between gap-3 mt-1 flex-wrap">
                                                    <div className="gap-2 d-flex align-items-center">
                                                        <div className="lh-1">
                                                            <span className="avatar bg-light p-2">
                                                                <BaseImage src="/build/assets/images/crypto-currencies/regular/Bitcoin.svg" alt="" />
                                                            </span>
                                                        </div>
                                                        <div className="fw-medium">Bitcoin - BTC</div>
                                                    </div>
                                                    <div className="text-end">
                                                        <span className="fw-medium d-block">0.374638535 BTC</span>
                                                        <span className="text-muted">$5,364.65</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="mb-3">
                                            <span className="form-label">Deposit To :</span>
                                            <div className="position-relative">
                                                <div className="p-2 border rounded d-flex align-items-center gap-2 mt-1">
                                                    <div className="lh-1">
                                                        <span className="avatar bg-light p-2">
                                                            <i className="ri-bank-line text-info fs-20"></i>
                                                        </span>
                                                    </div>
                                                    <div>
                                                        <span className="fw-medium d-block">Banking</span>
                                                        <span className="text-muted">Checking ...</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div>
                                            <div className="fs-14 py-2">
                                                <div className="d-inline-flex">
                                                    <span className="fw-medium text-dark">Price:</span><span className="text-muted ms-2 fs-14">6.003435</span>
                                                </div>
                                                <span className="text-dark fw-medium float-end">BTC</span>
                                            </div>
                                            <div className="fs-14 py-2">
                                                <div className="d-inline-flex">
                                                    <span className="fw-medium text-dark">Amount:</span><span className="text-muted ms-2 fs-14">2,34,4543.00</span>
                                                </div>
                                                <span className="text-dark fw-medium float-end">LTC</span>
                                            </div>
                                        </div>
                                        <div className="d-grid mt-3">
                                            <SpkButton Buttonvariant="danger" Buttontype="button" Customclass="btn btn-wave btn-lg">SELL CRYPTO</SpkButton>
                                        </div>
                                    </Tab.Pane>
                                </Tab.Content>
                            </Card.Body>
                        </Tab.Container>
                    </Card>
                </Col>
            </div>

            {/* <!-- End:: row-1 --> */}

        </Fragment>
    )
};

BuySell.layout = (page) => <MainLayout>{page}</MainLayout>;
export default BuySell;
