// Dashboard Template/vyzor-laravel-svelte/final/resources/js/components/showcode/ShowCode.svelte
<script>
    import {
        Card,
        CardHeader,
        CardFooter,
        CardBody,
    } from "@sveltestrap/sveltestrap"; // Ensure you have a Bootstrap card component or similar

    export let title;
    export let svelteCode = "";
    export let dataCode = "";
    export let customCardClass = "";
    export let customCardHeaderClass = "";
    export let customCardBodyClass = "";
    export let customCardFooterClass = "";

    let showCode = false;
    let activeTab = dataCode ? "svelte" : "svelte"; // Default to 'svelte' tab

    const toggleCode = () => {
        showCode = !showCode;
    };

    const handleTabChange = (tab) => {
        activeTab = tab;
    };
</script>

<Card class={`custom-card ${customCardClass}`}>
    <CardHeader class={`justify-content-between ${customCardHeaderClass}`}>
        <div class="card-title">{@html title}</div>
        <div class="prism-toggle">
            <button class="btn btn-sm btn-primary-light" on:click={toggleCode}>
                {showCode ? "Hide Code" : "Show Code"}
                <i
                    class={`ms-2 fs-14 align-middle d-inline-block ${showCode ? "ri-code-s-slash-line" : "ri-code-line"}`}
                ></i>
            </button>
        </div>
    </CardHeader>
    {#if showCode}
        <CardFooter class={`border-top-0 ${customCardFooterClass}`}>
            <div class="tabs">
                <button
                    class={`btn tab-button btn-primary-light btn-wave ${activeTab === "svelte" ? "active" : ""}`}
                    on:click={() => handleTabChange("svelte")}
                >
                    Svelte
                </button>
                {#if dataCode}
                    <button
                        class={`btn tab-button btn-primary-light ${activeTab === "data" ? "active" : ""}`}
                        on:click={() => handleTabChange("data")}
                    >
                        Data
                    </button>
                {/if}
            </div>
            <pre class="language-html showcode-code">
                <code class="language-html">
                    {activeTab === "svelte" ? svelteCode : dataCode}
                </code>
            </pre>
        </CardFooter>
    {:else}
        <CardBody class={customCardBodyClass}>
            <slot />
        </CardBody>
    {/if}
</Card>

<style>
    /* Add any necessary styles here */
</style>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/layouts-components/showcode/showcode.jsx

import React, { useState } from 'react';
import { Card } from 'react-bootstrap';
import SpkButton from '../../@spk-reusable-components/general-reusable/reusable-uielements/spk-buttons';


const ShowCode = ({ title, reactCode, dataCode, reusableCode, customCardClass, customCardHeaderClass, customCardBodyClass, customCardFooterClass, children }) => {

    const [showCode, setShowCode] = useState(false);
    const [activeTab, setActiveTab] = useState('react');

    const toggleCode = () => {
        setShowCode(!showCode);
    };

    const handleTabChange = (tab) => {
        setActiveTab(tab);
    };

    const shouldShowDataTab = !!dataCode;
    //const shouldShowReusableTab = !!reusableCode;

    return (
        <Card className={`custom-card ${customCardClass}`}>
            <Card.Header className={`justify-content-between ${customCardHeaderClass}`}>
                <div className="card-title" dangerouslySetInnerHTML={{ __html: title }}></div>
                <div className="prism-toggle">
                    <SpkButton Size='sm' Buttonvariant="primary-light" onClickfunc={toggleCode}>
                        {showCode ? 'Hide Code' : 'Show Code'}
                        <i className={`${showCode ? 'ri-code-s-slash-line' : 'ri-code-line'} ms-2 align-middle inline-block`}></i>
                    </SpkButton>
                </div>
            </Card.Header>
            {showCode ? (
                <Card.Footer className={`border-top-0 ${customCardFooterClass}`}>
                    <div className="tabs">
                        <SpkButton Buttonvariant='' Customclass={`tab-button text-default ${activeTab === 'react' ? 'active' : ''}`} onClickfunc={() => handleTabChange('react')}>React </SpkButton>
                        {shouldShowDataTab && (
                            <SpkButton Buttonvariant='' Customclass={`tab-button text-default ${activeTab === 'data' ? 'active' : ''}`} onClickfunc={() => handleTabChange('data')}>Data</SpkButton>
                        )}
                        {reusableCode && (
                            <SpkButton Buttonvariant='' Customclass={`tab-button text-default ${activeTab === 'reusable' ? 'active' : ''}`} onClickfunc={() => handleTabChange('reusable')}>Reusable Code</SpkButton>
                        )}
                    </div>
                    <pre className="language-html showcode-code">
                        <code className="language-html">
                            {activeTab === 'react'
                                ? reactCode
                                : activeTab === 'data'
                                    ? dataCode
                                    : activeTab === 'reusable'
                                        ? reusableCode
                                        : null}
                        </code>
                    </pre>
                </Card.Footer>
            ) : (
                <Card.Body className={`${customCardBodyClass}`}>{children}</Card.Body>
            )}
        </Card>
    );
};

export default ShowCode;
