// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/dashboards-reusable/spk-stockcard.svelte
<script>
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";
    import Spkapexcharts from "../charts/Spkapexcharts.svelte";

    export let stock = {};
    export let cardClass = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody>
        <div
            class="d-flex gap-2 flex-wrap align-items-center justify-content-between mb-3"
        >
            <div class="d-flex flex-fill align-items-center">
                <div class="me-2 lh-1">
                    <span class="avatar avatar-md">
                        <Image src={stock.imgSrc} alt="" class="invert-1" />
                    </span>
                </div>
                <div class="lh-1">
                    <span class="d-block text-default fw-medium">
                        {stock.title}
                    </span>
                </div>
            </div>
            <div class="fs-12 text-end">
                <span class="text-uppercase fw-semibold">{stock.subtitle}</span>
                <span class={`text-${stock.percentColor} d-block`}>
                    {stock.percent}
                    <i class={`ti ti-arrow-bear-${stock.percentColor==='danger'?'left':'right'}`}></i>
                </span>
            </div>
        </div>

        <div class="d-flex align-items-end justify-content-between">
            <div>
                <span class="d-block text-muted fs-12">Current value</span>
                <h6 class="fw-semibold mb-0">{stock.value}</h6>
            </div>
            <div id={stock.chartId}>
                <Spkapexcharts
                    id={stock.chartId}
                    options={stock.chartOptions}
                />
            </div>
        </div>
    </CardBody>
</Card>

// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/dashboards-reusable/spk-stockcard.tsx

import { Fragment } from "react";
import { Card, Image } from "react-bootstrap";
import Spkapexcharts from "../reusable-plugins/spk-apexcharts";

interface StockCardProps {
  stock: {
    imgSrc: string;
    title: string;
    subtitle: string;
    percent: string;
    percentColor: string;
    value: string;
    chartId: string;
    chartOptions: any;
    chartSeries: any;
  };
  cardClass?: string;
}

const SpkStockCard: React.FC<StockCardProps> = ({ stock, cardClass = "" }) => {
  return (
    <Fragment>
      <Card className={`custom-card mb-0 ${cardClass}`}>
        <Card.Body>
          <div className="d-flex gap-2 flex-wrap align-items-center justify-content-between mb-3">
            <div className="d-flex flex-fill align-items-center">
              <div className="me-2 lh-1">
                <span className="avatar avatar-md">
                  <Image src={stock.imgSrc} alt="" className="invert-1"/>
                </span>
              </div>
              <div className="lh-1">
                <span className="d-block text-default fw-medium">
                  {stock.title}
                </span>
              </div>
            </div>
            <div className="fs-12 text-end">
              <span className="text-uppercase fw-semibold">{stock.subtitle}</span>
              <span className={`text-${stock.percentColor} d-block`}>
                {stock.percent}
                <i className="ti ti-arrow-bear-right"></i>
              </span>
            </div>
          </div>

          <div className="d-flex align-items-end justify-content-between">
            <div>
              <span className="d-block text-muted fs-12">Current value</span>
              <h6 className="fw-semibold mb-0">{stock.value}</h6>
            </div>
            <div id={stock.chartId}>
              <Spkapexcharts height={20} width={120} type={"area"} chartOptions={stock.chartOptions} chartSeries={stock.chartSeries}/>
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkStockCard;
