// Dashboard Template/vyzor-svelte/final/src/lib/@spk/uielements/reusable-cards/spkimageoverlaycard.svelte
<script lang="ts">
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Image,
    } from "@sveltestrap/sveltestrap";

    export let Imgsrc: string = "";
    export let Footertext: string = "";
    export let Overlayclass: string = "";
    export let CustomTitleclass: string = "";
    export let Customimgclass: string = "";
    export let Custombodyclass: string = "";
    export let Customfooterclass: string = "";
    export let Title: string = "";
    export let CustomClass: string = "";
    export let CardHeaderTag: boolean = true;
    export let CardFooterTag: boolean = true;
</script>

<Card class={`custom-card ${CustomClass}`}>
    <Image src={Imgsrc} class={Customimgclass} alt="..." />
    <div class={`card-img-overlay d-flex flex-column p-0 ${Overlayclass}`}>
        {#if CardHeaderTag}
            <CardHeader class="card-header">
                <div class={`card-title ${CustomTitleclass}`}>
                    {Title}
                </div>
            </CardHeader>
        {/if}
        <CardBody class={Custombodyclass}>
            <slot />
        </CardBody>
        {#if CardFooterTag}
            <CardFooter class={Customfooterclass}>{Footertext}</CardFooter>
        {/if}
    </div>
</Card>

// Dashboard Template/vyzor-nuxt/final/app/components/@spk/reusable-uielements/reusable-cards/spkimageoverlaycard.vue
<script setup>
defineProps({
    CustomClass: String,
    Imgsrc: String,
    Overlayclass: String,
    CardHeader: {
        type: Boolean,
        default: true
    },
    Title: String,
    Custombodyclass: String,
    CustomTitleclass: String,
    Customfooterclass: String,
    CardFooter: {
        type: Boolean,
        default: true
    },
    Footertext: String
})

</script>
<template>
    <div :class="`card custom-card ${CustomClass}`">
        <img :src="Imgsrc" class="card-img" alt="...">
        <div :class="`card-img-overlay d-flex flex-column p-0 ${Overlayclass}`">
            <template v-if="CardHeader">
                <div class="card-header">
                    <div :class="`card-title ${CustomTitleclass}`">
                        {{ Title }}
                    </div>
                </div>
            </template>
            <div :class="`card-body ${Custombodyclass}`">
                <slot name="cardContent" />
            </div>
            <template v-if="CardFooter">
                <div :class="`card-footer ${Customfooterclass}`">{{ Footertext }}</div>
            </template>
        </div>
    </div>
</template>
