// Dashboard Template/vyzor-laravel-svelte/starterkit/resources/js/shared/@spk/uielements/reusable-cards/spktitlecards.svelte
<script>
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        CardTitle,
        Image,
    } from "@sveltestrap/sveltestrap";
    import SpkButton from "../Button/SpkButton.svelte";

    export let CustomBodyclass = "";
    export let CustomHeaderclass = "";
    export let Imgsrc = "";
    export let Footertext = "";
    export let Title = "";
    export let Customclass = "";
    export let Customfooterclass = "";
    export let Icon = "";
    export let LinkClass = "";
    export let Icontag = false;
    export let Linktag = false;
    export let ButtonTag = false;
    export let Cardheader = false;
    export let Imagetag = false;
    export let Cardfooter = false;
    export let Anchortagbefore = false;
    export let OnclickFunc;
    export let Navigate = "";
    export let AnchortagNavigate = "";
</script>

<Card class={Customclass}>
    {#if Imagetag}
        <Image src={Imgsrc} class="card-img-top" alt="..." />
    {/if}
    {#if Anchortagbefore}
        <!-- svelte-ignore attribute_invalid_property_name -->
        <!-- svelte-ignore a11y_consider_explicit_label -->
        <a href={AnchortagNavigate} class="card-anchor"></a>
    {/if}
    {#if Cardheader}
        <CardHeader class={CustomHeaderclass}>
            <CardTitle>
                {Title}
            </CardTitle>
            {#if Linktag}
                <a
                    href={Navigate}
                    data-bs-toggle="card-remove"
                    on:click={OnclickFunc}
                    class={LinkClass}
                >
                    {#if Icontag}
                        <i class={Icon}></i>
                    {/if}
                </a>
            {/if}
        </CardHeader>
    {/if}
    <CardBody class={CustomBodyclass}>
        <slot />
    </CardBody>
    {#if Cardfooter}
        <CardFooter class={Customfooterclass}>
            {#if ButtonTag}
                <SpkButton color="primary">Read More</SpkButton>
            {:else}
                {Footertext}
            {/if}
        </CardFooter>
    {/if}
</Card>

// Dashboard Template/vyzor-nuxt/final/app/components/@spk/reusable-uielements/reusable-cards/spktitlecards.vue
<script setup>
defineProps({
    Customclass: String,
    Imagetag: {
        type: Boolean,
        default: false
    },
    Imgsrc: String,
    Anchortagbefore: {
        type: Boolean,
        default: false
    },
    AnchortagNavigate: {
        type: [URL, String],
    },
    CustomHeaderclass: String,
    Title: String,
    Linktag: Boolean,
    Navigate: [URL, String],
    OnclickFunc: {
        type: Function,
    },
    LinkClass: String,
    Icontag: {
        type: Boolean,
        default: false
    },
    Icon: String,
    CustomBodyclass: String,
    condition: Boolean,
    Customfooterclass: String,
    ButtonTag: Boolean,
    Cardheader: Boolean
})

</script>

<template>
    <div :class="`card ${Customclass}`">
        <template v-if="Imagetag">
            <img :src="Imgsrc" class="card-img-top" alt="...">
        </template>
        <template v-if="Anchortagbefore">
            <a :href="AnchortagNavigate" class="card-anchor"></a>
        </template>
        <template v-if="Cardheader">
            <div :class="`card-header ${CustomHeaderclass}`">
                <div class="card-title">
                    {{ Title }}
                </div>
                <template v-if="Linktag">
                    <a :href="Navigate" data-bs-toggle="card-remove" @click="OnclickFunc" :class="LinkClass"></a>
                </template>
                <template v-if="Icontag">
                    <i :class="Icon"></i>
                </template>
            </div>
        </template>
        <div :class="`card-body ${CustomBodyclass} `">
            <slot />
        </div>
        <template v-if="Cardfooter">
            <div :class="`card-footer ${Customfooterclass}`">
                <template v-if="ButtonTag">
                    <button class="btn btn-primary">Read More</button>
                </template>
            </div>
        </template>
    </div>
</template>
