// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/layouts-components/backtotop/backtotop.jsx

import React, { useEffect, useRef } from 'react'


const Backtotop = () => {
    const scrollToTopRef = useRef(null);
    const screenUp = () => {
        window.scrollTo(0, 0);
    };

    useEffect(() => {
        const handleScroll = () => {
            if (scrollToTopRef.current) {
                window.scrollY > 100 ? (scrollToTopRef.current.style.display = "flex") : (scrollToTopRef.current.style.display = "none")
            }
        };

        window.addEventListener("scroll", handleScroll);

        return () => {
            window.removeEventListener("scroll", handleScroll);
        };
    }, []);

    return (
        <div ref={scrollToTopRef} className="scrollToTop" onClick={screenUp}>
            <span className="arrow"><i className="ti ti-arrow-big-up fs-16"></i></span>
        </div>
    )
}

export default Backtotop

// Dashboard Template/vyzor-nuxt/staterkit/app/components/common/backtotop.vue
<template>
    <div class="scrollToTop" ref="scrollToTop" style="display: flex;">
        <span class="arrow lh-1"><i class="ti ti-arrow-big-up fs-18"></i></span>
    </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue';

const scrollToTop = ref(null);

const onScroll = () => {
    if (scrollToTop.value) {
        if (window.scrollY > 100) {
            scrollToTop.value.style.display = 'flex';
        } else {
            scrollToTop.value.style.display = 'none';
        }
    }
};

onMounted(() => {
    window.addEventListener('scroll', onScroll);

    if (scrollToTop.value) {
        scrollToTop.value.onclick = () => {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        };
    }
});

onUnmounted(() => {
    window.removeEventListener('scroll', onScroll);

    if (scrollToTop.value) {
        scrollToTop.value.onclick = null; // cleanup click handler
    }
});
</script>
