// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/heatmap-chart/heatmap-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import { Heatboptions, Heatbseries, Heatmultioptions, Heatmultiseries, Heatrangeoptions, Heatrangeseries, Heatshadeoptions, Heatshadeseries } from "../../../../shared/data/charts/apexcharts/heatmapdata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const HeatmapChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Heatmap Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Heatmap Charts" activepage="Apex Heatmap Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Heatmap Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="heatmap-basic">
                                <Spkapexcharts chartOptions={Heatboptions} chartSeries={Heatbseries} type="heatmap" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Multi Series Heatmap Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="heatmap-multiseries">
                                <Spkapexcharts chartOptions={Heatmultioptions} chartSeries={Heatmultiseries} type="heatmap" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Color Range Heatmap Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="heatmap-colorrange">
                                <Spkapexcharts chartOptions={Heatrangeoptions} chartSeries={Heatrangeseries} type="heatmap" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Heatmap Range Without Shades</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="heatmap-range">
                                <Spkapexcharts chartOptions={Heatshadeoptions} chartSeries={Heatshadeseries} type="heatmap" width={"100%"} height={350} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
HeatmapChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default HeatmapChart;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/charts/apex-charts/heatmap-chart.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import Spkapexcharts from "@/shared/@spk/charts/Spkapexcharts.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        CardTitle,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
    import {
        Heatboptions,
        Heatmultioptions,
        Heatrangeoptions,
        Heatshadeoptions,
    } from "@/shared/data/charts/apexcharts/heatmapadata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>HeatmapChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->
<!-- Page Header -->
<Pageheader
    homepage="Apex Heatmap Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Heatmap Charts"
/>
<!-- Page Header Close -->
<!-- Start::row-1 -->

<Row>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Basic Heatmap Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="heatmap-basic">
                    <Spkapexcharts id="heatmap-basic" options={Heatboptions} />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Multi Series Heatmap Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="heatmap-multiseries">
                    <Spkapexcharts
                        id="heatmap-multiseries"
                        options={Heatmultioptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Color Range Heatmap Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="heatmap-colorrange">
                    <Spkapexcharts
                        id="heatmap-colorrange"
                        options={Heatrangeoptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Heatmap Range Without Shades</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="heatmap-range">
                    <Spkapexcharts
                        id="heatmap-range"
                        options={Heatshadeoptions}
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->
