// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/Pages/charts/apex-charts/polararea-chart/polararea-chart.jsx

import MainLayout from "@/Layouts/layout";
import Spkapexcharts from "../../../../shared/@spk-reusable-components/reusable-plugins/spk-apexcharts";
import { Areaoptions, Areaseries, Monooptions, Monoseries } from "../../../../shared/data/charts/apexcharts/polarareadata";
import Pageheader from "../../../../shared/layouts-components/pageheader/pageheader";
import { Head } from "@inertiajs/react";
import React, { Fragment } from "react";
import { Card, Col, Row } from "react-bootstrap";


const PolarareaChart = () => {

    return (

        <Fragment>

            {/* <!-- Page Header --> */}

            <Head title={"Apex Polar Area Charts"} />

            <Pageheader title="Apex Charts" subtitle="Apex Charts" currentpage="Apex Polar Area Charts" activepage="Apex Polar Area Charts" />

            {/* <!-- Page Header Close --> */}

            {/* <!-- Start::row-1 --> */}

            <Row>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Basic Polar Area Chart</Card.Title>
                        </Card.Header>
                        <Card.Body>
                            <div id="polararea-basic">
                                <Spkapexcharts chartOptions={Areaoptions} chartSeries={Areaseries} type="polarArea" width={"100%"} height={320} />
                            </div>
                        </Card.Body>
                    </Card>
                </Col>
                <Col xl={6}>
                    <Card className="custom-card">
                        <Card.Header>
                            <Card.Title>Polar Area Monochrome Chart</Card.Title>
                        </Card.Header>
                        <Card.Body className="px-0">
                            <div id="polararea-monochrome">
                                <Spkapexcharts chartOptions={Monooptions} chartSeries={Monoseries} type="polarArea" width={"100%"} height={320} />

                            </div>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* <!--End::row-1 --> */}

        </Fragment>
    )
};
// Assign layout
PolarareaChart.layout = (page) => <MainLayout>{page}</MainLayout>;
export default PolarareaChart;

// Dashboard Template/vyzor-laravel-svelte/final/resources/js/Pages/charts/apex-charts/polararea-chart.svelte
<script context="module">
    import MainLayout from "@/layouts/MainLayout.svelte";
    export const layout = MainLayout;
</script>

<script>
    import Pageheader from "@/components/page-header/Pageheader.svelte";
    import Spkapexcharts from "@/shared/@spk/charts/Spkapexcharts.svelte";
    import {
        Card,
        CardBody,
        CardHeader,
        CardTitle,
        Col,
        Row,
    } from "@sveltestrap/sveltestrap";
    import {
        Areaoptions,
        Monooptions,
    } from "@/shared/data/charts/apexcharts/polarareachartdata";
</script>

<!-- Page Title -->
<svelte:head>
    <title>PolarareaChart | Vyzor - Svelte Admin & Dashboard Template</title>
</svelte:head>
<!-- Page Title Close -->

<!-- Page Header -->
<Pageheader
    homepage="Apex Polar Area Charts"
    activepage="Charts"
    subTitle="Apex Charts"
    page="Apex Polar Area Charts"
/>
<!-- Page Header Close -->

<!-- Start::row-1 -->

<Row>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Basic Polar Area Chart</CardTitle>
            </CardHeader>
            <CardBody>
                <div id="polararea-basic">
                    <Spkapexcharts options={Areaoptions} id="polararea-basic" />
                </div>
            </CardBody>
        </Card>
    </Col>
    <Col xl={6}>
        <Card class="custom-card">
            <CardHeader>
                <CardTitle>Polar Area Monochrome Chart</CardTitle>
            </CardHeader>
            <CardBody class="px-0">
                <div id="polararea-monochrome">
                    <Spkapexcharts
                        options={Monooptions}
                        id="polararea-monochrome"
                    />
                </div>
            </CardBody>
        </Card>
    </Col>
</Row>

<!--End::row-1 -->
