// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/general-reusable/reusable-uielements/reusable-cards/spkimageoverlaycard.jsx

import React, { Fragment } from 'react'
import { Card, Image, } from 'react-bootstrap'
import { Link } from "@inertiajs/react";
import BaseImage from '@/shared/layouts-components/baseimage/baseimage';


const Spkimageoverlaycard = ({ Imgsrc, CustomClass, stretchedLink = false, CardHeader = true, Overlayclass, CardFooter = true, Footertext, Customfooterclass, Custombodyclass, CustomTitleclass, Customimgclass, Title, children }) => {
    return (
        <Fragment>
            <Card className={`custom-card ${CustomClass}`}>
                {stretchedLink ?
                    <Link href={`${__APP_BASE_PATH__}/pages/blog/blog-details`} className="stretched-link"></Link>
                    : ""}
                <BaseImage src={Imgsrc} className={Customimgclass} alt="..." />
                <div className={`card-img-overlay d-flex flex-column p-0 ${Overlayclass}`}>

                    {CardHeader ?
                        <Card.Header className="card-header">
                            <div className={`card-title ${CustomTitleclass}`}>
                                {Title}
                            </div>
                        </Card.Header>
                        : ""}
                    <Card.Body className={Custombodyclass}>
                        {children}
                    </Card.Body>
                    {CardFooter ? <Card.Footer className={Customfooterclass}>{Footertext}</Card.Footer> : ""}

                </div>
            </Card>
        </Fragment>
    )
}

export default Spkimageoverlaycard

// Dashboard Template/vyzor-laravel-svelte/starterkit/resources/js/shared/@spk/uielements/reusable-cards/spkimageoverlaycard.svelte
<script>
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Image,
    } from "@sveltestrap/sveltestrap";

    export let Imgsrc = "";
    export let Footertext = "";
    export let Overlayclass = "";
    export let CustomTitleclass = "";
    export let Customimgclass = "";
    export let Custombodyclass = "";
    export let Customfooterclass = "";
    export let Title = "";
    export let CustomClass = "";
    export let CardHeaderTag = true;
    export let CardFooterTag = true;
</script>

<Card class={`custom-card ${CustomClass}`}>
    <Image src={Imgsrc} class={Customimgclass} alt="..." />
    <div class={`card-img-overlay d-flex flex-column p-0 ${Overlayclass}`}>
        {#if CardHeaderTag}
            <CardHeader class="card-header">
                <div class={`card-title ${CustomTitleclass}`}>
                    {Title}
                </div>
            </CardHeader>
        {/if}
        <CardBody class={Custombodyclass}>
            <slot />
        </CardBody>
        {#if CardFooterTag}
            <CardFooter class={Customfooterclass}>{Footertext}</CardFooter>
        {/if}
    </div>
</Card>
