// Dashboard Template/vyzor-svelte/final/src/lib/@spk/dashboards-reusable/spk-coursecard.svelte
<script lang="ts">
    import { Card, CardBody } from "@sveltestrap/sveltestrap";
    import SpkBadge from "../uielements/badge/SpkBadge.svelte";

    interface Course {
        svgIcon?: string;
        svgColor?: string;
        title?: string;
        value?: string | number;
        percent?: string | number;
        icon?: string;
    }

    export let course: Course = {};
    export let cardClass: string = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody>
        <div class="d-flex align-items-start gap-3 flex-wrap">
            <div class="lh-1">
                <span
                    class={`avatar avatar-lg avatar-rounded bg-${course.svgColor} svg-white`}
                >
                    {@html course.svgIcon}
                </span>
            </div>
            <div>
                <span class="d-block mb-1">
                    {course.title}
                </span>
                <div class="d-flex align-items-center gap-2">
                    <h5 class="fw-semibold mb-0">{course.value}</h5>
                    <SpkBadge
                        Color=""
                        CustomClass={`bg-${course.svgColor}-transparent rounded-pill`}
                    >
                        <i class={course.icon}></i>
                        {course.percent}
                    </SpkBadge>
                </div>
            </div>
        </div>
    </CardBody>
</Card>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/dashboards-reusable/spk-coursecard.jsx
import React, { Fragment } from "react";
import { Card } from "react-bootstrap";
import SpkBadge from "../general-reusable/reusable-uielements/spk-badge";


const SpkCourseCard = ({ course, cardClass = "" }) => {
    return (
        <Fragment>
            <Card className={`custom-card ${cardClass}`}>
                <Card.Body>
                    <div className="d-flex align-items-start gap-3 flex-wrap">
                        <div className="lh-1">
                            <span className={`avatar avatar-lg avatar-rounded bg-${course.svgColor} svg-white`}>
                                {course.svgIcon}
                            </span>
                        </div>
                        <div>
                            <span className="d-block mb-1">
                                {course.title}
                            </span>
                            <div className="d-flex align-items-center gap-2">
                                <h5 className="fw-semibold mb-0">{course.value}</h5>
                                <SpkBadge variant="" Customclass={`bg-${course.svgColor}-transparent rounded-pill`}>
                                    <i className={course.icon}></i> {course.percent}
                                </SpkBadge>
                            </div>
                        </div>
                    </div>
                </Card.Body>
            </Card>
        </Fragment>
    );
};

export default SpkCourseCard;
