// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/dashboards-reusable/spk-analyticscard.svelte
<script >
    import { Card, CardBody } from "@sveltestrap/sveltestrap";
    
    export let analytic = {};
    export let cardClass = "";
    export let bodyClass = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class={bodyClass}>
        <div class="d-flex align-items-start gap-3">
            <div>
                <span
                    class={`avatar avatar-md bg-${analytic.svgColor} svg-white`}
                >
                    {@html analytic.svgIcon}
                </span>
            </div>
            <div>
                <span class="d-block text-muted">{analytic.title}</span>
                <h5 class="fw-semibold mb-1">{analytic.value}</h5>
                <div class="text-muted fs-12">
                    <span class={`text-${analytic.iconColor}`}>
                        <i class={analytic.icon}></i>
                        {analytic.percent}
                    </span>{" "}
                    {analytic.year}
                </div>
            </div>
        </div>
    </CardBody>
</Card>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/dashboards-reusable/spk-analyticscard.jsx


import { Fragment } from "react";
import { Card } from "react-bootstrap";


const SpkAnalyticsCard = ({analytic, cardClass, bodyClass}) => {
  return (
    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className={bodyClass}>
          <div className="d-flex align-items-start gap-3">
            <div>
              <span className={`avatar avatar-md bg-${analytic.svgColor} svg-white`}>
                {analytic.svgIcon}
              </span>
            </div>
            <div>
              <span className="d-block text-muted">{analytic.title}</span>
              <h5 className="fw-semibold mb-1">{analytic.value}</h5>
              <div className="text-muted fs-12">
                <span className={`text-${analytic.iconColor}`}>
                  <i className={analytic.icon}></i> {analytic.percent}
                </span>{" "}
                {analytic.year}
              </div>
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkAnalyticsCard;
