// Dashboard Template/vyzor-react-ts/final/src/shared/@spk-reusable-components/reusable-pages/spk-profilecard.tsx

import { Fragment } from "react";
import { Card, Image } from "react-bootstrap";
import SpkButton from "../general-reusable/reusable-uielements/spk-buttons";

interface ProfileData {
  imgSrc: string;
  name: string;
  mail?: string;
  color?: string; 
  icon?: string; 
  followers?:string;
}

interface SpkProfileCardProps {
  profile: ProfileData;
  cardClass?: string;
  bodyClass?: string;
}

const SpkProfileCard: React.FC<SpkProfileCardProps> = ({ profile, cardClass, bodyClass }) => {
  return (
    <Fragment>
      <Card className={`custom-card ${cardClass}`}>
        <Card.Body className={bodyClass}>
          <div className="d-flex align-items-center gap-2 flex-wrap">
            <div className="lh-1">
              <span className="avatar avatar-lg avatar-rounded">
                <Image src={profile.imgSrc} alt={profile.name} />
              </span>
            </div>
            <div className="flex-fill">
              <span className="fw-semibold d-block">{profile.name}</span>
              <span className="text-muted fs-13">{profile.mail}</span>
            </div>
            <div>
              <SpkButton Buttonvariant="" Customclass={`btn btn-${profile.color}-ghost`}><i className={`ri-user-${profile.icon}-line me-1`}></i>{profile.followers}</SpkButton>
            </div>
          </div>
        </Card.Body>
      </Card>
    </Fragment>
  );
};

export default SpkProfileCard;

// Dashboard Template/vyzor-svelte/final/src/lib/@spk/reusable-pages/spk-profilecard.svelte
<script lang="ts">
    import { Card, CardBody, Image } from "@sveltestrap/sveltestrap";
    import SpkButton from "../uielements/Button/SpkButton.svelte";

    interface ProfileData {
        imgSrc?: string;
        name?: string;
        mail?: string;
        color?: string;
        icon?: string;
        followers?: string;
    }

    export let profile: ProfileData = {};
    export let cardClass: string = "";
    export let bodyClass: string = "";
</script>

<Card class={`custom-card ${cardClass}`}>
    <CardBody class={bodyClass}>
        <div class="d-flex align-items-center gap-2 flex-wrap">
            <div class="lh-1">
                <span class="avatar avatar-lg avatar-rounded">
                    <Image src={profile.imgSrc} alt={profile.name} />
                </span>
            </div>
            <div class="flex-fill">
                <span class="fw-semibold d-block">{profile.name}</span>
                <span class="text-muted fs-13">{profile.mail}</span>
            </div>
            <div>
                <SpkButton
                    color=""
                    customClass={`btn btn-${profile.color}-ghost`}
                    ><i class={`ri-user-${profile.icon}-line me-1`}
                    ></i>{profile.followers}</SpkButton
                >
            </div>
        </div>
    </CardBody>
</Card>
