// Dashboard Template/vyzor-svelte/final/src/lib/@spk/reusable-widgets/spk-employeecard.svelte
<script lang="ts">
    import { Col, Card, CardBody } from "@sveltestrap/sveltestrap";

    // Define the interface for widget props
    interface WidgetProps {
        title?: string;
        value?: number | string;
        iconClass?: string;
        badgeText?: string;
        percentChange?: string;
        color?: string;
        percentageColorClass?: string;
        badge?: boolean;
        crmbadge?: boolean;
        crmicon?: string;
        cardColor?: string;
        valueClass?: string;
        endText?: string;
        divClass?: string;
        crmiconColor?: string;
        crmpercentChange?: string;
    }

    // Define `widget` as a prop with type `WidgetProps`
    export let widget: WidgetProps = {};
</script>

<Col>
    <Card class={`custom-card widget-card-style1 ${widget.cardColor}`}>
        <CardBody>
            <div
                class={`d-flex align-items-start gap-3 flex-wrap ${widget.divClass}`}
            >
                <div class="lh-1">
                    <span class={`avatar avatar-md bg-${widget.color}`}>
                        <i class={`${widget.iconClass} fs-5`}></i>
                    </span>
                </div>
                <div class="flex-fill">
                    <span class="d-block">{widget.title}</span>
                    <h5 class={`fw-semibold ${widget.valueClass}`}>
                        {widget.value}
                    </h5>
                    {#if widget.badge}
                        <span class={`badge bg-${widget.color}-transparent`}>
                            {widget.badgeText}
                        </span>
                    {/if}
                </div>
                <div class={`${widget.endText}`}>
                    {#if widget.crmbadge}
                        <div class={`fw-semibold text-${widget.crmiconColor}`}>
                            <i
                                class={`ti ti-arrow-narrow-${widget.crmicon} me-1`}
                            ></i>{widget.crmpercentChange}
                        </div>
                    {/if}
                    <div class={`${widget.percentageColorClass}`}>
                        {widget.percentChange}
                    </div>
                    {#if widget.crmbadge}
                        <div class="text-muted fs-12">This Year</div>
                    {/if}
                </div>
            </div>
        </CardBody>
    </Card>
</Col>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/reusable-widgets/spk-employeecard.jsx

import React from 'react';
import { Card } from 'react-bootstrap';


const SpkEmployeeStatCard = ({widget}) => {
  return (
    <div className="col">
      <Card className={`custom-card widget-card-style1 ${widget.cardColor}`}>
        <Card.Body>
          <div className={`d-flex align-items-start gap-3 flex-wrap ${widget.divClass}`}>
            <div className="lh-1">
              <span className={`avatar avatar-md bg-${widget.color}`}>
                <i className={`${widget.iconClass} fs-5`}></i>
              </span>
            </div>
            <div className="flex-fill">
              <span className="d-block">{widget.title}</span>
              <h5 className={`fw-semibold ${widget.valueClass}`}>{widget.value}</h5>
              {widget.badge &&
                <span className={`badge bg-${widget.color}-transparent`}>
                  {widget.badgeText}
                </span>
              }
            </div>
              <div className={`${widget.endText}`}>
                  {widget.crmbadge &&
                    <div className={`fw-semibold text-${widget.crmiconColor}`}>
                      <i className={`ti ti-arrow-narrow-${widget.crmicon} me-1`}></i>{widget.crmpercentChange}
                    </div>
                  }
              <div className={`${widget.percentageColorClass}`}>{widget.percentChange}</div>
              {widget.crmbadge &&
               <div className="text-muted fs-12">This Year</div>
              }
              </div>
          </div>
        </Card.Body>
      </Card>
    </div>
  );
};

export default SpkEmployeeStatCard;
