// Dashboard Template/vyzor-laravel-svelte/final/resources/js/shared/@spk/dashboards-reusable/crypto-reusable/spk-walletcard.svelte
<script>
    import SpkButton from "@/shared/@spk/uielements/Button/SpkButton.svelte";
    import {
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Image,
    } from "@sveltestrap/sveltestrap";

    export let wallet = {};
</script>

<Card class="custom-card">
    <CardHeader>
        <div class="card-title">{wallet.title}</div>
    </CardHeader>
    <CardBody>
        <div class="d-flex align-items-center justify-content-between gap-2">
            <div class="d-flex align-items-center gap-2">
                <div class="lh-1">
                    <span class="avatar avatar-rounded position-relative">
                        <Image src={wallet.imgSrc} alt={wallet.title} />
                    </span>
                </div>
                <div>
                    <span class="d-block text-muted fs-12 fw-normal"
                        >{wallet.available}</span
                    >
                    <span class="fw-medium">{wallet.value}</span>
                </div>
            </div>
            <div>
                <span class="fw-medium">{wallet.price}</span>
                <span class="d-block text-muted fs-12 fw-normal">In USD</span>
            </div>
        </div>
    </CardBody>
    <CardFooter>
        <div class="btn-list text-center">
            <SpkButton color="primary" customClass="btn btn-w-lg btn-wave">
                Deposit
            </SpkButton>
            <SpkButton color="danger" customClass="btn btn-w-lg btn-wave">
                Withdraw
            </SpkButton>
        </div>
    </CardFooter>
</Card>

// Dashboard Template/vyzor-laravel-react-inertia/final/resources/js/shared/@spk-reusable-components/dashboards-reusable/crypto-reusable/spk-walletcard.jsx

import { Fragment } from "react";
import { Card, Image } from "react-bootstrap";
import SpkButton from "../../general-reusable/reusable-uielements/spk-buttons";
import BaseImage from "@/shared/layouts-components/baseimage/baseimage";


const SpkWalletCard = ({ wallet }) => {

  return (
    <Fragment>
      <Card className="custom-card">
        <Card.Header>
          <div className="card-title">{wallet.title}</div>
        </Card.Header>
        <Card.Body>
          <div className="d-flex align-items-center justify-content-between gap-2">
            <div className="d-flex align-items-center gap-2">
              <div className="lh-1">
                <span className="avatar avatar-rounded position-relative">
                  <BaseImage src={wallet.imgSrc} alt={wallet.title} />
                </span>
              </div>
              <div>
                <span className="d-block text-muted fs-12 fw-normal">{wallet.available}</span>
                <span className="fw-medium">{wallet.value}</span>
              </div>
            </div>
            <div>
              <span className="fw-medium">{wallet.price}</span>
              <span className="d-block text-muted fs-12 fw-normal">In USD</span>
            </div>
          </div>
        </Card.Body>
        <Card.Footer>
          <div className="btn-list text-center">
            <SpkButton Buttonvariant="primary" Customclass="btn btn-w-lg btn-wave"> Deposit </SpkButton>
            <SpkButton Buttonvariant="danger" Customclass="btn btn-w-lg btn-wave"> Withdraw </SpkButton>
          </div>
        </Card.Footer>
      </Card>
    </Fragment>
  );
};

export default SpkWalletCard;
